### ISSUE TITLE
make symfony/console dependency optional

### ISSUE THREAD

**Issue by kaznovac** [doctrine/DoctrineBundle#1002]
i have a case where i don't execute commands in production environment, so i don't need 'symfony/console' and registration of the commands in the production code.

**Comment by SenseException** [comment]
Is there any negative impact for creating this short proposal? Please evaluate about what your current use case is and what you want to gain by making console optional.

**Comment by MatTheCat** [comment]
I guess nobody wants dependecies they won't use.

**Comment by kaznovac** [comment]
@SenseException less code in production => less code audit and smaller attack surface.
also compiled container is smaller (one can create compiler pass to manually remove unwanted services) => better performance

**Comment by alcaeus** [comment]
Generally, I don't have a problem reducing the scope of our dependencies. However, with the current discussion around PHP 7.4 breaking a lot of those "optional" dependencies in the Symfony DI container (see https://github.com/symfony/symfony/issues/32995), I'd rather wait until we've found a proper solution to that problem.

That said, if we do decide to make `symfony/console` (or any other dependencies for that matter) optional, I have no problem doing that in a minor release: you shouldn't rely on transitive dependencies, so I don't consider this a BC break. I'll put this on the roadmap for 2.x and we'll see where the road goes.

**Comment by MatTheCat** [comment]
https://github.com/symfony/symfony/issues/32995 has been fixed :tada:

**Comment by stof** [comment]
is DoctrineBundle really the only package making your keep `symfony/console` as a requirement rather than a dev requirement ? AFAIK, removing the Symfony console entirely on prod servers will be quite complex (at least because of the cache warmup).

**Comment by MatTheCat** [comment]
I see your point @stof so it’s a shame I cannot recall what my project became :thinking:

**Comment by ostrolucky** [comment]
Agreed with @stof, removing symfony/console doesn't look realistic to do for symfony project and optional dependencies handling is always awkward to do. Anybody still think it's worth removing this dependency? @doctrine/team-symfony-integration  @greg0ire

**Comment by stof** [comment]
Well, as I'm almost sure that it will still be impossible to remove `symfony/console` from the project, having this dependency in the bundle does not hurt (as it does not add a new dependency in the project), and it avoids the pain of managing compatible versions of optional dependencies. So my vote is for the status quo here.

**Comment by fabpot** [comment]
I would also vote for not removing `symfony/console` here. If you are using `DoctrineBundle`, I'm 99% sure that you will get this dependency somehow anyway (1% is for someone who would try really hard to work around it).

**Comment by ostrolucky** [comment]
Good. Let's close then.
