### ISSUE TITLE
Remove dependencies of DoctrineCacheBundle

### ISSUE THREAD

**Issue by maxhelias** [doctrine/DoctrineBundle#1003]
I saw that the DoctrineCacheBundle bundle will be deprecated for the next major release.

https://github.com/doctrine/DoctrineCacheBundle#deprecation-warning

To be able to advance on this way, it will be necessary to remove the dependencies to this bundle like :
https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/DoctrineExtension.php#L48

**Comment by alcaeus** [comment]
See #981, after which we can drop this in master. Closing here since we’re on it.
