### ISSUE TITLE
Use EXPLAIN QUERY PLAN when using SQLite

### ISSUE THREAD

**Issue by MatTheCat** [doctrine/DoctrineBundle#1006]
While SQLite does support `EXPLAIN` its return is somewhat cryptic:

![explain](https://user-images.githubusercontent.com/1898254/63580008-20584c00-c594-11e9-83ea-ddcd0bb372ee.png)

Maybe it would be better to use [EXPLAIN QUERY PLAN](https://www.sqlite.org/eqp.html):

![explain-query-plan](https://user-images.githubusercontent.com/1898254/63580176-88a72d80-c594-11e9-92ca-7529cc89d3e3.png)

WDYT?

**Comment by stof** [comment]
this indeed seems better. Can you open a pull request implementing the change ?

**Comment by MatTheCat** [comment]
I'm on it.
