### ISSUE TITLE
syntax error, unexpected ':', expecting ',' or ')'

### ISSUE THREAD

**Issue by BoukadidaA7med** [doctrine/DoctrineBundle#1011]
![image](https://user-images.githubusercontent.com/33417750/63770092-494a4b00-c8cc-11e9-83b8-41676613a332.png)

**Comment by BoukadidaA7med** [comment]
I am new with symfony this is the "maincontroller.php"
using PHP 7
can you guys help me to find what's the problem here ???

**Comment by alcaeus** [comment]
Please don't open issues in repositories that have nothing to do with your problem whatsoever. This is in no way related to DoctrineBundle.
