### ISSUE TITLE
[RFC][Idea]Review fallback doctrine:schema:update command

### ISSUE THREAD

**Issue by TheGarious** [doctrine/DoctrineBundle#1012]
**Description**  
I would like to create an alternative to fallback of this command if the database is not created. For example by putting the command to create it or directly ask if you want to create it. This avoids wasting time. 

What do you think of that? 

**Example**  
![image](https://user-images.githubusercontent.com/10236869/63837396-b36df900-c97b-11e9-97c0-f6db46a9c265.png)
Replace By 
Unknown database `symfony`
Do you want to run "doctrine:database:create" instead?  (yes/no) [no]:
OR 
You need use this command `php bin/console doctrine:database:create` or create your database in a different way.

**Comment by SenseException** [comment]
I like the idea that a text appears about which command will have to be run to create the database.

**Comment by TheGarious** [comment]
Ok thanks, i work for this idea

**Comment by ostrolucky** [comment]
@TheGarious Are you still interested in this feature, or we may close this issue?

**Comment by TheGarious** [comment]
@ostrolucky i still interested in this feature, i work for this month.

**Comment by ostrolucky** [comment]
I don't see point of keeping this issue around. If anybody is interested in it, please open PR directly.
