### ISSUE TITLE
Allow wiring specific entity managers and repositories into services

### ISSUE THREAD

**Issue by alcaeus** [doctrine/DoctrineBundle#1021]
When injecting an entity manager into a service, auto wiring the service by using the `EntityManagerInterface` type will always wire the default entity manager. This makes it complicated to inject a custom entity manager for users that have more than one manager configured.

To select a correct entity manager, users would have to create a specific entity manager for each entity that decorates the entity manager service created. This could be done automatically in a compiler pass by using a service tag which specifies which entity manager to use.

The syntax would be simple:
```xml
<tag name="doctrine.entity_manager" entity="App\Entity\MyEntity" />
```

Same goes for repositories. Currently, users have to create an empty repository class if they want to use service repositories that they can inject into other services. To avoid this boilerplate code, we can leverage the same technique:

```xml
<tag name="doctrine.repository" entity="App\Entity\MyEntity" />
```

This is similar to what the MonologBundle does when configuring a channel using the `monolog.logger` tag.

**Comment by stof** [comment]
> To select a correct entity manager, users would have to create a specific entity manager for each entity that decorates the entity manager service created. This could be done automatically in a compiler pass by using a service tag which specifies which entity manager to use.
> 
> The syntax would be simple:
> 
> ```
> <tag name="doctrine.entity_manager" entity="App\Entity\MyEntity" />
> ```

I don't understand what you mean here. You talk about creating specific entity managers, but your issue is about *injecting* managers.

**Comment by alcaeus** [comment]
Okay, maybe I worded the paragraph wrong.

Currently, users would have to create a specific entity manager class that decorates the original entity manager to select the proper one. This however needs a bunch of boilerplate code that shouldn't be necessary.

The proposed tag would be a different solution for the problem, allowing users to apply the tag and thus no longer having to redeclare a specific entity manager to allow autowiring.

**Comment by ostrolucky** [comment]
I'm not a fan of this idea. I really dislike monologbundle way of injecting loggers and I say we should not take it as example. Pretty much same thing can be achieved nowadays with [binding](https://symfony.com/blog/new-in-symfony-4-1-getting-container-parameters-as-a-service)

**Comment by alcaeus** [comment]
Binding works for me, but we can also use more complex service aliases to also use the variable name. This would also help solve a problem we have when people type hint the `ObjectManager` interface but have ORM and ODM installed. We can configure service aliases like this:
```
<service id="Doctrine\Common\Persistence\ManagerRegistry $entityManagerRegistry" alias="doctrine" />

<service id="Doctrine\Common\Persistence\ObjectManager $defaultEntityManager" alias="doctrine.orm.default_entity_manager" />
<service id="Doctrine\ORM\EntityManagerInterface $otherEntityManager" alias="other_entity_manager" />
```

This would no longer require using a tag to inject managers, but rather use the combination of type and variable name to inject the correct entity manager by name.

@nicolas-grekas @weaverryan @fabpot is this an acceptable and understood use of this functionality in Symfony, or would you recommend a different way?

**Comment by stof** [comment]
@alcaeus using such named types aliases for autowiring is indeed the way things are intended to work for people using autowiring.

**Comment by ostrolucky** [comment]
Is binding meant to be used for bundles though? My comment was that problem that was explained in OG post is easily solvable in userland. Users should define their own names that make sense and their own definition/bind of $defaultEntityManager etc. I don't think there is anything for us to do here.

**Comment by ostrolucky** [comment]
Closing as explained.
