### ISSUE TITLE
Remove PHP 7.4 from `allow_failures`

### ISSUE THREAD

**Issue by carusogabriel** [doctrine/DoctrineBundle#1023]
PHP 7.4 will be released [soon](https://wiki.php.net/todo/php74) and we need to ensure that `Doctrine` is compatible with it.

All we need to do is to remove these following lines

https://github.com/doctrine/DoctrineBundle/blob/af8ac792c9b970ff2bc25b49ab9b31afd9e03dbf/.travis.yml#L84-L85

 and verify that everything is working.

This is a very good issue for those who want to participate in https://hacktoberfest.digitalocean.com.

**Comment by greg0ire** [comment]
@Klizzy pro-tip for your next contribution: use "Closes #1023" rather than "See #1023" and it will auto-close the issue

**Comment by Klizzy** [comment]
thank you very much for this tipp, didn't know about this!
