### ISSUE TITLE
I can't enable driverOptions configuration to connect to database (with doctrine/dbal).

### ISSUE THREAD

**Issue by yoshiaki-natsume** [doctrine/DoctrineBundle#1030]
Hello there.

I need to set driverOptions but if I use driverOptions keyword, Symfony raise error like

> InvalidConfigurationException
>Unrecognized option "driverOptions" under "doctrine.dbal.connections.default" in ArrayNode.php line 311

Then I fix `arrayNode('options')` to `arrayNode('driverOptions')` at [here](https://github.com/doctrine/DoctrineBundle/blob/1.12.x/DependencyInjection/Configuration.php#L161), Symfony doesn't raise error.
And it can connect to database with driverOptions configuration.

configuration about options is defined at https://github.com/doctrine/DoctrineBundle/blob/1.12.x/DependencyInjection/Configuration.php#L161
and there is no definition about driverOptions
but doctrine/dbal refer driverOptions param at https://github.com/doctrine/dbal/blob/2.9/lib/Doctrine/DBAL/Connection.php#L352
and options just passed with other params at https://github.com/doctrine/dbal/blob/2.9/lib/Doctrine/DBAL/Connection.php#L356

Is it correct behavior? Maybe DoctrineBundle should add driverOptions node.

thank you.

**Comment by dmaicher** [comment]
Within the doctrine bundle configuration the key `options` is actually mapped to `driverOptions` for the connection:

https://github.com/doctrine/DoctrineBundle/blob/1.12.x/DependencyInjection/DoctrineExtension.php#L234 

Also see https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration

**Comment by dmaicher** [comment]
I'm closing here as it was explained above and there was no further feedback.
