### ISSUE TITLE
[RFC]Disable schema:update if you use migration command

### ISSUE THREAD

**Issue by TheGarious** [doctrine/DoctrineBundle#1034]
Description
Since i use migration file in project with team, i can't block command schema:update for forcing used migration only.

I think use a configuration or other possibility (optionnal) for choose only one of command.

Example
For example in .env
DATABASE_UPDATE:MIGRATION_FILE

**Comment by dmaicher** [comment]
Maybe you can just remove this command (the registered service) in a compiler pass if you really want to avoid that it can be executed?

**Comment by alcaeus** [comment]
I would say that's the way to go. There are valid reasons to use schema:update in some cases, and I don't think it's within the scope of the bundle to start disabling commands.
