### ISSUE TITLE
PHPCS - Referenced sniff "Doctrine" does not exist

### ISSUE THREAD

**Issue by qkdreyer** [doctrine/DoctrineBundle#1046]
I can't find anywhere the *Doctrine* ruleset, and this line makes **phpcs** fails with the following error : 

```
ERROR: Referenced sniff "Doctrine" does not exist
```

https://github.com/doctrine/DoctrineBundle/blob/0d20a98fb80807e020e9371625dba4e81dad157a/phpcs.xml.dist#L15

**Comment by alcaeus** [comment]
If you have installed all dependencies with `composer install`, the ruleset should be there. You can confirm this by running `composer show -i doctrine/coding-standard` in your DoctrineBundle directory.

Are you running the `phpcs` binary installed in your `vendor/bin` directory or from a global install?

**Comment by qkdreyer** [comment]
It looks like I'm using an older [doctrine-bundle](https://github.com/doctrine/DoctrineBundle/tree/1.9.x) version (1.9.x) which wasn't dev requiring the doctrine/coding-standard package that was added in 1.11.x.

I'm using the vscode phpcs extension which was automatically triggering this error.

**Comment by alcaeus** [comment]
Yep: 1.9.x could not include the coding standard due to the bundle supporting PHP 5. You'll have to work around this by installing it yourself.

**Comment by qkdreyer** [comment]
I'm now correctly ignoring **\*/vendor/\*** folder using the vscode *phpcs.ignorePatterns* setting.
