### ISSUE TITLE
Trying create database 

### ISSUE THREAD

**Issue by manhalabdulrazzak** [doctrine/DoctrineBundle#1053]
hi i am try to create database for my project when i enter the command in terminal he give me this massage i try look in google but i am not find anything useful

1. ` php bin/console doctrine:database:create

In AbstractMySQLDriver.php line 106:

  An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to t
  he client

In PDOConnection.php line 31:

  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

In PDOConnection.php line 27:

  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

In PDOConnection.php line 27:

  PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]

doctrine:database:create [--shard SHARD] [--connection [CONNECTION]] [--if-not-exists] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>`

**Comment by dmaicher** [comment]
You you using Mysql8?

https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to

Anyway I don't think this issue is related to Doctrine.

**Comment by manhalabdulrazzak** [comment]
> Are you using Mysql8?
> 
> https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to
> https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/
> 
> Anyway I don't think this issue is related to Doctrine.

yes ! i use My Sql 8

**Comment by alcaeus** [comment]
Closing: this is not related to the bundle. Thanks @dmaicher for posting a fix.
