### ISSUE TITLE
Messenger table not yet filtered out by WellKnownSchemaFilterPass

### ISSUE THREAD

**Issue by weaverryan** [doctrine/DoctrineBundle#1061]
From #1037, the `WellKnownSchemaFilterPass` works overall, but the Messenger part was flawed. There is no `Connection` service that is added when the Doctrine transport is active. Instead, (check `FrameworkExtension`), for each transport, a factory is used to create the transport. It's quite dynamic, unfortunately (to support env vars), which makes it impossible to see at container build time which type of transport it will use.

I'm not sure of a good solution - I'm hoping @nicolas-grekas might have an idea!

**Comment by ostrolucky** [comment]
Indeed, this needs concrete proposal in order to make this actionable. Might require changes on symfony side.

**Comment by alcaeus** [comment]
@nicolas-grekas do you have an idea on how to solve this?
