### ISSUE TITLE
DoctrineTransportFactory.php bad implementation

### ISSUE THREAD

**Issue by onavascuez** [doctrine/DoctrineBundle#1062]
Just yesterday I was updated my project, and some packages includes new DoctrineBundle 2.0.0, and I was found this error:

```
In DoctrineTransportFactory.php line 29:
                                                                               
  Argument 1 passed to Symfony\Component\Messenger\Transport\Doctrine\Doctrin  
  eTransportFactory::__construct() must be an instance of Symfony\Bridge\Doct  
  rine\RegistryInterface, instance of Doctrine\Bundle\DoctrineBundle\Registry  
   given, called in /builds/php/bcn/svc-pre-booking-manager/var/cache/test/Co  
  ntainerGv2wPhF/getMessenger_Transport_Doctrine_FactoryService.php on line 1  
  2
```

New Registry doesn't have implementation of RegistryInterface causing this fail.

**Comment by dmaicher** [comment]
@alcaeus so I guess `symfony/messenger` 4.3 is incompatible with DoctrineBundle 2?

https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/Messenger/Transport/Doctrine/DoctrineTransportFactory.php#L29

**Comment by xabbuh** [comment]
fixed in symfony/symfony#34517

**Comment by malorentelopez** [comment]
Hi all,

I'm having the same issue even with DoctrineBundle v2.0.2 and Symfony in v4.3.8.

Regards,

MA

**Comment by stof** [comment]
@malorentelopez the fix in Symfony is not released yet. You will need to use the dev version of 4.3 for now (it will be part of the next patch release)
