### ISSUE TITLE
count Distinct doctrine

### ISSUE THREAD

**Issue by mit2pl** [doctrine/DoctrineBundle#1064]
i have question i create select 
$this->getDoctrine()->getRepository(Village::class)->findBy(['iduser' => $uzytkownik->getId()]);

and i want add 
count disinct, i foun this:
countDistinct('idworld')
but it not working, what i need to do ?

**Comment by alcaeus** [comment]
Hi! This is an issue tracker, not a support forum. Please join us in the #doctrine channel on the Symfony Slack, or join our Doctrine Slack. Thanks!
