### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by destevetewis** [doctrine/DoctrineBundle#1065]
User Deprecated: Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0.

How to configure to avoid this problem?

**Comment by maxhelias** [comment]
On your `config/packages/doctrine.yaml` file, change the `orm.naming_strategy` to `doctrine.orm.naming_strategy.underscore_number_aware`

**Comment by destevetewis** [comment]
Thank you very much!
