### ISSUE TITLE
Metadata cache no longer clears in dev environment

### ISSUE THREAD

**Issue by weaverryan** [doctrine/DoctrineBundle#1069]
Hi!

I believe @alcaeus is alread aware of the issue, but I couldn't find an issue for it yet. This relates also to #1066.

Basically, the new cache changes have a flaw in them: the metadata is being cached in all environments, which requires a cache clear to see Doctrine metadata changes. The easiest path is to "backup" to some sort of an "array" cache for all environments except for "prod".

**Comment by alcaeus** [comment]
Yeah, I was a bit too optimistic when leaving in the default config. By default, the bundle uses the `app` and `system` cache pools. These are configured with sensible defaults, thus also preventing performance issues in dev.

There are a couple of approaches with these defaults:
* In the dev and test environments, metadata is cached aggressively in the `system` cache pool. This requires a complete clear of the system cache pool to reload metadata
* In the test environment, the `app` cache pool is used to cache results. This can create issues between subsequent test runs, as it may reuse result caches from a previous test run.

With that in mind, I would suggest the following:
* For dev and test environments, resort to using an `array` cache adapter for the metadata and result pools. From what I can tell, the query cache may remain in the `system` cache pool, but it can also be changed for consistence
* In the prod environment, use the current defaults (`app` pool for results, `system` for queries and metadata).

**Comment by dmaicher** [comment]
I would propose to restore the previous behavior on DoctrineBundle:

- we won't use system/app cache pools by default
- if no pool is configured we should create new pools that use array adapters (similar to the previously used default `ArrayCache`)

And then adjust the recipe for `prod` to use the system/app pools (similar to how it was done before).

People might have more different environments and I'm not sure we should enable persistent caching by default on those. I would let the users decide to overwrite the default array caching if needed :blush:

**Comment by alcaeus** [comment]
That sounds like a plan. Can you make those changes? I believe 1.12 might be accepted as well if people leave cache config empty.

**Comment by dmaicher** [comment]
I will look into it today :+1:

**Comment by dmaicher** [comment]
New releases 1.12.1 and 2.0.1 are fixing this issue.
