### ISSUE TITLE
User Deprecated: YAML mapping driver is deprecated and will be removed in Doctrine ORM 3.0, please migrate to annotation or XML driver.

### ISSUE THREAD

**Issue by calbrecht** [doctrine/DoctrineBundle#1071]
composer show doctrine/doctrine-bundle
versions : * 2.0.0

composer show doctrine/orm
versions : * v2.7.0

There are still references to the `YamlDriver` and `SimplifiedYamlDriver` within the code of doctrine-bundle which result in log messages about the deprecation when installed beside doctrine/orm v2.7.0.

https://github.com/doctrine/DoctrineBundle/search?q=SimplifiedYamlDriver+OR+YamlDriver&unscoped_q=SimplifiedYamlDriver+OR+YamlDriver

Shouldn't those references be removed?

**Comment by alcaeus** [comment]
YAML has been deprecated in ORM 2.7 (and already been removed in ORM 3.0) for various reasons, one of them being that we need to maintain its metadata driver separately from XML and annotations, causing additional workload. This is certainly true, but the deprecation has not yet been reflected in this bundle for lack of an alternative (at the moment, the only alternative is users switching away from YAML). We're working on a suitable alternative that hopefully solves this problem for any future configuration formats as well.

**Comment by stof** [comment]
Are these referenced to YamlDriver and SimplifiedYamlDriver used even when there is no YAML mapping file registered ?

**Comment by ostrolucky** [comment]
Right, we need to clear this up. @calbrecht in what way are you getting these deprecation messages? Is it output from some SA analyzer, phpunit output, PHP error log? Are you using YAML mapping?

**Comment by calbrecht** [comment]
@ostrolucky output is from PHP error log. We are not using YAML mapping.

**Comment by ostrolucky** [comment]
Is it when running phpunit, some bin/console command, or some page in web browser?

**Comment by calbrecht** [comment]
It occurs in the logs at every request served.

**Comment by mmoll** [comment]
I think this happens because of the deprecation handling in symfony and probably the fix would be to release a new major version of doctrine-bundle with the YamlDriver removed from `Resources/config/orm.xml` and requiring doctrine/orm 2.7+?

**Comment by alcaeus** [comment]
> probably the fix would be to release a new major version of doctrine-bundle with the YamlDriver removed

No. We will not be removing the YAML driver from the Symfony integration.

**Comment by xabbuh** [comment]
Could it be a solution to lazily register the driver so that they will only be used when there is actually any mapping for said format?

**Comment by ostrolucky** [comment]
I've updated doctrine/orm and doctrine/doctrine-bundle in symfony-demo and am not getting Yaml deprecations. We will appreciate reproducer.

**Comment by jblac** [comment]
I'm a little late to the game but let me make sure i've got this straight.   you have deprecated and removed yaml, a very well used and highly respected format...  for xml, a format that needs to die; and annotations, a format that shouldn't exist?

Who's bright idea was that?  This is the only thing that's keeping me from using symfony again - symfony without doctrine is trash, and doctrine without yaml is worthless.

**Comment by Pictor13** [comment]
I don't like annotation either (as long as they aren't natively supported by PHP).

But about XML I disagree.
Sure, XML *makes you feel like* you want to die; sometimes. But it's a very solid, *versatile* and portable language.
It's just more verbose; and requires you to understand more concepts in order to use it properly.

YAML is easier, faster, more readable, but I never liked to use it, except of very simple files.

**Comment by jblac** [comment]
XML is near 50 years old, it's time it be put out to pasture.

**Comment by alcaeus** [comment]
@jblac please voice your concern in the ORM issue tracker (https://github.com/doctrine/orm), but remember that this has been discussed back and forth without any sensible outcome. DoctrineBundle is merely mirroring any change in ORM.

I'm locking this issue as there's nothing the bundle maintainers can do here (and please rest assured that we've tried).
