### ISSUE TITLE
[FEAT] DropDatabaseDoctrineCommand shortcuts

### ISSUE THREAD

**Issue by Guikingone** [doctrine/DoctrineBundle#1072]
Hi everyone 👋 

Small question about `DropDatabaseDoctrineCommand`, is there any historical reasons to not define a shortcut when it comes to `force`, `shard`, `connection` and `if-exists` ? 🤔 

Thanks a lot for the answer and have a great day 🙂

**Comment by alcaeus** [comment]
> is there any historical reasons [...]

Not that I'm aware of. Not sure if shortcuts are necessary, but then on the other hand I don't have a particularly strong opinion against them. 🤷‍♂️

**Comment by Guikingone** [comment]
Hi 👋 

Thanks for the feedback, is that something that I can contribute on? It is worth the work? 🤔

**Comment by greg0ire** [comment]
Maybe the reason would be that it's best the user is 100% sure they know what they are doing when using such a dangerous command. It's worth the work if you use that command often, but not sure all the options are used very often besides `--force`

**Comment by ostrolucky** [comment]
Introducing shortcuts would block these shortcuts from use in future options. I also don't see big benefit of having them.

**Comment by SenseException** [comment]
It's more a DX thing here. Less type-work for a user and a more fluent work with the command in case it has to be called more than just one time with different options. The benefit depends on the  typing preferences of a user.

**Comment by Guikingone** [comment]
Agree with @SenseException, this issue is really focused on the DX vision, simple example when using project with Makefile's, most of the time, we use something similar to `make db-drop` but what if we need to use the command without make (or in a Docker container?), typing `--force` can be boring but it's not something that block us, don't get me wrong, it's really about the DX. 

So, if you think that there's no benefits of defining an alias, I think that we can close this issue 🙂

**Comment by alcaeus** [comment]
I don't think it's bad to have the shortcuts. @Guikingone since you have some in mind, do you want to create a PR for them? Thanks!

**Comment by Guikingone** [comment]
@alcaeus Yes, no problem, I'm gonna start working on it tomorrow 🙂

**Comment by ostrolucky** [comment]
Are you still interested to contribute this? If so, when? If you don't, we should close this issue, as I don't see enough support from community.

**Comment by Guikingone** [comment]
Hi @ostrolucky 👋 

Yes, I've a first valid implementation (with tests), I push it tomorrow as a PR 🙂
