### ISSUE TITLE
ManagerRegistery should reset entity managers on kernel.reset

### ISSUE THREAD

**Issue by nicolas-grekas** [doctrine/DoctrineBundle#1083]
Follow up of https://github.com/symfony/symfony/issues/34720

[`ManagerRegistry`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/ManagerRegistry.php) is able to reset entity managers, but I think we missed wiring this capability with the `kernel.reset` tag so that EM are reset between requests in long-running loops.

Given the dependency on `LazyLoadingInterface`, this should be done only when the interface is found of course.

**Comment by alcaeus** [comment]
I can take a look later today. Treating as a bug for now so we can also fix this in 1.12, otherwise we'd have this on 2.1 only.

**Comment by alcaeus** [comment]
Fixed in #1099, will be released in 1.12.3.
