### ISSUE TITLE
Automatic connection to configured databases on each Symfony request

### ISSUE THREAD

**Issue by vtexier** [doctrine/DoctrineBundle#1088]
We are suffering Postgresql connection spamming coming from our Symfony applications.

After some investigation, we have discovered this :
* Doctrine connect to every configured database each time a Symfony request is made.
* Doctrine do this even if no request is done on this database during the request.

We have three databases configured in `config.yml/doctrine/dbal/connections`.
So we experience connection limit on our database servers !

Can we deactivate this behavior ?

Can Doctrine only connect to the database at the first request ?

DoctrineBundle Version 1.11.2.

**Comment by alcaeus** [comment]
Related to #1070 - I'll defer to @nicolas-grekas 😉

**Comment by nicolas-grekas** [comment]
Do #1087 fix the issue?
If not, what triggers the actual conection?

**Comment by ostrolucky** [comment]
this usually happens with misconfigured server_version option

**Comment by vtexier** [comment]
@ostrolucky thanks !

I have added the `server_version` parameter and the unwanted connection does not occur anymore.

In a web context, this parameter should be mandatory to avoid the unwanted side-effect of overloading the database server with connections.
