### ISSUE TITLE
Composer update - DoctrineBundle error with namespace

### ISSUE THREAD

**Issue by djmetla** [doctrine/DoctrineBundle#1089]
Yesterday i use composer update. Any idea how to fix ? Thanks 
<img width="1127" alt="Snímka obrazovky 2019-12-10 o 12 56 08" src="https://user-images.githubusercontent.com/2371031/70527692-cda79d80-1b4c-11ea-98cd-b294a752ed3c.png">

**Comment by alcaeus** [comment]
Please check `bundles.php` to see if `DoctrineCacheBundle` is still being loaded. If so, please remove the line.

We have seen this on some installations with symfony/flex, but haven't been able to reproduce it.

**Comment by djmetla** [comment]
@alcaeus thank you very much :) now is all ok.
