### ISSUE TITLE
Transaction commit failed because the transaction has been marked for rollback only

### ISSUE THREAD

**Issue by dimpels** [doctrine/DoctrineBundle#1092]
Hi

I've integrated Moodle and SuiteCRM using Myddleware.  Within Myddleware, I am getting this message.

What does this mean?  Please help me!!!

"Transaction commit failed because the transaction has been marked for rollback only. (/var/www/html/empowerme.school/myddleware/vendor/doctrine/dbal/lib/Doctrine/DBAL/ConnectionException.php line 12)"
![ERROR MESSAGE](https://user-images.githubusercontent.com/57750761/70734092-4147d700-1d14-11ea-8d93-dbfdff79c574.jpg)
![ERROR MESSAGE](https://user-images.githubusercontent.com/57750761/70734111-4e64c600-1d14-11ea-81bd-c72f4b9c6453.jpg)

**Comment by ostrolucky** [comment]
First, this is no support forum. Second, I don't know why issue is here and not in https://github.com/doctrine/dbal, since error is triggered from there. Try to use stackoverflow or one of options mentioned at https://www.doctrine-project.org/community/index.html
