### ISSUE TITLE
New doctrine/persistence version is broken

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineBundle#1093]
I just upgraded `doctrine/persistence` from 1.2 to 1.3
My project (Symfony 4.4.1 with DoctrineBundle 2.0.2) is broken with:

>Argument 1 passed to Doctrine\ORM\Configuration::setMetadataDriverImpl() must be an instance of Doctrine\Common\Persistence\Mapping\Driver\MappingDriver, instance of Doctrine\Persistence\Mapping\Driver\MappingDriverChain given, called in var/cache/dev/ContainerXDKITvY/AppApp_KernelDevDebugContainer.php on line 703

If I force `doctrine/persistence` to stay on 1.2.* it's working again.
I also tried to use `doctrine/doctrine-bundle` with version "^2.0@dev", no luck

**Comment by nicolas-grekas** [comment]
Check https://github.com/doctrine/persistence/pull/82
