### ISSUE TITLE
Bundle does not work with Symfony 3.4 installed as full-stack framework

### ISSUE THREAD

**Issue by xelan** [doctrine/DoctrineBundle#1094]
According to the [2.0 Upgrade guide of the 2.0.x branch](https://github.com/doctrine/DoctrineBundle/blob/2.0.x/UPGRADE-2.0.md), the bundle in version 2 should work with Symfony 3.4 LTS. However, according to `composer.json`  several Symfony 4.x components are required, resulting in a conflict if Symfony is installed as `symfony/symfony`.

**Comment by alcaeus** [comment]
If you look at the [composer.json](https://github.com/doctrine/DoctrineBundle/blob/abac3fd176865a3bb283da421e7030bf7b7aad1c/composer.json#L33) for the 2.0 branch, you'll see that some Symfony components are accepted in a 3.4 version, but some of them aren't. Obviously, this means that if you are using `symfony/symfony` 3.4, you won't be able to use version 2.0 of this bundle. Please use 1.12 instead.

**Comment by phillipsnick** [comment]
@alcaeus https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md states that this bundle supports 3.4 LTS. Assuming by the comment above that is not the case then.

**Comment by ostrolucky** [comment]
You can use mix of symfony 3.4 and 4.x components. Obviously this is not the case when using `symfony/symfony` dependency, you will need to break such dependency down to specific ones.

**Comment by oleg-andreyev** [comment]
It would nice to **reflect** this fact in UPGRADE notes.

**Comment by ostrolucky** [comment]
Bear in mind 1.x of bundle is working perfectly fine with both 3.x and 4.x symfony version, so there is no need to do bundle update when moving between symfony 3.x and 4.x.

**Comment by oleg-andreyev** [comment]
it's working fine. In our project due to dependencies (resolved to doctrine/common: ~1.0) is generating 1mil deprecations in 5 min.. so it's not okay for use.
