### ISSUE TITLE
ServiceEntityRepository uses deprecated interface

### ISSUE THREAD

**Issue by denisvmedia** [doctrine/DoctrineBundle#1096]
https://github.com/doctrine/DoctrineBundle/blob/d521b739f51a822476440378200f4707783e6e89/Repository/ServiceEntityRepository.php#L5

Here is how it's now defined:

```
    /**
     * @deprecated 1.3 Use Doctrine\Persistence\ManagerRegistry
     */
    interface ManagerRegistry extends \Doctrine\Persistence\ManagerRegistry
    {
    }
```

Do you have plans to fix it?

**Comment by nicolas-grekas** [comment]
I'd say yes, see https://github.com/doctrine/DoctrineBundle/pull/1095

**Comment by alcaeus** [comment]
As mentioned, this is already in progress. Closing here.
