### ISSUE TITLE
[Help] Convert this SQL query in Doctrine Query builder with suquery

### ISSUE THREAD

**Issue by chiqui3d** [doctrine/DoctrineBundle#1113]
Hello,
I hope you can help me to be able to make this query in Doctrine, I have tried many ways but I have not been successful, I hope you can help me.

```sql
SELECT SUM(N.secondsAttendance - N.secondsPauses) as ActualValue
FROM
SELECT SUM(TIME_TO_SEC(TIMEDIFF(a.check_out, a.check_in))) AS secondsAttendance,
(SELECT SUM(TIME_TO_SEC(TIMEDIFF(t.start_at, t.stopped_at))) FROM timeslice t WHERE t.attendance_id = a.id) AS secondsPauses
  FROM attendance a
  where yearweek(DATE(a.check_in), 1) = yearweek(curdate(), 1)
  GROUP BY a.id)
 N;
```

# SqlFiddle:

http://sqlfiddle.com/#!9/646be/21/0

**Comment by ostrolucky** [comment]
Unfortunately I have to close this, as this is not a support forum and this is not an actual Doctrine bundle issue. Try to use some of our [community channels](https://www.doctrine-project.org/community/).
