### ISSUE TITLE
[performance] DoctrineDataCollector SchemaValidator could be optional

### ISSUE THREAD

**Issue by bastnic** [doctrine/DoctrineBundle#1115]
I love the details and the validation given by the DoctrineDataCollector SchemaValidator. But on a serious project, it's useful only a couple of times, and cost a lot at each dev request. We already have a command for that (`bin console doctrine:schema:validate`) that we can launch manually and put in CI.

I'm talking about that: https://github.com/doctrine/DoctrineBundle/blob/master/DataCollector/DoctrineDataCollector.php#L61

It forces to get a loooot of data about any entity type, seems to be more than useful for the job being made to comply with the request.

I want to put that behind a feature switch, same as the `profiling_collect_backtrace`, but before creating a PR, I want to know the opinion of the maintainers about that. Is it something than you can consider merging? 

This feature switch could be set as true by default to provide the full DX by default bu be disable by power user if needed. I know I will on ALL my project: we are talking about minutes / hours cpu by each member of my team per day.

![image](https://user-images.githubusercontent.com/84887/71380138-797dce00-25ce-11ea-9b9c-66afcfd46190.png)

ps: -21% means -160ms.

**Comment by bastnic** [comment]
FYI, this snapshot is made before [this fix](https://github.com/doctrine/annotations/issues/300) to simulate the real dev experience right now, but it a litle bit less dramatic with it. But still painful.

**Comment by ostrolucky** [comment]
You link to whole foreach loop which also gets information about caches, while rest of the post talks about schema validation. With your proposal to remove only schema validation, only execution of inner foreach can be shaved off. If you want to remove both foreaches, your post is misleading.

In symfony-demo, removing inner foreach represents difference of 4.65% only and outer foreach 6.62% according my measurements, which I consider as not worth the change.

If this is significant difference in your case, I would suggest to replace `data_collector.doctrine` with your own. I would not approve adding such feature toggle into DoctrineBundle itself, especially since you came up with more universal solution how to speed this up in https://github.com/doctrine/annotations/issues/300

Thoughts?

**Comment by bastnic** [comment]
HI @ostrolucky, thanks you for your feedback. 

I was indeed only talking about the validation part, that requires loading all the metadata / annotation stack. 

I run the number again to show you the real impact in regard of the doctrine patch. All the numbers in my scenario by commenting only https://github.com/doctrine/DoctrineBundle/blob/master/DataCollector/DoctrineDataCollector.php#L64-L81:

| what  | whole time | count getMetadataFor | uniq class call in getMetadataFor |  count filemtime | enhancement
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| master  | 560  | 817 | 51 | 10973 | - 
| https://github.com/doctrine/annotations/issues/300 | 478 | 917 | 51 | ~0  | 15%
| this patch  | 451  | 824 | 23 | 10973 | 18%
| both | 405 | 824 | 23 | ~0 | 28%

Without this patch, we load metadata for 51 different entities. With this, we load metadata for only 23 of them (the ones really used in the current page). The doctrine patch make the loading of these many more entities faster, but are not enough (for me at least) to compensate.

So the big difference is that the SchemaValidator go very deep in the relations of the loaded entities even on fields that we do not care in the current page. It makes it load a lot of other metadata that are obviously not cached.

Great news, it's better/worse than I thought. 

In my case this is a no brainer. I've another way to get this information without the profiler, and I can add it in my CI. I'm in a position where I can enhance my DX, but it's not the case for everyone. 

**It's so big that it motivates me to have a warmup in dev env.**. 

`time bin/console doctrine:schema:validate --skip-sync` took less than half a second to run, and the SchemaValidator takes more than 100ms per page, so if we avoid a kernel refresh every 5 reload, it's a win (and it better be the case).

**Comment by ostrolucky** [comment]
> SchemaValidator goes very deep in the relations of the loaded entities even on fields that we do not care in the current page. It makes it load a lot of other metadata

Does it? As far as I can see collector calls `getLoadedMetadata` which should load only metadata already present in memory and schema validator doesn't do any additional loading itself.

We can also think about not doing validation in data collector at all. I believe it is not ultimately its job. Collector can perhaps just store class metadata and schema validator can be triggered only after opening the doctrine profiler tab, via twig extension.

**Comment by bastnic** [comment]
I just checked `symfony/demo`. Having 4.65% gain in the cleanest app ever that have only 4 entities seems actually already big to me. 

With my bigger app, it's fluctuate between different route types:
- on the heaviest doctrine-wise page, this doesn't impact much, because there is a good chance that almmost all metadata are already loaded, it's almost invisble.
- on the lightest pages with just a few data of heavy objects displayed, like the scenario given before (which is a real one and the most called route of my API), it's 18%... 

> Does it? As far as I can see collector calls `getLoadedMetadata` which should load only metadata already present in memory and schema validator doesn't do any additional loading itself.

Example:
- go /order/1 that displays only the id.
- it load the entity `Order` 1, that is related to a `Product`.
- we loaded the Order and the Product.
- the DoctrineDataCollector arrives. It sees the Order and the Product that are loaded. It will go through ALL the dependencies of the Product. And load like 10 new entity top to load `metatadataFor` (pim stuff, media, attributes).

**Comment by bastnic** [comment]
>  can also think about not doing validation in data collector at all. I believe it is not ultimately its job

I'm not a DX expert, and validation must be useful to someone, but we can agree that for the impact it can have now, it's seems not worthy. Hance the feature switch I purposed. 

Your solution can be the best of both world: only cost time / cpu when you ask for the profiler. But if you watch an old profile, you will get the errors of the current entities state. I don't mind.

**Comment by ostrolucky** [comment]
Your example makes sense in your application only, can you demonstrate it on symfony-demo instead? I still don't see what can trigger loading of metadata of all relations.

> But if you watch an old profile, you will get the errors of the current entities state

No, old classmetadata (which should be serialized by datacollector) is meant to be used for validation there. But if metadata loading is culprit here, this approach will obviously not help.

**Comment by bastnic** [comment]
> No, old classmetadata (which should be serialized by datacollector) is meant to be used for validation there. But if metadata loading is culprit here, this approach will obviously not help.
Yep, not useful.

> Your example makes sense in your application only, can you demonstrate it on symfony-demo instead? I still don't see what can trigger loading of metadata of all relations.

Can't test right now, and of course less easier with 4 entities with one related to every others.

but on what I see, there is no two way relations. Add a property "lastPost" on the user, then load user 1, never display the data about the post. It will show you the validation of user and post, but il will have loaded metadatas of tags and comments, that it would have never loaded before (lazy data, no join from scratch, theses entities are not initialized and so never called, metadata never loaded. But they will be... with the SchemaValidator that will load the relation of Post).

**Comment by ostrolucky** [comment]
> but il will have loaded metadatas of tags and comments, that it would have never loaded before

That's not what I see. Post metadata is loaded as soon as User is loaded via UserProvider, not when SchemaValidator runs. 

Additionally, main gain I see in blackfire is from lateCollect, which is not very relevant, since that happens when Kernel terminates, which is after all output was flushed.

**Comment by bastnic** [comment]
Post Metadata is indeed loaded with the user. It's normal. I'm talking
about the relation of post, so tag and comment Metadata, that are not
useful for user, so not loaded at runtime but loaded via the
SchémaValidator.

**Comment by ostrolucky** [comment]
I see now, it's loaded here https://github.com/doctrine/orm/blob/62c952d2583c6344cd1c2d24cd32a2f1c2e68b4c/lib/Doctrine/ORM/Tools/SchemaValidator.php#L108. I think this feature request can be satisfied with injectable `SchemaValidator`. Then you can replace it with your mock which does nothing. WDYT?

**Comment by greg0ire** [comment]
I know I always use `doctrine:schema:validate`, I don't think this data collector has ever brought any value to me, so I'm up for the feature switch too 👍

**Comment by bastnic** [comment]
Very very glad, thanks for your patience @ostrolucky!
