### ISSUE TITLE
Table already exists when upgrading bundle

### ISSUE THREAD

**Issue by Rubc** [doctrine/DoctrineBundle#1117]
When trying to upgrade DoctrineBundle from version: "1.12.2" to version: "1.12.6", or from 1.12.2 to 2.0, we always get this error when running PHPUnit : 'SQL error: table sessions already exists'.

Is this a bug?

**Comment by ostrolucky** [comment]
It was a bug fix for #987. `sessions` table is no longer deleted automatically, hence either you should take care of that yourself, or make sure to create it once only. AFAIK symfony does create table only when it's missing, so you are doing some custom things that you need to fix yourself.

cc @nicolas-grekas
