### ISSUE TITLE
Update ocramius/proxy-manager version

### ISSUE THREAD

**Issue by o-rel** [doctrine/DoctrineBundle#1130]
Hi, in current package.json ocramius/proxy-manager version is ^2.1. This version is using old Zendframework's packages, wich have moved to Laminas.

Current version of ocramius/proxy-manager (2.6) has changed those package to their new repositories.

**Comment by alcaeus** [comment]
`^2.1` allows installing `^2.6`. If it isn't installed automatically, your system or other dependencies may prevent the update. There's nothing to do for us here.
