### ISSUE TITLE
Console commands: compatiblity with upcoming doctrine/dbal 3.0

### ISSUE THREAD

**Issue by dmaicher** [doctrine/DoctrineBundle#1179]
Due to some deprecations and the new `ConnectionProvider` interface we need to fix a few things to be compatible with `doctrine/dbal` 3.0.

See https://github.com/doctrine/dbal/pull/3956, https://github.com/doctrine/dbal/pull/4059

Also related was this fix: https://github.com/doctrine/DoctrineBundle/pull/1170

Some thoughts: 
- we will need an adapter from `Symfony\Bridge\Doctrine\ManagerRegistry` to `Doctrine\DBAL\Tools\Console\ConnectionProvider` and inject that into the 2 commands `RunSqlDoctrineCommand` and `ImportDoctrineCommand` (can we use the dbal commands directly and deprecate the proxy commands?)
- remove usages of `Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper`

**Comment by ostrolucky** [comment]
Yes, I concluded same. But like I mentioned in #1170 I don't want to change DoctrineBundle only to find dbal changed their API before release.

**Comment by dmaicher** [comment]
@ostrolucky I think now we could work on this?

Since release [2.11](https://github.com/doctrine/dbal/releases/tag/2.11.0) I now have some deprecations related to this on some projects:

```
Other deprecation notices (1)

  1x: Not passing a connection provider as the first constructor argument is deprecated
    1x in Application::run from Symfony\Bundle\FrameworkBundle\Console

**Comment by ostrolucky** [comment]
Yep

**Comment by Adirelle** [comment]
> Since release [2.11](https://github.com/doctrine/dbal/releases/tag/2.11.0) I now have some deprecations related to this

It also triggers an error when using the `--connection` parameter:

```
$ bin/console doctrine:query:sql --connection=someconnection 'CREATE SCHEMA IF NOT EXISTS someschema'

In RunSqlCommand.php line 108:

   Specifying a connection is only supported when a ConnectionProvider is used
```

With these versions:
* doctrine/dbal 2.11.1
* doctrine/doctrine-bundle 2.1.2

**Comment by dmaicher** [comment]
@Adirelle indeed. I proposed a fix for that issue here: https://github.com/doctrine/DoctrineBundle/pull/1226

**Comment by ostrolucky** [comment]
Fixed in master
