### ISSUE TITLE
[feature] Access to EM from Repository

### ISSUE THREAD

**Issue by ivan1986** [doctrine/DoctrineBundle#1183]
Hello

Now need inject repository and em both in controller or service.
In old symfony before autoware it not be a issue - we use `getDoctrine()->getRepository(Entity::class)` and `getDoctrine()->getEntityManager()->flush()`
Now we inject in class or function `EntityRepository` and `EntityManager` because we need `EntityRepository` for get Entities and `EntityManager` for save in all change actions (call flush or persist).
Also need inject correct EM for repository if use many em. I think good solution will be allow access to `getEntityManager` in class `ServiceEntityRepository` (change from protect to public) because we very offen need em with repository and injection methon is changed.
I don't see any architectural issues of this solution and it's good and usefull shortcut in symfony di enviroment.

**Comment by ostrolucky** [comment]
Have your own base repository with this functionality or propose this in ORM. ServiceEntityRepository is not a correct place to do this.
