### ISSUE TITLE
[1.12.10] Could not clear metadata cache

### ISSUE THREAD

**Issue by JarJak** [doctrine/DoctrineBundle#1187]
Background:
One of the fields in an entity class has been renamed. Metadata cache keeps the old name so I want to clear it up.

When running command:
```
bin/console doctrine:cache:clear-metadata --flush -vvv
```

I get the following error:
```
[ReflectionException] Property TheEntity::$renamedField does not exist
Exception trace:
ReflectionProperty->__construct() at vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/RuntimeReflectionService.php:75
Doctrine\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty() at vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:966
Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection() at vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:753
Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection() at vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:753
Doctrine\ORM\Mapping\ClassMetadataFactory->wakeupReflection() at vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:183
Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:91
Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata() at vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php:68
Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp() at vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:52
Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:686
Symfony\Component\HttpKernel\Kernel->initializeContainer() at vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:135
```

To me it looks like Symfony is trying to warm up cache while booting up the kernel, which triggers doctrine cache warmer before clearing up the old cache.

Running the command second time does not give an error.

I use Redis as cache driver if it matters.

**Comment by pajon** [comment]
Hello,
i have the same issue. Until `2.0.2` there wasn't required dependency (`"doctrine/persistence": "^1.3.3"`).

```
Updating doctrine/persistence (1.3.7 => 2.0.0): Loading from cache
Downgrading doctrine/doctrine-bundle (2.1.0 => 2.0.2): Loading from cache
```

Composer file [2.0.2](https://github.com/doctrine/DoctrineBundle/blob/2.0.2/composer.json#L27) and [2.0.3](https://github.com/doctrine/DoctrineBundle/blob/2.0.3/composer.json#L30).

More info from `doctrine/persistence` [there](https://github.com/doctrine/persistence/releases/tag/2.0.0) and [there](https://github.com/doctrine/persistence/pull/106).

**Comment by ostrolucky** [comment]
@pajon How is doctrine/persistence version related to this issue?

@JarJak From what you wrote, I would suggest to create issue in Symfony, as it's an Symfony issue if it triggers cache warmup before it cleared old cache.
