### ISSUE TITLE
Add QueryBuilder::setFetchMode

### ISSUE THREAD

**Issue by kirya-dev** [doctrine/DoctrineBundle#1189]
Add new method QueryBuilder::setFetchMode

**Comment by stof** [comment]
QueryBuilder is not implemented by DoctrineBundle, so there is nothing to do here.

And btw, when requesting it to the right project, I strongly suggestyou to take the time to describes the reasons why you want the feature (otherwise, I'm almost sure that maintainers won't bother about doing it)

**Comment by kirya-dev** [comment]
Opened new issue https://github.com/doctrine/orm/issues/8219
