### ISSUE TITLE
Symfony 5.1.3 & 4.4.11 incompatible with 2.1

### ISSUE THREAD

**Issue by nusphere** [doctrine/DoctrineBundle#1190]
since in the latest version of symfony/doctrine-bridge - requires doctrine/persistence: ^1.3|^2 - now. The updates struggles and downgrades the doctrine-bundle to 2.0.2

```
- Removing doctrine/sql-formatter (1.1.0)
- Updating doctrine/persistence (1.3.7 => 2.0.0): Loading from cache
- Updating doctrine/common (2.13.3 => 3.0.2): Loading from cache
- Installing jdorn/sql-formatter (v1.2.17): Loading from cache
- Downgrading doctrine/doctrine-bundle (2.1.0 => 2.0.2): Loading from cache
```

**Comment by nusphere** [comment]
#1181

**Comment by dmaicher** [comment]
Cannot reproduce any problems on `symfony/demo` after I updated dependencies:

``` 
it@1ddd48e9948c:/var/www/symfony-demo  (master) $ composer show symfony/doctrine*
symfony/doctrine-bridge v5.1.3 Symfony Doctrine Bridge

it@1ddd48e9948c:/var/www/symfony-demo  (master) $ composer show doctrine/doctrine-bundle*
doctrine/doctrine-bundle 2.1.0 Symfony DoctrineBundle

it@1ddd48e9948c:/var/www/symfony-demo  (master) $ composer show doctrine/persistence*
doctrine/persistence 1.3.7 The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
``` 

How does your composer.json look like?

**Comment by nusphere** [comment]
Hier my composer packages:

```sh
www-data@7c20cf566566:/var/www$ composer show symfony/doctrine*
symfony/doctrine-bridge v5.1.3 Symfony Doctrine Bridge

www-data@7c20cf566566:/var/www$ composer show doctrine/doctrine-bundle*
doctrine/doctrine-bundle 2.0.2 Symfony DoctrineBundle

www-data@7c20cf566566:/var/www$ composer show doctrine/persistence*
doctrine/persistence 2.0.0 The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.

**Comment by dmaicher** [comment]
Can you show your `composer.json`? At least the relevant `symfony/*`and `doctrine/*` constraints.

And can you show the output of `composer why-not doctrine/doctrine-bundle ^2.10`?

**Comment by nusphere** [comment]
I am using flex, with a private repository, but in none of our private repositories is doctrine/persistence required to ^2.0

the composer.lock show me a requirement doctrine/persistence for of doctrine/common 3.0.2

<img width="528" alt="Bildschirmfoto 2020-07-24 um 14 20 24" src="https://user-images.githubusercontent.com/5822825/88390574-d6d23b80-cdb8-11ea-91e4-54c8c723f96a.png">


`output of composer why-not doctrine/doctrine-bundle ^2.10`
www-data@7c20cf566566:/var/www$ composer why-not doctrine/doctrine-bundle ^2.10
There is no installed package depending on "doctrine/doctrine-bundle" in versions not matching ^2.10

**Comment by nusphere** [comment]
<img width="520" alt="Bildschirmfoto 2020-07-24 um 14 25 30" src="https://user-images.githubusercontent.com/5822825/88390974-8f987a80-cdb9-11ea-97ca-92c925ccaf82.png">

```bash

www-data@7c20cf566566:/var/www$ composer show symfony/*
symfony/asset                      v5.1.3  Symfony Asset Component
symfony/browser-kit                v5.1.3  Symfony BrowserKit Component
symfony/cache                      v5.1.3  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v2.1.3  Generic abstractions related to caching
symfony/config                     v5.1.3  Symfony Config Component
symfony/console                    v5.1.3  Symfony Console Component
symfony/css-selector               v5.1.3  Symfony CssSelector Component
symfony/debug-bundle               v5.1.3  Symfony DebugBundle
symfony/debug-pack                 v1.0.8  A debug pack for Symfony projects
symfony/dependency-injection       v5.1.3  Symfony DependencyInjection Component
symfony/deprecation-contracts      v2.1.3  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.1.3  Symfony Doctrine Bridge
symfony/dom-crawler                v5.1.3  Symfony DomCrawler Component
symfony/dotenv                     v5.1.3  Registers environment variables from a .env file
symfony/error-handler              v5.1.3  Symfony ErrorHandler Component
symfony/event-dispatcher           v5.1.3  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v2.1.3  Generic abstractions related to dispatching event
symfony/expression-language        v5.1.3  Symfony ExpressionLanguage Component
symfony/filesystem                 v5.1.3  Symfony Filesystem Component
symfony/finder                     v5.1.3  Symfony Finder Component
symfony/flex                       v1.9.1  Composer plugin for Symfony
symfony/form                       v5.1.3  Symfony Form Component
symfony/framework-bundle           v5.1.3  Symfony FrameworkBundle
symfony/http-foundation            v5.1.3  Symfony HttpFoundation Component
symfony/http-kernel                v5.1.3  Symfony HttpKernel Component
symfony/intl                       v5.1.3  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lock                       v5.1.3  Symfony Lock Component
symfony/maker-bundle               v1.20.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                       v5.1.3  A library to manipulate MIME messages
symfony/monolog-bridge             v5.1.3  Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0  Symfony MonologBundle
symfony/options-resolver           v5.1.3  Symfony OptionsResolver Component
symfony/orm-pack                   v1.0.8  A pack for the Doctrine ORM
symfony/phpunit-bridge             v5.1.3  Symfony PHPUnit Bridge
symfony/polyfill-ctype             v1.18.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.18.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.18.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.18.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.18.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.18.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.18.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.18.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.18.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v5.1.3  Symfony Process Component
symfony/profiler-pack              v1.0.4  A pack for the Symfony web profiler
symfony/property-access            v5.1.3  Symfony PropertyAccess Component
symfony/property-info              v5.1.3  Symfony Property Info Component
symfony/routing                    v5.1.3  Symfony Routing Component
symfony/security-bundle            v5.1.3  Symfony SecurityBundle
symfony/security-core              v5.1.3  Symfony Security Component - Core Library
symfony/security-csrf              v5.1.3  Symfony Security Component - CSRF Library
symfony/security-guard             v5.1.3  Symfony Security Component - Guard
symfony/security-http              v5.1.3  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.1.3  Symfony Serializer Component
symfony/serializer-pack            v1.0.3  A pack for the Symfony serializer
symfony/service-contracts          v2.1.3  Generic abstractions related to writing services
symfony/stopwatch                  v5.1.3  Symfony Stopwatch Component
symfony/string                     v5.1.3  Symfony String component
symfony/swiftmailer-bundle         v3.4.0  Symfony SwiftmailerBundle
symfony/translation                v5.1.3  Symfony Translation Component
symfony/translation-contracts      v2.1.3  Generic abstractions related to translation
symfony/twig-bridge                v5.1.3  Symfony Twig Bridge
symfony/twig-bundle                v5.1.3  Symfony TwigBundle
symfony/validator                  v5.1.3  Symfony Validator Component
symfony/var-dumper                 v5.1.3  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v5.1.3  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v5.1.3  Symfony WebLink Component
symfony/web-profiler-bundle        v5.1.3  Symfony WebProfilerBundle
symfony/webpack-encore-bundle      v1.7.3  Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v5.1.3  Symfony Yaml Component

**Comment by dmaicher** [comment]
And the output of `composer why-not doctrine/common 2.*`?

**Comment by nusphere** [comment]
```bash
www-data@7c20cf566566:/var/www$ composer why-not doctrine/common 2.*
There is no installed package depending on "doctrine/common" in versions not matching 2.*

**Comment by michaljusiega** [comment]
Maybe its related to https://github.com/doctrine/DoctrineBundle/pull/1181 ?

**Comment by nusphere** [comment]
After some research, it might be depending on `doctrine/common` which is require `doctrine/persistence` ^2.0
`doctrine/common` is a requirement of `doctrine/orm` in version constrain ^2.11 || ^3.0 and implemented by `symfony/orm-pack` v1.0.8

**Comment by nusphere** [comment]
I added manual a fixed version of `doctrine/orm`

<img width="336" alt="Bildschirmfoto 2020-07-24 um 14 49 26" src="https://user-images.githubusercontent.com/5822825/88392822-efdceb80-cdbc-11ea-97ec-dab11584fe1f.png">

Now, a composer update works correct:

<img width="600" alt="Bildschirmfoto 2020-07-24 um 14 49 20" src="https://user-images.githubusercontent.com/5822825/88392930-23b81100-cdbd-11ea-916d-fc4fcdb177b9.png">

it seems a confusing dependency chain is working here. I don't like to have fixed version constrains. When I am using my normal `symfony/orm-pack` - it will update the newest `doctrine/orm` which is open the version constrain for `doctrine/common` which is requiring the `doctrine/persistence` ^2.0.

so the `doctrine/persistence` ^2.0. should be supported by this bundle.

**Comment by nusphere** [comment]
Conclusion:

After the release from today. Symfony 5.1.3 and Symfony 4.4.11 will open the version constrain for `doctrine/persistence` to ^2.0 through `symfony/doctrine-bridge`. This setting open the dependency chain for `doctrine/orm` which opens the version constrain for doctrine/common through ^2.11 || ^3.0. 

After opening the version constrain in `symfony/doctrine-bridge` for `doctrine/persistence` ^2.0 - `doctrine/orm` in its newest release v2.7.3 could depend on `doctrine/common` ^3.0 - with requires `doctrine/persistence` only with ^2.0.

This open the requirement for doctrine/doctrine-bundle for `doctrine/persistence` - otherwise it will block `doctrine/orm` and `doctrine/common`

**Comment by stof** [comment]
So, doctrine/orm 2.7.3 supports *only* the v2 of doctrine/persistence ?

**Comment by nusphere** [comment]
doctrine/orm 2.7.3 supports doctrine/common in version ^2.11 || ^3.0 and doctrine/persistence ^1.3.3 || ^2.0

but it will try to update the latest version of each requirement. So doctrine/common 3.0 will be installed which requiered doctrine/persistence  ^2.0 only.

**Comment by stof** [comment]
well, it depends. If your doctrine-bundle dependency is `^2.1`, you will directly get a solution using doctrine/persistence 1.3, doctrine/orm 2.7.3 and doctrine-bundle 2.1.0.
For the case of requiring `doctrine/doctrine-bundle` `^2.0`, Composer indeed has the choice to either use the latest doctrine/persistence or the latest doctrine/doctrine-bundle, and might make a different choice than the one you would want (but both are equally valid, and which solution is selected depends on the order in which the solver decides on packages as it will use the first valid solution it finds).

There is a WIP about adding support for doctrine/persistence 2, but it is currently not ready to be merged.

**Comment by nusphere** [comment]
thank you for the help around this issue. 

in my case, the upgrade to doctrine/persistance 2.0 was a hugh problem, especialy for my repositories. the solution for my problem was to fix this upgrade - because there was no reason to upgrade a major release of some dependencies.

i checked some deep dependecies in our code, so it will work for now. 

i would like to close this issue, because supporting persistance 2.0 should done by a major realease of this bundle.

at this time nothing is wrong with this bundle, more a configuration problem in some deeper dependencies.

thank you @stof for giving the clue about my problem. you right, it depends...

br nusphere
