### ISSUE TITLE
[Suggestion] add a cleaner way to register custom DBAL types.

### ISSUE THREAD

**Issue by Axelandre42** [doctrine/DoctrineBundle#1191]
**Description**
I was trying to find a way to register automatically types from a bundle. The only way I've found is to modify Doctrine's configuration on the fly using a `PrependExtensionInterface` implementation (see #336). That doesn't look clean for the following reasons:

* *Modifying configuration can easily lead to deprecation usage*: if there's a configuration schema change, it makes every other relying bundle using a deprecation.
* *Using low-level method to change settings can slightly impact performance*: it's like a dive, low-level has to dive deeper (and might ask more effort to process).
* *Doing the `PHP code -> $config array -> PHP code` way might give headaches*: you need to know configuration reference 😆 .

**Proposal**
Use a `CompilerPass` to register programmatically custom types! It avoids using the `$config` array and makes all the way easier with a simpler call in the bundle's `build()` method.

(I'm about to work on a pull-request; if you have a better idea, please tell)

**Comment by ostrolucky** [comment]
Just reading and modifying `doctrine.dbal.connection_factory.types` in your compiler pass didn't work?

**Comment by Axelandre42** [comment]
I meant it would be better to have that work done on the Doctrine side...

**Comment by ostrolucky** [comment]
What work? You asked for programmatic way to register custom types, you have that.

**Comment by Axelandre42** [comment]
And what happens if the configuration structure changes ?

**Comment by ostrolucky** [comment]
Any API we introduce will have this problem. You have what you asked for, let's close.
