### ISSUE TITLE
BC break at 2.1.1

### ISSUE THREAD

**Issue by KartaviK** [doctrine/DoctrineBundle#1201]
At version 2.1.1 i got this

```bash
!!  
!!  In DefinitionErrorExceptionPass.php line 54:
!!                                                                                 
!!    Cannot autowire service "App\Repository\UserRepository": argument "$regi  
!!    stry" of method "__construct()" references interface "Doctrine\Common\Persi  
!!    stence\ManagerRegistry" but no such service exists. Did you create a class   
!!    that implements this interface?                                              
!!              
```

Restoring at 2.1.0 and all works fine

**Comment by bastien70** [comment]
Same problem

`Cannot autowire service "App\Repository\App\AbsenceRepository": argument "$registry" of method "__construct()" references interface "Doctrine\Common\Persistence\ManagerRegistry" but no such service exists. Did you create a class that implements this interface?`

**Comment by dmaicher** [comment]
I guess we need to restore this service alias?

https://github.com/doctrine/DoctrineBundle/compare/2.1.0..2.1.1#diff-526de6d56db54965998fa70108bbe787L70

**Comment by KartaviK** [comment]
The main problem that there was removed that alias and old usages (who already use this class) was broken.
In current version ServiceEntityRepository uses `Doctrine\Persistence\ManagerRegistry` that does not have alias to `Doctrine\Common\Persistence\ManagerRegistry`. In new automatically generated repositories there are correct classes

**Comment by KartaviK** [comment]
You can totally rename `use Doctrine\Common\Persistence\ManagerRegistry` to `use Doctrine\Persistence\ManagerRegistry` in project and all will work fine

**Comment by dmaicher** [comment]
Release `2.1.2` fixes this BC break.
