### ISSUE TITLE
Update from 2.1.0 to 2.1.2 breaks compatibility

### ISSUE THREAD

**Issue by Knallcharge** [doctrine/DoctrineBundle#1204]
Hi,

I just updated the DoctrineBundle from version 2.1.0 to 2.1.2 and am getting errors in some external libraries that include classes with changed paths/namescapes. Don't know if this is the bundle itself or the dependencies it pulls (doctrine/persistence 1.3.8 => 2.0.0, doctrine/common 2.13.3 => 3.0.2).

Here are two errors I'm getting for Tetranz\Select2EntityBundle and Sg\DatatablesBundle:
Argument 1 passed to Tetranz\Select2EntityBundle\Form\Type\Select2EntityType::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given

Argument 1 passed to Sg\DatatablesBundle\Datatable\Column\ColumnBuilder::__construct() must be an instance of Doctrine\Common\Persistence\Mapping\ClassMetadata, instance of Doctrine\ORM\Mapping\ClassMetadata given

Downgrading DoctrineBundle to 2.1.0 resolved the problem.

**Comment by ostrolucky** [comment]
There is nothing we can do here unfortunately, this is transitive dependency problem. Please open the bug in the bundle, asking them to support doctrine/persistence. Meanwhile, explicitly require doctrine/persistence:^1 in your project.
