### ISSUE TITLE
Bundle (2.1.x) cannot be installed on 3.4.x

### ISSUE THREAD

**Issue by oleg-andreyev** [doctrine/DoctrineBundle#1205]
In https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md, it is stated that bundle supports 3.4 LTS
But because of bundle is requiring symfony/doctrine-bridge ^4.3.7 it cannot be done.

symfony/doctrine-bridge is conflicting with symfony/http-kernel: <4.3.7, so it cannot be installed for 3.4 LTS

**Comment by ostrolucky** [comment]
Please see this comment https://github.com/doctrine/DoctrineBundle/issues/1094#issuecomment-565489335
