### ISSUE TITLE
`./bin/console   doctrine:schema:create --dump-sql` generates invalid SQL

### ISSUE THREAD

**Issue by cmahnke** [doctrine/DoctrineBundle#1208]
Running `./bin/console   doctrine:schema:create --dump-sql` creates invalid SQL, the results are prepended with the following line ` The following SQL statements will be executed:`

It's probably better to insert a comment sign before this line or omit it at all, since the user probably knows what to expect when running with `--dump-sql`: Not some redundant message but proper SQL.

I'm using DoctrineBundle 2.1.2

**Comment by ostrolucky** [comment]
Not a doctrine bundle issue. Please create issue in DBAL.

**Comment by cmahnke** [comment]
Thanks, done: https://github.com/doctrine/dbal/issues/4259

**Comment by greg0ire** [comment]
@ostrolucky we can use the "Transfer issue" feature now ;)

**Comment by ostrolucky** [comment]
Yes, but issue description needs to be updated by OP as well, so better to create new issue
