### ISSUE TITLE
Add "different statements" field to Symfony Web Debug Toolbar

### ISSUE THREAD

**Issue by lomby92** [doctrine/DoctrineBundle#1210]
Copy of: https://github.com/symfony/symfony/issues/38158

**Description**  
The Symfony Web Debug Toolbar is a powerful tool. Whenever a dev sees a colored section it starts to fear what it has potentially broken.

The Doctrine section is very useful as it shows the number of queries and the query time. If something goes wrong it became red/yellow and the dev is ready to detect what/where is the problem.
This section could be better if it also takes into account the __different statements__ count (that is already shown in the dedicated Symfony profiler page).

This information is useful to detect repeated queries that potentially impact performances. It could be also a detector for N+1 queries created due to a Doctrine bug.

**Example**  
The "different statements" information could be placed into the div that appears on mouse hover (as in the image below)
![proposal](https://user-images.githubusercontent.com/5825081/93365028-8ec81600-f849-11ea-8db9-8166ea5f1b88.png)

To have a fast detection of repeated queries, the Doctrine section of the toolbar could be colored with orange/yellow (the alert color) when the count of "different statements" is less than the count of "database queries".

**Comment by ostrolucky** [comment]
I am not convinced that this is reliable enough indicator to raise warning. For all I know, user can have complicated query with 2 different set of parameters, which is not an N+1 problem. I believe it will lead to false positives which will decrease value of this toolbar. Having duplicated queries is not an issue until there is too much queries, so current condition is enough. If you are interested in having N+1 detection, we need something smarter than that.

**Comment by lomby92** [comment]
I agree that false positives could decrease the value of the toolbar.

How about reducing the scope of changes?
Maybe we can introduce just the "Different statements" into the div (as proposed) without apply any styling.

In this way we can avoid misunderstandings about the yellow colour and, at the same time, we add a useful info.

**Comment by ostrolucky** [comment]
I'm fine with that
