### ISSUE TITLE
doctrine:database:create and doctrine:database:drop not working with Slaves configuration and Doctrine/DBAL 2.11

### ISSUE THREAD

**Issue by Dodenis** [doctrine/DoctrineBundle#1214]
Since Doctrine/dbal 2.11 master/slave connection options have been replaced by primary/replica.

The commands `doctrine:database:create` and `doctrine:database:drop` displays the following error:
`Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped.`

**Comment by ostrolucky** [comment]
Should be solved in next release
