### ISSUE TITLE
dbal.schema_filter is ignored for specific table 'messenger_messages'

### ISSUE THREAD

**Issue by fabien007** [doctrine/DoctrineBundle#1225]
Since symfony 5.1 the table 'messenger_messages' is no longer exclude by the `schema_filter`'s setting :  `schema_filter: ~^(?!messenger_messages)~`

Since symfony 5.1 i got:
`php bin/console doctrine:schema:update --dump-sql`
`ALTER TABLE messenger_messages CHANGE body body LONGTEXT NOT NULL;`

I should not have `messenger_messages` in any SQL queries because of my `schema_filter`'s setting

 `MessengerTransportDoctrineSchemaSubscriber.onSchemaCreateTable` inject SQL code for table 'messenger_messages' on the event `ToolEvents::postGenerateSchema`

In this case, `schema_filter` is ignored but shoud not.

**Comment by ostrolucky** [comment]
You answered your own question. Since this got broken when symfony was updated to 5.1 (and not doctrine-bundle), this is most likely symfony issue, so you should report it there.

**Comment by fabien007** [comment]
I created an issue on symfony github as advised : [https://github.com/symfony/symfony/issues/38398](https://github.com/symfony/symfony/issues/38398)
