### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by jdelaune** [doctrine/DoctrineBundle#1227]
Any chance of getting a release tagged (even if its a beta release)? As with Symfony 5.2-Beta1 you hit issues unless you require the dev-master branch of DoctrineBundle because of this commit:

https://github.com/doctrine/DoctrineBundle/commit/12833cdad657129406f8d8f8f5d3d35c16e8da22

Thanks

**Comment by ostrolucky** [comment]
Referenced commit is for supporting new features, can you elaborate what regressions are you seeing in Symfony 5.2?

**Comment by jdelaune** [comment]
Well yes its a new feature in Symfony 5.2, if you use the new ulid doctrine types in Symfony 5.2 then you get errors like this:

`[error] Error thrown while running command "doctrine:schema:update". Message: "Unknown column type "ulid_binary" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.`

Unless you start using the dev-master branch of DoctrineBundle because of the commit I referenced above.

**Comment by ostrolucky** [comment]
Yeah so that's expected. Anyways yeah we will release 2.2 soon-ish

**Comment by jdelaune** [comment]
Okay thanks
