### ISSUE TITLE
Feature request - Extract as CSV

### ISSUE THREAD

**Issue by z31fbras** [doctrine/DoctrineBundle#1228]
Hi there! 👋

This would be awesome to extract data from the database in a pretty format.
I tried bin/console doctrine:query:sql.
Although, the return value is formatted like this:
```
array(87) {
  [0]=>
  array(3) {
    ["id"]=>
    int(97)
    ["answer"]=>
    string(1) "4"
    ["question"]=>
    string(49) "Accueil et disponibilité de l'équipe"
  }
...
```

This format is not convenient for the user I extracted the data for 😣
CSV extract would be perfect.

If there any existing solutions for this need, I would love to hear about them!

**Comment by ostrolucky** [comment]
No sorry, this is out of scope of this project.

**Comment by stof** [comment]
`doctrine:query:sql` is meant as a quick debugging tool, not an extract tool

**Comment by z31fbras** [comment]
Thanks @stof For explaining the reason to me! 👍
