### ISSUE TITLE
Use PrimaryReadReplicaConnection instead of MasterSlaveConnection

### ISSUE THREAD

**Issue by zazoomauro** [doctrine/DoctrineBundle#1235]
In order to avoid deprecation message:

`DEPRECATION: Doctrine\DBAL\Connections\MasterSlaveConnection is deprecated since doctrine/dbal 2.11 and will be removed in 3.0, use Doctrine\DBAL\Connections\PrimaryReadReplicaConnection instead. /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php:98
`

**Comment by Seldaek** [comment]
Related to this, primary/replica parameters are impossible to set, so even if one sets `                wrapper_class: 'Doctrine\DBAL\Connections\PrimaryReadReplicaConnection'` in the doctrine bundle config, it fixes the deprecation warning about the class, but then PrimaryReadReplicaConnection fails hard with `InvalidArgumentException("primary or replica configuration missing")`

**Comment by ostrolucky** [comment]
See https://github.com/doctrine/DoctrineBundle/pull/1237. Does that solve issue for all of you?

**Comment by ostrolucky** [comment]
merged in master/2.2
