### ISSUE TITLE
doctrine:migration:create not create a database with a specific charset

### ISSUE THREAD

**Issue by wcervini** [doctrine/DoctrineBundle#1239]
**Symfony version(s) affected**: 4.4.15

**Description**  
when try to create a database  on console, take the default charset default on MySQL Database.

**How to reproduce**  
Udpate the doctrine.yaml file (See screenshot1):
![Screenshot1](https://user-images.githubusercontent.com/51060/97111289-f0479400-16d5-11eb-8c4a-9842a95c6c77.jpg)

**Possible Solution**  
- run on console doctrine:migrations:generate
-  udpate function up on the created migration file (See Screenshot2):

![Screenshot2](https://user-images.githubusercontent.com/51060/97111290-f178c100-16d5-11eb-9e77-109efdca36fe.jpg)

**Comment by ostrolucky** [comment]
`doctrine:migration:create` is not a command coming with doctrine-bundle. Why do you think this is a DoctrineBundle issue? And what sql do you expect to be generated based on that configuration? You have obfuscated the resulting collation.

**Comment by wcervini** [comment]
I opened an incident in another Symfony group and they told me that it was related to Doctrine bundle

**Comment by wcervini** [comment]
I check the code doctrine/doctrine-bundle/Command/CreateDatabaseDoctrineCommand.php line102 only create the database
with out charset or collate parameter.

**Comment by ostrolucky** [comment]
Title is talking about `doctrine:migration:create` command though. `CreateDatabaseDoctrineCommand.php` is `doctrine:database:create`

**Comment by wcervini** [comment]
sorry my mistake writing the title:. Your right , the problem is when you create a database, when you migrate everything works fine, all the tables are created following the doctrine.yaml parameters, including or not the collate and the charset established in the configuration file. Only doctrine: databse: create does not include the collate and charset command parameters in the creation of the database query.

**Comment by ostrolucky** [comment]
What's the SQL generated by `doctrine:database:create` and what's the expected SQL for given configuration?

**Comment by wcervini** [comment]
this is my doctrine.yml

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.3.25'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_spanish_ci
 #               url: '%env(resolve:DATABASE_URL)%'
                dbname: servigarantia
                host: 127.0.0.1
                user: servi
                password: K4limer0garantia
                unix_socket: /var/run/mysqld/mysql.sock

right now dcotrine:database:create only generate "create table %dbname%" reading parameters from dotrine.yml, and not take the parameter collate and charset. the expected SQL "create datababase %dbname% collate = %collate%  charset = %charset%"

**Comment by ostrolucky** [comment]
This is a limitation of DBAL https://github.com/doctrine/dbal/blob/b5e15999e8f626b9a50edef142fffc7be57d0211/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L405. As you see it accepts database name only, nothing else. So we can't help you here in a bundle. Please open issue in DBAL if you wish to proceed further.
