### ISSUE TITLE
Using DoctrineDataCollector with EntityManagerDecorator fails

### ISSUE THREAD

**Issue by planim** [doctrine/DoctrineBundle#1247]
version: 2.2.x 
symfony environment: DEV or TEST with profiler enabled

This assert fails when I use custom EntityManagerDecorator:

https://github.com/doctrine/DoctrineBundle/blob/2aacd8380030fb2497a896fe33aaa5b1052feccc/DataCollector/DoctrineDataCollector.php#L67

After changing to:

`assert($em instanceof EntityManagerInterface);`

everything seems to be ok.

**Comment by pkly** [comment]
This applies to all spots in the bundle which use assert. 
Which includes data collection and command helper, possibly more.

**Comment by ostrolucky** [comment]
Easily solvable by disabling assertions.

**Comment by stof** [comment]
I think these assertions should be using EntityManagerInterface.

@ostrolucky this is not really a solution but only a workaround, as it disables also assertions in the project code (you cannot disable them per file). Wrong assertions in the code should be considered as bugs.

**Comment by ostrolucky** [comment]
As you can see via a label I added, this is acknowledged. I'm just downplaying seriousness of this. Assertions can be easily disabled. And most certainly should be disabled on production already.

**Comment by stof** [comment]
@ostrolucky the data collector is used in debug mode only. So this would force people to disable assertions in their dev setups too.

> Let's spend time until this is fixed by collecting which assertions are wrong.

We should probably start fixing the known ones actually. If they need to disable assertions because of a known issue, they won't discover issues elsewhere in the code...

**Comment by ostrolucky** [comment]
They don't have to disable assertions, they are also free to fix the assertions and open to PR. Disabling assertions is quick, easy workaround, not an actual fix as you said.

**Comment by pkly** [comment]
Well, 2 assertion failures. One mentioned and one in the command helper. I'll make a pr later today.

**Comment by ostrolucky** [comment]
Fix available at https://github.com/doctrine/DoctrineBundle/issues/1247. We would appreciate people to test.

**Comment by planim** [comment]
Problem solved in all my cases in https://github.com/doctrine/DoctrineBundle/pull/1248/commits/300ff15827454f90bb02bad4a454069183a0e24a

**Comment by ostrolucky** [comment]
Fixed in 2.2.1
