### ISSUE TITLE
Console commands prefer 'master' over ' primary' when using Slaves

### ISSUE THREAD

**Issue by prengerjarno** [doctrine/DoctrineBundle#1257]
Following #1215 and doctrine/dbal#4295, the console commands now support the new 'primary' config while the MasterSlaveConnection also has BC support for 'master'. This now leads to the console commands using the 'master' config which is missing the driver option.

I think it can simple prefer the 'primary' config.

**Comment by ostrolucky** [comment]
This looks like same issue as here https://github.com/doctrine/DoctrineBundle/issues/1252 

What version are you using?

**Comment by prengerjarno** [comment]
@ostrolucky I thought that at first as well, but after the fix in #1252 i still am missing the 'driver' param when using the create and drop commands, which results in not being able to create the connection. With the PrimaryReadReplicaConnection this is explicitly added to the primary/replica params.

I am using 1.12.12
