### ISSUE TITLE
Deprecation with Symphony 5.1.0 -> NodeDefinition::setDeprecated() requires 3 arguments

### ISSUE THREAD

**Issue by jordyno** [doctrine/DoctrineBundle#1270]
Since symfony/config 5.1: The signature of method "Symfony\Component\Config\Definition\Builder\NodeDefinition::setDeprecated()" requires 3 arguments: "string $package, string $version, string $message", not defining them is deprecated.

{▼
  \vendor\symfony\config\Definition\Builder\NodeDefinition.php:176 {▼
    Symfony\Component\Config\Definition\Builder\NodeDefinition->setDeprecated() …
    › if (\func_num_args() < 2) {
    ›     trigger_deprecation('symfony/config', '5.1', 'The signature of method "%s()" requires 3 arguments: "string $package, string $version, string $message", not defining them is deprecated.', __METHOD__);
    › 
  }
  \vendor\doctrine\doctrine-bundle\DependencyInjection\Configuration.php:94 {▼
    ›     ->scalarNode('class')->isRequired()->end()
    ›     ->booleanNode('commented')->setDeprecated()->end()
    › ->end()
  }
}

**Comment by stof** [comment]
which version of the bundle are you using ?

**Comment by ostrolucky** [comment]
You are using old version, please upgrade
