### ISSUE TITLE
Missing argument for doctrine.query_sql_command definition

### ISSUE THREAD

**Issue by dFayet** [doctrine/DoctrineBundle#1271]
Hello,

As of doctrine/dbal 3.0, the Doctrine's command `RunSqlCommand` has a mandatory `ConnectionProvider` parameter, but `RunSqlDoctrineCommand` does not define it.

I'm not calling the command directly, but the Symfony container file built is not valid.

Adding the [argument](https://github.com/doctrine/DoctrineBundle/blob/95c9daff56c0eba9a8df1838c46a63a52735dde0/Resources/config/dbal.xml#L106) added for the new command in the proxy seems to resolve this problem, but is it wanted?

Have a great day.

**Comment by ostrolucky** [comment]
Yes. And link given is not to a proxy a command. `RunSqlDoctrineCommand` is deprecated, check readme notes.

**Comment by dFayet** [comment]
Yes, I know it is deprecated, but the service `RunSqlDoctrineCommand`still exists in Symfony's container, despite I'm not using it.
I see the error when I clear cache, and psalm hangs on it.

**Comment by dFayet** [comment]
Yes, I know it has been deprecated, but I do not use the proxy command.
Symfony is building the container with it, because it is defined as a service.

That leads to warnings on cache:clear command, and PHPStan hanging itself because of the invalid definition

**Comment by ostrolucky** [comment]
What warning? Please post the message and stack trace

**Comment by dFayet** [comment]
For both cache:clear and PHPStan, I have the error `  Too few arguments to function Doctrine\DBAL\Tools\Console\Command\RunSqlCommand::__construct(), 0 passed in /app/var/cache/test/ContainerOGNINjX/getDoctrine_QuerySqlCommandService.php on line 24 and exactly  
   1 expected                                                                                                                                                                                                     
                `

If I look in the given file, at the line 24 I have `$container->privates['doctrine.query_sql_command'] = $instance = new \Doctrine\Bundle\DoctrineBundle\Command\Proxy\RunSqlDoctrineCommand();`

As I had some doubt, I created a brand new dummy project and it faces the exact same issue.

**Comment by enumag** [comment]
Just ran into this as well. Could you make a release with this fix?

**Comment by dFayet** [comment]
@enumag you can do a workaround to make your project work:
```yaml

# config/services.yaml
services:
    # other services definitions ...

    Doctrine\Bundle\DoctrineBundle\Command\Proxy\RunSqlDoctrineCommand:
        arguments: ['@Doctrine\Bundle\DoctrineBundle\Dbal\ManagerRegistryAwareConnectionProvider']
```

**Comment by ostrolucky** [comment]
Release created
