### ISSUE TITLE
Transaction and their propagation management

### ISSUE THREAD

**Issue by TheHett** [doctrine/DoctrineBundle#1274]
The Symfony now uses one global entiry manager (or Document Manager for DoctrineODM, the essence is the same).
It leads to the troubles when we deal with long-lived demons (console applications). For excample we may want to clear UoW in some service, but this will affect other services. The application have one global registry and that's not good.

In the Spring Framework this problem is solved by using sessions and transaction propagation levels:
simple article https://www.baeldung.com/spring-transactional-propagation-isolation
full official documentation https://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/transaction.html#tx-propagation

It is worth noting that the Spring uses own individual Document Manager for each isolated transaction (session).

Have you considered adding a similar mechanism to the Symfony?
It would be very cool to be able to manage transactions and their propagation level through annotations.

PS: I doubted where I should place this proposal: here or in doctrine repo. I think that it is over repo level.

**Comment by stof** [comment]
This is not something that can be added in DoctrineBundle itself, which is only about configuring the DBAL and ORM projects in a Symfony context. We cannot add this concept without support in the ORM.

**Comment by ostrolucky** [comment]
DBAL 2.11 automatically handles lost connections https://github.com/doctrine/dbal/pull/4119, what other issues with long lived demons you have? Anyways, as @stof pointed out, this would need to be added to dbal/orm.

**Comment by TheHett** [comment]
> DBAL 2.11 automatically handles lost connections doctrine/dbal#4119, what other issues with long lived demons you have? Anyways, as @stof pointed out, this would need to be added to dbal/orm.

@ostrolucky no, that's not what I was talking about

> This is not something that can be added in DoctrineBundle itself, which is only about configuring the DBAL and ORM projects in a Symfony context. We cannot add this concept without support in the ORM.

@stof I suspect that this is not the level of doctrine. This is only concept how we should use Document Manager (more precisely, several DM's).

Сan anyone tell me which component should be responsible for this?

**Comment by ostrolucky** [comment]
It's not clear what are you trying to do. You can use multiple entity managers without issues already. And spring documentation is not very clear either, you should do the work and explain what are you asking here better.

**Comment by TheHett** [comment]
@ostrolucky the repositories are injected by higher layer and it do not offer a choice which DM should be used. 
In default configuration provided by `DoctrineBundle` uses one global DM, is not it so?

> It's not clear what are you trying to do

Doctrine made in the likeness JPA, but without transaction propagation management ability. Are you used original JPA?
I'm trying to understand why no one needs it.

**Comment by ostrolucky** [comment]
>  @ostrolucky the repositories are injected by higher layer and it do not offer a choice which DM should be used.
> In default configuration provided by DoctrineBundle uses one global DM, is not it so?

Keyword here is _default_. You specify your entity managers in your doctrine.yaml config and this configuration includes which entity is managed by which entity manager.

> Are you used original JPA?

No, I didn't use it and I don't know what is transaction propagation management.

**Comment by TheHett** [comment]
@ostrolucky 
Sorry, but I'm afraid you don't have the competence to discuss this. You can close the ticket if there is no one here who understands this.

**Comment by ostrolucky** [comment]
Since we are not smart enough to understand your requirements and you are not willing to explain them better, feel free to open the PR with your changes. In the meanwhile, I'm indeed closing this issue.
