### ISSUE TITLE
DBAL PHP 8.0 problem

### ISSUE THREAD

**Issue by Mecanik** [doctrine/DoctrineBundle#1277]
I've been trying to work around this, but I hit a dead end. The error is reported on PHP 8:

`Compile Error: Declaration of Doctrine\\DBAL\\Driver\\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)`

One can always edit the code in the file but... is there another "fix" ?

Thanks

**Comment by Mecanik** [comment]
Forgot to mention, this happens when you don't specify server_version in doctrine.yaml and using mysql.

**Comment by ostrolucky** [comment]
Update doctrine/dbal. For future, please report problem in https://github.com/doctrine/dbal
