### ISSUE TITLE
lint:twig

### ISSUE THREAD

**Issue by malutanpetronel** [doctrine/DoctrineBundle#1292]
Please check these:

 ERROR  in /application/vendor/doctrine/doctrine-bundle/Resources/views/Collector/db.html.twig (line 195)
      193    
      194                                    <div>
  >>  195                                        <strong class="font-normal text-small">Parameters</strong>: {{ profiler_dump(query.params, 2) }}
  >> Unknown "profiler_dump" function. 
      196                                    </div>
      197    
  ERROR  in /application/vendor/doctrine/doctrine-bundle/Resources/views/Collector/db.html.twig (line 195)
      193    
      194                                    <div>
  >>  195                                        <strong class="font-normal text-small">Parameters</strong>: {{ profiler_dump(query.params, 2) }}
  >> Unknown "profiler_dump" function. 
      196                                    </div>
      197

**Comment by stof** [comment]
this function is registered by WebProfilerBundle, and this template is used only by the profiler integration. So there is no issue.
