### ISSUE TITLE
Custom order by for To Many ArrayCollection

### ISSUE THREAD

**Issue by droutin** [doctrine/DoctrineBundle#1303]
Hi,

How can I make custom order for ArrayCollection. I have sizes for product and I need to sort it by logic. So it will be XS -> XXL.
I have created findAll for ProductSize Entity, but that isn't it.
```
public function findAll()
    {
        return $this->createQueryBuilder('p')
            ->addSelect(
                '(CASE WHEN p.name = "XS" THEN 1
                WHEN p.name = "S" THEN 2
                WHEN p.name = "M" THEN 3
                WHEN p.name = "L" THEN 4
                WHEN p.name = "XL" THEN 5
                WHEN p.name = "XXL" THEN 6
                ELSE 5 END) AS size_order',
            )
            ->addOrderBy('size_order', 'ASC')
            ->getQuery()
            ->getResult();
    }
```

```
/**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="ProductSize", mappedBy="product")
     */
    private $sizes;
```

**Comment by ostrolucky** [comment]
Unfortunately I have to close this, as this is not a support forum and this is not an actual issue. Try to use some of our [community channels](https://www.doctrine-project.org/community/).

**Comment by droutin** [comment]
ehm. Sorry but Symfony Doctrine Slack link is not working. I can't register

**Comment by tarlepp** [comment]
> ehm. Sorry but Symfony Doctrine Slack link is not working. I can't register

hmm, it's working for me - https://symfony-devs.slack.com/join/shared_invite/zt-o2tdcgkh-fmr7bHYBO5T5LpV9QqjSDg#/shared-invite/email
