### ISSUE TITLE
Unable to make:entity since update doctrine/doctrine-bundle (2.3.0)

### ISSUE THREAD

**Issue by vtiertant** [doctrine/DoctrineBundle#1307]
Hello, 

After update my composer, doctrine-bundle is update to 2.3.0.

Now, when i try to 

`php bin/console make:entity`

When i choose a Class name, the file is created but console immediately returns the following error : 

`[ERROR] Only annotation mapping is supported by make:entity, but the <info>App\Entity\Test</info> class uses a         
         different format. If you would like this command to generate the properties & getter/setter methods, add your  
         mapping configuration, and then re-run this command with the <info>--regenerate</info> flag.`

I have no problem before this update.

I'm currently in symfony 5.2.5 version.

Anyone else have this problem?

**Comment by stof** [comment]
`make:entity` is part of MakerBundle. And this is currently being fixed in https://github.com/symfony/maker-bundle/pull/844
