### ISSUE TITLE
Usage of parameters in mapping files

### ISSUE THREAD

**Issue by lionelgaillard** [doctrine/DoctrineBundle#131]
Hi,

Could be conceivable to preprocess xml/yml mapping files to replace %parameters% from Symfony's DIC ?

**Comment by PReimers** [comment]
@lionelgaillard this issue exists since Nov. 2012.

Is it still open?

**Comment by lionelgaillard** [comment]
Hi,
I don't know.

**Comment by PReimers** [comment]
@lionelgaillard 

Is it possible for you to test it with the latest release?
And if not, could you provide a usecase (and a small example project) to make your issue more clear.

**Comment by lionelgaillard** [comment]
I'll not make promises, I'm not sure to have time, but I can try to explain better.

At the time of this idea, it seemed that, for reusable and sharable bundles, the preferred formats for entities metadata were YAML or XML over annotations.

Also, I don't remember what, but there were, in Symfony or some popular bundle, some YAML config files containing placeholders like %myParam% corresponding to some Symfony's parameters...

I guess the %myParam% placeholder was replaced by the value of the "myParam" Symfony's parameter at compile time of the bundle's configuration.

The idea was to have the same thing for Doctrine's entities metadata files: Having variables which would have been resolved before to be loaded by Doctrine.

Actually the use case I had in head in 2012, could now be resolved easily because, from flex, bundles can automatically configure the application when installed.

If I remember correctly, entities metadata had to be mapped to the entity's FQCN, which was problematic for bundles providing entities that the user can extend.

And because of that, metadata where copy/pasted from bundle to Application.

Another way was to presume the FQCN of the final entity by convention (e.g. NewsBundle => App/Entities/Post).

Variables in metadata could have been a solution to that particular problem.

**Comment by ostrolucky** [comment]
There is a possibility to replace current mapping drivers with ones based on symfony/config. I believe this use case would then be solved by itself.

**Comment by lionelgaillard** [comment]
Ok, so that request is obsolete.
I close the issue, then.
Thank you guys
