### ISSUE TITLE
[DataCollector] Runnable query different than actually executed one

### ISSUE THREAD

**Issue by Wirone** [doctrine/DoctrineBundle#1312]
**Description**
When using query builder with something like:
```
$qb->andWhere("foo.value IN (:foo_values)");
$qb->setParameter("foo_values", ['bar'], Connection::PARAM_INT_ARRAY);
```
Doctrine data collector in Symfony profiler shows "runnable query" with `foo.values IN ('bar')` but actually database query contains `foo.values IN (0)` because of `Connection::PARAM_INT_ARRAY` param type. It is very misleading, because looking at the profiler you may think the query is correct (even though the result is not).

**How to reproduce**
- configure MySQL connection in Doctrine
- use query builder with `IN` clause using array of strings as param value and `Connection::PARAM_INT_ARRAY` as type (which is incorrect)

**Possible Solution**
~~It looks like `doctrine_replace_query_parameters` Twig filter (used for rendering runnable query) should also use `query.types` and cover such edge cases like invalid `Connection::PARAM_*_ARRAY`~~ (see [comment](#issuecomment-809225933)). In general: logic behind generating "runnable query" should be as close as possible to execution logic.

**Additional context**
I was struggling with this for long time yesterday because I was getting results that I shouldn't. Looking at Monolog's logs from `doctrine` channel, then on Doctrine data collector's runnable query - it was all looking good, but unfortunately actual query was different. At the end I checked MySQL's general log and spotted difference in the `IN (...)` clause. Stupid mistake in query builder, but time wasted mostly because of profiler which was displaying "incorrect" query, different than the executed one.

Originally reported in symfony/symfony#40566

**Comment by ostrolucky** [comment]
Indeed. Transferred back.

**Comment by ostrolucky** [comment]
I don't think this is a doctrine-bundle bug. All of these bugs come from DoctrineBridge, like explained in https://github.com/doctrine/DoctrineBundle/issues/627. DoctrineBridge transforms these parameters before sending them to us. Please report bug for Symfony folks.

**Comment by Nyholm** [comment]
Hey @ostrolucky, you are probably correct, but could you help me finding this bug?

The `db.html.twig` in the bundle is printing the query parameters with the twig function `doctrine_replace_query_parameters()`. The query parameters themselves are collected by the doctrine bridge. 

Im not sure how we can guarantee that the value for "runnable query" is the exact same query that is executed.

**Comment by Wirone** [comment]
@ostrolucky @Nyholm Actually after some debugging I don't think it's DoctrineBridge's fault. Collector gets queries from `Doctrine\DBAL\Logging\SQLLogger` and does not know anything about binding types (there are only types used for converting between PHP and database values). It's Doctrine's `Doctrine\DBAL\Connection` that logs query and params' values, but it does it before binding typed values to the statement. Problem would be solved if parameters' values were resolved using provided types _before_ logging query/params. It's not possible to achieve those exact values later because `SQLLogger` does not pass information about binding types.

**Comment by Nyholm** [comment]
Okey. Does that sound like a reasonable step forward for you, Gabriel?

If so, how would we do that?

**Comment by ostrolucky** [comment]
> Does that sound like a reasonable step forward for you

What step? Are you referring to following?

> Problem would be solved if parameters' values were resolved using provided types before logging query/params.

That part is in `Doctrine\DBAL\Connection::executeQuery`. There is nothing there for doctrine-bundle to do.

Even if we could do something in logger (like trying to expand parameters there), `DbalLogger` is in doctrine-bridge, so again nothing to do for doctrine-bundle.

**Comment by beberlei** [comment]
Changing the interface of SQLLogger is not really likely and very long term giveb that DBAL 3 is already out and DoctrineBundle still requires v2

**Comment by ostrolucky** [comment]
What interface change? `\Symfony\Bridge\Doctrine\Logger\DbalLogger` receives `$types` but is simply choosing not to do  anything with it,

**Comment by Wirone** [comment]
> That part is in Doctrine\DBAL\Connection::executeQuery. There is nothing there for doctrine-bundle to do.
> Even if we could do something in logger (like trying to expand parameters there), DbalLogger is in doctrine-bridge, so again nothing to do for doctrine-bundle.

@ostrolucky Let's don't focus on proper repository for a moment and just think about possible solution - then issue can be moved. It was created here initially because at first look it seemed like a problem with rendering runnable query in profiler's collector, which is part of a bundle.

> `\Symfony\Bridge\Doctrine\Logger\DbalLogger` receives `$types` but is simply choosing not to do anything with it,

Personally I think it's OK that `DbalLogger` does not do anything with it. After another look at what logger receives I must correct [what I said before](#issuecomment-806554201) because `Connection::PARAM_INT_ARRAY` is passed as type, so collector receives it later (I've checked, it's available under `query.types` in `vendor/doctrine/doctrine-bundle/Resources/views/Collector/db.html.twig`). But IMHO it's not logger's nor collector's responsibility to normalize those params using types - it would be logic redundancy and possible way of desynchronising such logic at any point. Still think that logger should receive final values, resolved just before executing the query. Do provided params should be replaced with normalized ones? Not sure...

> Changing the interface of SQLLogger is not really likely and very long term giveb that DBAL 3 is already out and DoctrineBundle still requires v2

@beberlei I don't think bc-breaking interface change is required, it's totally fine for logging query with params as long as params are logged properly (values that query was executed with, not values that were passed to the Doctrine for execution). From my PoV there are 2 ways of fixing this on DBAL side:

- normalizing params' values before logging, so logger would receive real values used for execution. This does not require any changes in the interface but could be confusing ("why there are values X when I passed Y?") - still better than false values.
- adding 4th, optional argument to the `SQLLogger::startQuery` that would represent normalized params' values so they could be compared with provided ones and such value change like described above could be debugged

PS. If it was `SQLLogger::startQuery(string $query, Metadata $data)` with params' values and types wrapped as metadata object, it could be possible to add another metadata (normalized values) without bc-break. But it isn't like that, so instead of adding 4th argument as simple array, like mentioned above, such object could be added as 4th argument and current 2nd and 3rd arguments could be deprecated and removed in the future release. It would be possible then to extend data passed to the loggers without bc-breaks. But I don't know if it's the correct way, so...

**Alternatives:**

- Normalize values in `Symfony\Bridge\Doctrine\Logger\DbalLogger::startQuery()` using provided `$types` (which currently is not used, as @ostrolucky mentioned). This could fix the issue but it might be confusing too, since it would override source data, used and processed by `DoctrineDataCollector` (normalizing to database value using provided type)
- Pass types to `doctrine_replace_query_parameters` Twig filter and handle any edge type casting there, so runnable query would be "the same" as executed one (this would be confusing too because params are rendered as-is with `profiler_dump(query.params, 2)` so there would be difference between displayed params's values and values used in runnable query)
- Normalize values in `DoctrineDataCollector` (but which one? `Symfony\Bridge\Doctrine\DataCollector\*` or `Doctrine\Bundle\DoctrineBundle\DataCollector\*`?). This would be my 2nd choice after DBAL because it would ensure that params' values are consistent for whole collector (displayed params would be the same as ones used in runnable query).

As you can see there are multiple options but IMHO solving this at lowest-possible level would be the best. It's DBAL which executes query and prepares params for that - I think it should log final values used for execution BUT along with original values passed. This way BDAL would be central and only point of normalizing values and no other library (bundle, bridge) should manipulate the logged data.

Sorry for the long message, I thought it could be good to analyze this problem and propose some solutions, not only report and wait :slightly_smiling_face:

**Comment by ostrolucky** [comment]
> normalizing params' values before logging, so logger would receive real values used for execution. This does not require any changes in the interface but could be confusing ("why there are values X when I passed Y?") - still better than false values.

This is my preference too. Should be simple change in DBAL and would fix it for non-symfony users too.

**Comment by stof** [comment]
I think doing this "normalization" before logging could be confusing, because it also alters the SQL in case of `CONNECTION::PARAM_*_ARRAY`.
My preferences goes into handling types properly in `doctrine_replace_query_parameters` to generate the right runnable query based on the full set of DBAL param features.

**Comment by ostrolucky** [comment]
Doing normalization before logging is confusing, because log will show something else than user passed in.
Doing normalization after logging is confusing, because log will not show what SQL query was actually executed.

This is catch22 and I guess only way out is to show/log both queries. Before and after normalization. Or choose one, not the other. I would prefer seeing real sql queries there.

**Comment by Wirone** [comment]
> This is catch22 and I guess only way out is to show/log both queries. Before and after normalization. Or choose one, not the other. I would prefer seeing real sql queries there.

Yeah, my comment was so long because thinking of it I saw pros and cons of each of the approaches.. And that "catch-22" was covered in paragraph about `Doctrine\DBAL\Logging\SQLLogger` where I proposed additional argument with "normalized" params (I think query is already final there, only params' values not). Alternatives can solve it too, but each of them have drawbacks.

As a developer, I prefer to see real queries and params in the logger/collector. If I saw wrong values there, I could debug why those values were wrong. But I got correct query with "wrong" params (not typecasted for binding) and was wondering why runnable query executed directly in MySQL returned different result. On the other hand changing this behaviour and logging "normalized" params seems like BC-break somehow. Tough choice :sweat_smile:

**Comment by ostrolucky** [comment]
We should cooperate with DBAL on this, please create issue there.

**Comment by ostrolucky** [comment]
Looks like this discussion is over, so we may as well close the issue

**Comment by beberlei** [comment]
@ostrolucky i don't think this is the responsibility of the DBAL, because converting the params based on the types could be an expensive operation that the DBAL has no interst in performing without knowing the information is actually used.

**Comment by ostrolucky** [comment]
DBAL already does conversion. Problem is it logs the query before conversion happens, which is what's causing the problem here.
