### ISSUE TITLE
Unable to set custom shard manager

### ISSUE THREAD

**Issue by cyberemissary** [doctrine/DoctrineBundle#1314]
Good Day,

In https://github.com/doctrine/DoctrineBundle/blob/70be9d41da1c75c613d79e9d3c604d179cd705b0/DependencyInjection/DoctrineExtension.php#L405 the `$options['shardManagerClass']` will always be empty because it gets `unset()` a few lines prior as it is not part of `$nonRewrittenKeys` array.

So there is no way to provide a custom shard manager class via configs as it just gets unset.

Is this intentional or is it a bug?

**Comment by ostrolucky** [comment]
Yeah it's most certainly a bug

**Comment by cyberemissary** [comment]
Could you tell me which branch to target? I'll submit PR right away

**Comment by ostrolucky** [comment]
default one

**Comment by cyberemissary** [comment]
On a separate note I noticed this: https://github.com/doctrine/dbal/issues/3595
Any recommendations of what I could when upgrading to next doctrine that doesn't have native sharding support?
Are you by chance planning to add the support to this bundle maybe?

**Comment by ostrolucky** [comment]
I don't have recommendation as I don't use it. We don't plan to add support for it here, though.
