### ISSUE TITLE
Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getSequenceNextValSQL' is not supported by platform.

### ISSUE THREAD

**Issue by ThibaultVlacich** [doctrine/DoctrineBundle#1317]
Since I upgraded to 2.3.0, I'm getting this error when I'm trying to persist an object on a MariaDB server.

```php
$this->getDoctrine()->getManager()->persist($obj);
```

Is throwing the following exception:

> Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getSequenceNextValSQL' is not supported by platform.

Seems fine on MySQL.

My config contains `override_url: true` and serverVersion is present in the database URL (`serverVersion=mariadb-10.5.9`)

**Comment by ostrolucky** [comment]
Doesn't seem doctrine-bundle problem. What else did you upgrade?

**Comment by ThibaultVlacich** [comment]
It also upgraded doctrine/dbal to 2.13.0 (from 2.12.1)

**Comment by stof** [comment]
@ostrolucky I'm quite sure that this is actually related to the `override_url` change in DoctrineBundle, which probably did not account for the fact that DBAL allows the URL query string to configure more options too

**Comment by ostrolucky** [comment]
@ThibaultVlacich can you confirm if issue is fixed if you have `override_url: false`?

**Comment by ThibaultVlacich** [comment]
Ok, I did more testing, like upgrading packages one by one, and the issue appears when I upgrade doctine/orm from 2.8.1 to 2.8.2, so doctrine/orm seems to be the culprit.

**Comment by ostrolucky** [comment]
Thanks for confirming. No doctrine-bundle issue then.

**Comment by ThibaultVlacich** [comment]
@ostrolucky I did more testing, and I'm coming back to my initial founding, doctrine-bundle is the issue.

I re-did the upgrading of packages, one by one, and the issue appear when I upgrade doctrine-bundle to 2.13.0 (issue also present with 2.13.1).

Here's my git diff, showing that the only change is indeed doctrine-bundle.

```
diff --git a/composer.json b/composer.json
index 7eba8bd..1cbc94e 100644
--- a/composer.json
+++ b/composer.json
@@ -20,7 +20,7 @@
         "doctrine/annotations": "1.12.1",
         "doctrine/common": "3.1.2",
         "doctrine/dbal": "2.13.0",
-        "doctrine/doctrine-bundle": "2.2.3",
+        "doctrine/doctrine-bundle": "2.3.1",
         "doctrine/doctrine-migrations-bundle": "3.0.2",
         "doctrine/orm": "2.8.4",
         "google/apiclient": "2.9.1",
diff --git a/composer.lock b/composer.lock
index 706c661..dfae5ab 100644
--- a/composer.lock
+++ b/composer.lock
@@ -4,7 +4,7 @@
         "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
         "This file is @generated automatically"
     ],
-    "content-hash": "94f751d02c1294e1f4fb4f04c3a351df",
+    "content-hash": "eb244813e30b52dca91625fe504d3eb0",
     "packages": [
         {
             "name": "clue/stream-filter",
@@ -625,16 +625,16 @@
         },
         {
             "name": "doctrine/doctrine-bundle",
-            "version": "2.2.3",
+            "version": "2.3.1",
             "source": {
                 "type": "git",
                 "url": "https://github.com/doctrine/DoctrineBundle.git",
-                "reference": "015fdd490074d4daa891e2d1df998dc35ba54924"
+                "reference": "a08bc3b4d8567cdff05e89b272ba1e06e9d71c21"
             },
             "dist": {
                 "type": "zip",
-                "url": "https://api.github.com/repos/doctrine/DoctrineBundle/zipball/015fdd490074d4daa891e2d1df998dc35ba54924",
-                "reference": "015fdd490074d4daa891e2d1df998dc35ba54924",
+                "url": "https://api.github.com/repos/doctrine/DoctrineBundle/zipball/a08bc3b4d8567cdff05e89b272ba1e06e9d71c21",
+                "reference": "a08bc3b4d8567cdff05e89b272ba1e06e9d71c21",
                 "shasum": ""
             },
             "require": {
@@ -646,7 +646,7 @@
                 "symfony/config": "^4.3.3|^5.0",
                 "symfony/console": "^3.4.30|^4.3.3|^5.0",
                 "symfony/dependency-injection": "^4.3.3|^5.0",
-                "symfony/doctrine-bridge": "^4.3.7|^5.0",
+                "symfony/doctrine-bridge": "^4.4.7|^5.0",
                 "symfony/framework-bundle": "^3.4.30|^4.3.3|^5.0",
                 "symfony/service-contracts": "^1.1.1|^2.0"
             },
@@ -659,25 +659,25 @@
                 "doctrine/orm": "^2.6",
                 "friendsofphp/proxy-manager-lts": "^1.0",
                 "phpunit/phpunit": "^7.5 || ^8.0 || ^9.3",
-                "symfony/phpunit-bridge": "^4.2",
+                "psalm/plugin-phpunit": "^0.15.1",
+                "psalm/plugin-symfony": "^2.2.4",
+                "symfony/phpunit-bridge": "^5.2",
                 "symfony/property-info": "^4.3.3|^5.0",
                 "symfony/proxy-manager-bridge": "^3.4|^4.3.3|^5.0",
+                "symfony/security-bundle": "^4.4|5.0",
                 "symfony/twig-bridge": "^3.4.30|^4.3.3|^5.0",
                 "symfony/validator": "^3.4.30|^4.3.3|^5.0",
                 "symfony/web-profiler-bundle": "^3.4.30|^4.3.3|^5.0",
                 "symfony/yaml": "^3.4.30|^4.3.3|^5.0",
-                "twig/twig": "^1.34|^2.12|^3.0"
+                "twig/twig": "^1.34|^2.12|^3.0",
+                "vimeo/psalm": "^4.7"
             },
             "suggest": {
                 "doctrine/orm": "The Doctrine ORM integration is optional in the bundle.",
+                "ext-pdo": "*",
                 "symfony/web-profiler-bundle": "To use the data collector."
             },
             "type": "symfony-bundle",
-            "extra": {
-                "branch-alias": {
-                    "dev-master": "2.3.x-dev"
-                }
-            },
             "autoload": {
                 "psr-4": {
                     "Doctrine\\Bundle\\DoctrineBundle\\": ""
@@ -715,7 +715,7 @@
             ],
             "support": {
                 "issues": "https://github.com/doctrine/DoctrineBundle/issues",
-                "source": "https://github.com/doctrine/DoctrineBundle/tree/2.2.3"
+                "source": "https://github.com/doctrine/DoctrineBundle/tree/2.3.1"
             },
             "funding": [
                 {
@@ -731,7 +731,7 @@
                     "type": "tidelift"
                 }
             ],
-            "time": "2021-01-19T20:29:53+00:00"
+            "time": "2021-04-05T14:21:02+00:00"
         },
         {
             "name": "doctrine/doctrine-migrations-bundle",
diff --git a/config/packages/doctrine.yaml b/config/packages/doctrine.yaml
index 123eb42..b27d2f3 100644
--- a/config/packages/doctrine.yaml
+++ b/config/packages/doctrine.yaml
@@ -11,6 +11,7 @@ doctrine:
             datetime: App\Types\UTCDateTimeType
             datetimez: App\Types\UTCDateTimeType
         url: '%env(resolve:DATABASE_URL)%'
+        override_url: true
     orm:
         auto_generate_proxy_classes: true
         naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

```

Before: no issue, after: issue is present. This issue should be re-opened.

**Comment by ostrolucky** [comment]
We don't know how to reproduce this, though. Can you please try reproducing this on eg. https://github.com/symfony/demo ?

It would also help if you bisected this to smaller chunk, eg. you skipped 2.2.4 so we don't know if issue is there or not

**Comment by ThibaultVlacich** [comment]
Oh right, I totally missed 2.2.4. I just tested and no issue with 2.2.4.
It appears with 2.3.0.

I'll try to make a reproduction, but I already have a hard time reproducing it with my own project code, because I do not see the issue on my local machine, only on my production server. And I use the same Docker image for MariaDB on both so I'm not really sure.

Only thing I'm sure of, is that there's no issue with doctrine-bundle <2.3.0, and the issue is there with doctrine-bundle >=2.3.0.

**Comment by ostrolucky** [comment]
Use APP_ENV=prod on your local machine, that will help you with reproducing it

**Comment by ThibaultVlacich** [comment]
Ok, I think I found the source of the issue. It's the [changes made to the cache](https://github.com/doctrine/DoctrineBundle/commit/011cb9622788602505dc3e9f8e518428e9572aa9).

My DATABASE_URL is injected into my Docker image at runtime (via `-e` parameter on the `docker run` command). Which means that cache was already warmed up before it's available, and generated on default values. And since `cache:clear` is not clearing that cache anymore, it's containing information that are not correct.

If I manually delete `/var/cache/prod/doctrine/orm/default_metadata.php` after my Docker image is up, the issue disappear.

EDIT: the issue re-appear as soon as the `default_metadata.php` is re-generated (via `php bin/console cache:clear` for example). Everything is working fine only when the file is not present. So, it's not an issue with DATABASE_URL not being available, but with the cache itself? No issue in dev mode obviously as the cache is bypassed.

**Comment by ostrolucky** [comment]
@ossinkine what to do here? could you take a look?

**Comment by stof** [comment]
make sure that your config available during cache warmup defines the right driver and server version for the connection. These things are what are impacting the ORM metadata, so changing the DBAL platform at runtime will indeed break.

**Comment by ThibaultVlacich** [comment]
Basically my tests are:
1/ It's not working

2/
```
/var/www/symfony # rm var/cache/prod/doctrine/orm/default_metadata.php
```
It's working (cache is not present).

3/ I'm making sure my config is correct
```
/var/www/symfony # cat config/packages/doctrine.yaml
doctrine:
    dbal:
        driver: 'pdo_mysql'
        charset: utf8mb4
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        url: '%env(resolve:DATABASE_URL)%'
        override_url: true
```
```
/var/www/symfony # echo $DATABASE_URL
mysql://xxx:xxx@database-mariadb:3306/xxx?serverVersion=mariadb-10.5.9
```
4/ I'm regenerating the cache with `php bin/console cache:clear`, and it's not working again.

Config is OK when the cache is created, but it's not working.

**Comment by ostrolucky** [comment]
Sorry, we can't help without reproducer.
