### ISSUE TITLE
Charset passed via URL is overridden

### ISSUE THREAD

**Issue by dlegatt** [doctrine/DoctrineBundle#1325]
https://github.com/doctrine/DoctrineBundle/blob/e6a9c16d51a1f0399c7de0099a50cf06527a3ff4/ConnectionFactory.php#L87

Working with SQL Server and wanting to pass the charset through he URL configuration instead of modifying the doctrine.yaml file and I'm finding that this line is automatically overriding whatever charset option I pass.

Example:

In Symfony .env.local: `DATABASE_URL=sqlsrv://sa:password@127.0.0.1/my_db?charset=UTF-8`

I would expect "UTF-8" charset value to be passed to the SQL Server connection driver, but it gets overridden by this line. Can `$params['charset']` be checked before defaulting to `utf8`?

**Comment by ostrolucky** [comment]
Do you have `override_url` option enabled? Can you check if behaviour is same with either value?

**Comment by dlegatt** [comment]
I believe I did test changing that to true or false hd no effect. Debugging and watching the values of the Paramus array, any char set value that I pass via url is lost after this line.

**Comment by ostrolucky** [comment]
Just asking because that line you passed is guarded behind this condition https://github.com/doctrine/DoctrineBundle/blob/e6a9c16d51a1f0399c7de0099a50cf06527a3ff4/ConnectionFactory.php#L60

**Comment by dlegatt** [comment]
I don't believe that option affects this, `$overriddenOptions` is an empty array.  I just made a new Symfony skeleton and only installed the ORM pack. Here is my `$params` after setting `DATABASE_URL` to `sqlsrv://db_user:db_password@127.0.0.1/db_name?charset=UTF-8`. This was right before line 60:

```
array:8 [
  "url" => "sqlsrv://db_user:db_password@127.0.0.1/db_name?charset=UTF-8"
  "driver" => "pdo_mysql"
  "host" => "localhost"
  "port" => null
  "user" => "root"
  "password" => null
  "driverOptions" => []
  "defaultTableOptions" => []
]
```

The `$params` array is correctly defined when `DriverManager::getConnection()` is called on line 76

```
array:10 [
    "url" => "sqlsrv://db_user:db_password@127.0.0.1/db_name?charset=UTF-8"
    "driver" => "sqlsrv"
    "host" => "127.0.0.1"
    "port" => null
    "user" => "db_user"
    "password" => "db_password"
    "driverOptions" => []
    "defaultTableOptions" => []
    "dbname" => "db_name"
    "charset" => "UTF-8"
  ]
```

But the charset value is overwritten as I described

**Comment by nicolas-grekas** [comment]
This `$params['charset'] = 'utf8';` and the if/else around should be wrapped in a `if (! isset($params['charset'])) {` check I suppose.

Can you send a PR @dlegatt please, on branch 2.3.x I suppose, with some tests?
