### ISSUE TITLE
[RFC] Add some tools for translatable entities

### ISSUE THREAD

**Issue by Nek-** [doctrine/DoctrineBundle#1330]
Hello,

One question people can ask themself after they translate their application is how to translate their entities.

Of course, there are many many ways to do it. But I think this bundle can suggest an implementation.

The idea is simple: adding tooling to help to translate entities. By adding this in the doctrine bundle, it also enables API platform to support translated entities by default instead of enforcing custom work every time.

My suggestion would be to add a `TranslatableTrait` and a `TranslationTrait` somehow how it exists in doctrine behavior package from KNP. We could also imagine some tooling for forms and serialization.

I think this would complete the toolset that Symfony has to translate applications.

What do you think about it?

**Comment by stof** [comment]
This bundle is only about wiring the ORM and DBAL with Symfony, not about extending the ORM with extra features. So the feature should either stay in the extension packages (the KNP one for instance) or be directly in the ORM

**Comment by ostrolucky** [comment]
Agreed. We don't want to have this feature in bundle, sorry. Closing here

**Comment by Nek-** [comment]
In this case, does it make sense to add this kind of feature inside the translator of Symfony?
