### ISSUE TITLE
ArrayCollections initialize as null sometimes

### ISSUE THREAD

**Issue by pkly** [doctrine/DoctrineBundle#1333]
Hi, I have this weird issue where (usually during installation, which is a drop -> create -> fixture load) sometimes an entity will load and it's property (which is a collection) will not get initialized (even though in `__construct()` there's `$this->collection = new ArrayCollection();`)
I'm unsure whether this is a purely Doctrine issue or one related to the bundle, so I'm sorry if this is in the incorrect place.
If needed I can try and create a reproduction in a skeleton project.
Overall it's not a huge issue, but it's kinda weird since we need to create special conditions so that this doesn't crash our code.

DoctrineBundle 2.3.1
Doctrine/ORM 2.7.5
Symfony 4.4.21

**Comment by stof** [comment]
the ORM does not run the constructor during hydration. So if you have some properties that are not mapped by the ORM, they won't be initialized if the initialization logic is in the constructor. You would need to use a `postLoad` lifecycle callback.
But anyway, reporting that on the bundle looks wrong to me, as it is only about wiring the ORM. And without reproduction steps, we can only try to guess.

**Comment by ostrolucky** [comment]
Yep, this can't really be a bundle issue. Sorry, closing
