### ISSUE TITLE
Command doctrine:mapping:import does not add default 0 value

### ISSUE THREAD

**Issue by st0at** [doctrine/DoctrineBundle#1336]
When command is run on table with property with default value 0 set in database, command does not add this near property: `options={"default"="0"}`. Other default values, like decimal value 0.00, works fine, "default" value in options is added.

**Comment by ostrolucky** [comment]
Sorry but this command is deprecated and will not receive bugfixes.

**Comment by st0at** [comment]
Is there any alternative to that command?

**Comment by ostrolucky** [comment]
Alternative is unfortunately creating the mapping manually
