### ISSUE TITLE
An option named "em" already exists.

### ISSUE THREAD

**Issue by trickeyone** [doctrine/DoctrineBundle#1338]
I created a new Symfony project with `doctrine/doctrine-bundle` @ 2.3.1 and I'm getting this error when just running `./bin/console` to list available commands.

```
In InputDefinition.php line 232:
                                                        
  [Symfony\Component\Console\Exception\LogicException]  
  An option named "em" already exists.                  
                                                        

Exception trace:
  at /path/to/my/project/app/vendor/symfony/console/Input/InputDefinition.php:232
 Symfony\Component\Console\Input\InputDefinition->addOption() at /path/to/my/project/app/vendor/symfony/console/Command/Command.php:408
 Symfony\Component\Console\Command\Command->addOption() at /path/to/my/project/app/vendor/doctrine/doctrine-bundle/Command/Proxy/ClearMetadataCacheDoctrineCommand.php:32
```

It looks like the issue is that `Doctrine\ORM\Tools\Console\Command\ClearCache\MetadataCommand` already defines the "em" optional as required. This is causing the validation error.

I understand that ORM 2.9 is not release, just wanted to highlight the issue.

Granted, I'm using `doctrine/orm` @ 2.9 to leverage PHP8 attributes, so that is likely is causing the disparity. However, I do not see any changes in `doctrine/orm` or here (2.4) that corrects the issue.

**Comment by stof** [comment]
the fix is already in progress in https://github.com/doctrine/DoctrineBundle/pull/1327

**Comment by trickeyone** [comment]
Thank you!

**Comment by stof** [comment]
I'm closing this issue as doctrine/orm 2.9 is not released yet, and finishing the bundle PR is already in the list of things to do before the release.
