### ISSUE TITLE
Wrapper class option, but warnings about DBAL\Connection constructor

### ISSUE THREAD

**Issue by mewejo** [doctrine/DoctrineBundle#1344]
Hello and thanks for the great work on this.

I'm using the `doctrine.dbal.connections.x.wrapper_class` option, setting it to a class which extends `Doctrine\DBAL\Connection` as documented.

I'm having to redefine the constructor so I can access the original passed params and set them to my own `$params` property, allowing me to change them elsewhere in the connection class. Re-declaring the constructor is throwing this warning:

```
The "Doctrine\DBAL\Connection::__construct()" method is considered internal The connection can be only instantiated by the driver manager. It may change without further notice. You should not extend it from "App\Doctrine\DBAL\OrganizationConnectionWrapper"
```

Having `$params` as private is also a problem elsewhere, as when I need to call connect(), I need to have that method redefined too, so `$params` are passed to the DB driver correctly.

I think this would be solved by `$params` being protected instead of private, or a method allowing them to be set (at the developers risk, as they then wouldn't match the potential current active _conn/connection, maybe an explicit option to enable that per connection?). I prefer not to re-declare methods if I'm not adding functionality to a particular method, and the way I've had to do it seems fragile, and spammed with internal warnings due to the constructor.

I'm using the above to allow a multi tenant application to run on a connection which has its credentials modified via a call to the connection after it has been instantiated by the manager.

I might be doing all of this wrong, sorry if I've completely missed something.

**Comment by ostrolucky** [comment]
What action do you expect from doctrine-bundle? I don't see any suggestion in your post that we can do. All of those issues are in doctrine/dbal, so not sure why is this issue here.

**Comment by mewejo** [comment]
Sorry @ostrolucky - I did check the option was in this repo but looks like it's re-mapped to `wrapperClass` for DBAL.

Teach me for posting an issue quickly! Sorry to waste your time.
