### ISSUE TITLE
Many-to-many with mapped superclass not working

### ISSUE THREAD

**Issue by userfriendly** [doctrine/DoctrineBundle#135]
Not sure if this a bug or not, but I think that according to the docs this should work - in a vendor bundle I have an entity defining a unidirectional many-to-many relation to a mapped superclass, e.g. the entity is Group and defines the many-to-many relation to a UserInterface, which is resolved correctly in the app configuration (as other many-to-one relations defined for it in other entities of this vendor bundle work fine).

I'm going by these docs:

https://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html#mapped-superclasses

http://symfony.com/doc/master/cookbook/doctrine/resolve_target_entity.html

However, I'm getting a weird error:

```
An exception occurred while executing 'INSERT INTO acme_group_user (group_id, user_id) VALUES (?, ?)' with params {"1":2,"2":1,"3":2,"4":1}:

SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
```

For some reason it's adding 4 parameters to the statement instead of 2.

Oddly enough, this works perfectly fine when I replace the mapped superclass in the mapping with the actual final entity. But that wasn't the point of the exercise... :( I need to use the mapped superclass.

Also, other entities in that GroupBundle that are referencing the UserInterface in different relation types, e.g. many-to-one, there the relations work perfectly fine too.

The schema validates as well, using doctrine:schema:validate in the console.

Here's a pastie with all the code and mappings involved: http://pastie.org/5372087

**Comment by AmaliDeveloper** [comment]
You can get the solution in this tutorial Good Work [Link](https://youtu.be/26sKlfv9aJk)
