### ISSUE TITLE
Missing service doctrine.orm.default_attribute_metadata_driver

### ISSUE THREAD

**Issue by spackmat** [doctrine/DoctrineBundle#1355]
Hi, I switched a smaller project to mapping definitions via PHP 8 attributes after upgrading to doctrine/orm to 2.9. I then changed the mapping type in `doctrine.orm.mappings.App.type` from `annotation` to `attribute` to reflect that change. After that, I got that nasty error message:

> The service "doctrine.orm.default_attribute_metadata_driver" has a dependency on a non-existent parameter "doctrine.orm.metadata.attribute.class". Did you mean one of these: "doctrine.orm.metadata.driver_chain.class", "doctrine.orm.metadata.annotation.class", "doctrine.orm.metadata.xml.class", "doctrine.orm.metadata.yml.class", "doctrine.orm.metadata.php.class", "doctrine.orm.metadata.staticphp.class", "doctrine.orm.validator.unique.class"?

Obviously, the service `doctrine.orm.default_attribute_metadata_driver` is not defined, so I added that to the `Resources/config/orm.xml` just below the line for the AnnotationDriver:

```` xml
<parameter key="doctrine.orm.metadata.attribute.class">Doctrine\ORM\Mapping\Driver\AttributeDriver</parameter>
````

Now the error is gone and my code works just fine with attributes mapping instead of annotations mapping.

I'm not sure if that is all to make attributes mapping fly here or if this is the right place to fix that, so I didn't make a PR out of that, yet.

**Comment by ostrolucky** [comment]
This feature will be in 2.4. It's already there in dev branch actually.

**Comment by COil** [comment]
I had the same issue, my doctrine bundle was locked to `2.3.x`. Use :  

    "doctrine/doctrine-bundle": "^2.4"
