### ISSUE TITLE
Idea - Autowire service repositories using a typed interfaced and their FQDN.

### ISSUE THREAD

**Issue by drupol** [doctrine/DoctrineBundle#1370]
Hello,

Today I've been asked if it would be possible to inject repositories using typed interfaces and based on their FQDN.

A bit like the Monolog Bundle and their logger / channels. (https://symfony.com/doc/current/logging/channels_handlers.html#monolog-autowire-channels)

I made a bundle out of it, you can find it here: https://github.com/loophp/service-object-repository-bundle

Do you think it would be a good addition in `symfony/doctrine-bundle` ?

Let me know what, I'm ready to provide the PR for this if you find it useful.

**Comment by stof** [comment]
the use case for custom repositories is to implement custom methods in them. So I don't see a need to typehint them using a generic EntityRepository interface.

**Comment by ostrolucky** [comment]
Also, https://github.com/loophp/service-object-repository-bundle doesn't seem to exist anymore

**Comment by drupol** [comment]
> Also, https://github.com/loophp/service-object-repository-bundle doesn't seem to exist anymore

Indeed, I don't need it anymore. However, this idea could have been generalized for any services, and this bundle can do it in a better way: https://github.com/loophp/service-alias-autoregister-bundle
