### ISSUE TITLE
DoctrineLoader relies on symfony/validator as a peer dependency

### ISSUE THREAD

**Issue by m-vo** [doctrine/DoctrineBundle#1377]
**Description**
`DoctrineExtension#loadValidatorLoader` registers the `DoctrineLoader` as a service. This class uses the `Symfony\Component\Validator\Mapping\Loader\AutoMappingTrait` (from `symfony/validator`) which might not be available.

As soon as this service gets autloaded at container build time* this will produce a fatal error under PHP8.1:

```
PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class "Symfony\Component\Validator\Mapping\Loader\AutoMappingTrait" not found while loading "Symfony\Bridge\Doctrine\Validator\DoctrineLoader`
```

*) one scenario is for instance reading class annotations/attributes and thereby calling `$container->getReflectionClass()` 

**How to reproduce**
1. Set up a Sf application with doctrine-bundle installed.
1. Add a compiler pass that does the following:
    ```php
    foreach ($container->getDefinitions() as $definition) {
      $container->getReflectionClass($definition->getClass(), false);
    }
    ```
1. Build the container.

----
This reminded me a bit of https://github.com/symfony/symfony/issues/32395. :slightly_smiling_face:  Maybe we could mark the service as synthetic if the `AutoMappingTrait` is not available or register a dummy instead?

(ref [symfony/symfony#41796](https://github.com/symfony/symfony/issues/41796))

**Comment by alcaeus** [comment]
Yep, that is correct. IMO, this logic should only be invoked if the `DoctrineLoader` class exists, similar to how other logic is invoked conditionally. A PR with a fix is highly appreciated :)

**Comment by m-vo** [comment]
Alright, I'm closing this in favor of #1379 then.
