### ISSUE TITLE
Can't instantiate custom generator

### ISSUE THREAD

**Issue by julienmiclo** [doctrine/DoctrineBundle#1381]
Hello,

I don't know if is the good place but i have an bug how block me from last 4 days. So you are my last hope until i recreate from scratch (and i don't want to do that).

I do this :
`docker compose exec php bin/console doctrine:fixtures:load`

and make this :
```
[critical] Error thrown while running command "doctrine:fixtures:load". Message: "Can't instantiate custom generator : UlidGeneratorService"

In ClassMetadataFactory.php line 695:

Can't instantiate custom generator : UlidGeneratorService
```
and this :
`2021-07-26T21:16:11+00:00 [info] User Deprecated: Since doctrine/doctrine-bundle 2.4: The "connection_override_options" connection parameter is deprecated`

my **UlidGeneratorService** 
```php
class UlidGeneratorService extends AbstractIdGenerator
{
    public function generate(EntityManager $em, $entity): string
    {
        $ulid = new Ulid();
        return $ulid->toBase58();
    }
}
```
my column in entity :
```php
/**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UlidGeneratorService::class)
     * @ORM\Column(type="string", length=22, unique=true)
     */
    private ?string $id = "";
```

Thank you if you can help me.

**Comment by dmaicher** [comment]
Maybe you should use `@ORM\CustomIdGenerator(class="My\Custom\UlidGeneratorService")` ? So passing the FQCN.

**Comment by julienmiclo** [comment]
OK i'm dumb. Can you explain me why it's works ?

**Comment by dmaicher** [comment]
As you can see from the exception message the class configured was `UlidGeneratorService` which is not a FQCN and so the `class_exists` check here failed:

https://github.com/doctrine/orm/blob/2.9.x/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L648

So the annotation parser could not handle your `@ORM\CustomIdGenerator(class=UlidGeneratorService::class)` annotation

**Comment by jvasseur** [comment]
Actually the annotation reader is capable of understanding the `UlidGeneratorService::class` syntax, you where probably missing an `use` statement making it resolved to the wrong namespace.

**Comment by julienmiclo** [comment]
@dmaicher thank you

@jvasseur no my `use` statement is correct for this class.
