### ISSUE TITLE
Setting the "doctrine.dbal.password" option while the "url" one is defined is deprecated

### ISSUE THREAD

**Issue by zorn-v** [doctrine/DoctrineBundle#1384]
I have setup, where db created with random generated password (docker etc.) and putted in `.env.local`
Base url is defined in `.env` (type/host/user/dbname/dbversion etc is not changed), only part that needed to change is password.
So I have config like this
```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        password: '%env(DB_PASSWORD)%'
#...
```

Yes I can define type/host/user/dbname/dbversion in separate env vars but it seems cumbersome

PS. Init db script looks like this
```bash
#!/bin/bash
set -e
cd `dirname $0`/..

if [ ! -d var/mysql ]
then
    MYSQL_PASSWORD=`openssl rand -hex 32`
    sed -i '/^DB_PASSWORD=/d' .env.local
    echo DB_PASSWORD=$MYSQL_PASSWORD >> .env.local
    export MYSQL_PASSWORD
    docker-compose up -d db
    echo -n Waiting while db will be created...
    while [ ! -d var/mysql/dbname ]
    do
        let 'TRY=TRY+1'
        [ $TRY -ge 60 ] && echo -e ' \033[0;31mFAIL\033[0m' && exit 1
        sleep 1
    done
    echo -e ' \033[0;32mDONE\033[0m'
fi
```

**Comment by ostrolucky** [comment]
That doesn't work though. This is why override_url option was added, but subsequently deprecated. It's also why combining both is deprecated. As you can see different people have different opinion what should override what, hence we are ending never ending discussion by not allowing it.

**Comment by zorn-v** [comment]
> That doesn't work though

But it work as I expect.

> hence we are ending never ending discussion by not allowing it.

Yep, and this is just another opinion.

PS. `url` is lower priority and and other options override it. Whats wrong with it ?

**Comment by ostrolucky** [comment]
It works only in cases when DATABASE_URL doesn't contain password. If it does, it will override whatever was set in password field. These kind of semantics are tricky to get right, that's why it's easier and more transparent to stick with one or the other. What's difficult about exporting whole DATABASE_URL in your init script instead of just DB_PASSWORD?

**Comment by zorn-v** [comment]
> What's difficult about exporting whole DATABASE_URL in your init script instead of just DB_PASSWORD?

Did you write bash scripts sometimes ?
Did you think it is good idea to hardcode something in scripts ?

In other case we need to read url from .env, parse it, paste pasword in right place and then echo to .env.local

**Comment by ostrolucky** [comment]
This is one line change of turning 
```
echo DB_PASSWORD=$MYSQL_PASSWORD >> .env.local
```
into something like
```
echo DATABASE_URL=mysql://root:$MYSQL_PASSWORD@mysql/dbname >> .env.local
```

I fail to see what's bad about it, or why is it better to hardcode things in .env.local but bad in bash script. You are already hardcoding things like volume, database name or variable names in bash script - all of that assumes it alignes with whatever is in .env.local. You also don't care about other variables like mysql user that might be defined in DATABASE_URL and could be different, despite that this entrypoint is responsible for setting this stuff up. And I actually also don't see the point of generating random password there. Anyways, point of deprecation has been explained. Your current logic will fall apart as soon as somebody puts password in DATABASE_URL. If you don't like what I suggested, there is again option of not using `url` option, it's not that cumbersome...

**Comment by zorn-v** [comment]
Well actually that password also needed in other scripts in pure (e.g. for run something like `mysql -p$DB_PASSWORD` or to use it in `docker-compose.yaml`).
Anyway I get your point.

> And I actually also don't see the point of generating random password there.

Here
```bash
MYSQL_PASSWORD=`openssl rand -hex 32`
```

**Comment by ostrolucky** [comment]
I know where you do it, I don't know why you do it. There is no point to have random password on dev machine and this doesn't look like something that should be used on production.

**Comment by zorn-v** [comment]
Yep, it is for production. And for dev also to use same scripts (auto create db and other automatics) with little difference (e.g. `./bin/dev-start` script).
So you just need to `git clone` and `./bin/update` for up new "configured" instance. 
There also some wrappers like `./bin/cli` to run `./bin/console` in configured docker container, `./bin/db-backup` etc. 
Only docker and docker-compose needed on "bare metal machine" without any other project specific dependencies. 
So I can use/switch any version of php/db, can easily attach/detach other services like redis in future if needed, which automatically up in update script and so on. In other words I have full control of used stacks and can easy change its if needed and it will be transparent for "devopsers" of my app (just run `./bin/update`)

About "topic deprecation" seems I just stop using url for db. As you say "it's not that cumbersome" if think better :smile:
