### ISSUE TITLE
serverVersion parameter is documented incorrectly

### ISSUE THREAD

**Issue by mburtscher** [doctrine/DoctrineBundle#1389]
I've struggled to get my Symfony application up and running using a Postgresql database. In Symfony's generated `.env` the documentation for Postgresql says the following:

```php
# For a PostgreSQL database, use: "postgresql://db_user:db_password@127.0.0.1:5432/db_name?serverVersion=11&charset=utf8"
```

However, my application was trying to connect to the database on every startup to automatically detect the server version. I was not even able to call any `bin/console doctrine:database:create` because the application failed on boot before even being able to create the database.

After hours of debugging, I figured out that everything works fine if you use `?server_version=` parameter instead of `?serverVersion=`. Is it possible that this is documented incorrectly?

**Comment by ostrolucky** [comment]
That text is not managed by this repository, but by https://github.com/symfony/recipes. But I do not see how your report can be accurate, we have couple tests for this and it's `serverVersion`, not `server_version`. You might want to provide reproducer.

**Comment by mburtscher** [comment]
@ostrolucky Thank you for the quick reply. I will follow up in the recipes repository if I am able to create a reproducible project. I am quite surprised by the behavior as well 🤷
