### ISSUE TITLE
Is metadata_cache_driver deprecated or not?

### ISSUE THREAD

**Issue by christiaan** [doctrine/DoctrineBundle#1391]
https://github.com/doctrine/DoctrineBundle/blob/2.4.x/UPGRADE-2.3.md has this part

> Configuration
> 
>     The metadata_cache_driver configuration key has been deprecated. PHP Array cache is now automatically registered when %kernel.debug% is false.

However https://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers does not mention metadata_cache_driver being deprecated.

**Comment by stof** [comment]
Looks like the doc needs to be updated

**Comment by christiaan** [comment]
Which of the two?

**Comment by stof** [comment]
The configuration doc is outdated (it looks like it has not been updated to reflect the new deprecation added in DoctrineBundle 2.3)

**Comment by ostrolucky** [comment]
I don't get it, how is it outdated? It's still deprecated https://github.com/doctrine/DoctrineBundle/blob/32c4d1688044d73946ea7257054a2bccf2f8d6a6/DependencyInjection/Configuration.php#L734-L738

**Comment by christiaan** [comment]
This is what confused me.

> The metadata_cache_driver configuration key has been deprecated. PHP Array cache is now automatically registered when %kernel.debug% is false.

Sounds like you can still use other cache_drivers for the metadata. So I looked at the documentation here https://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers and here https://github.com/doctrine/DoctrineBundle/blob/2.4.x/Resources/doc/configuration.rst#caching-drivers

However none of the documentation mentions how this is deprecated. How should I handle the metadata_cache_driver, should I still use it untill it is finally removed, or can I already remove it now and should it be discouraged to use it.

**Comment by ostrolucky** [comment]
You should remove it. Do you have suggestion how to improve the message?

**Comment by christiaan** [comment]
Does the configuration key still do something? If not.

 > The metadata_cache_driver configuration key has been removed. Setting it does not do anything anymore. Metadata caching is now handled automatically and cannot be configured.

And remove all mentions of the key from all documentation.


If however it still does something, then I do not know what it does so I cannot suggest how to handle that.

**Comment by ostrolucky** [comment]
Well it's deprecated so it does something now, but configuration will stop existing in next major version.

**Comment by christiaan** [comment]
In that case

> The metadata_cache_driver configuration key is deprecated. The default metadata cache should now always be faster or as fast as anything you can configure yourself. Remove the configuration to enable the default cache.

**Comment by ruudk** [comment]
@christiaan FWIW, I created [an issue](https://github.com/doctrine/DoctrineBundle/issues/1393) to ask to undo the deprecation. You might see performance decreases when using a large application in debug mode.

**Comment by ostrolucky** [comment]
Undeprecated in https://github.com/doctrine/DoctrineBundle/pull/1405
