### ISSUE TITLE
doctrine:schema:drop --full-database does not drop assets that have been created manually

### ISSUE THREAD

**Issue by jean553** [doctrine/DoctrineBundle#1395]
Doctrine bundle version: 2.4.2

I have two types of database assets/tables:
- tables created with migrations and entities through doctrine commands (`doctrine:migrations:diff`, `doctrine:migrations:migrate`),
- tables created manually outside of Doctrine,

When I execute `doctrine:schema:drop --full-database`, all the tables created through Doctrine are correctly deleted. The tables created manually are not deleted though. So, the "full database" is not deleted.

Is it normal behavior or is it a bug ?

**Comment by ostrolucky** [comment]
Bundle is just providing wiring for the command, logic is in doctrine/orm repository. Create issue there please.
