### ISSUE TITLE
Exception with latest ORM/DBAL

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineBundle#1403]
When trying to load fixtures with ORM 2.10 and DBAL 3:

>In DoctrineCommandHelper.php line 28:
[Symfony\Component\ErrorHandler\Error\ClassNotFoundError]                                        
  Attempted to load class "ConnectionHelper" from namespace "Doctrine\DBAL\Tools\Console\Helper".  
  Did you forget a "use" statement for another namespace?

It was working with ORM 2.9 and DBAL 2.

**Comment by ostrolucky** [comment]
Can you check with dev branch of doctrine-bundle?

**Comment by derrabus** [comment]
This should've been fixed by #1399, but that change had not been released. Please check if DoctrineBundle 2.4.3 fixes the issue for you.

**Comment by garak** [comment]
> This should've been fixed by #1399, but that change had not been released. Please check if DoctrineBundle 2.4.3 fixes the issue for you.

It does. Thank you!
