### ISSUE TITLE
Attempted to load class "ConnectionHelper"

### ISSUE THREAD

**Issue by nicor42** [doctrine/DoctrineBundle#1411]
Hello,

context: `[doctrine/doctrine-bundle:2.3.2]`

when executing a command like: `bin/console doctrine:schema:drop`, I get the error :

```bash
In DoctrineCommandHelper.php line 28:

  Attempted to load class "ConnectionHelper" from namespace "Doctrine\DBAL\Tools\Console\Helper".
  Did you forget a "use" statement for another namespace?
```

This is supposed to be fixed in version `2.4` with https://github.com/doctrine/DoctrineBundle/pull/1399

mainly with the following code : (Command/Proxy/DoctrineCommandHelper.php:28)

```php
        if (class_exists(ConnectionHelper::class)) {
            $helperSet->set(new ConnectionHelper($em->getConnection()), 'db');
        }
```

Is it possible to fix it for lower versions, like `2.3` ?

(for project dependencies reasons, I cannot yet upgrade)

thank you

**Comment by ostrolucky** [comment]
No sorry, 2.3 is not maintained.

**Comment by stof** [comment]
Note that if you cannot updated to doctrine-bundle 2.4, a workaround is to stick to DBAL 2.x instead of using 3.x

**Comment by nicor42** [comment]
`composer require "doctrine/dbal:^2.13"` works for me 🎉 . thanks for the tip
