### ISSUE TITLE
Driver options are not passed to the primary\replica configuration

### ISSUE THREAD

**Issue by GDXbsv** [doctrine/DoctrineBundle#1416]
When we use 
```
  'options'               => [
      \PDO::ATTR_STRINGIFY_FETCHES        => 1,
      \PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false
  ],
```
With one connection without replicas, this options passed in the driver configuration. (See \Doctrine\DBAL\Driver\PDO\MySQL\Driver::connect --> `$params['driverOptions']`)

When we add a replica, then the bundle do not include those driver options in the replica and primary configuration options.

**Comment by ostrolucky** [comment]
We don't do that, because doing that causes other issues, like https://github.com/doctrine/DoctrineBundle/pull/1253. Can you try if you experience expected behaviour with doctrine-bundle 2.2.0? That's the version where we did pass driverOptions over to replicas.

**Comment by GDXbsv** [comment]
I did try 2.2.0 it does not work.

1. It does not work with dbal3, so I had to test with dbal2
2. the bundle pass driver options in the new format for dbal3 which is not fit to dbal2, so it can not work at all.
3. But even in this case according to xdebug options exists only in primary but not in replica. In the last version, they were removed from primary as well.

I mostly need to pass to all the connections \PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false. Is it a way how I can do it differently?

**Comment by ostrolucky** [comment]
I think you just have to pass options explicitly to each replica config instead of relying on them being passed from the primary config. How does your config look like?

**Comment by GDXbsv** [comment]
But I can not pass. The bundle does not support it.
And in new version they even do not go in primary, the bundle do not pass them from the main config.

My config:
```
                    'default' => [
                        'server_version'        => '5.7',
                        'charset'               => 'utf8mb4',
                        'options'               => [
                            \PDO::ATTR_STRINGIFY_FETCHES        => 1,
                            \PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false
                        ],
                        'default_table_options' => [
                            'charset' => 'utf8mb4',
                            'collate' => 'utf8mb4_unicode_ci',
                        ],
                        'mapping_types'         => ['uuid_binary' => 'binary'],
                        'url'                   => '%env(resolve:DATABASE_URL)%',
                        'keep_replica'          => false,
                         'replicas'              => [
                             'replica' => [
                                 'url'            => '%env(DATABASE_REPLICA_URL)%',
                             ],
                         ],
                    ],
```

**Comment by Alez** [comment]
Can confirm. As of now, there is no way to pass DriverOptions via config .
dbal 3.3.1
bundle 2.5.2
