### ISSUE TITLE
Deprecation in Symfony 5.4

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineBundle#1427]
The "Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension::getMappingResourceConfigDirectory()" method will require a new "string|null $bundleDir" argument in the next major version of its parent class "Symfony\Bridge\Doctrine\DependencyInjection\AbstractDoctrineExtension", not defining it is deprecated.

**Comment by dmaicher** [comment]
Should be resolved on 2.5.x?

**Comment by ostrolucky** [comment]
Correct, it will be resolved in 2.5.
