### ISSUE TITLE
Incompatible interfaces

### ISSUE THREAD

**Issue by andreo-code** [doctrine/DoctrineBundle#1428]
Hi. I started a new project and package installation fails.

`Declaration of Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension::getMappingResourceConfigDirectory(): string must be compatible with Symfony\Bridge\Doctrine\DependencyInjection\AbstractDoctrineExtension::getMappingResourceConfigDirectory(?string $bundleDir = null): string`

Stack:
PHP 8.1 
Bundle version: latest ^3.0
Symfony version: latest ^6.0

Best Regards.

**Comment by derrabus** [comment]
I've transferred this issue because it has nothing to do with DoctrineMigrationsBundle.

Your issue was fixed by #1418. Can you upgrade DoctrineBundle to `^2.5@dev` and check if the error goes away?

**Comment by derrabus** [comment]
@ostrolucky Can we release 2.5.0 soon-ish to address this issue?

**Comment by ostrolucky** [comment]
Users should be reporting this on Symfony side, not here. BC break happened there. Anyways, 2.5 released

**Comment by derrabus** [comment]
Thank you!
