### ISSUE TITLE
Wire a middleware for logging

### ISSUE THREAD

**Issue by derrabus** [doctrine/DoctrineBundle#1429]
Follows doctrine/dbal#4967

The way we currently use to wire a logger is deprecated in DBAL 3.2 and has been removed in DBAL 4. We should instead wire the new middleware.

**Comment by wnunezc** [comment]
I wonder how this goes; the update of the package in which version will it be corrected?

![image](https://user-images.githubusercontent.com/1207306/145883288-6f8e96f0-6d41-489e-8471-11e884628bed.png)

![image](https://user-images.githubusercontent.com/1207306/145883323-00f89044-8c11-4a10-8f7d-d1c2f8beb1fa.png)

![image](https://user-images.githubusercontent.com/1207306/145883416-bdaf7bad-b9f5-4d18-9117-e7b74b8c46cf.png)

**Comment by derrabus** [comment]
> I wonder how this goes; the update of the package in which version will it be corrected?

It will be corrected as soon as somebody corrects it.

**Comment by dmaicher** [comment]
Done in https://github.com/doctrine/DoctrineBundle/pull/1456
