### ISSUE TITLE
Issue while loading cache.

### ISSUE THREAD

**Issue by xenatis** [doctrine/DoctrineBundle#1433]
Hello,
I am having an issue with symfony cache, triggering the firewall of my host (infomaniak.com). The bug appends in PhpFilesAdapter.php, at line 145 } elseif (\is_array($expiresAt = include $file)) {.

This bug occure only in prod environnement , not in dev.

It appens when loading data cached by Doctrine.

server error log contains these two lines:
dev2.mtrestauration.ch [Wed Nov 24 17:31:07.895529 2021] [fastcgi:error] [pid 28937:tid 140261951948544] (104)Connection reset by peer: [client 185.89.252.62:0] FastCGI: comm with server "/home/clients/7573ef37723d942376be65f1b4365d88/.config/apache/my.domain.ch/.fpm/php5.external" aborted: read failed: "Connection reset by peer"

dev2.mtrestauration.ch [Wed Nov 24 17:31:07.895597 2021] [fastcgi:error] [pid 28937:tid 140261951948544] [client 185.89.252.62:0] FastCGI: incomplete headers (0 bytes) received from server "/home/clients
/7573ef37723d942376be65f1b4365d88/.config/apache/my.domain.ch/.fpm/php5.external"

Content of the file issuing the error
[AEgM13ZzWZDKCG0XaHuQ.txt](https://github.com/doctrine/DoctrineBundle/files/7597750/AEgM13ZzWZDKCG0XaHuQ.txt)

Is there any way to use another type of cache or to solve this issue?
Thanks!

**Comment by ostrolucky** [comment]
Sorry, I don't see how is this related to doctrine bundle.

**Comment by Gulivertx** [comment]
Hello,
I have the same error.
But this error not  appears if I switch to dev environment. Something with MYSQL/Doctrine cache but not sure...

`
www.bulledeculture.ch [Tue Nov 30 13:48:05.543083 2021] [fastcgi:error] [pid 1744:tid 140066793940736] (104)Connection reset by peer: [client 82.146.220.4:0] FastCGI: comm with server "/home/clients/f440899c544cc1a5f2f8712ea7101c00/.config/apache/www.bulledeculture.ch/.fpm/php5.external" aborted: read failed: "Connection reset by peer"
`

@xenatis are you on Infomaniak cloud server ? Edit : Just see that yes, as us. Sounds like this error come from Infomaniak.

**Comment by xenatis** [comment]
I am on Infomaniak "mutualisé".

It appears that is it a PHP 7.4.25 issue, while reading THAT file. 

I did tests with PHP 8.0.1 and 7.3, no problem.

**Comment by Gulivertx** [comment]
> I am on Infomaniak "mutualisé".
> 
> It appears that is it a PHP 7.4.25 issue, while reading THAT file.
> 
> I did tests with PHP 8.0.1 and 7.3, no problem.

Thanks for your answer, ok if I change the PHP version I also not have any problem. Only with PHP 7.4.25 on a cloud server.

**Comment by seyfcom** [comment]
Exact same problems on Infomaniak shared hosting. 
@ostrolucky Thats not really helping your quick reaction. It is maybe not only doctrine, but it can help a lot of people to find it here. The problem is in doctrine's code with php 7.4.25.

**Comment by nicolas-grekas** [comment]
This looks like a duplicate of https://github.com/symfony/symfony/issues/44256 (@ostrolucky was right closing therefore ;) )
Please provide a reproducer there.

**Comment by sdespont** [comment]
@seyfcom @xenatis I have asked Infomaniak to update the PHP version of my cloud server to 7.4.26. Unfortunately, the problem persist with the last PHP version.

**Comment by sdespont** [comment]
Downgrading to "doctrine/orm": "2.9.*" is working. Version 2.10 introduces "Support for PSR-6 result caches". Would it be a possible reason?
