### ISSUE TITLE
Attribute "AsEntityListener" is missing the "entity" argument

### ISSUE THREAD

**Issue by SimonMarx** [doctrine/DoctrineBundle#1438]
Hey,

currently im switching everything to attributes in my project. I have some EntityListeners and want to use the `AsEntityListener` attribute for it.

i would expect that i can it assign like:

```php
#[AsEntityListener(event: Events::prePersist, entity: AuthToken::class)]
class AuthTokenPrePersistListener
{
    public function __invoke(AuthToken $token, LifecycleEventArgs $args): void
    {
        // do stuff
    }
}
```

But checking the AsEntityListener class shows that i cannot assign a entity class to that listener attribute

```php
class AsEntityListener
{
    public function __construct(
        public ?string $event = null,
        public ?string $method = null,
        public ?bool $lazy = null,
        public ?string $entityManager = null
    ) {
    }
}
```

Shouldn't it be possible by adding `public ?string entity = null` argument to the Attribute construct and then extends the part where the Autoconfiguration is configured in the `DoctrineExtension`?

```php
            $container->registerAttributeForAutoconfiguration(AsEntityListener::class, static function (ChildDefinition $definition, AsEntityListener $attribute) {
                $definition->addTag('doctrine.orm.entity_listener', [
                    'event'          => $attribute->event,
                    'method'         => $attribute->method,
                    'lazy'           => $attribute->lazy,
                    'entity_manager' => $attribute->entityManager,
                    'entity'         => $attribute->entity      // extended to add entity as attribute
                ]);
            });
```

Am i wrong? Do i miss some part of code where is described what to do when using the `AsEntityListener` to assign it explicit to a entity class?

**Comment by ostrolucky** [comment]
AsEntityListener is for symfony event dispatcher. LifecycleEventArgs is for doctrine dispatcher. So you cannot use AsEntityListener for it.

**Comment by stof** [comment]
@ostrolucky aren't you confusing `AsEntityListener` and `AsEventListener` ? there is no concept of entity listener in the Symfony dispatcher.

**Comment by stof** [comment]
The change suggested by @SimonMarx actually makes sense. The `doctrine.orm.entity_listener` tag indeed has an optional `entity` attribute that is not supported by the `AsEntityListener` added in https://github.com/doctrine/DoctrineBundle/pull/1345
