### ISSUE TITLE
Add support for `SchemaIgnoreClasses`

### ISSUE THREAD

**Issue by simPod** [doctrine/DoctrineBundle#1454]
I was thinking if we could add `SchemaIgnoreClasses` config (https://github.com/doctrine/orm/pull/9202)

_I checked if I could do it myself but I'm not very familiar with symfony bundles and it seemed too difficult when considered the time I'd have to invest in it_

**Comment by dmaicher** [comment]
Implemented in https://github.com/doctrine/DoctrineBundle/pull/1532
