### ISSUE TITLE
Provide abstraction for the collector

### ISSUE THREAD

**Issue by 0xPaul** [doctrine/DoctrineBundle#1464]
The collector feature is very useful for any Symfony project that interacts with a SQL database, however, not all projects use Doctrine. In particular, I use [amphp/postgres](https://github.com/amphp/postgres) and would very much like to write and maintain a bundle integration that can reuse the collector in this library by plugging in queries and timings collected from the Amp library instead. Could we work together to find a way to make the entire collector feature reusable for different database library back-ends?

**Comment by ostrolucky** [comment]
I'm not sure how feasible is it. Our collector requires orm, dbal, symfony bridge. If you have solution to that, I'm open to the idea, but I don't want to do the work myself. Feel free to hit me up on https://www.doctrine-project.org/slack

**Comment by ostrolucky** [comment]
Looks like this went nowhere
