### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by nedelyux** [doctrine/DoctrineBundle#1466]
You need replace
`
    ports:
      - "5432"
`

to 

`
    ports:
      - "5432:5432"
`

in `docker-compose.override.yml
`

**Comment by ostrolucky** [comment]
Wrong repository. We don't ship docker-compose file.

**Comment by jurchiks** [comment]
@ostrolucky which is the right repository then? I tried searching for the right one, but all I found was this issue.

This error occurs when installing `symfony/orm-pack`, which adds the following block of code to `docker-compose.override.yml` (_if_ you're using Docker, e.g. via `dunglas/symfony-docker`):
```
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
```

However, this port configuration means that port 5432 of _db container_ is exposed via a _random_ port on the _host machine_, which makes it inconvenient to work with. Hence why the suggested change to `"5432:5432"` to expose the same port to the host machine.

Clearly, the comment in the code block states that it comes from this repository. Also, `symfony/orm-pack` does not contain any code itself, only a `composer.json` file, so it can't possibly be the source of this code block.

**Comment by andrew-demb** [comment]
@jurchiks here it is  https://github.com/symfony/recipes/blob/41d2cf13ea897a08b0f376d20011a69a73ec0366/doctrine/doctrine-bundle/2.8/manifest.json#L44
