### ISSUE TITLE
Log DBAL2.13 deprecations in Symfony profiler?

### ISSUE THREAD

**Issue by sofigio** [doctrine/DoctrineBundle#1473]
Hello, 

I see DBAL 2.13 added the deprecations logging, disabled by default (https://www.doctrine-project.org/2021/03/29/dbal-2.13.html ) 

How can I enable it in Symfony, to show in the profiler when, for example, `fetch()` is used instead of `fetchAssociative()`? 
In the configuration reference I found nothing...

**Comment by ostrolucky** [comment]
Add `\Doctrine\Deprecations\Deprecation::enableWithTriggerError()` to index.php. Seamless integration won't happen here, it was decided in past that for seamless integration, doctrine/deprecations package should integrate a symfony bundle itself.. https://github.com/symfony/symfony/pull/41408
