### ISSUE TITLE
instalation with symfony 4.4. throws error

### ISSUE THREAD

**Issue by hulvat** [doctrine/DoctrineBundle#1474]
After composer require doctrine/doctrine-bundle in fresh symfony instalation composer throws error 

_There is no extension able to load the configuration for "when@test" (in "C:\www\score-test\config/packages/doctrine.yaml"). Looked for namespace "when@test", found
!!     ""framework", "doctrine""_

Steps to reproduce
1. composer create-project symfony/skeleton:"4.4.*" project
2. cd project
3. composer require doctrine/doctrine-bundle

**Comment by ostrolucky** [comment]
1. This is not an doctrine-bundle issue, but issue of symfony recipe, that can be reported at https://github.com/symfony/recipes
2. It doesn't make sense to create new projects with symfony 4.4

**Comment by weaverryan** [comment]
Yes, this was done by design to make for a better experience for everyone, but with the negative of giving an error when installing on 4.4. But I agree that I would not expect anyone to be starting a new 4.4 app.

**Comment by nicolas-grekas** [comment]
https://github.com/symfony/recipes/pull/1056 should help
