### ISSUE TITLE
False collation on current 2.6.x-dev 89b7ed6 version

### ISSUE THREAD

**Issue by alexander-schranz** [doctrine/DoctrineBundle#1480]
### Bug Report

I'm trying to find out why my table schema is not correclty utf8mb4 after using `@dev` dependencies.

|    Q        |   A
|------------ | ------
| Version     | 2.6.x-dev 89b7ed6
| MySQL       | 5.7.37 / 8.0.27
| PHP         | 8.1.2

#### Summary

On current stable version all is correctly in my database utf8mb4. I have no collation set manually in doctrine.yaml. But after ugprading to `@dev` version the collation is created not longer as utf8mb4 which was the default since I think dbal 3 for mysql.

#### Current behaviour

The schema has a strange mixed collation now:

<img width="338" alt="Bildschirmfoto 2022-03-02 um 13 33 18" src="https://user-images.githubusercontent.com/1698337/156362671-6522911e-70fd-4a4a-8e42-6001ba7f11c8.png">

#### How to reproduce

```php
composer create-project sulu/skeleton
cd skeleton
composer config minimum-stability dev
composer update # installs doctrine-bundle 2.6.x-dev 89b7ed6
docker compose up
bin/console sulu:build dev
# check database e.g. `ac_activities` table
```

#### Expected behaviour

On 2.5.6 all works like expected:

<img width="335" alt="Bildschirmfoto 2022-03-02 um 13 36 43" src="https://user-images.githubusercontent.com/1698337/156362823-7fee5214-a38d-427c-b532-dad4081c5f73.png">

Maybe related to https://github.com/doctrine/DoctrineBundle/pull/1478 /cc @greg0ire

**Comment by ostrolucky** [comment]
I don't think we changed anything in doctrine-bundle that could have affected this. You should find first which dependency caused this (most likely dbal).

**Comment by alexander-schranz** [comment]
@ostrolucky already tested that. If I'm downgrading only doctrine-bundle to 2.5.6 and all other dependencies are unchanged the collation is correctly created.

The first run is with 2.6.x-dev https://github.com/doctrine/DoctrineBundle/commit/89b7ed68029975f44819f4db5dc756ea211920ea
The second one with 2.5.6

all other dependencies are the same:

![doctrine](https://user-images.githubusercontent.com/1698337/156369441-35007e2b-ee47-417f-9146-24fb470f92af.gif)

**Comment by dmaicher** [comment]
Strange... I also cannot spot anything that would explain this issue in the [diff](https://github.com/doctrine/DoctrineBundle/compare/2.5.6..2.6.x)

**Comment by alexander-schranz** [comment]
I would think that maybe doctrine/dbal still requires both to be define collate and collation: 

Now only the new option is defined: https://github.com/doctrine/DoctrineBundle/commit/f1423b2a640b6ac545b6e0c02575427a4dc1e9dc#diff-df25e842a7fa5aa6cfb5504f8a15789ce8988d620bcd4ace17d2000222feb507

But need to test that out if I added the other option if it works then.

Manually defining the default table options did atleast use the utf8mb4 this way did create the correct schema:

```
doctrine:
    dbal:
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
```

So it need have todo with the table default options.

**Comment by greg0ire** [comment]
Do you have any charset option defined in your database_url as well?

> Maybe related to https://github.com/doctrine/DoctrineBundle/pull/1478 /cc @greg0ire

It does look related, maybe you can try pinning to a commit before and after my PR, and see what happens?

**Comment by alexander-schranz** [comment]
@greg0ire we have nothing define also not in the `doctrine.yaml`:

https://github.com/sulu/skeleton/blob/2.x/config/packages/doctrine.yaml
https://github.com/sulu/skeleton/blob/2cb154888d20fd71022b8636a46015649cf05166/.env#L44

Defining it is just the current workaround.

**Comment by greg0ire** [comment]
Here is why I asked: https://github.com/symfony/recipes/pull/1059

Are you going through this code path: https://github.com/doctrine/DoctrineBundle/blob/6e578fd23ddb656af5c47c1014576490cebd4b0a/ConnectionFactory.php#L85-L87 ?

**Comment by alexander-schranz** [comment]
On commit `f1423b2a640b6ac545b6e0c02575427a4dc1e9dc` (2.5.6) it works and on next commit `1b75234e580e1682a57468d6af7ac5c9d4688d0c` it fails:

```
commit 1b75234e580e1682a57468d6af7ac5c9d4688d0c (HEAD)
Merge: 543ec0f f1423b2
Author: Grégoire Paris <postmaster@greg0ire.fr>
Date:   Sun Feb 13 22:48:32 2022 +0100

    Merge pull request #1477 from doctrine/2.5.x

    Merge 2.5.x up into 2.6.x
```

https://github.com/doctrine/DoctrineBundle/commit/1b75234e580e1682a57468d6af7ac5c9d4688d0c

**Comment by alexander-schranz** [comment]
Its strange on 2.5.6 the `$driver` is: Doctrine\DBAL\Driver\PDO\MySQL\Driver
on that commit `$driver` is: Doctrine\DBAL\Logging\Driver

**Comment by alexander-schranz** [comment]
That is why on that commit the `utf8mb4` part is skipt.

**Comment by alexander-schranz** [comment]
Changing:

```diff
-                if ($driver instanceof AbstractMySQLDriver) {
+                if ($driver->getDatabasePlatform() instanceof AbstractMySQLPlatform) {
```

Seems to work.

**Comment by greg0ire** [comment]
I think what broke this was https://github.com/doctrine/DoctrineBundle/pull/1456

**Comment by alexander-schranz** [comment]
Yes I tested the `2.5.x` on that works and `2.6.x` does not work. I also think it related to the logging middleware handling. But could not yet found a solution for it which does not make any tests failing.

**Comment by alexander-schranz** [comment]
We got a report from a doctrine-bundle `2.5.6` project which did have the same problem only on production. After debugging I have found out on production there is `Sentry` enabled which is also decorating the `Driver` and they end so in the same scenario with the tracingdriver of sentry:

https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/Doctrine/DBAL/TracingDriverForV3.php

**Comment by greg0ire** [comment]
One more reason to strongly deprecate this codepath.

**Comment by alexander-schranz** [comment]
@greg0ire time to bring back ensure production config command which requires than serverVersion and charset being set ;)

**Comment by Mika56** [comment]
Confirming we're only seeing this issue when SentryBundle is enabled.
Workaround is enabling SentryBundle only in `prod` in your `config/bundles.php` file

**Comment by alexander-schranz** [comment]
@Mika56 I recommend setting the `charset` on your server in the `DATABASE_URL`:

https://github.com/symfony/recipes/pull/1059/files#diff-12d522d4ed600c8eef096cb3ea3fcaa411fe6f3ba6aeb2039f822e7e57250727L14

**Comment by Mika56** [comment]
@alexander-schranz That did not fix the problem for us. Our migrations were trying to MODIFY every string column in the down() part
