### ISSUE TITLE
Add an option to skip errors

### ISSUE THREAD

**Issue by Lenny4** [doctrine/DoctrineBundle#1484]
When you try to import a bdd with:
```php
php bin/console doctrine:mapping:import "App\Entity" attribute --path=src/Entity
```
And at least one of the table doesn't have a primary key you get this message:
`Table my-table has no primary key. Doctrine does not support reverse engineering from tables that don't have a primary key.`

When I type `php bin/console doctrine:mapping:import --help` I don't see any option to skip table with no primary key. We only have a `filter` option where we can write a pattern to import only specific entities.

It would be great to have a `--skip-no-primary-key-table` or simply a `--skip-error-table`.

This way at the end the command output all succeded table and all error table.

For this specific error `Table my-table has no primary key. Doctrine does not support reverse engineering from tables that don't have a primary key.` to solve it we just need to change `lib/Doctrine/ORM/Mapping/Driver/DatabaseDriver.php`:

```php
if (! $table->hasPrimaryKey()) {
    throw new MappingException(
        'Table ' . $table->getName() . ' has no primary key. Doctrine does not ' .
        "support reverse engineering from tables that don't have a primary key."
    );
}
```
become
```php
if (! $table->hasPrimaryKey()) {
    if ($skipNoPrimaryKey) {
        // add table name in an array (in order to output error table when the command is over)
        continue;
    }
    throw new MappingException(
        'Table ' . $table->getName() . ' has no primary key. Doctrine does not ' .
        "support reverse engineering from tables that don't have a primary key."
    );
}

```

**Comment by ostrolucky** [comment]
Sorry, this is command is deprecated and we won't provide any more support for it

**Comment by Lenny4** [comment]
Hello @ostrolucky,

why is it deprecated ?

**Comment by ostrolucky** [comment]
Because it's deprecated in ORM
