### ISSUE TITLE
Error on middleware on 2.6 with logger

### ISSUE THREAD

**Issue by loic425** [doctrine/DoctrineBundle#1487]
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Doctrine\DBAL\Logging\Middleware::__construct() must implement interface Psr\Log\LoggerInterface, null given, called in /home/runner/work/SyliusResourceBundle/SyliusResourceBundle/src/Bundle/test/var/cache/test/ContainerRRyfIex/srcApp_KernelTestDebugContainer.php on line 3913 in /home/runner/work/SyliusResourceBundle/SyliusResourceBundle/vendor/doctrine/dbal/src/Logging/Middleware.php:16

versions
* doctrine/dbal 3.3.4

This is not the same error message as https://github.com/doctrine/DoctrineBundle/issues/1485 so, I added this one.

**Comment by dmaicher** [comment]
Indeed this can happen in case the `logger` service does not exist :confused: We need to handle this case

**Comment by l-vo** [comment]
@dmaicher fix suggestion pushed 🙏
