### ISSUE TITLE
Deprecation warning on Symfony\Bridge\Doctrine\Logger\DbalLogger

### ISSUE THREAD

**Issue by r-martins** [doctrine/DoctrineBundle#1489]
When running a bin/phunit, I get a deprecation warning:

> 1x: The "Symfony\Bridge\Doctrine\Logger\DbalLogger" class implements "Doctrine\DBAL\Logging\SQLLogger" that is deprecated Use {@see \Doctrine\DBAL\Logging\Middleware} or implement {@see \Doctrine\DBAL\Driver\Middleware} instead.

The best solution I could see so far was [this one](https://github.com/symfony/symfony/discussions/44307)...
>You don't. It'll get fixed in a combination of the symfony/doctrine-bridge and doctrine/doctrine-bundle packages.

Sorry if it's a duplicated and/or will be fixed on #1431.

I'm using `doctrine/doctrine-bundle` 2.6.0.

**Comment by r-martins** [comment]
Sorry, I noticed this is related to [Symfony/Doctrine-Bridge](https://github.com/symfony/doctrine-bridge) and this is already noted there in [this issue](https://github.com/symfony/symfony/issues/44495).

It points out to https://github.com/doctrine/DoctrineBundle/issues/1431 and https://github.com/doctrine/DoctrineBundle/issues/1429, and was fixed on https://github.com/doctrine/DoctrineBundle/pull/1456.

**Comment by dmaicher** [comment]
indeed this deprecation will be fixed if https://github.com/doctrine/DoctrineBundle/issues/1431 is implemented. So currently you cannot get rid of it yet.
