### ISSUE TITLE
doctrine:generate:entity doesn't create entity in right namespace with bundle inheritance

### ISSUE THREAD

**Issue by brunoroux** [doctrine/DoctrineBundle#149]
I use doctrine ORM in a symfony 2 project

I have 2 bundles in my project : a "GMPCommonBundle" and a "GMPLesNouvellesBundle".
GMPCommonBundle is parent of GMPLesNouvellesBundle

I used the following command line : php app/console doctrine:generate:entity --entity="GMPCommonBundle:Article"

The generated entity is in src/GMP/LesNouvellesBundle/Entity folder and its namespace is : namespace GMP\LesNouvellesBundle\Entity;

Afterwards I tried to update DB schema from generated entity with : php app/console doctrine:schema:update --dump-sql

I just had a "No Metadata Classes to process."

**Comment by Majkl578** [comment]
Closing this as wont fix here since entity generator is deprecated and will be removed in ORM 3.0. Sorry that it hasn't been adressed for such a long time.
