### ISSUE TITLE
MiddlewaresPass: You have requested a non-existent parameter "doctrine.connections"

### ISSUE THREAD

**Issue by Rastusik** [doctrine/DoctrineBundle#1494]
Hi, there is an error in the `Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\MiddlewaresPass` in doctrine-bundle **2.6.0**, specifically on line 34:
```php
foreach (array_keys($container->getParameter('doctrine.connections')) as $name) {
```
The compiler pass expects the `doctrine.connections` parameter to be set at all times, but this doesn't have to be true, because in the bundle extension, there is this condition:
```php
if (! empty($config['dbal'])) {
            $this->dbalLoad($config['dbal'], $container);
```
The method `dbalLoad` populates the `doctrine.conntections` parameter.

Usually, this problem shouldn't be occurring, because in the applications, the dbal configuration has to be present when using Doctrine.
But there is a special case - when developing bundles where doctrine-bundle is just a soft dependency. Som test suites may have enabled doctrine globally, but not configured it for each of the tests. Such tests break because of the expectation of the MiddlewaresPass.

I still can workaround this in our test suite, but shouldn't this situation be considered as a bug?

**Comment by stof** [comment]
this should indeed be fixed. The MiddlewaresPass should have an early return if the parameter is not defined (as it will have nothing to do).
Can you send a PR with the fix ?

**Comment by Rastusik** [comment]
@stof yeah, done. not sure if there should be any other changes regarding tests or other things
