### ISSUE TITLE
"There is no active transaction" during migration after upgrade from 2.5.7 to 2.6.0 

### ISSUE THREAD

**Issue by alexander-samusevich-sab** [doctrine/DoctrineBundle#1496]
Hello everyone!
I faced error during execute migration after upgrade `doctrine/doctrine-bundle` from 2.5.7 to 2.6.0. 
I tried to add `isTransactional()` method in the my migration class with `return false` but it didn't help. I have analized log of composer update and noticed that doctrine-bundle was upgraded to the new minor version. I reverted only doctrine-bundle back to 2.5.7  to check it and now migration works fine.

I use PHP 8.1, Symfony 5.4.7. Composer.lock file attached.
Thanks!

[composer.lock.zip](https://github.com/doctrine/DoctrineBundle/files/8402846/composer.lock.zip)

**Comment by dmaicher** [comment]
This was fixed in https://github.com/doctrine/migrations/pull/1249
