### ISSUE TITLE
Logging is enabled on prod since v2.6

### ISSUE THREAD

**Issue by gharlan** [doctrine/DoctrineBundle#1504]
Since 2.6 the logging classes are used on prod env.
I have noticed that in my monolog error mails on prod. With v2.5 there are no log messages in doctrine channel, with v2.6 I see all query logs etc. inside these error mails.

Is this change intended?

**Comment by dmaicher** [comment]
Indeed. This should be fixed by https://github.com/doctrine/DoctrineBundle/pull/1500

Let me quickly verify this locally. Then I think we can release 2.6.2 @ostrolucky ?

**Comment by ostrolucky** [comment]
2.6.2 released
