### ISSUE TITLE
Fix doctrine/orm deprecation: create + wire EntityManagerProvider for commands

### ISSUE THREAD

**Issue by dmaicher** [doctrine/DoctrineBundle#1509]
Since https://github.com/doctrine/orm/pull/8524 there is a new way of providing entity managers for the ORM commands. The currently used Helperset is deprecated.

So as a follow-up for https://github.com/doctrine/DoctrineBundle/pull/1327 we should create a new class that implements `Doctrine\ORM\Tools\Console\EntityManagerProvider` and uses a `Doctrine\Persistence\ManagerRegistry` to provide the default or named manager instance for the ORM commands.

We should probably also bump the minimum supported ORM version to make it easier.

Did I forget something @beberlei ? :blush:

**Comment by ostrolucky** [comment]
We already have https://github.com/doctrine/DoctrineBundle/blob/2.6.x/Dbal/ManagerRegistryAwareConnectionProvider.php. What else is needed?

**Comment by dmaicher** [comment]
> We already have https://github.com/doctrine/DoctrineBundle/blob/2.6.x/Dbal/ManagerRegistryAwareConnectionProvider.php. What else is needed?

Yeah we have that one for DBAL. We need something similar for ORM that implements [`Doctrine\ORM\Tools\Console\EntityManagerProvider`](https://github.com/doctrine/orm/blob/2.12.x/lib/Doctrine/ORM/Tools/Console/EntityManagerProvider.php#L9).
