### ISSUE TITLE
Use ArgumentResolverInterface for Doctrine Entities

### ISSUE THREAD

**Issue by Hanmac** [doctrine/DoctrineBundle#1527]
While reading the Doc for https://symfony.com/doc/current/controller/argument_value_resolver.html

i was wondering why there isn't a generic Value Resolver for entities managed by Doctrine

it says that it maybe collides with https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/converters.html and that the auto_convert needs to be disabled.

is there an advantage of the ParamConverter over using a ArgumentValueResolver?

From what i see only the 404 one?

**Comment by stof** [comment]
There is none because https://github.com/symfony/symfony/pull/43854 is not merged yet.

**Comment by stof** [comment]
there is no advantage for ParamConverter. ParamConverter is the older implementation of the feature is a third-party bundle. ArgumentValueResolver is meant to replace ParamConverter, but some of them (and in particular the doctrine resolver) were not implemented when doing the initial work on the feature, and then forgotten.

**Comment by Hanmac** [comment]
thanks i was looking for the wrong repository,  i will checkout the other issue too

**Comment by Hanmac** [comment]
Closed in favor of https://github.com/symfony/symfony/pull/43854

**Comment by stof** [comment]
Well, DoctrineBundle will indeed have some work to do to enable the ArgumentValueResolver. But only after the resolver is available in Symfony.

**Comment by Hanmac** [comment]
ah, once again i confused DoctrineBridge with DoctrineBundle

as for configuration, like enabling all routes, i don't know if that would be part of the bridge or the bundle
