### ISSUE TITLE
ProfilerController service not loaded when orm is not enabled.

### ISSUE THREAD

**Issue by ju1ius** [doctrine/DoctrineBundle#1530]
Since it's service definition resides in `Resources/config/orm.xml`, it's not available unless the orm is enabled.

Looking at the controller, it seems that there's nothing in there specifically requiring the orm, so shouldn't it be moved to the `Resources/config/dbal.xml` file?

**Comment by dmaicher** [comment]
Indeed the `ProfilerController` should also work when only using DBAL I guess.

@ju1ius could you test moving the definition into the dbal config and see if it works? If so could you open a PR to fix it? :blush:

**Comment by ju1ius** [comment]
> could you test moving the definition into the dbal config and see if it works?

@dmaicher I just did that and it works, yes.

> If so could you open a PR to fix it?

Gonna have a try at it as soon as I can.
