### ISSUE TITLE
DoctrineBundle 2.7.0 calls undefined method setSchemaIgnoreClasses

### ISSUE THREAD

**Issue by Xesau** [doctrine/DoctrineBundle#1536]
In orm 2.11 the method setSchemaIgnoreClasses was introduced. DoctrineBundle's composer.json has a conflict doctrine/orm <2.10 but that should be <2.11, or the version should be checked before setSchemaIgnoreClasses is called.

```
16:05:38 CRITICAL  [php] Uncaught Error: Call to undefined method Doctrine\ORM\Configuration::setSchemaIgnoreClasses() ["exception" => Error { …}]

In App_KernelDevDebugContainer.php line 1283:

  Attempted to call an undefined method named "setSchemaIgnoreClasses" of class "Doctrine\ORM\Configuration".
```

**Comment by Mon-Tea** [comment]
I had a similar error yesterday while updating symfony 4.3 to 4.4 …

I know it's not a final solution, but if you downgrade to doctrine/doctrine-bundle to 2.6.4 the error disappears. (Just a workaround)
But perhaps a diff can find the real solution ;)

**Comment by dmaicher** [comment]
Indeed it should be a conflict for `<2.11`. @Xesau do you want to provide a PR to fix this? :blush: 

@Mon-Tea a better solution/workaround is probably updating to `doctrine/orm` 2.11+
