### ISSUE TITLE
PHP8 attribute mapping support in command doctrine:mapping:import

### ISSUE THREAD

**Issue by la-costa** [doctrine/DoctrineBundle#1537]
Hi

Doctrine already supports  PHP8 Attributes, but the command `doctrine:mapping:import` does not.

Are there any plans to include this support?

```sh
php bin/console doctrine:mapping:import "App\Entity" attribute --path=src/Entity

In ExportException.php line 23:

  The specified export driver 'attribute' does not exist  
```

**Comment by ostrolucky** [comment]
No, that command is deprecated so won't be further improved.

**Comment by la-costa** [comment]
Hi @ostrolucky 

Is there another way to do this?

Because in the [documentation](https://symfony.com/doc/current/doctrine/reverse_engineering.html) of Symfony, this is the way #mandalorian

**Comment by stof** [comment]
Well, generating entities from an existing database is precisely what is deprecated

**Comment by aszenz** [comment]
This is a very common use case for legacy applications, generating entities from existing db's, is it deprecated also in doctrine

**Comment by stof** [comment]
The ORM maintainers have stopped maintaining that tooling yes (which was never complete, as it never handled references between table properly)
