### ISSUE TITLE
`driverOptions` is missing from `$params` starting in 2.6.3

### ISSUE THREAD

**Issue by nesl247** [doctrine/DoctrineBundle#1541]
https://github.com/doctrine/DoctrineBundle/pull/1506 removed `driverOptions` from the exclusion of the param rewrite. Because of this, extensions like https://github.com/facile-it/doctrine-mysql-come-back broke.

I would consider this a BC break.

**Comment by ostrolucky** [comment]
What's your opinion on this issue @simPod?

**Comment by simPod** [comment]
I'm not BC breaking guru, not sure how exactly it is defined. I'd say that there was a bug that got fixed. There were consumers that relied on that bug so is it a BC break? 🤷🏾‍♀️

**Comment by ostrolucky** [comment]
I agree. Sorry @nesl247.
