### ISSUE TITLE
Attempted to call an undefined method named "setSchemaIgnoreClasses" of class "Doctrine\ORM\Configuration" on 2.7 version

### ISSUE THREAD

**Issue by EnterVPL** [doctrine/DoctrineBundle#1542]
Hi,
After updating `doctrine/doctrine-bundle` from 2.6.3 to 2.7 error 
```
Attempted to call an undefined method named "setSchemaIgnoreClasses" of class "Doctrine\ORM\Configuration"
```
I downgraded to 2.6.4 and everything started working again

Will this error not occur in future versions?

**Comment by dmaicher** [comment]
See https://github.com/doctrine/DoctrineBundle/issues/1536
