### ISSUE TITLE
[Bug] Invalid service "doctrine.dbal.default_connection.configuration": class "Doctrine\DBAL\Logging\Middleware" does not exist.

### ISSUE THREAD

**Issue by dkarlovi** [doctrine/DoctrineBundle#1544]
The bundle allows 2.6+ allows both DBAL 2 and 3. I've checked why it's kept and it seems to get removed if the container doesn't have a `logger`.

I get the error in question with bundle 2.7.

With bundle 2.6, I get
```
Attempted to call an undefined method named "setMiddlewares" of class "Doctrine\DBAL\Configuration".
```

Conflicting bundle >= 2.6 fixes it, DBAL 2.13.9 and bundle 2.5.7 works.

**Comment by dmaicher** [comment]
Could you provide a reproducer? Not sure I understand the exact scenario when this happens.

**Comment by dkarlovi** [comment]
Creating a reproducer will be difficult since this is happening in a full stack app. I can try to debug it if you point me in the right direction, like why would the class be missing here (which it is) and why the service might be being created?

**Comment by dmaicher** [comment]
@ostrolucky I think its time to think about dropping DBAL 2 support (its EOL anyway, or?). We have too many possible scenarios :confused: 

@dkarlovi you get this error when running `lint:container`?

**Comment by dkarlovi** [comment]
@dmaicher No, it's when Symfony is building the container. If I downgrade to 2.5 (without any other changes whatsoever), it works. Note that 2.6 also doesn't work, but with a different error (pasted above). It's a change introduced in 2.6.

**Comment by dmaicher** [comment]
@dkarlovi I cannot reproduce this issue. Works fine on one of my apps with DBAL 2.13.9, DoctrineBundle 2.7.0, Symfony 6.0. Also the testsuite for the Bundle passes fine with DBAL 2.13.9.

So without a reproducer we cannot really help here.

**Comment by dkarlovi** [comment]
This is Symfony 5.4, with Pimcore 10.4.

As I said, I don't see a way to create a simple reproducer, otherwise I'd just PR the fix. :) Why would the service even be created if there's no such class? I can see the service definition existing, does it get removed in some way? Can you point me to where that happens, where does the bundle handle missing classes from DBAL3?

**Comment by dmaicher** [comment]
@dkarlovi there are some conditional statements like

```
$ grep -r 'interface_exists(Middleware' DependencyInjection/ DoctrineBundle.php 
DependencyInjection/DoctrineExtension.php:        if (! interface_exists(MiddlewareInterface::class) && $connection['logging']) {
DependencyInjection/DoctrineExtension.php:        if (! interface_exists(MiddlewareInterface::class)) {
DependencyInjection/DoctrineExtension.php:        return interface_exists(MiddlewareInterface::class) && class_exists(SfDebugMiddleware::class);
DoctrineBundle.php:        if (interface_exists(Middleware::class)) {
```

Those should make sure the logging middleware is only used on DBAL 3. No idea whats happening in your case...

**Comment by dkarlovi** [comment]
OK, I'll try to debug it if I get the chance. Let's close here and I'll follow up if I have some findings, thanks!

**Comment by scrummer** [comment]
@dkarlovi Did you find any solution to this one?

I ran into the same problem when updating a Pimcore installation from 6.9 to 10.x.

**Comment by dkarlovi** [comment]
@scrummer yes, pin the bundle to 2.5.

**Comment by dkarlovi** [comment]
@scrummer are you using Sentry by any chance?

**Comment by dkarlovi** [comment]
See https://github.com/getsentry/sentry-symfony/pull/608

**Comment by scrummer** [comment]
@dkarlovi Yes, I have sentry in the project. Thanks a lot for the link!

**Comment by dkarlovi** [comment]
This is actually quite annoying, Sentry Bundle created an item in somebody else's namespace and caused a bunch of bugs. :|
