### ISSUE TITLE
$setUnion not available ?

### ISSUE THREAD

**Issue by destructivecreator** [doctrine/DoctrineBundle#1547]
I am having troubles evaluating this mongo query using the aggregation builder

`data": {
      "$reduce": {
          "input": "$data",
          "initialValue": [],
          "in": { "$setUnion": ["$$value", "$$this"] }
      }
  }`
  
  ` ->reduce('$data',
                [],
                $aggregationBuilder->expr()->setUnion('$$this', '$$value');
            );`
  
  I can not find the setUnion operator, is this intentionally not part of the expression or I am not doing it right ?

**Comment by ostrolucky** [comment]
sorry, this is a wrong repository, we have nothing to do with mongo
