### ISSUE TITLE
Depreciation of doctrine:mapping:import ?

### ISSUE THREAD

**Issue by Gregwar** [doctrine/DoctrineBundle#1573]
As stated here:
https://symfony.com/doc/6.0/doctrine/reverse_engineering.html

>  The doctrine:mapping:import command used to generate Doctrine entities from existing databases was deprecated by Doctrine in 2019   and it's no longer recommended to use it
>  Instead, you can use the make:entity command from [Symfony Maker Bundle](https://symfony.com/bundles/SymfonyMakerBundle/current/index.html) to quickly generate the Doctrine entities of your application.

I fail to see how to use `make:entity` to fulfill the same purpose as the current  `doctrine:mapping:import`, can someone explain me?
Also, is there any way to create automatically the mapping using PHP attributes?

**Comment by Gregwar** [comment]
For example, how can I have the same result as:

```bash
symfony console doctrine:mapping:import App\\Entity annotation --path=src/Entity
```

Without using `doctrine:mapping:import` ?

**Comment by dmaicher** [comment]
>  Also, is there any way to create automatically the mapping using PHP attributes?

See https://github.com/doctrine/DoctrineBundle/issues/1537

**Comment by Gregwar** [comment]
I see, I think it's too bad since there are some use cases but I understand it's extra work

**Comment by stof** [comment]
If your goal is to migrate from annotations to attribute, the right solution is not to reverse-engineer your database to generate code with attributes (which would have provided a partial migration anyway as many things cannot be reverse-engineered).
The proper way to migrate your mapping from one format to another one is to take your existing mapping as source of truth. And the good news is that the tooling exists for that. See https://www.doctrine-project.org/2022/11/04/annotations-to-attributes.html
