### ISSUE TITLE
join on ManyToMany-Relation throws error: "Class App\\Entity\\>Entity> has no association named <name>"

### ISSUE THREAD

**Issue by Mauriceu** [doctrine/DoctrineBundle#1580]
Hello!

I am confused.

DoctrineBundle: v2.7.1
DoctrineORM: v2.13.2

I have 4 tables as follows:

**Grocery** and **GroceryTranslation** have a *OneToMany*
**Grocery** and **Tag** have a *ManyToMany*.
**Grocery** and **UserGrocery** have a *OneToMany*

Now a User may ask "Hey, what are my Groceries?"
So to find the answer I select from **UserGrocery**, join with **Grocery** (to get info about the actual groceries), then join **Grocery** with **GroceryTranslation** to get the display-names of the Groceries, and then join **Grocery** with **Tag** to get the corresponding tags.

I tried to say that exact same sentence in Doctrine with this:

```php
        # create the queryBuilder from UserGrocery-Repo
        $qb = $em->getRepository(UserGrocery::class)->createQueryBuilder('ug');
        

        $result = $qb
            ->leftJoin('ug.grocery', 'g') # Join on Grocery
            ->leftJoin('g.translation', 'gt') # Join on GroceryTranslation
            ->innerJoin('g.tags', 't') # Join on Tags with Grocery-Alias !!Fails!!
            ->where(
                $qb->expr()->eq('ug.owner', $user->getId()),
            )
            ->getQuery()
            ->execute();
```

This Query results in a Semantical Error as shown in the title:
**Error: Class App\\Entity\\Grocery has no field or association named "tags"**

Which kind of makes sense? Grocery does not have a *column tags*, but should Doctrine not be aware of the junction-table?

The Grocery-Entity has the properties **translation**, populated with GroceryTranslation-Items, and **tags** populated with Tag-Items - both are properties of type Collection.

```php
#[ORM\OneToMany(mappedBy: 'grocery', targetEntity: GroceryTranslation::class, orphanRemoval: true)]
private Collection $translation;

#[ORM\ManyToMany(targetEntity: Tag::class, mappedBy: 'grocery')]
private Collection $tags;
```

If I remove the **->innerJoin()** statement everything works, but obviously no Tags exist in the result.

Please help me...

**Comment by ostrolucky** [comment]
Sorry but this is not related to doctrine-bundle. Nor it looks like an issue to me. I suggest to create stackoverflow post or discussion at https://github.com/doctrine/orm/discussions
