### ISSUE TITLE
XML Mapping with custom-id-generator and service ID might not match class FQCN (IDE and XML validation tools)

### ISSUE THREAD

**Issue by AndreasA** [doctrine/DoctrineBundle#1582]
Not that important as it will still work but if one uses, a custom-id-generator with a service as `class` attribute, the attribute itself might not match the XML allowed regex, like e.g. `doctrine.uuid_generator` due to the `.`.

It produces an error in XML validation like: `The value 'doctrine.uuid_generator' of attribute 'class' on element 'custom-id-generator' is not valid with respect to its type, 'fqcn'.`

However, I think the issue is only with the IDE/XML validation tools directly and otherwise it works fine, so as mentioned not that important.

**Comment by AndreasA** [comment]
Not sure if this can be fixed easily without changing the FQCN validation in the original xsd to nearly allow everything

**Comment by ostrolucky** [comment]
XSD for mapping is not defined here but in doctrine/orm so I have to close here
