### ISSUE TITLE
[FEATURE PROPOSAL] Add `doctrine:server:await` command

### ISSUE THREAD

**Issue by Kolyunya** [doctrine/DoctrineBundle#1593]
It's a very common scenario when we run our integration tests inside CI/CD pipelines. Normally you would launch the DBMS server and then run integration tests.

A very common pitfall here is that DBMS usually needs quite some time to start. On a small CI/CD machine it could take up to a couple of minutes to start.

A bad approach to address this issue would be to add an empirically calculated timeout before running a test suite.

What I suggest here is to add a console command that would continuously try to execute something like `SELECT NOW();` against the DBMS server with N second timeout until the server is up and the query succeeds.

I personally find myself implementing this command in every project I make and I believe it would be useful for many people.

**Comment by ostrolucky** [comment]
I don't believe this is something that should be part of this project, sorry. There are lot of shell scripts, command examples or projects dedicated to this.
