### ISSUE TITLE
Setting the "doctrine.orm.controller_resolver.auto_mapping" config to false has no effect

### ISSUE THREAD

**Issue by ovidiuenache** [doctrine/DoctrineBundle#1594]
Disabling the auto mapping through the following config: `doctrine.orm.controller_resolver.auto_mapping` has no effect.

```
// config/packages/doctrine.yaml

doctrine:
    orm:
        controller_resolver:
            auto_mapping: false
```

The action for `POST /api/register` with a body holding JSON-encoded user information
```
// src/Controller/User/Register.php

namespace App\Controller\User;

use App\Entity\User;
use Symfony\Component\HttpFoundation\JsonResponse;
...

final class Register
{
    public function __invoke(
        User $data,
        ...
    ): JsonResponse {
    ...
```

When I make a POST request to the above-mentioned action I get the following exception:
`Binding entities to query parameters only allowed for entities that have an identifier.`

However, if I manually disable the mapping using the `MapEntity` attribute, everything works as expected:
```
namespace App\Controller\User;

use App\Entity\User;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
...

final class Register
{
    public function __invoke(
        #[MapEntity(disabled: true)]
        User $data,
        ...
    ): JsonResponse {
    ...
```

Reference: https://symfony.com/doc/current/doctrine.html#automatically-fetching-objects-entityvalueresolver

Specifically:
`This behavior is enabled by default on all your controllers. You can disable it by setting the doctrine.orm.controller_resolver.auto_mapping config option to false.`

Am I doing something wrong here or is there an issue with the configuration?

Thank you!

**Comment by dmaicher** [comment]
What is the stack trace for that exception?

**Comment by ovidiuenache** [comment]
@dmaicher 

`app.ERROR: An error has occurred while processing the request {"exception_message":"Binding entities to query parameters only allowed for entities that have an identifier.\nClass \"App\\Entity\\User\" does not have an identifier.","exception_trace":"#0 /home/ionutenache/personal-projects/api/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(452): Doctrine\\ORM\\ORMInvalidArgumentException::invalidIdentifierBindingEntity()\n#1 /home/ionutenache/personal-projects/api/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(197): Doctrine\\ORM\\EntityManager->find()\n#2 /home/ionutenache/personal-projects/api/vendor/symfony/doctrine-bridge/ArgumentResolver/EntityValueResolver.php(110): Doctrine\\ORM\\EntityRepository->find()\n#3 /home/ionutenache/personal-projects/api/vendor/symfony/doctrine-bridge/ArgumentResolver/EntityValueResolver.php(57): Symfony\\Bridge\\Doctrine\\ArgumentResolver\\EntityValueResolver->find()\n#4 /home/ionutenache/personal-projects/api/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php(60): Symfony\\Bridge\\Doctrine\\ArgumentResolver\\EntityValueResolver->resolve()\n#5 /home/ionutenache/personal-projects/api/vendor/symfony/http-kernel/Controller/ArgumentResolver.php(54): Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolver\\TraceableValueResolver->resolve()\n#6 /home/ionutenache/personal-projects/api/vendor/symfony/http-kernel/Controller/TraceableArgumentResolver.php(39): Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolver->getArguments()\n#7 /home/ionutenache/personal-projects/api/vendor/symfony/http-kernel/HttpKernel.php(155): Symfony\\Component\\HttpKernel\\Controller\\TraceableArgumentResolver->getArguments()\n#8 /home/ionutenache/personal-projects/api/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#9 /home/ionutenache/personal-projects/api/vendor/symfony/http-kernel/Kernel.php(184): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#10 /home/ionutenache/personal-projects/api/features/context/ClientContext.php(94): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#11 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(110): App\\Behat\\Context\\ClientContext->iRequest()\n#12 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(64): Behat\\Testwork\\Call\\Handler\\RuntimeCallHandler->executeCall()\n#13 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(138): Behat\\Testwork\\Call\\Handler\\RuntimeCallHandler->handleCall()\n#14 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\\Testwork\\Call\\CallCenter->handleCall()\n#15 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\\Testwork\\Call\\CallCenter->makeCall()\n#16 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\\Behat\\Tester\\Runtime\\RuntimeStepTester->testDefinition()\n#17 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\\Behat\\Tester\\Runtime\\RuntimeStepTester->test()\n#18 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(76): Behat\\Behat\\Hook\\Tester\\HookableStepTester->test()\n#19 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\\Behat\\EventDispatcher\\Tester\\EventDispatchingStepTester->test()\n#20 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\\Behat\\Tester\\StepContainerTester->test()\n#21 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\\Behat\\Tester\\Runtime\\RuntimeScenarioTester->test()\n#22 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(106): Behat\\Behat\\Hook\\Tester\\HookableScenarioTester->test()\n#23 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\\Behat\\EventDispatcher\\Tester\\EventDispatchingScenarioTester->test()\n#24 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\\Behat\\Tester\\Runtime\\IsolatingScenarioTester->test()\n#25 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\\Behat\\Tester\\Runtime\\RuntimeFeatureTester->test()\n#26 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(74): Behat\\Behat\\Hook\\Tester\\HookableFeatureTester->test()\n#27 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\\Behat\\EventDispatcher\\Tester\\EventDispatchingFeatureTester->test()\n#28 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\\Testwork\\Tester\\Runtime\\RuntimeSuiteTester->test()\n#29 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(75): Behat\\Testwork\\Hook\\Tester\\HookableSuiteTester->test()\n#30 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\\Testwork\\EventDispatcher\\Tester\\EventDispatchingSuiteTester->test()\n#31 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(73): Behat\\Testwork\\Tester\\Runtime\\RuntimeExercise->test()\n#32 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\\Testwork\\EventDispatcher\\Tester\\EventDispatchingExercise->test()\n#33 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\\Testwork\\Ordering\\OrderedExercise->test()\n#34 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\\Testwork\\Tester\\Cli\\ExerciseController->testSpecifications()\n#35 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\\Testwork\\Tester\\Cli\\ExerciseController->execute()\n#36 /home/ionutenache/personal-projects/api/vendor/symfony/console/Command/Command.php(312): Behat\\Testwork\\Cli\\Command->execute()\n#37 /home/ionutenache/personal-projects/api/vendor/symfony/console/Application.php(1020): Symfony\\Component\\Console\\Command\\Command->run()\n#38 /home/ionutenache/personal-projects/api/vendor/symfony/console/Application.php(312): Symfony\\Component\\Console\\Application->doRunCommand()\n#39 /home/ionutenache/personal-projects/api/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\\Component\\Console\\Application->doRun()\n#40 /home/ionutenache/personal-projects/api/vendor/symfony/console/Application.php(168): Behat\\Testwork\\Cli\\Application->doRun()\n#41 /home/ionutenache/personal-projects/api/vendor/behat/behat/bin/behat(34): Symfony\\Component\\Console\\Application->run()\n#42 /home/ionutenache/personal-projects/api/vendor/bin/behat(120): include('...')\n#43 {main}"}`

**Comment by dmaicher** [comment]
@nicolas-grekas maybe you can help here. It seems that `auto_mapping: false` is not completely turning off the feature, or? From what I see that sets `MapEntity::$mapping = []`. But it seems the resolver is still trying to find it by identifier.

Should this be used to disable it fully also for such cases?

```yaml
doctrine:
    orm:
        controller_resolver:
            enabled: false

**Comment by stof** [comment]
`auto_mapping: false` does not disable the entity resolver entirely (that's what `enabled: false` is about). It only disables the automatic generation of a mapping using all matching request attribute.
With `auto_mapping: false`, the resolver will only apply in 2 cases:
- when a `MapEntity` attribute is set on the argument providing an explicit mapping, this mapping is used
- when a request attribute named `id` or named like the controller argument name is found, the resolver tries to resolve it by primary key.

Side note: if your argument holding a deserialized json body is managed by an argument resolver, things should also work fine (as each argument is resolved once, and they are not stored in request attributes). A conflict indeed occurs when mixing the EntityValueResolver with the old system of SensioFrameworkExtraBundle's ParamConverter that worked by storing converted values in the request attributes.

**Comment by dmaicher** [comment]
Does this makes things clear @ovidiuenache ?

**Comment by ovidiuenache** [comment]
It does! Thank you @stof and @dmaicher for making things clear! We can close this!
