### ISSUE TITLE
[2.8.0] BC breaks introduced

### ISSUE THREAD

**Issue by theofidry** [doctrine/DoctrineBundle#1603]
See my comment in https://github.com/doctrine/DoctrineBundle/pull/1587/files#r1059322805 where I think the services removed introduce a BC break.

**Comment by ostrolucky** [comment]
We were aware of this, see discussion at https://github.com/doctrine/DoctrineBundle/pull/1586

**Comment by theofidry** [comment]
I'm still confused: what's the expected replacement? The linked discussion mentions they are no longer used but it's unclear from what point this happened (especially since they were not deprecated at the same time).

Might also be worth highlighting that this is a deliberate BC break in the release notes with maybe an explanation or what you are expected to use instead.

**Comment by ostrolucky** [comment]
[This was highlighted in our upgrade guide](https://github.com/doctrine/DoctrineBundle/blob/2.8.x/UPGRADE-2.8.md). As for replacement, in general it's DBAL middlewares. Exact use depends on your use case though.

**Comment by theofidry** [comment]
>This was highlighted in our upgrade guide.

Ah fair. Sorry I did not think to check for upgrades guide since there was details in the release notes. I expected everything to be in one place not scattered in different places. It's not uncommon though so my bad for assuming so.

>As for replacement, in general it's DBAL middlewares. Exact use depends on your use case though.

This is quite... broad no gonna lie. It's a bit disappointing, I really did not expect to have to dig so much for minor version upgrade.

I guess I'll have to go with making the constraint stricter to restrict to the patch version instead of the minor version. Might be a one time lack of luck, but I also did not assume you could get a complete behaviour change + services being removed in minor versions.
