### ISSUE TITLE
phpstan failure on LazyGhostTrait with Sym5.4.*

### ISSUE THREAD

**Issue by craigh** [doctrine/DoctrineBundle#1614]
phpstan level 3 analysis now failing with 

> Fatal error: Trait "Symfony\Component\VarExporter\LazyGhostTrait" not found in /my-app/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php on line 31

This is on upgrade of `doctrine/DoctrineBundle` from `2.7.2` to `2.8.2`

I am using Symfony 5.4.18

**Comment by greg0ire** [comment]
Please read and apply: https://symfony.com/doc/current/contributing/code/stack_trace.html

**Comment by craigh** [comment]
Hi @greg0ire thank you for replying. I have no stack trace. It isn't a php error. It is a php **stan** analysis error. This runs in my gitlab pipeline. The only result there is

```cli
$ ./vendor/bin/phpstan analyse --error-format=gitlab
[81](https://gitlab.com/<name>/<repo>/jobs/3569690293#L81)Note: Using configuration file /builds/<name>/<repo>/phpstan.neon.dist.
[82](https://gitlab.com/<name>/<repo>/-/jobs/3569690293#L82)Fatal error: Trait "Symfony\Component\VarExporter\LazyGhostTrait" not found in /builds/<name>/<repo>/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php on line 31
```

for reference, the `phpstan.neon.dist` file only configs the level to **3**. There are no other configs of note.

**Comment by greg0ire** [comment]
Oh right, sorry. Well I don't think this is the right place to report this. If you don't have a PHP error, then it means PHPStan shouldn't report anything. `LazyServiceEntityRepository` is not supposed to be used at all when `LazyGhostTrait` is not available. Still, it refers to it, which is not something uncommon or something PHPStan usually chokes on.

Also, you should be able to get more information with `-vvv` and `--debug`

**Comment by craigh** [comment]
I don't really understand the internals, but I think the problem is that the `Doctrine\Bundle\DoctrineBundle\Repository\LazyServiceEntityRepository` class exists and **uses** the `LazyGhostTrait` but the trait isn't defined for Symfony 5.4. It seems the Repository class shouldn't be defined if the Trait isn't defined?

**Comment by greg0ire** [comment]
If you look closer, you'll see that `LazyServiceEntityRepository` is used conditionally: https://github.com/doctrine/DoctrineBundle/blob/251cd5aaea32bb92cdad4204840786b317dcdd4c/Repository/ServiceEntityRepository.php#L13-L21

So it never gets autoloaded and thus defined when the trait isn't.

**Comment by craigh** [comment]
This is the class that phpstan is seeing:

https://github.com/doctrine/DoctrineBundle/blob/251cd5aaea32bb92cdad4204840786b317dcdd4c/Repository/LazyServiceEntityRepository.php

not the instance - remember, Stan is static inspection.

**Comment by ostrolucky** [comment]
What do you suggest we do?

**Comment by craigh** [comment]
> What do you suggest we do?

At least keep the ticket open until the conversation is completed? 🤷 

[It appears the phpstan folks are attempting to fix the issue](https://github.com/phpstan/phpstan-doctrine/issues/409) in their most recent release (which I am using) but it didn't fix it for me.

https://github.com/phpstan/phpstan-doctrine/commit/e1437a270ed0512b69141729d7c4b3107946a1cf

**Comment by greg0ire** [comment]
If we keep every vague, unactionable, bug report open, it will prevent us from given priority to actual issues.

If you want to be treated differently, start using more common sense:
- If I mention "Also, you should be able to get more information with -vvv and --debug" then maybe use these flags and post the output?
- If you use phpstan-doctrine, then maybe mention it? It can have a big impact on how PHPStan behaves.
- If you use phpstan-doctrine, try and see if the issue persists without it, that's something you can try before opening an issue actually.
- If we keep answering to you for free after the issue gets closed, don't complain about the issue being closed. What is the big deal?

More generally, we try to keep Github issues for bug reports and feature requests only. If you seek support, there's https://github.com/doctrine/DoctrineBundle/discussions. Issue is for stuff where we are clearly in the wrong. This lacks clarity.

**Comment by craigh** [comment]
Hi @greg0ire thanks again for responding. I'm not sure why your tone seems so hostile. I'm simply trying to solve a problem which didn't exist before my upgrade to DoctrineBundle 2.8.2. Since there was no problem with 2.7.2, I assumed the problem  is with DoctrineBundle. I'm sure you see the logic in that assumption.

for the record, I _had run__ with both `--debug` and `-vvv` and found no new information, so I didn't post it. If you care, here it is:

```cli
 % ./vendor/bin/phpstan analyse --debug -vvv

Note: Using configuration file /path/to/phpstan.neon.
PHP Fatal error:  Trait "Symfony\Component\VarExporter\LazyGhostTrait" not found in /path/to/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php on line 31
Fatal error: Trait "Symfony\Component\VarExporter\LazyGhostTrait" not found in /path/to/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php on line 31
% 
```

Shockingly, I had forgotten I had also installed phpstan-doctrine. Apparently bad memory is not acceptable.

I guess I will freeze my install at 2.7.2.

I'm sorry to have wasted your precious time.

**Comment by greg0ire** [comment]
> I'm not sure why your tone seems so hostile

It's mostly the waste of time you pointed out. I knew from the get go that we were not going to be able to help you without some kind of reproducer, and that this wasn't going to be fruitful, hence the closing. Sorry I made you feel bad by closing the issue, but I thought after demonstrating how the trait being not defined was fully accounted for in our logic, you would be convinced this was not the right place for reporting this. Also, I understand now why you didn't report the output with debug or vvv, but it would have helped if you showed you listened a bit to what I said. Anyway, of course it's OK to forget you have installed something, it's not the issue it's just… you gotta help us help you. Even after reading https://github.com/doctrine/DoctrineBundle/issues/1614#issuecomment-1374901150, one can't tell if you have phpstan-doctrine installed or not, so you have us consider several scenarios for this which yeah, does waste a bit of our time, it's true. And our time might not be the most precious of all, but it's given for free, so, a bit of consideration from time to time would be nice.

**Comment by ondrejmirtes** [comment]
This problem can happen pretty easily:

```php
require_once __DIR__ . '/vendor/autoload.php';

use Doctrine\Bundle\DoctrineBundle\Repository\LazyServiceEntityRepository;

class_exists(LazyServiceEntityRepository::class);
```

This is enough to make this bundle crash without PHPStan being involved at all.

The problem is that you put a class in your autoloader, but the class is broken unless another dependency is required. That's why PHPStan considers this class to be safely autoloadable but actually isn't.

I'm gonna fix it on phpstan-doctrine's side, but it's something to keep in mind when designing your classes.

**Comment by greg0ire** [comment]
I'm not sure what you're suggesting? Do you mean we should wrap the class definition with an `if trait_exists()` statement as an extra measure on top of what we're doing in https://github.com/doctrine/DoctrineBundle/blob/251cd5aaea32bb92cdad4204840786b317dcdd4c/Repository/ServiceEntityRepository.php#L13-L21 ?

Or that maybe we should have this file outside the path from which we can autoload stuff? That doesn't seem very doable right now by the way: https://github.com/doctrine/DoctrineBundle/blob/251cd5aaea32bb92cdad4204840786b317dcdd4c/composer.json#L77-L81

**Comment by ondrejmirtes** [comment]
I don't really know, personally I'd avoid "optional" dependencies altogether because they're messy. "LazyServiceEntityRepository" should be defined in a package that has both DoctrineBundle and VarExporter in `require`...

**Comment by greg0ire** [comment]
Yeah we're definitely in a gray area, I guess we'll have to come up with our own best practices, and doing that preliminary check could be one of them.

**Comment by craigh** [comment]
Glad I could help!
