### ISSUE TITLE
Compile error after introduction of LazyServiceEntityRepository

### ISSUE THREAD

**Issue by mikefox** [doctrine/DoctrineBundle#1615]
In our project (Symfony 6.2 and PHP 8.2) we had the following error with version 2.8.1 of the project:

  Compile Error: Declaration of Symfony\Component\VarExporter\LazyGhostTrait::createLazyGhost(Closure|array $initializer, ?array $skippedProperties = null, ?ContainerEitUOS3\UserRepositoryGhostAe7ae8b $instance = null): ContainerEitUOS3\MyProject_KernelTestDebugContainer must be compatible with Doctrine\Bundle\DoctrineBundle\Repository\LazyServiceEntityRepository::createLazyGhost(Closure|array $initializer, ?array $skippedProperties = null, ?Doctrine\Bundle\DoctrineBundle\Repository\LazyServiceEntityRepository $instance = null): ContainerEitUOS3\MyProject_KernelTestDebugContainer

For the time being we've locked the version of `doctrine/doctrine-bundle` down to 2.8.0.

**Comment by ostrolucky** [comment]
@nicolas-grekas

**Comment by hovisser** [comment]
Same problem here (symfony 6.2.4/ PHP 8.2).

PHP Fatal error:  Declaration of Symfony\Component\VarExporter\LazyGhostTrait::createLazyGhost(Closure|array $initializer, ?array $skippedProperties = null, ?ContainerP2ADS8Q\AccountRepositoryGhostEa032d1 $instance = null): ContainerP2ADS8Q\App_KernelDevDebugContainer must be compatible with Doctrine\Bundle\DoctrineBundle\Repository\LazyServiceEntityRepository::createLazyGhost(Closure|array $initializer, ?array $skippedProperties = null, ?Doctrine\Bundle\DoctrineBundle\Repository\LazyServiceEntityRepository $instance = null): ContainerP2ADS8Q\App_KernelDevDebugContainer in /vendor/symfony/var-exporter/LazyGhostTrait.php on line 45

**Comment by stof** [comment]
This looks like a bug in PHP itself as the signature in the error message is not the signature in the code. It might be similar to https://github.com/php/php-src/issues/9675 where a cache is corrupted and messes up things between multiple classes.

**Comment by nicolas-grekas** [comment]
Should be fixed by https://github.com/symfony/symfony/pull/48939

**Comment by nicolas-grekas** [comment]
As a workaround, you might try removing the "lazy" flag on your repository definition. It might be useless anyway.
