### ISSUE TITLE
Wrong proxy classes check in AbstractManagerRegistry if lazy ghost is enabled

### ISSUE THREAD

**Issue by mba242** [doctrine/DoctrineBundle#1620]
doctrine/orm creates proxy class implementations of various interfaces depending on whether the lazy ghost setting is enabled or not.
[ProxyFactory line 116](https://github.com/doctrine/orm/blob/2.14.x/lib/Doctrine/ORM/Proxy/ProxyFactory.php#L116)

doctrine/persistence checks a proxy class by its interface.
[AbstractManagerRegistry line 176](https://github.com/doctrine/persistence/blob/3.1.x/src/Persistence/AbstractManagerRegistry.php#L176)

doctrine/DoctrineBundle doesn't care and intializes doctrine/persistence with the old Proxy interface.
[Registry line 30](https://github.com/doctrine/DoctrineBundle/blob/2.8.x/Registry.php#L30)

Doctrine\Persistence\AbstractManagerRegistry->getManagerForClass($proxyClassName) returns null when lazy ghost is enabled.

**Comment by burned42** [comment]
I was just faced with the same issue after updating the [flex recipe](https://github.com/symfony/recipes/pull/1140) which enabled the lazy ghost objects.

And I can also confirm your findings, changing to the used proxy class name to `Doctrine\Persistence\Proxy` at https://github.com/doctrine/DoctrineBundle/blob/2.8.x/Registry.php#L30 seemed to work for me, though I'm not sure if that's a proper fix or if it would break other things.

A quick fix for me was to disable `enable_lazy_ghost_objects` again for now.

**Comment by mba242** [comment]
> [...]changing to the used proxy class name to `Doctrine\Persistence\Proxy` at https://github.com/doctrine/DoctrineBundle/blob/2.8.x/Registry.php#L30 seemed to work for me, though I'm not sure if that's a proper fix or if it would break other things.

I guess it will breaks something in case lazy ghost is disabled. In think it needs the same check like in the ProxyFactory class and give depending interface name to parent.

Anyway - there is a lot around in doctrine universe. I don't know if there more effects.

**Comment by nicolas-grekas** [comment]
Changing the namespace looks enough to me. PR sent as #1621
