### ISSUE TITLE
[2.9] How to update user code to avoid "subscriber" deprecations?

### ISSUE THREAD

**Issue by weaverryan** [doctrine/DoctrineBundle#1636]
Hi!

In #1635, some subscribers were deprecated in favor listeners. This leaves deprecations like:

> Since doctrine/doctrine-bundle 2.9: The "doctrine.orm.messenger.doctrine_schema_subscriber" service is deprecated. You should stop using it, as it will be removed in the future

What I can't figure out is what to *do*. Is there a way to... opt "into" the new listener service so that the susbcriber service is not used? Or am I missing the point?

Thanks!

**Comment by nicolas-grekas** [comment]
Upgrade to Symfony 6.3 dude 😎

**Comment by nicolas-grekas** [comment]
Maybe we should drop the service deprecation? The class is already deprecated so removing the service will come naturally when dropping support for Symfony < 6.3. Up for a PR?

**Comment by ostrolucky** [comment]
Indeed

**Comment by alli83** [comment]
Yes indeed, the message was not really explicit. As suggested they are now removed in https://github.com/doctrine/DoctrineBundle/pull/1638
