### ISSUE TITLE
Array to string conversion in 2.9

### ISSUE THREAD

**Issue by tacman** [doctrine/DoctrineBundle#1639]
when trying to access the Symfony profiler (to see the database queries), I'm getting 

An exception has been thrown during the rendering of a template ("Warning: Array to string conversion").

Only with version 2.9, reverting to 2.8.3 is fine

        "doctrine/doctrine-bundle": "~2.8.3",

**Comment by ostrolucky** [comment]
Can you provide more details? Do you have a stack trace? Which Symfony version do you have installed?

**Comment by tacman** [comment]
Perhaps it was a cache issue, I reverted to 2.8, everything worked, then went back to 2.9 this morning and it seems to work.  I'll post the trace if it happens again.
