### ISSUE TITLE
Question: It posible to create dbal's custom type with symfony container?

### ISSUE THREAD

**Issue by aywan** [doctrine/DoctrineBundle#1642]
I want to inject custom serializer service inside dbal's type.
```
final class MyDataType extends JsonType implements SerializerAwareInterface
{
   private MySerializer $serializer;
   // ....

    #[Required]
    public function setMySerializer(MySerializer $serializer): void
    {
        $this->serializer = $serializer;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform): ?MyData
    {
        return $this->serializer->deserilize($value);
    }
    // ...
}
```

I have considered a few potential solutions:
1. use static
2. get container with hack through event manager through `AbstractPlatform $platform`
3. inject serializer manually at some moment, or create and register type manually (when?)

And it seems to me that the right way is to create types through the Symfony container, something like that:
https://github.com/doctrine/DoctrineBundle/blob/2.9.x/ConnectionFactory.php#L149
```
        foreach ($this->typesConfig as $typeName => $typeConfig) {
            if (Type::hasType($typeName)) {
                Type::getTypeRegistry()->override($typeName, $container->get($typeConfig['class']));
            } else {
                Type::getTypeRegistry()->register($typeName, $container->get($typeConfig['class']));
            }
        }
```
I am not very familiar with Symfony and would appreciate some help with my problem.

**Comment by dmaicher** [comment]
I guess one option (not sure its the best one) could be to decorate the ConnectionFactory and similar to https://github.com/doctrine/DoctrineBundle/blob/2.9.x/ConnectionFactory.php#L149 inject your custom Type instance there before the connection is created

**Comment by dmaicher** [comment]
If this does not solve your issue please consider opening a [discussion](https://github.com/doctrine/DoctrineBundle/discussions) for it.
