### ISSUE TITLE
yml-configuration with json schema validation

### ISSUE THREAD

**Issue by breitschopf** [doctrine/DoctrineBundle#1652]
Hi,

yml-files can be validated with the power of json-schemas, inclusive auto-completion and error detection.
In nearly each IDE (e.g. PhpStorm) it is possible to set a "JSON Schema Mapping" for yml files.

For e.g. a mapping can be set for all *.dcm.yml files which ensures validation for all of these files.

And some common mappings are automatically applied by IDEs out of the box.

Yml-files with validation would be a big improvement in comparison to clumsy xml files.
Please take it under consideration.

Regards

**Comment by ostrolucky** [comment]
YAML files for doctrine mapping is deprecated, so no improvements will be made on this front

**Comment by breitschopf** [comment]
They are set as deprecated because no validation was possible so far.

**Comment by ostrolucky** [comment]
That's not a discussion for a bundle, we just follow ORM's decision, so if you want to revert this decision, better to discuss this in https://github.com/doctrine/orm
