### ISSUE TITLE
How to migrate platform_service config?

### ISSUE THREAD

**Issue by simPod** [doctrine/DoctrineBundle#1656]
In v2.9 the upgrade guide says 

> - the DBAL `platform_service` connection option is deprecated now. Use a driver middleware that would instantiate the platform instead.

Can we find some example how to migrate?

**Comment by dmaicher** [comment]
On DBAL's side the `platform` connection parameter was [deprecated](https://github.com/doctrine/dbal/blob/3.6.x/src/Connection.php#LL203C16-L203C16).

Maybe the example mentioned [here](https://github.com/doctrine/dbal/pull/5699) helps you?

**Comment by ostrolucky** [comment]
Yeah try to follow that example together with https://symfony.com/bundles/DoctrineBundle/current/middlewares.html. If you struggle with that, please ask in our community channels https://www.doctrine-project.org/community/index.html

**Comment by simPod** [comment]
Works, thanks!
