### ISSUE TITLE
Cannot drop Sqlite database on windows using doctrine:database:drop

### ISSUE THREAD

**Issue by MartinDepero** [doctrine/DoctrineBundle#1658]
Hi everyone,

Since version 2.9.0 we have issue using the `doctrine:database:drop` command with sqlite database on windows env.

Since this version, the command does not drop the database (as `dropDatabase()` is deprecated for Sqlite) but directly delete the _.db_ file (using `unlink()`).

Unfortunately, a connection is open before droppping the database but never closed.
So, on windows, because of this non-closed connection, the _.db_ file can't be deleted.
That throws an error, which is catched, resulting in this error : 

> Warning: unlink(...): Resource temporarily unavailable

The right thing to do seems to close the connection before unlink. Something like this :

```php
// Command/DropDatabaseDoctrineCommand.php:106

                if ($schemaManager instanceof SqliteSchemaManager) {
                    // dropDatabase() is deprecated for Sqlite
                    $connection->close(); // Add this to fix
                    if (file_exists($name)) {
                        unlink($name);
                    }
                } else {
                    $schemaManager->dropDatabase($name);
                }
```
But I let you fix it in the way you think is the best.

Thanks a lot in advance

**Comment by ostrolucky** [comment]
Not sure why you think this is an issue in doctrine-bundle. Please report issue in doctrine/dbal repository.

**Comment by dmaicher** [comment]
Hm interesting. And this works on DoctrineBundle `< 2.9.0`? Wondering how :thinking: 

I mean here is also no logic to close any open connection: https://github.com/doctrine/dbal/blob/3.6.x/src/Schema/SqliteSchemaManager.php#L114-L126

**Comment by MartinDepero** [comment]
Yes, it works on DoctrineBundle 2.8.3 but not on >=2.9.0

Indeed, in SqliteSchemaManager::dropDatabase, there is no connection closure logic. (I didn't realise that before opening this issue).
So I guess something else has changed with 2.9.0.

Found this change in the history : 
https://github.com/doctrine/DoctrineBundle/commit/402d02ba1dd9bdb5b828e0e8d59b9e8935931175#diff-d85edf07d9e5d7c0e9c357c1543afcde2587b0b81a677d9dbe3c500f605a404e
I revert this change to try. It works well on 2.9.0 without passing the configuration to the reopened connection.

In my case the problem seems to come from the middlewares in the configuration passed to the reopened connection.
(if no middleware in configuration, no problem)

Is this more a dbal issue ?

**Comment by ostrolucky** [comment]
Does https://github.com/doctrine/DoctrineBundle/pull/1686 fix your issue?

**Comment by MartinDepero** [comment]
A bit late, I confirm that #1686 fix my issue. Thanks
