### ISSUE TITLE
doctrine:schema:update missing

### ISSUE THREAD

**Issue by vwasteels** [doctrine/DoctrineBundle#166]
it seems like my 

`php app/console doctrine:schema:update`

command is not available anymore, am I missing some config ?

`There are no commands defined in the "doctrine:schema" namespace.`

The other doctrine command are all there ...

Thanks for helping !!

**Comment by stilllife00** [comment]
This still happens to me

    "symfony/symfony": "2.3.*",
    "doctrine/doctrine-bundle": "^1.5",

Ubuntu 14.04
