### ISSUE TITLE
URL connection parameter is deprecated

### ISSUE THREAD

**Issue by cesurapp** [doctrine/DoctrineBundle#1665]
New symfony 6.3 installation. Doctrine and Phpunit installed.

.env:
```
DATABASE_URL=postgresql://root:@127.0.0.1:5432/testdb?serverVersion=14
```

test file:
```
public function testSomething(): void
{
    $kernel = self::bootKernel();

    $this->assertSame('test', $kernel->getEnvironment());
    $doctrine = static::getContainer()->get('doctrine')->getManager();        
}
```
phpunit test result:

```
Remaining indirect deprecation notices (2)

  1x: The "url" connection parameter is deprecated. Please use Doctrine\DBAL\Tools\DsnParser to parse a database url before calling Doctrine\DBAL\DriverManager. (DriverManager.php:256 called by DriverManager.php:172, https://github.com/doctrine/dbal/pull/5843, package doctrine/dbal)
    1x in UserTest::tearDown from App\Tests

  1x: Doctrine\DBAL\Connection::getEventManager is deprecated. (Connection.php:296 called by EntityManager.php:167, https://github.com/doctrine/dbal/issues/5784, package doctrine/dbal)
    1x in UserTest::tearDown from App\Tests
```

**Comment by greg0ire** [comment]
Regarding the first deprecation, I think the recommendation documented here: https://github.com/doctrine/dbal/blob/3.6.x/UPGRADE.md#deprecated-the-url-connection-parameter 
should be applied here and in other places in this bundle where the `DriverManager` is called: https://github.com/doctrine/DoctrineBundle/blob/e6da248067559c88792aa12320f9b11323583937/ConnectionFactory.php#L70

**Comment by greg0ire** [comment]
For the second, I suppose the ORM should deprecate not passing a dedicated entity manager to the constructor of `EntityManager`.

**Comment by dmaicher** [comment]
@ostrolucky let's re-open until @stof fixed the url parameter deprecation

**Comment by dmaicher** [comment]
Will be part of 2.10.0
