### ISSUE TITLE
explicit transactions and EntityManager::flush() yields deprecation warning.

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [doctrine/DoctrineBundle#1666]
hi

for my tests i use a simple setup/teardown functions which starts and rollsback transactions.

```php
        $this->em = $this->container->get(EntityManagerInterface::class);
        $this->em->beginTransaction();
```

and 

```php
    protected function tearDown(): void
    {
        $this->em->rollback();
        parent::tearDown();
    }
```

starting with the latest versions i start to get deprecation warnings about nested transactions, when prepareing the database:

```
        $this->revision = new Revision(1, $this->provider);
        $this->em->persist($this->provider);
        $this->em->flush();
```

i am wondering if thats correct, and if flush() should start a nested transactions? is that intentionally or is that a bug? :thinking: 

since i am running postgres, which does not support nested transactions, i am wondering if that was previously silently ignored?

```
 🐘 07:41:31 » docker@127.0.0.1:5432/fis # begin;
Time: 0.572 ms
 🐘 07:41:32 » docker@127.0.0.1:5432/fis *# begin;
WARNING:  there is already a transaction in progress
Time: 0.397 ms
```

**Comment by ostrolucky** [comment]
I think issue is that you are doing $this->em->beginTransaction();. This is not needed because transactions in ORM are implicit. I would suggest to just remove that.

**Comment by dmaicher** [comment]
Did you configure DBAL to use savepoints for nested transactions? This can be configured on connection level: 

```yaml
doctrine:
    dbal:
        connections:
            default:
                use_savepoints: true
``` 

Maybe this would solve the problem.

**Comment by verfriemelt-dot-org** [comment]
> I think issue is that you are doing $this->em->beginTransaction();. This is not needed because transactions in ORM are implicit. I would suggest to just remove that.

if i remove that, all (nested)transactions during flush will be in fact flushed to disk. this is what i want to avoid to keep my testdatabase clean and in a reproducable state.
this is faster compared to using for example deletes or a database purger.

the question now is, should - without the use of savepoints, which i did *not* enabled - doctrine recognize a current transaction and do not attempt to open a nested transaction during a flush?
i checked the documentation, and found this question unanswered. :thinking: but maybe its just an assumption i made

> Did you configure DBAL to use savepoints for nested transactions? This can be configured on connection level:

this would in fact solve the notification, since savepoints are supported.

**Comment by dmaicher** [comment]
> if i remove that, all (nested)transactions during flush will be in fact flushed to disk. this is what i want to avoid to keep my testdatabase clean and in a reproducable state.
this is faster compared to using for example deletes or a database purger.

You could also look into https://github.com/dmaicher/doctrine-test-bundle

> the question now is, should - without the use of savepoints, which i did not enabled - doctrine recognize a current transaction and do not attempt to open a nested transaction during a flush?
i checked the documentation, and found this question unanswered. thinking but maybe its just an assumption i made

this should then be raised at doctrine/dbal and not here on the Bundle repo though
