### ISSUE TITLE
Table name prefixes depending on Entity class namespace prefixes

### ISSUE THREAD

**Issue by mpdude** [doctrine/DoctrineBundle#1674]
I am opening this here as a cross-posting of https://github.com/doctrine/orm/issues/10772.

#### Use case

I have a Symfony application and use two third-party bundles. Both bundles bring along an ORM entity classes, including Acme\Entity\Category and SuperduperInc\Entity\Category. Both compete for the category table name.

What I'd like to have is a configuration setting that can be used to give table name prefixes depending on entity class namespace prefixes.

If I could configure table name prefixes Acme\Entity\=> acme_ and SuperduperInc\Entity\ => superduper_, this could be resolved.

It might be feasible using the ORMs event system and the `loadClassMetadata` event.

**Comment by ostrolucky** [comment]
I don't believe this is a common enough need to warrant having this in bundle, sorry
