### ISSUE TITLE
ServiceEntityRepository slow for PHP Unit tests

### ISSUE THREAD

**Issue by stepozer** [doctrine/DoctrineBundle#1682]
After upgrade from 2.8.0 to 2.8.1 I found big performance degradation for my big Symfony project. From 5 minutes to 8 minutes. I found if I totally disable this code (Repository/ServiceEntityRepository.php):

```
if (trait_exists(LazyGhostTrait::class)) {
    /**
     * @template T of object
     * @template-extends LazyServiceEntityRepository<T>
     */
    class ServiceEntityRepository extends LazyServiceEntityRepository
    {
    }
} else {
```

In this case everything working as before. How totally disable this `LazyGhostTrait`? I don't need it. I also found some performance issue with Symfony 6.1=>6.3 I believe it is related to same issue. This LazyGhostTrait very strange functionality and slow in test mode. I want totally disable it. 

Symfony version: 6.3
Doctine Bundle version 2.8.1
PHPUnit version 9.6.3

**Comment by ostrolucky** [comment]
Do you have `enable_lazy_ghost_objects` option set to false? Is removing that conditional decisive, or removing this concrete branch of conditional decisive? Try simply negating the condition.

Related: https://github.com/doctrine/DoctrineBundle/issues/1651

Anyways, if you have performance issues with classes using LazyGhostTrait, I would say you should report this issue for symfony/var-exporter in https://github.com/symfony/symfony/issues

cc @nicolas-grekas
