### ISSUE TITLE
[BC break][LazyServiceEntityRepository] Cannot filter query with inheriting class fields anymore

### ISSUE THREAD

**Issue by ambroisemaupate** [doctrine/DoctrineBundle#1693]
### Bug Report

|    Q        |   A
|------------ | ------
| Since     | 2.8.1
| doctrine/dbal | 3.3.0 to 3.6.5 |
| doctrine/orm | 2.16.0 |

#### Summary

Since `doctrine/doctrine-bundle` v2.8.1 I cannot filter a query on inherited class with its fields.
I've tried to fix `doctrine/dbal` version from 3.3 to 3.6. This issue only occurs  when I upgrade `doctrine/doctrine-bundle` after 2.8.0.

#### Current behaviour

```php
namespace MyProject\Model;

#[Entity]
#[InheritanceType('SINGLE_TABLE')]
#[DiscriminatorColumn(name: 'discr', type: 'string')]
#[DiscriminatorMap(['person' => Person::class, 'employee' => Employee::class])]
class Person
{
    #[Column(name: 'user_name', nullable: true, unique: false, length: 250)]
    protected string $name;
}

#[Entity]
class Employee extends Person
{
    #[Column(name: 'rank', nullable: true, unique: false, length: 250)]
    protected string $rank;
}
```
---

Now imagine you have to query **only** Employees by their rank:

```php
$queryBuilder = $this->managerRegistry->getRepository(MyProject\Model\Employee::class)
$queryBuilder
    ->andWhere($queryBuilder->expr()->eq('o.rank', 'boss'))
    ->getDQL();
```

Since `doctrine/doctrine-bundle` 2.8.1 generated DQL looks like that:

```sql
MyProject\Model\Person o 
    WHERE o INSTANCE OF MyProject\Model\Employee AND 
        o.rank = "boss"
```

Then trigger error: 

```
[Semantical Error] line 0, col 316 near 'rank': Error: Class MyProject\\Model\\Person has no field or association named rank
```

#### Expected behaviour

Before 2.8.1, generated DQL looked like:

```sql
MyProject\Model\Employee o 
    WHERE o.rank = "boss"
```

**Comment by ostrolucky** [comment]
There weren't many changes in 2.8.1. Can you pinpoint the issue? https://github.com/doctrine/DoctrineBundle/compare/2.8.0...2.8.1 Also, are you sure you updated doctrine-bundle only and nothing else got updated?

**Comment by ambroisemaupate** [comment]
I only see the new `LazyServiceEntityRepository` class which could missmatch parent and child classes ?

I only upgraded `doctrine/doctrine-bundle`  from 2.8.0 to 2.8.1 and nothing else to see the problem.

```
composer update -o         
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.4.*"
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading doctrine/doctrine-bundle (2.8.0 => 2.8.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading doctrine/doctrine-bundle (2.8.0 => 2.8.1): Extracting archive
```

**Comment by ambroisemaupate** [comment]
My entities use a `Repository` class that extends `Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository`, since 2.8.1, ServiceEntityRepository became an alias of `LazyServiceEntityRepository`

**Comment by ambroisemaupate** [comment]
That's it, if I change my repositories to not extend `LazyServiceEntityRepository` anymore but extend `\Doctrine\ORM\EntityRepository` and implement `ServiceEntityRepositoryInterface` the problem is solved.

`LazyServiceEntityRepository` may break parent and child class field resolving...

**Comment by ostrolucky** [comment]
I cannot reproduce the issue. Perhaps you are using some older, buggy version of var-exporter or orm? Otherwise please add some isolated example/project we can use as reproducer.
