### ISSUE TITLE
Default transaction isolation level configuration

### ISSUE THREAD

**Issue by someniatko** [doctrine/DoctrineBundle#1700]
DBAL allows overriding transaction isolation level (session-wise I presume): https://www.doctrine-project.org/projects/doctrine-dbal/en/2.4/reference/transactions.html

I would like to set the default isolation level in the Symfony bundle's configuration for a given connection config.

Perhaps if set, this setting should make execute a `Connection#setTransactionIsolation($level)` method, which under the hood executes a SQL statement (at least for MySQL/MariaDB), before any other query / statement is executed.

**Comment by ostrolucky** [comment]
There isn't such config on configuration level in DBAL, this setting is per transaction, as it executes a query

**Comment by someniatko** [comment]
This setting can be enabled on global level, on session level, and per-query (or per transaction) - at least in MySQL/MariaDB. DBAL's `Connection#setTransactionIsolation($level)` sets it per-session, which is exactly what I need.

For instance, this is from `AbstractMySQLPlatform` of DBAL:

```php
    public function getSetTransactionIsolationSQL($level)
    {
        return 'SET SESSION TRANSACTION ISOLATION LEVEL ' . $this->_getTransactionIsolationLevelSQL($level);
    }
```

**Comment by someniatko** [comment]
Meanwhile I have implemented this in my project as a DBAL Middleware: https://gist.github.com/someniatko/60c26399cf83a613c3c852f11a8ca76f

I think a similar approach could be used in the bundle.

**Comment by stof** [comment]
If the DBAL maintainer add such middleware in DBAL itself, I'm OK with adding its configuration in DoctrineBundle.

But otherwise, I would leave it to a middleware handled separately, either in your own project or in a bundle you share that would provide this middleware and tag it to register it.

the only non-core middlewares that are registered by the bundle itself are the ones related to integrating DBAL with the Symfony profiler (for which the middlewares are implemented in `symfony/doctrine-bridge` and not in `doctrine/dbal`).

**Comment by someniatko** [comment]
I get your point, yeah, this is not a totally trivial addition in a sense it is not just a static configuration value, but requires some runtime behavior, which is SQL statement execution. And you would not like to add such behaviors to the bundle to keep it clean and with a focused purpose.

The question on how to set the default transaction isolation level in Symfony came up a few times on stackoverflow before, so such feature is not totally unnecessary. However indeed you are right that a middleware with the behavior itself probably does not belong here. It also does not belong to the `symfony/doctrine-bridge` either because it has nothing to do with integrating the two. And for DBAL I believe it's not "core" enough, so yeah, it seems it can only live as a separate lib.

**Comment by ostrolucky** [comment]
Thanks for understanding. Let's close.
