### ISSUE TITLE
MessengerTransportDoctrineSchemaListener is being be registered if symfony/doctrine-messenger is not installed.

### ISSUE THREAD

**Issue by oleg-andreyev** [doctrine/DoctrineBundle#1706]
### Symfony version(s) affected

6.3.x

### Description

```sh
❯ composer info 'symfony/*' | grep doctrine-messenger
<empty>
```

Listener that is responsible for creating schema is being called.
![image](https://github.com/symfony/symfony/assets/1244112/65aa96f8-c054-4149-88eb-dc67240be6fb)

While this may not be an issue in majority of cases because there is a validation for `DoctrineTransport`
It's causing issue when iterating over all `transports`, it tries to initialise transport and throwing 

```
No transport supports the given Messenger DSN.
or 
Environment variable not found: "MESSENGER_TRANSPORT_DSN". 
```

### Possible Solution

Current workaround

```php
class AppCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        /**
         * The Doctrine transport component (symfony/doctrine-messenger) is optional.
         * Remove service definition, if it is not available
         */
        if (class_exists(DoctrineTransportFactory::class)) {
            return;
        }

        $definition = $container->getDefinition('doctrine.dbal.default_connection.event_manager');
        $listeners = $definition->getArgument(1);
        foreach ($listeners as $i => $listener) {
            if (!is_string($listener)) {
                [, $listener] = $listener;
            }

            if ($listener === 'doctrine.orm.messenger.doctrine_schema_listener') {
                unset($listeners[$i]);
            }
        }
        $definition->setArgument(1, array_values($listeners));
    }
}
```

**Comment by oleg-andreyev** [comment]
https://github.com/symfony/symfony/issues/52049

**Comment by HypeMC** [comment]
I believe this is a problem in your configuration, not the service wiring/compiler pass. If you've removed the doctrine messenger transport, you also need to remove all references to it. How does your `messenger.yaml` look like, have you removed the default failure transport config which uses doctrine, eg `failed: 'doctrine://default?queue_name=failed'`?

**Comment by ostrolucky** [comment]
You are not really explaining why you believe that MessengerTransportDoctrineSchemaListener should work only if symfony/doctrine-messenger is present

**Comment by oleg-andreyev** [comment]
@ostrolucky if I don't have `doctrine-messenger` installed, I don't have any "logic" that will publish/consume messages from `transport table` and if I don't have any logic to publish/consume message from `transport table` it should not be added to schema.

Schema is not altered which is correct, but it should not be even called if `doctrine-messenger` is no present, agree?

**Comment by ostrolucky** [comment]
Agreed. PR welcome.
