### ISSUE TITLE
Added readonly while the Repository isn't PHP >= 8.1

### ISSUE THREAD

**Issue by Hanmac** [doctrine/DoctrineBundle#1736]
Using [Dependency Analysis (8.0, highest, ^5.4)](https://github.com/Setono/CronExpressionBundle/actions/runs/7169709489/job/19520731716#logs)
Doing this `composer-require-checker check`

showed this Error
                                                           
>  Parsing the file [/home/runner/work/CronExpressionBundle/CronExpressionBundle/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryProxy.php] resulted in an error: Syntax error, unexpected T_STRING, expecting T_VARIABLE on line 34     

https://github.com/doctrine/DoctrineBundle/blob/4d7352a8b27f36866d2b62ac7d2016782270a07d/Repository/ServiceEntityRepositoryProxy.php#L34-L35

While at the same time:

https://github.com/doctrine/DoctrineBundle/blob/4d7352a8b27f36866d2b62ac7d2016782270a07d/composer.json#L32

either the PHP Version in the composer.json should have been bumped, or the `readonly` shouldn't have been added

**Comment by stof** [comment]
This code indeed looks broken (promoted properties should not be used either as the min PHP version is 7.4)

**Comment by dmaicher** [comment]
But that class should only be used with ORM 3, or?

https://github.com/doctrine/DoctrineBundle/blob/4d7352a8b27f36866d2b62ac7d2016782270a07d/Repository/ServiceEntityRepository.php#L32

And ORM 3 requires PHP 8.1

**Comment by Hanmac** [comment]
@dmaicher https://github.com/maglnet/ComposerRequireChecker somehow found the file and tried to parse it on the lower PHP versions

**Comment by wouterj** [comment]
Imho, this a bug with the static analysis tool: the class is not used on PHP 8.0.

Also sharing what I said on Slack:

> I don't really understand why it's running `composer-require-checker` on all versions. But if it's using the latest version of `composer-require-checker`, it should understand PHP 8.1 syntax even when running PHP 8.0 (as `nikic/php-parser`'s parsing is independent on the actual PHP version afaik)

**Comment by ostrolucky** [comment]
I agree. It's issue in a tool, not in this repo. We can close.
