### ISSUE TITLE
Incompatibility with symfony/doctrine-bridge 7.x

### ISSUE THREAD

**Issue by DjLeChuck** [doctrine/DoctrineBundle#1737]
Services `doctrine.orm.listeners.doctrine_dbal_cache_adapter_schema_subscriber`, `doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber` and `doctrine.orm.listeners.doctrine_token_provider_schema_subscriber` are using classes which no longer exists in `symfony/doctrine-bridge` as stated in the `CHANGELOG`: https://github.com/symfony/doctrine-bridge/blob/7.0/CHANGELOG.md

This classes was already deprecated and are now removed from the codebase.

Each of this services should use a `Listener` instead of `Subscriber`:
* `doctrine.orm.listeners.doctrine_dbal_cache_adapter_schema_subscriber`: should use `DoctrineDbalCacheAdapterSchemaListener` instead of `DoctrineDbalCacheAdapterSchemaSubscriber`
* `doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber`: should use `DoctrineDbalCacheAdapterSchemaListener` instead of `PdoCacheAdapterDoctrineSchemaSubscriber`
* `doctrine.orm.listeners.doctrine_token_provider_schema_subscriber`: should use `RememberMeTokenProviderDoctrineSchemaListener` instead of `RememberMeTokenProviderDoctrineSchemaSubscriber`

I’m OK todo a PR, but what’s the requirements about BC Breaks?
Note that the service `doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber` was already not working with vers 6.3.

**Comment by ostrolucky** [comment]
We cannot just remove those class imports from codebase to preserve compatibility with older Symfony versions. However, there is a compatibility layer which switches between new and old classes. So what particular issue are you running into?

**Comment by DjLeChuck** [comment]
Our project is using `symfony/doctrine-bridge` v7.0.0 and `doctrine/doctrine-bundle` 2.11.1.

Adding calls to `ResolveTargetEntityListener::addResolveTargetEntity` using a `CompilerPass` doesn’t work anymore: no error, it’s just never called.

```php
$resolveTargetEntityListener = $container->findDefinition('doctrine.orm.listeners.resolve_target_entity');
$interface = 'App\My\EntityInterface';
$entity = 'App\My\Entity';
$resolveTargetEntityListener->addMethodCall('addResolveTargetEntity', [$interface, $entity, []]);
```

Switching back to `symfony/doctrine-bridge` v6.3.2 and `doctrine/doctrine-bundle` 2.10.2: all is working as expected.

---

What’s the compatibility layer you refer to?

**Comment by DjLeChuck** [comment]
To be clear: I’m not suggesting to remove any class, I’m suggesting to correct declaration of the three services in order to use the `Listerner` and not the `Subscriber` (which doesn’t exists anymore in `symfony/doctrine-bridge` 7.0) 😄

**Comment by ostrolucky** [comment]
We are using listener instead of subscriber in case subscribers are not available, BC layer for that can be seen eg. at https://github.com/doctrine/DoctrineBundle/blob/846b923363b9357c10fd7ee59360b8bca3201074/DependencyInjection/DoctrineExtension.php#L457-L460

Not sure why it doesn't work in your case. If you can dig deeper into it, that would be appreciated.

**Comment by DjLeChuck** [comment]
Yes, I’m on it! I’ve seen the Extension after posting my message.

Will get back soon I hope. :)

**Comment by DjLeChuck** [comment]
So... It was a missing tag on our side on the `doctrine.orm.listeners.resolve_target_entity`.

Sorry for the noise, I’m closing this non-issue!
