### ISSUE TITLE
Unable to setup custom id generator - MappingDriver seems like bugged

### ISSUE THREAD

**Issue by Arkemlar** [doctrine/DoctrineBundle#1738]
https://github.com/doctrine/DoctrineBundle/blob/7290b3afa49e126bae4a982c50c2a309ef4851ca/Mapping/MappingDriver.php#L55

This line of code is blocking "CUSTOM" generated value strategy. For some reason it overrides generator type to "NONE" and therefore brokes custom generator mechanics because doctrine will choose wrong case in switch block:
it chooses this case
https://github.com/doctrine/orm/blob/f80ef66ffb68bfa842071e2d818e87a07a2d014e/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L706
instead of this
https://github.com/doctrine/orm/blob/f80ef66ffb68bfa842071e2d818e87a07a2d014e/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L720
<img width="876" alt="изображение" src="https://github.com/doctrine/DoctrineBundle/assets/19671202/2769542a-1d3f-4c9a-971d-3916095e8204">

Why doctrine bundle does that? Can we fix it real quick?

**Comment by ostrolucky** [comment]
That line of code shouldn't trigger, because it's guarded by condition `$this->idGeneratorLocator->has($metadata->customGeneratorDefinition['class'])`. Could you provide more info?
