### ISSUE TITLE
Unsetting "dbname" param leads to incorrectly casting deprecation

### ISSUE THREAD

**Issue by kwolniak** [doctrine/DoctrineBundle#1743]
While preparing the database for testing, I execute the command `doctrine:database:drop`.
And there is a code:
https://github.com/doctrine/DoctrineBundle/blob/4089f1424b724786c062aea50aae5f773449b94b/Command/DropDatabaseDoctrineCommand.php#L76
and inside `constructPdoDsn` function it leads to cast deprecation in line 92:
https://github.com/doctrine/dbal/blob/0ac3c270590e54910715e9a1a044cc368df282b2/src/Driver/PDO/PgSQL/Driver.php#L68-L105
so this deprecation is incorrect because `dbname` is set via url.

**Comment by ostrolucky** [comment]
I am not sure what we can do here, since this is posgres specific. I don't think we should put in postgres specific code branch for this here. I would say this deprecation is informational and stuff should work with dbal 4.x, right?

**Comment by ostrolucky** [comment]
This has been resolved by https://github.com/doctrine/DoctrineBundle/pull/1761
