### ISSUE TITLE
Add support to the new id entity generation preferences in Doctrine ORM 3.0

### ISSUE THREAD

**Issue by TeLiXj** [doctrine/DoctrineBundle#1744]
In the lastest ORM beta version, a new setting is used to configure the default value for the `#[ORM\GeneratedValue]` attribute if has no values https://github.com/doctrine/orm/releases/tag/3.0.0-beta1

This appears in a deprecation notice in the lastest versions of Symfony and I only found a workaround using a compiler pass https://github.com/doctrine/DoctrineBundle/issues/1740#issuecomment-1903582154 but I think that should be configured directly in the bundle

**Comment by BigBenJr** [comment]
Indeed I encounter this depreciation message:

> User Deprecated: Relying on non-optimal defaults for ID generation is deprecated, and IDENTITY results in SERIAL, which is not recommended. Instead, configure identifier generation strategies explicitly through configuration. We currently recommend "SEQUENCE" for "Doctrine\DBAL\Platforms\PostgreSqlPlatform", so you should use $configuration->setIdentityGenerationPreferences([ "Doctrine\DBAL\Platforms\PostgreSqlPlatform" => ClassMetadata::GENERATOR_TYPE_SEQUENCE, ]); (ClassMetadataFactory.php:755 called by ClassMetadataFactory.php:629, https://github.com/doctrine/orm/issues/8893, package doctrine/orm)

What is the best fix at the moment ?

**Comment by RazielRodrigues** [comment]
Can I work on that?

**Comment by ostrolucky** [comment]
of course

**Comment by TeLiXj** [comment]
closed by https://github.com/doctrine/DoctrineBundle/pull/1813
