### ISSUE TITLE
Missing SimplifiedYamlDriver but it is still required in code.

### ISSUE THREAD

**Issue by kczereczon** [doctrine/DoctrineBundle#1750]
I just have installed latest version of doctrine bundle. 
I know that yml was deprecated but didn't expect that it will be removed totally from doctrine I thought that new
driver will comes in.

In getDoctrine_Orm_DefaultEntityManagerService.php line 60:
  Attempted to load class "SimplifiedYamlDriver" from namespace "Doctrine\ORM\Mapping\Driver".  
  Did you forget a "use" statement for another namespace?
  
Packages versions:
doctrine/doctrine-bundle: 2.11.1
doctrine/doctrine-migrations-bundle: 3.3
doctrine/orm: 3.0

**Comment by ostrolucky** [comment]
This is expected, Yaml was removed completely in ORM 3.x. You need to migrate to different format.
