### ISSUE TITLE
Create and drop PostgreSQL database fails

### ISSUE THREAD

**Issue by seb-jean** [doctrine/DoctrineBundle#1757]
Hello,
With ORM 3, `doctrine:database:create` and `doctrine:database:drop` failed.

**Comment by ostrolucky** [comment]
Hi, can you please provide more information?

**Comment by jeremy-vvf** [comment]
Same for me, `dbname` doesn't exist on the Driver connection, so he wants to delete "root" database.
The result of this line `$this->constructPdoDsn($safeParams)` on Driver class give `pgsql:host=127.0.0.1;port=5432;`. The `dbname` is missing.

**Comment by ostrolucky** [comment]
So this is Pgsql specific?

**Comment by seb-jean** [comment]
Yes postgresql

**Comment by andreybolonin** [comment]
https://github.com/doctrine/dbal/issues/6296
