### ISSUE TITLE
DBAL 4 `setNestTransactionsWithSavepoints` deprecation

### ISSUE THREAD

**Issue by dmaicher** [doctrine/DoctrineBundle#1758]
With the latest [recipe changes ](https://github.com/symfony/recipes/pull/1290) we are always explicitly enabling savepoints. 

However on DBAL 4 this leads to 

>    44x: Doctrine\DBAL\Connection::setNestTransactionsWithSavepoints is deprecated and will be removed in 5.0 (Connection.php:948 called by App_KernelTestDebugContainer.php:611, https://github.com/doctrine/dbal/pull/5383, package doctrine/dbal)

How should we handle this? Revert the recipe change? Somehow fix it here?

Also see https://github.com/symfony/demo/pull/1494 where I removed `use_savepoints: true` for now.

**Comment by ostrolucky** [comment]
Yeah I would say it should just be removed from recipe. Recipes are mostly installed first time when the bundle is installed, which is usually when project is new, in that case newest orm and dbal would be installed.
