### ISSUE TITLE
Prefix pgsql uses PDO PgSQL driver instead of PgSQL

### ISSUE THREAD

**Issue by hacfi** [doctrine/DoctrineBundle#1763]
At https://github.com/doctrine/DoctrineBundle/blob/2.11.x/ConnectionFactory.php#L42 the prefix `pgsql` is mapped to `pdo_pgsql` instead of `pgsql` which makes a difference here:
https://github.com/doctrine/dbal/blob/4.0.x/src/DriverManager.php#L80-L86

Was there a reason for this or might this be an overlook? The only way to use the `pgsql` driver right now is setting it manually under `doctrine:` -> `dbal:` -> `driver: pgsql` and then use a url without a prefix (`DATABASE_URL=//app:!ChangeMe!@127.0.0.1:5432/app`).

**Comment by ostrolucky** [comment]
Same list is used in dbal 3.x https://github.com/doctrine/dbal/blob/00d8f60e1ea400ccb65f3a48ecfb3b7465b54908/src/DriverManager.php#L103-L112. You would have to dig in there to find out historical reason why it was done. In bundle, same list was just taken over.

What you can use here, is `driverClass` option. This way bundle/dbal doesn't need to rely on the driver alias.

**Comment by cizordj** [comment]
Setting the `driver_class` option is not really a solution, I found these comments on the source code.

`vendor/doctrine/dbal/src/DriverManager.php:`
```php
// The requested driver from the URL scheme takes precedence
// over the default custom driver from the connection parameters (if any).
````

```php
// If a schemeless connection URL is given, we require a default driver or default custom driver
// as connection parameter.
```

**Comment by stof** [comment]
Unlike the deprecated mapping of the DriverManager of DBAL 3.x which was hardcoded, the mapping defined in DoctrineBundle is the *default* mapping. The actual mapping used in a project combines this default mapping and the bundle configuration. So you can configure it.

**Comment by cizordj** [comment]
You're right, we CAN combine the default mapping with our own configuration.

```yaml
---
doctrine:
  dbal:
    driver_schemes:
      custom_scheme: driver_name
      pgsql: pgsql
```

However, we cannot replace the keys in the original map:

```txt
Registering a scheme with the name of one of the official drivers is forbidden, as those are defined in DBAL itself. The following schemes are forbidden: pgsql
```

Being able to so would solve the issue reported here without needing to mess with the schemas in the environment variables.
