### ISSUE TITLE
Custom fields always treated as changed in Postgres

### ISSUE THREAD

**Issue by speller** [doctrine/DoctrineBundle#1765]
I'm defining a custom class for `numeric` fields:

```php
class MyDecimalType extends DecimalType
{
    public function getName(): string
    {
        return 'my_decimal';
    }

    public function convertToPHPValue($value, AbstractPlatform $platform): Decimal
    {
         // ...
    }
}
```

I've added it to class mappings:

```yml
doctrine:
  dbal:
    types:
      my_decimal: App\Entity\Type\MyDecimalType
```

The field definition is the following:

```php
        #[ORM\Column(type: 'my_decimal', precision: 12, scale: 4, nullable: true)]
        public ?Decimal $vat,
```

The table on this entity is created correctly. But on every run of the `doctrine:migrations:diff` command, such field is treated as modified and appears in all further auto-generated migrations.

From my quick research, I understood that the issue happens on schema comparison. The "from" schema is read from the database and the field type is detected as `\Doctrine\DBAL\Types\DecimalType` but the "to" schema is read from entities and the field type is detected as `\App\Entity\Type\MyDecimalType`. So it compares class names and decides that the field has changed while it doesn't. What I'm doing wrong?

**Comment by dmaicher** [comment]
Is this possibly related to `Doctrine\DBAL\Types\Type::requiresSQLCommentHint()`? Wrong repository for reporting this issue though.

**Comment by ostrolucky** [comment]
Indeed. Not sure why issue is in bundle, it's unlikely it's there and no proof was provided otherwise.
