### ISSUE TITLE
`CREATE SCHEMA public` is added to all `down` migrations in Postgres

### ISSUE THREAD

**Issue by speller** [doctrine/DoctrineBundle#1766]
I'm using the bundle with Postrgres 16. The database URL is `postgresql://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME?serverVersion=16.2&charset=utf8`. But on every `doctrine:migrations:diff` it creates migrations like the following:

```php
final class Version20240311103945 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
    }
}
```
How to fix this?

**Comment by ostrolucky** [comment]
better to post questions like this to stackoverflow, I don't see issue in a bundle, since it doesn't have anything to do with generating migrations
