### ISSUE TITLE
Decorating DoctrineRegistry service breaks 'explain query' functionality in symfony webprofiler.

### ISSUE THREAD

**Issue by pjordaan** [doctrine/DoctrineBundle#1772]
I decorated the DoctrineRegistry service in my application so I can combine the Doctrine registry from this bundle and an EntityManager instance created outside this bundle by a different library (if there is a better solution for this, feel free to send me in the right direction).

Everything seems to work, except the explain query action found in the symfony web profiler. It seems the ProfilerController is not using Doctrine\Persistence\ManagerRegistry as typehint, but is expecting a specific class instead. It results in this error:

```
An exception has been thrown during the rendering of a template ("Doctrine\Bundle\DoctrineBundle\Controller\ProfilerController::__construct(): Argument #2 ($registry) must be of type Doctrine\Bundle\DoctrineBundle\Registry, App\Bridge\Doctrine\MergedRegistry given, called in /var/www/html/var/cache/dev/ContainerPcHORIt/getProfilerControllerService.php on line 23").
```

Is it possible to typehint this as Doctrine\Persistence\ManagerRegistry so decorating the Doctrine registry can be done without problems?

**Comment by dmaicher** [comment]
this will be fixed in the upcoming 2.12 release
