### ISSUE TITLE
Using SQLite results in "no such table" error

### ISSUE THREAD

**Issue by WishCow** [doctrine/DoctrineBundle#178]
I'm not sure if this is a Symfony or a Doctrine, or a DoctrineBundle (or a misconfiguration) related problem, but I cannot get Symfony2 to work with SQLite databases. If I configure Symfony to use SQLite, every table access results in the following PDOException:

An exception occurred while executing 'SELECT \* FROM user':
SQLSTATE[HY000]: General error: 1 no such table: user

This is on a completely fresh sf2 install (php composer.phar create-project symfony/framework-standard-edition path 2.2.1), but I can also confirm the same problem on 2.1.7.

config.yml:

``` yaml
doctrine:
    dbal:
        driver:   pdo_sqlite
        user:     xxx
        password: xxx
        charset:  UTF8
        path:     /tmp/test.sqlite
```

Use the CLI client to generate a table:

echo "CREATE TABLE user (id INTEGER NOT NULL, PRIMARY KEY(id));" | sqlite3 /tmp/test.sqlite

Edit Acme\DemoBundle\Controller\WelcomeController:

``` php
    public function indexAction()
    {
        $conn = $this->get('database_connection');
        $users = $conn->fetchAll('SELECT * FROM user');
        return $this->render('AcmeDemoBundle:Welcome:index.html.twig');
    }
```

Accessing the starting page now results in the exception mentioned above. I can confirm that the table is visible with the CLI sqlite3 client, and I can also access it if I write a simple php script that uses Doctrine DBAL:

``` php
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\DriverManager;
require('vendor/autoload.php');
$params = [
    'driver' => 'pdo_sqlite',
    'path' => '/tmp/test.sqlite',
    'user' => 'xxx',
    'password' => 'xxx',
    'charset' => 'UTF8'
];
$config = new Configuration();
$conn = DriverManager::getConnection($params, $config);
$users = $conn->fetchAll('SELECT * FROM user');
var_dump($users); // works
```

**Comment by kylemilloy** [comment]
Anyone got a mirror for that link above?

**Comment by WishCow** [comment]
I don't have a mirror, but I think the gist of the problem is that depending on some systemd configuration, your user/services might get a private /tmp folder in some cases. Try moving the database out of /tmp, to somewhere else, and see if it solves your problem.

**Comment by gogaz** [comment]
I'm having the same issue on Windows, so it doesn't look like it's related to systemd for me

**Comment by adamquaile** [comment]
I had this, and my issue was that I had missed `%kernel.project_dir%` from my path

`DATABASE_URL=sqlite:///%kernel.project_dir%/database.sqlite` worked where `DATABASE_URL=sqlite:///database.sqlite` only worked in the CLI.
