### ISSUE TITLE
Default dbname broken since 2.11.4

### ISSUE THREAD

**Issue by TamasSzigeti** [doctrine/DoctrineBundle#1783]
Hi!
We are using a custom `default_dbname` on DigitalOcean postgres servers because `postgres` db is not accessible there. After #1761 when running `doctrine:database:create`, it fails with "FATAL: no such database: postgres"

**Comment by ostrolucky** [comment]
Can you try if https://github.com/doctrine/DoctrineBundle/pull/1784 fixes the issue for you?

BTW that option is deprecated, you should move away from it anyways.

**Comment by TamasSzigeti** [comment]
It does fix it indeed, thank you!

I can see now that it is deprecated in v4 but not sure how to replace it, the db url already contains the db name that is to be created, but it is still trying to connect to `postgres` db without a default… Unless it does not do that in v4 in which case it will indeed be obsolete. Until then, I see no way to move away from it.

**Comment by ostrolucky** [comment]
Yes DBAL does not connect to postgres anymore in v4. But bundle will 😅
