### ISSUE TITLE
Incorrect string value saving emoji

### ISSUE THREAD

**Issue by Guervyl** [doctrine/DoctrineBundle#1792]
I have a Symfony project using doctrine. When the text has emoji to insert in the database I get the error `An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\xA4\x97Gr...' for column ....` 

I have search the web and the said to change the database charset to `utf8mb4` and I did change to `utf8mb4_general_ci`. The database I'm using is `mariadb 10.6.5`. I can confirm that the problem is not the database because using phpmyadmin I can execute the insert query successfully and it saves with the emoji. But using Doctrine I keep getting the error. 

The stack trace is:

 ```
at C:\wamp64\www\invoice-manager\vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php:117
  at Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(object(Exception), object(Query))
     (C:\wamp64\www\invoice-manager\vendor\doctrine\dbal\src\Connection.php:1938)
  at Doctrine\DBAL\Connection->handleDriverException(object(Exception), object(Query))
     (C:\wamp64\www\invoice-manager\vendor\doctrine\dbal\src\Connection.php:1880)
  at Doctrine\DBAL\Connection->convertExceptionDuringQuery(object(Exception)
```

And the text is `🤗Gracias por comunicarse....` 

The real mysql error is `An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\xA4\\x97 G...' for column....`

If I remove the emoji it works fine.

**Comment by greg0ire** [comment]
Invalid _datetime_ format? :thinking:

**Comment by ostrolucky** [comment]
Sorry this has nothing to do with bundle

**Comment by Guervyl** [comment]
Actually it is a doctrine error. I leave a video to see a live error https://drive.google.com/file/d/11q61P4phZWWW2McDauut5ilW5ZOMPiBl/view?usp=sharing

**Comment by ostrolucky** [comment]
Doctrine != doctrine-bundle. We just provide wiring for doctrine/dbal and doctrine/orm. Look at this:

![image](https://github.com/doctrine/DoctrineBundle/assets/496233/bac461b6-b772-494b-b702-b03690964452)
There are no usages of `Doctrine\Bundle`, so this is a wrong repository.

But also, this is unlikely a problem in any of the doctrine repositories. This is more like issue with db encoding/configuration. Better to create a stackoverflow post I would say.

**Comment by stof** [comment]
and also better providing a reproducing case

**Comment by Guervyl** [comment]
As I installed doctrine bundle through Symfony, I don't know what is the correct repository. 

Can you please point me at what repository should I ask for help? Should it be https://github.com/doctrine/dbal or https://github.com/doctrine/orm? 

Also I will post it on stackoverflow to see if someone can help because on stackoverflow the mostly focus on database problem while this is just a problem inside doctrine persistence (`Doctrine\Persistence`).  

And it is an urgent problem I need to fix it immediately to advance with the development.

**Comment by Guervyl** [comment]
Cool. I just found a fix. I had to pass the query parameters `charset=utf8mb4&collation=utf8mb4_unicode_ci` to the connection string.
