### ISSUE TITLE
Impossible to profile LoadDataFixturesDoctrineCommand

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineBundle#1801]
Symfony 6.4.7
DoctrineBundle 2.12.0
ORM 3.1.3

When I try to run `bin/console do:fi:lo  --profile -v` I get the following:

>[Error]                                                                                                                                                                   
  Call to protected method Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand::execute() from scope Symfony\Component\Console\Command\TraceableCommand 

trace:
```
at /myproject/vendor/symfony/console/Command/TraceableCommand.php:331
Symfony\Component\Console\Command\TraceableCommand->execute() at /myproject/vendor/symfony/console/Command/Command.php:326
Symfony\Component\Console\Command\Command->run() at /myproject/vendor/symfony/console/Command/TraceableCommand.php:286
Symfony\Component\Console\Command\TraceableCommand->run() at /myproject/vendor/symfony/console/Application.php:1096
Symfony\Component\Console\Application->doRunCommand() at /myproject/vendor/symfony/framework-bundle/Console/Application.php:126
Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /myproject/vendor/symfony/console/Application.php:324
Symfony\Component\Console\Application->doRun() at /myproject/vendor/symfony/framework-bundle/Console/Application.php:80
Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /myproject/vendor/symfony/console/Application.php:175
```

The command is working properly without the `--profile` flag.

**Comment by ostrolucky** [comment]
Looks like wrong repo. Command is in https://github.com/doctrine/DoctrineFixturesBundle, profile feature itself in https://github.com/symfony/symfony
