### ISSUE TITLE
Update to 2.12 breaks Symfony debug toolbar

### ISSUE THREAD

**Issue by jirikmik** [doctrine/DoctrineBundle#1807]
Hello,

after update to 2.12 debug toolbar stopped work with message 

> An error occurred while loading the web debug toolbar. Open the web profiler.

After click it shows:

> The profiler template "@Doctrine/Collector/db.html.twig" for data collector "db" does not exist.

Symfony 7.0.8 and 7.1.0. 

How to solve? Thanks

**Comment by dmaicher** [comment]
I cannot reproduce that. Works fine for me on Symfony 7.0.8.

Can you list your `doctrine/*` and `symfony/*` composer dependencies?

And one more thing: So this fails for you? `bin/console debug:twig @Doctrine/Collector/db.html.twig`?

**Comment by jirikmik** [comment]
Yes, after upgrade to 2.12 it fails:

```
Matched File
------------
 Template name "@Doctrine/Collector/db.html.twig" not found

Configured Paths
----------------
 ----------- --------------------------------------------------
  Namespace   Paths
 ----------- --------------------------------------------------
  @Doctrine   vendor/doctrine/doctrine-bundle/Resources/views/
 ----------- --------------------------------------------------
```

**Comment by jirikmik** [comment]
Excuse me, list of dependencies:
[dependencies.txt](https://github.com/user-attachments/files/15586160/dependencies.txt)

**Comment by dmaicher** [comment]
> Yes, after upgrade to 2.12 it fails:
> 
> ```
> Matched File
> ------------
>  Template name "@Doctrine/Collector/db.html.twig" not found
> 
> Configured Paths
> ----------------
>  ----------- --------------------------------------------------
>   Namespace   Paths
>  ----------- --------------------------------------------------
>   @Doctrine   vendor/doctrine/doctrine-bundle/Resources/views/
>  ----------- --------------------------------------------------
> ```

Hm strange. It should be using the new directory structure. Here my output

```
Matched File
------------

                                                                                                                        
 [OK] vendor/doctrine/doctrine-bundle/templates/Collector/db.html.twig                                                  
                                                                                                                        

Configured Paths
----------------

 ----------- -------------------------------------------- 
  Namespace   Paths                                       
 ----------- -------------------------------------------- 
  @Doctrine   vendor/doctrine/doctrine-bundle/templates/  
 ----------- -------------------------------------------- 
``` 

@ostrolucky any idea? :thinking:

**Comment by dmaicher** [comment]
@jirikmik did you try to completely purge your cache? like `rm -rf var/cache/*`?

**Comment by ostrolucky** [comment]
Ah yeah, this looks like a stale cache

**Comment by jirikmik** [comment]
A did clean only dev cache but now I removed whole cache dir with `rm -fvr` command and it is does not help.

**Comment by ostrolucky** [comment]
I think we will need a self contained reproducer for this :/

**Comment by jirikmik** [comment]
Sorry, I am new here -  what does it mean for me?

**Comment by ostrolucky** [comment]
Eg. a ZIP file or a link to repository which contains a project where we can just do `composer install` and run `bin/console` and it will show us the error you experience

**Comment by jirikmik** [comment]
During preparing data I have found that completely remove and than resync _vendor_ directory solved this problem. Three projects (6.4, 7.0, 7,1) and two different webservers...
_I am developing in PhpStorm on Windows and also composer I am running on my pc and than synchronize changes with PhpStorms Diff. Same tool I used for new upload of vendor directory._
Thanks to everybody for help.
