### ISSUE TITLE
Class `AnnotationDriver` not found issue

### ISSUE THREAD

**Issue by NicolasPineau** [doctrine/DoctrineBundle#1810]
composer.json for version 2.12 requires "doctrine/orm": "^2.17 || ^3.0" as a dev dependency.
In [this file](https://github.com/doctrine/DoctrineBundle/blob/2.12.x/src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php) the class `Doctrine\ORM\Mapping\Driver\AnnotationDriver` is used but it does not exist anymore since version 3.0 of doctrine/orm.

**Comment by ostrolucky** [comment]
We still need to reference it because we still support orm 2
