### ISSUE TITLE
"No Active Transaction" Error After Reconnecting Database in Worker Mode

### ISSUE THREAD

**Issue by girinabin** [doctrine/DoctrineBundle#1815]
I'm running FrankenPHP in worker mode with Doctrine ORM. I encountered an issue where, after manually closing the database connection (by bringing down the MySQL service with docker-compose down and then bringing it back up with docker-compose up), some requests start failing with a "There is no active transaction" exception. Other requests pass successfully, but the error continues for 4-5 requests before stabilizing.

i am running 
 "doctrine/doctrine-bundle": "^2.13",
 symfony: 7.1
php 8.3

output log:
{"message":"Beginning transaction","context":{},"level":100,"level_name":"DEBUG","channel":"doctrine","datetime":"2024-08-18T12:11:49.548382+05:45","extra":{}}
{"message":"Rolling back transaction","context":{},"level":100,"level_name":"DEBUG","channel":"doctrine","datetime":"2024-08-18T12:11:49.548573+05:45","extra":{}}
{"message":"Uncaught PHP Exception Doctrine\\DBAL\\Driver\\PDO\\PDOException: \"There is no active transaction\" at /opt/www/vendor/doctrine/dbal/src/Driver/PDO/PDOException.php line 20","context":{"exception":{"class":"Doctrine\\DBAL\\Driver\\PDO\\PDOException","message":"There is no active transaction","code":0,"file":"/opt/www/vendor/doctrine/dbal/src/Driver/PDO/PDOException.php:20","previous":{"class":"PDOException","message":"There is no active transaction","code":0,"file":"/opt/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:135"}},"errors":null},"level":500,"level_name":"CRITICAL","channel":"app","datetime":"2024-08-18T12:11:49.548958+05:45","extra":{}}

**Comment by ostrolucky** [comment]
Error looks expected. Worker expects database connection and you are shutting down database server

**Comment by girinabin** [comment]
After database connection established there is still issue for some other requests

**Comment by ostrolucky** [comment]
Probably because those other requests are using an old thread that still uses old network connection. I'm sorry but this isn't very actionable issue for us. And if you still insist on something being done, proper place is symfony/doctrine-bridge, this is quite similar to https://github.com/symfony/symfony/pull/53214
