### ISSUE TITLE
Idea for migrations files improvment

### ISSUE THREAD

**Issue by EfrosIonelu** [doctrine/DoctrineBundle#1818]
I haven't read all issues and ideas, maybe this idea was added there before.

I am working on a project more than 2 years and there are to many migrations files.
It will be great to support a folder structure like this: migrations/#year#/#month#/#migrationsName#.php

i am using
php bin/console doctrine:migrations:diff
and
php bin/console doctrine:migrations:generate

and i would like to have a structure that will be better to visualize and search in.
thanks.

**Comment by ostrolucky** [comment]
You are confusing the project, you probably meant to create this in https://github.com/doctrine/DoctrineMigrationsBundle. But my 2c is that migrations are not supposed to be kept forever, once you think you have too many of them, you should roll them up, you can find articles like this via search engine https://localheinz.com/articles/2020/06/10/rolling-up-database-migrations-with-doctrine/
