### ISSUE TITLE
missing doctrine.dbal.idle_connection_listener at 6.4.x

### ISSUE THREAD

**Issue by connorhu** [doctrine/DoctrineBundle#1828]
symfony/doctrine-bridge: 6.4.12
doctrine/doctrine-bundle: 2.13.0

After I updated the doctrine-bundle package to the latest 2.13, I got this error message:
"Class "Symfony\Bridge\Doctrine\Middleware\IdleConnection\Listener" used for service "doctrine.dbal.idle_connection_listener" cannot be found."

As you can see the version of the symfony packages is 6.4.x, but the listener was not released until 7.1. For this reason, 2.13 is currently incompatible with bridge version 6.x.

What is the intention here?
Is 2.13 already incompatible with the <=7.0.x packages, or should the code handle this incompatibility?

Thank you for your help.

**Comment by stof** [comment]
the service should be removed when using older versions of the bridge IMO.

**Comment by connorhu** [comment]
I checked the PR that added the listener and it's well written. I updated it again and now it's fine. I guess there was some cache problem. I'll close it, if I run into it again and it turns out to be a real bug, I'll reopen it. Sorry for the noise.
