### ISSUE TITLE
resolve_target_entities into my bundle

### ISSUE THREAD

**Issue by pcastrotigre** [doctrine/DoctrineBundle#185]
I am trying to add some resolver entities from my bundle by making this:

    $def = $container->findDefinition('doctrine.orm.listeners.resolve_target_entity');       
        
    $def->addMethodCall('addResolveTargetEntity', array(
            $groupInterface, $groupClass, array()
    ));

If you realize i am passing params configured for my bundle ($groupInterface and $groupClass). I need this params being initialized into my bundle and this will configure the target entities.

However, the service resolve_target_entity is private, so i can not use it. I would not like to duplicate the code of that service into my bundle just for do that. So, how could i do?

**Comment by jrobeson** [comment]
It seems like this issue could be closed?
