### ISSUE TITLE
OracleSessionInit is NOT loaded properly in the Dependency Injection

### ISSUE THREAD

**Issue by iftah** [doctrine/DoctrineBundle#217]
Hi,
I moved my project from MySQL to Oracle, and I get this error when I try to insert into the database.

An exception occurred while executing 'INSERT INTO arborescence (IDNT_ARBR, NOM_ARBR, DATE_CREATION, IDNT_SERV, IDNT_UTLS) VALUES (?, ?, ?, ?, ?)' with params [7, "B", "2013-10-09 00:00:00", 7, 1]:
ORA-01861: literal does not match format string

I solved this problem by adding the following code to : app/config/config.yml

services:
    oracle.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit 
        tags:
            - { name: doctrine.event_listener, event: postConnect }

This seems to be a bug in the DoctrineBundle. If we use the MySQL driver, the corresponding MysqlSessionInit is loaded properly in the Dependency Injection extension. But this doesn't happen with the OracleSessionInit class, if you we the Oracle driver.

Respectfully,
iftah

**Comment by jljunior3** [comment]
Can anyone help me where I set this in laravel?

services:
    oracle.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }

**Comment by stof** [comment]
well, I don't know how the DBAL integration into Laravel is configured, but I know for sure that this is the wrong place to ask. DoctrineBundle is only about integrating Doctrine with Symfony 2. you need to contact the maintainers of the laravel integration

**Comment by yezongyang** [comment]
I am using oracle11g, I have fixed the problem with @iftah config code when using query builder. But why?

**Comment by manfredjb** [comment]
@jljunior3, maybe is too late. But I have solved this in laravel at the moment when you create the connection passing the `Event Manager` as third parameter:

```
$eventManager = new \Doctrine\ORM\EntityManager();
$eventManager->addEventSubscriber(new \Doctrine\DBAL\Event\Listeners\OracleSessionInit());

$em = EntityManager::create($dbParams, $config, $eventManager);
```

**Comment by yaziderman** [comment]
For those who may face the same problem with Zend2, and Basing on the answer of @deeky666 I have get it fixed by replacing the line 

`return EntityManager::create($connection, $config); `

in the file: EntityManageFactory.php, under the Function createService.php
with the following lines:

```
$dbh = $em->getConnection();
$sth = $dbh->prepare("ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'");
$sth->execute();
return $em;
```

**Comment by Ocramius** [comment]
> in the file: EntityManageFactory.php, under the Function createService.php

@yaziderman please don't monkey-patch libraries. Also, absolutely **DO NOT** suggest others to do that.

What you want in your case is using a [delegator factory](http://ocramius.github.io/blog/zend-framework-2-delegator-factories-explained/) ([docs here](https://zendframework.github.io/zend-servicemanager/delegators/)) that acts on the `doctrine.configuration.orm_default` serfice, adding a listener to it.

</rant>

**Comment by karousn** [comment]
i have the same problem, and by added oracle listener haven't any effect on problem when we use more then database other oracle in the same time.
So @Ocramius : are they any possibility/PR/solutions to inject the listener on ORM configuration level to decoupling using the same listener by other declared ORM ?

**Comment by kimhemsoe** [comment]
@karousn Did you specify connection name with the tagging?

**Comment by karousn** [comment]
i forget to specify the connection, thank's @kimhemsoe it is work now
