### ISSUE TITLE
Introduce Container aware entity listener resolver in order to use entity listener as service

### ISSUE THREAD

**Issue by egeloen** [doctrine/DoctrineBundle#223]
Hey guys!

I'm currently moving some logic inside the new entity listeners introduced in Doctrine 2.4. The bundles supports this feature by allowing to define our own entity listener resolver service in the configuration. The issue about that is you have to redefine all the logic in order to be able to use entity listener as service.

For now, to be able to use entity listener as service, I have created a `ContainerAwareEntityListenerResolver` which maps class names to service id through a compiler pass. When it resolves the entity listener, if the class names exists, I just return the service else it fallbacks on the Default entity listener resolver behavior.

My question is: do you think this feature can be natively supported by the bundle? If yes, I can share my work in a PR.

**Comment by pkruithof** [comment]
I've implemented this in #443
