### ISSUE TITLE
Logger extension bundle

### ISSUE THREAD

**Issue by adrienbrault** [doctrine/DoctrineBundle#225]
The StatsdBundle has a doctrine logger, to send queries times etc to statsd. However it does not work without enabling debug and profiling on doctrine connections (the default in the production env).

See https://github.com/liuggio/StatsDClientBundle/blob/master/DependencyInjection/Compiler/CollectorCompilerPass.php#L40-L45 and https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/DoctrineExtension.php#L105-L135

It would be useful to always have a chain logger on every connection, or have a tag to add loggers and this stuff would be handled by the doctrine bundle.

**Comment by PReimers** [comment]
@adrienbrault can you confirm, the changes in doctrine/dbal#3572 fixed your issue?
