### ISSUE TITLE
Feature Request: have a little backtrace in profiler in dev env

### ISSUE THREAD

**Issue by guillaumepotier** [doctrine/DoctrineBundle#256]
Hi there,

Sorry if this is not the place to ask that, I was not really sure. But I'm currently finding very hard to debug finely queries made in the profiler, and see which file / function / class / method fired them. This is really something missing.

I though it would fit here asking if possible to store, in dev mode, php backtrace for executed queries and retrieve it in the profiler.

If this is not the right place to ask, could you please tell me where I could ask this ?

Thanks for your help

Best

**Comment by Koc** [comment]
ref #275

**Comment by kimhemsoe** [comment]
Closing. Explained in #275
