### ISSUE TITLE
custom data type + schema updated

### ISSUE THREAD

**Issue by jjbier** [doctrine/DoctrineBundle#259]
I have created a custom data type "timestamp" but whe exec 
"php app/console d:s:u --force"  this comand reponse all time 

Updating database schema...
Database schema updated successfully! "17" queries were executed

Can you help me?

**Comment by trsteel88** [comment]
Did anyone ever work out what is causing this issue? I'm getting this on my machine. Seems to be only when a table contains comments (e.g. "(DC2Type:datetime)").

This is only occurring for me in MariaDB 10.2.8. I removed this install and replaced it with MySQL 5.7.19 and it stopped the repetitive updates.

**Comment by Majkl578** [comment]
@trsteel88 In your case it'd possibly be the same issue as https://github.com/doctrine/doctrine2/issues/6565 / https://github.com/doctrine/dbal/pull/2825?

**Comment by belgattitude** [comment]
Should be fixed with https://github.com/doctrine/dbal/pull/2825

**Comment by lcobucci** [comment]
https://github.com/doctrine/dbal/pull/2825 has just been merged and it will be released on DBAL `v2.7.0`, please test if your issue is fixed when using `"doctrine/dbal": "2.7.x-dev@dev"` and let us know.

**Comment by ostrolucky** [comment]
Closing for lack of feedback. I'm sure anyone reading this understands.
