### ISSUE TITLE
Extra config options for entity generation

### ISSUE THREAD

**Issue by henrypenny** [doctrine/DoctrineBundle#263]
I recently had to extend GenerateEntitiesDoctrineCommand to set propertyVisibility to `'protected'` and generateAnnotations to `true` in one of my projects.

I would be nice if these could be configured and/or overridden via CLI flags.

Or is there already a way to do this?

**Comment by kimhemsoe** [comment]
Entity generation is deprecated. Take a look the MakerBundler which is symfonys new command for code generation.
