### ISSUE TITLE
Can't load entities from bundles using PSR-4

### ISSUE THREAD

**Issue by arthens** [doctrine/DoctrineBundle#282]
According to [PSR-4](https://github.com/php-fig/fig-standards/blob/master/proposed/psr-4-autoloader/psr-4-autoloader.md), the namespace of a class doesn't have to be a direct mapping to the filesystem. See the [first example of the specs](https://github.com/php-fig/fig-standards/blob/master/proposed/psr-4-autoloader/psr-4-autoloader.md#3-examples)

This doesn't look to be supported because of:
https://github.com/doctrine/DoctrineBundle/blob/master/Mapping/DisconnectedMetadataFactory.php#L143

This method tries to remove the namespace from the path, and fails because it can't find it.

e.g. of a bundle using PSR-4 and `VendorName\BundleName` as a prefix

``` php
$namespace = "VendorName\BundleName\Entity";
$path = "/site/vendor/vendorname/bundlename/Entity";
```

will fail because there's no direct mapping

**Comment by alex-ception** [comment]
Up on this feature, as it would be very useful. Is this still not planned ?

**Comment by xabbuh** [comment]
> Misread what Ocramius said, ok. That's funny because in Sf doc the doctrine:generate:entities is completly misused.

@alex-ception Can you open an issue on the Symfony documentation repository if you think that it can be improved?

**Comment by quentincurtet** [comment]
Hi,

I can't generate crud because of the base path
Is it due to PSR-4?

Thx

**Comment by fpiccinali** [comment]
What do you think about this hack : 
In Mapping/DisconnectedMetaDataFactory.php, line 144 : 
```
    private function getBasePathForClass($name, $namespace, $path) {
        $reflector = new \ReflectionClass($name);
        $destination = dirname($reflector->getFileName());
        return $destination;

/*
        $namespace = str_replace('\\', '/', $namespace);
        $search = str_replace('\\', '/', $path);
        $destination = str_replace('/' . $namespace, '', $search, $c);
        if ($c != 1) {
            throw new \RuntimeException(sprintf('Can\'t find base path for "%s" (path: "%s", destination: "%s").', $name, $path, $destination));
        }

        return $destination;
*/
    }

It works with psr-4. 

If one of doctrine's guru agree with this way, i can try to fork and submit a pull request.

**Comment by fpiccinali** [comment]
What about customize doctrine:generate:entities ? 

Instead of rebuild all doctrine with psr-4 support - witch seems complicated  -, what about adding an argument to the command in order to activate folders mode : 
- mode with "namespaced folders"
- mode with "direct folders" 

This way each one can select the way it prefer ?

**Comment by janvennemann** [comment]
Here is a fix for PSR-4 compatibility which acts as an optional lookup before the default PSR-1 path generation. It uses the composer autoloader to check for registered PSR-4 prefix paths. If for some reason no composer autoloader is present it continues to generate base paths the old way. It's therefore fully backwards compatible.

https://gist.github.com/janvennemann/46b2626eee2a4808ed75

The entity and crud controller generators work out of the box with this fix. The path passed to the entity repository generator is still wrong and needs to be fixed, but i don't need that at the moment so i haven't done that yet.

**Comment by kirkmadera** [comment]
Thanks @Ocramius for the clarity on why this isn't a priority. The entity generation is great, but you need to generate them elsewhere and copy them over either way (even with PSR-4 support) to avoid overwriting existing entity files which may have additional logic in them. Adding PSR-4 support might lead people to use this over and over again to keep their entities up to date, which could be problematic.

**Comment by multifinger** [comment]
Voting for PSR-4 support.
I'm developing several bundles and PSR-4 is the best choice to simplify bundle dirrectory structure
But without PSR-4 support in Doctrine I cant update my entites (and repositories classes as well), so instead of running 1 quick command (that takes no time at all) I need to create class manually, copy all new fields and methods, create repository class. For 10-fields entity it could take up to 1 hour!
So I think this feature is realy must have. 
Please support it ...

**Comment by Ocramius** [comment]
>  I cant update my entites 

_STOP_RE_GENERATING_ENTITIES_BASED_ON_DB_CHANGES_

**Comment by multifinger** [comment]
I'm generating entities based on *.orm.yml schema. 
yml provides more readable view of entity structure rather than php doc

**Comment by multifinger** [comment]
adding repositoryClass for example in yml requires to create that class, generate-task can do it for me, but without PSR-4 support i can't do that

**Comment by Ocramius** [comment]
Same stuff: you *write* the entity classes. The code generation was never meant to be used as a "refresh" mechanism, and this scenario is actively considered feature abuse by doctrine core, so we don't support it.

**Comment by multifinger** [comment]
OK, what about creating new entities? Generation command is supported feature, so it should work in common cases. PSR-4 has the same rights to work as PSR-0

**Comment by Ocramius** [comment]
They'd just be generated in the PSR-0 path, and then you copy them over.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
