### ISSUE TITLE
Annotation service exception

### ISSUE THREAD

**Issue by NV-iloweb** [doctrine/DoctrineBundle#283]
I am trying to use `createAnnotationMappingDriver` but I get an error 
`The service "doctrine.orm.default_entity_manager" has a dependency on a non-existent service "doctrine.orm.metadata.annotation_reader".`

The service is declared this way : `<service id="doctrine.orm.metadata.annotation_reader" alias="annotation_reader" public="false" />`

If I either set the service to public="true" or use "annotation_reader" in the Reference created in createAnnotationMappingDriver, it works.

Am I doing something wrong or is there really a problem ?

**Comment by kimhemsoe** [comment]
Closing. As explained by Stof :)
