### ISSUE TITLE
Clearify shorten configuration syntax

### ISSUE THREAD

**Issue by wouterj** [doctrine/DoctrineBundle#299]
The shorten syntax for `connections` and `entity_managers` in the configuration is truly great. But the current implementation has a very big flawback: The error messages are not clear enough. If you are not aware that there is a shorten version, you'll have a hard time understanding code examples in documentations.

We've had a couple of issues about this in the Symfony docs lately: https://github.com/symfony/symfony-docs/pull/3878, https://github.com/symfony/symfony-docs/pull/3946, https://github.com/symfony/symfony-docs/pull/393

Assume you have this config (which is incorrect since it uses both the expanded and shorten syntax):

``` yaml
doctrine:
  orm:
    auto_mapping: true
    entity_managers:
      default:
        dql: ...
```

You get this error message:

> Unrecognized options "auto_mapping" under "doctrine.orm"

As if the `auto_mapping` option doesn't exists at all.

I propose to improve these error message to include that you already use the expanded version and thus it needs to be placed under the specific entity manager. For instance:

> The configuration contains specific entity managers, you should move the "auto_mapping" option to a specific entity manager.

/cc @weaverryan

**Comment by alcaeus** [comment]
Closing here as this can't be changed since it's the config component handling things (and because the issue hasn't been touched in more than 4 years).
