### ISSUE TITLE
Import Mapping Command Filter  Option Still Reads Entire DB

### ISSUE THREAD

**Issue by MarcusFulbright** [doctrine/DoctrineBundle#317]
The --filter option for the import mapping command only applies when Doctrine writes the meta data to a file, not when doctrine interprets the DB. This becomes problematic when people try to import specific tables, using --filter, that are totally fine, however other tables throw errors (such as a missing primary key or an unknown field type). Doctrine should not prevent the import of desired tables because undesired tables cause errors. 

It feels like --filter should apply to the database read. Does this sound like a fair request or is there a reason for --filter's current behavior?

**Comment by rprestemon** [comment]
+1

**Comment by patrick-mcdougle** [comment]
In the meantime, I'm going to resort to exporting the tables I need to a different (temporary) database and only include the tables I need and then run the mapping:import command. But this solution would certainly be more preferred.

+1

**Comment by cerber717** [comment]
+1

**Comment by sonu27** [comment]
Wow, this is old!

**Comment by PReimers** [comment]
@MarcusFulbright is this still an issue?

**Comment by ostrolucky** [comment]
Unfortunately our hand was recently forced to deprecate the command due to removed functionality in orm and hence most likely this issue won't receive fix, sorry about that. Let's close and keep track of issues we can do something about instead.
