### ISSUE TITLE
mapping_types configuration option make doctrine:database:create throw an error

### ISSUE THREAD

**Issue by lexwolfy** [doctrine/DoctrineBundle#327]
Hi,

I'm currently trying to use enum in my symfony project with this solution :

```
doctrine:
    /* config */
    mapping_types:
        enum: string
```

But after adding this option to my config.xml, doctrine:database:create command doesn't work anymore, throwing me this error : 

```
[Doctrine\DBAL\Exception\ConnectionException]                                     
An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'databasename'
```

After few researches, I figured out that adding mapping_types cause doctrine to check for databasePlatform and databasePlatformVersion by connecting to database using the databasename in connection param but the database is not created yet.. so error.

Did I miss something in my config ? Even so, I think this error shouldn't be.

Thanks,

**Comment by bassim** [comment]
@lexwolfy, did you manage to get a work-around for this?

**Comment by lexwolfy** [comment]
I do not use doctrine:database:create anymore, but a mysql command line instead... and then doctrine:schema:update

**Comment by dvc** [comment]
@lexwolfy , @bassim, try this:

parameters:
  # workaround to avoid DB init failure (https://github.com/doctrine/DoctrineBundle/issues/351#issuecomment-65771528)
  database_server_version: 5.5

**Comment by deeky666** [comment]
The parameter is called `server_version`

**Comment by dvc** [comment]
exactly! :)

  parameters:
     database_server_version: 5.5

  doctrine:
      dbal:
          connections:
              default:
                  server_version: %database_server_version%

**Comment by kimhemsoe** [comment]
Setting the version_version fixes the issue. This is an issue from dbal and not much we can do about it here. Closing.
