### ISSUE TITLE
Resolve target entities in compiler pass

### ISSUE THREAD

**Issue by ln-e** [doctrine/DoctrineBundle#330]
I'm using compiler pass to resolve my bundle's entities like this:

```
public function process(ContainerBuilder $container)
{
    //...
    $def = $container->findDefinition('doctrine.orm.listeners.resolve_target_entity');

    foreach ($interfaces as $interface=>$class){
        $def->addMethodCall('addResolveTargetEntity', array($interface, $class, array()));
    }
}
```

And it works only if i specify at least one configured interface (doesn't matter fake or not) in the doctrine configuration:

```
orm:
    resolve_target_entities:
        SomeFakeInterface: SomeFakeClass
```

Without this fake interface service `doctrine.orm.listeners.resolve_target_entity` won't be tagged as `doctrine.event_listener` tag in DoctrineExtension, thus it won't be collected by DoctrineBundle's compiler pass `RegisterEventListenersAndSubscribersPass` and it won't be properly registred as EntityManager's listener. Service becomes useless at all.

I found a pull request #83 which probably could solve this issue, but it was rejected...  So, is there a way to be able resolve some interfaces in my compiler pass without providing fake configuration?

**Comment by robcaw** [comment]
Did you ever find a solution to this?

**Comment by hacfi** [comment]
Maybe a PrependExtension helps: http://symfony.com/doc/current/components/dependency_injection/compilation.html#prepending-configuration-passed-to-the-extension

**Comment by stof** [comment]
this would be the way to go, yes

**Comment by laudeon** [comment]
Hello,

I know this is an old issue, but I have been in this trouble today and I didn't find anything about that.

> Symfony 2.8.4
> DoctrineBundle 1.5.2

I tried the PrependExtension as is suggested, and it works fine. But I don't know if it's really the good answer? In fact, the interfaces, in my case, are directly integrated and not configured separatly ; like below

```php
/**
  * @param \Symfony\Component\DependencyInjection\ContainerBuilder $container
  */
public function prepend(ContainerBuilder $container)
{
    $myConfigs = $container->getExtensionConfig('my_bundle');

    $doctrineConfig = [];
    $doctrineConfig['orm']['resolve_target_entities']['EntityInterfaceOne'] = $myConfigs[0]['entities']['entityOne'];
    $doctrineConfig['orm']['resolve_target_entities']['EntityInterfaceTwo'] = $myConfigs[0]['entities']['entityOne'];
    $doctrineConfig['orm']['resolve_target_entities']['EntityInterfaceThree'] = $myConfigs[0]['entities']['entityThree'];

    $container->prependExtensionConfig('doctrine', $doctrineConfig);
}
```

I think, it is a start point and it must be improved.

**Comment by hacfi** [comment]
@laudeon Does you extension implement `Symfony\Component\DependencyInjection\Extension\PrependExtensionInterface` ? Do your entries show up in `bin/console debug:config doctrine`?

**Comment by laudeon** [comment]
@hacfi Yes `BundleExtension` implements `PrependExtensionInterface`. The return of `debug:config doctrine` show me my entries added with `::prepend()` in the right place :)

**Comment by PhilippeMenard** [comment]
Old issue but I am facing the exact same challenge. I want to use the prepend route but at that time my bundle's config is empty (not yet loaded). I want to assign a value from my bundles configuration to doctrine's resolve_target_entites array (like @laudeon is doing)

What am I doing wrong here ?

**Comment by PhilippeMenard** [comment]
Hello, I am trying to use PrependExtensionInterface to accomplish something similar.

The trouble I am having is that the values I want to insert into doctrine's configuration are dependent on my bundle's config. So of course as prepend is called before load, my bundle's config is not loaded.

How do I gain access to my bundle's configuration in the scope of the "prepend" function ? Do I need to make a second bundle whose job is only to bind configuration values ?

Thanks

**Comment by kimhemsoe** [comment]
Closing as solutions and workarounds exists.
