### ISSUE TITLE
Support for configuring DBAL to use existing connection

### ISSUE THREAD

**Issue by Revisor** [doctrine/DoctrineBundle#335]
Hi,
DBAL accepts a parameter 'pdo' which allows it to reuse an existing PDO connection:
https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#driver

The Doctrine Bundle however doesn't accept this parameter. Is there any other clean way to make DBAL reuse an existing connection?

Thanks.

**Comment by pounard** [comment]
+1 for this, I do need it too.

**Comment by jkoudys** [comment]
+1 especially useful for those of us who want to start migrating legacy systems, and need to use some other DBAL (e.g. an old WordPress connection) and would prefer not to double the DB connections each request uses.

**Comment by kimhemsoe** [comment]
I think you can do it with driver class.
Just create your own driver by copy it from dbal and you should be sorted i
believe.

When you have done the migration you can fallback to default drivers.

**Comment by ekonoval** [comment]
Does anybody managed to reuse the mysqli existing connection?

**Comment by kimhemsoe** [comment]
You can get the mysqli connection handle from dbal if you wish. It is not pretty ofc.
Look at: MysqliConnection::getWrappedResourceHandle()
Dont think to much about the naming here :D


Alternative you can write you own driver, as a previous post mentions the easiest way to achieve that is by c/p the existing driver and make your changes, please don't try to extend them, just c/p

**Comment by ekonoval** [comment]
Thank you very much for detailed explanation, I'll try that =)

**Comment by ekonoval** [comment]
Finally I came across a solution like this:

```
$entityManager = EntityManager::create([
    //'driver'   => 'mysqli',
    'driverClass' => MysqliCustomDriver::class,

    'host' => DB_HOST,
    // ....
], $config);

class MysqliCustomDriver extends Driver
{
    public function connect(array $params, $username = null, $password = null, array $driverOptions = [])
    {
//        return new MysqliCustomConnection($params, $username, $password, $driverOptions);
        return new MysqliCustomConnection([], '', '', []);
    }

    public function getName()
    {
        return 'mysqli_ib';
    }

}

class MysqliCustomConnection extends MysqliConnection {
    // a lot of copy-paste here ...

    public function __construct(array $params, $username, $password, array $driverOptions = [])
    {
        /**
         * \DB is my legacy class using mysqli and having already opened mysqli connection
         * which I'm going to reuse
         */
        $this->_conn = \DB::getInstance()->getConnectionID();
    }

    // a lot of copy-paste here ...
}
```

And I can even mix code from my legacy DB::getInstance()->query($sql) with DQL code in a single transaction and commit or roolback the set of mixed queries

**Comment by kimhemsoe** [comment]
Please dont extend MysqliConnection, C/P into your own project

**Comment by ostrolucky** [comment]
Sorry folks not happenning, DBAL is removing this option https://github.com/doctrine/dbal/pull/3554.
