### ISSUE TITLE
[feature] add a DI tag to auto-register DBAL types in 3rd party bundle(s)

### ISSUE THREAD

**Issue by FredoVelcro** [doctrine/DoctrineBundle#336]
I often use custom DBAL mapping types and it would be nice to simply register them by defining as  services with a DI tag like "dbal.type". 
I know it can be done with the "doctrine/dbal/types" config entry but when distributing bundles, it is better that the bundle autoregister its own custom types by itself...

What do you think about it ?

**Comment by fpiccinali** [comment]
@stof thanks for the advices.
In sf2.6 you should use: 
  $container->prependExtensionConfig('doctrine', $config);

**Comment by stof** [comment]
@fpiccinali indeed. Sorry for the typo in the method name

**Comment by kimhemsoe** [comment]
Closing as "wont fix".
