### ISSUE TITLE
Fatal error when trying explain queries like "start transaction"

### ISSUE THREAD

**Issue by SweetLemonade** [doctrine/DoctrineBundle#346]
Description: https://github.com/symfony/symfony/issues/12307

Maybe I figure out what is the problem and solved it, but I found better solution then last one.

`Doctrine\DBAL\Logging\SQLLogger.php`

``` php
public function startQuery($sql, array $params = null, array $types = null);
```

Should be:

``` php
public function startQuery($sql, array $params = array(), array $types = array());
```

Because the first variant set `$params` and `$types` to `NULL` when we logging queries like `transaction`.

When function `resolveParams` in file `Doctrine\DBAL\Connection.php` can't receive `NULL` in `$params` and `$types`.

**Comment by kimhemsoe** [comment]
Closing. If still an issue you are welcome to write and i will reopen.
