### ISSUE TITLE
Allow quote_strategy option in configuration

### ISSUE THREAD

**Issue by pawellen** [doctrine/DoctrineBundle#349]
Can you allow in vendor/doctrine/doctrine-bundle/Doctrine/Bundle/DoctrineBundle/DependencyInjection/Configuration.php
option "quote_strategy" to change default quote strategy ? There are some cases when need to integrate project with already existing database that have strange table/column names. For exampe (`group`, `order`). I have created class thad adds `Grave Accent` to tablenames but I can only use it by adding
$em->getConfiguration()->setQuoteStrategy(new GraveAccentQuoteStrategy());
anytime when I use one of those tables.

**Comment by flower2222** [comment]
Great idea.

**Comment by nnnnathann** [comment]
+1
