### ISSUE TITLE
[PROFILER][DX] integrate explain analyzer

### ISSUE THREAD

**Issue by thkoch2001** [doctrine/DoctrineBundle#354]
_From @thkoch2001 on November 21, 2014 10:43_

MariaDB provides an [online explain analyzer tool](https://mariadb.org/explain_analyzer/analyze/). We could add a link to every SQL query that opens the analyzer [using the api](https://mariadb.com/kb/en/mariadb/documentation/clients-and-utilities/explain-analyzer-api/).
Even better, of course, would be an integration of such an analyzer tool in symfony. Would anybody like to get a drink with Monty and ask him to open source the tool? :-)

_Copied from original issue: symfony/symfony#12534_

**Comment by javiereguiluz** [comment]
I think we could close this issue as "fixed". Symfony Profiler already shows the `EXPLAIN` information generated by MySQL, PostgreSQL, etc. If you want to go further and analyze that information with third-party tools, I  think that's way out of the scope of the profiler. Thanks!

**Comment by ostrolucky** [comment]
Agreed, maintaining integration with external APIs would be too much burden with too little benefit
