### ISSUE TITLE
Convert custom type to database value before using QueryBuilder

### ISSUE THREAD

**Issue by ilterra** [doctrine/DoctrineBundle#356]
I have defined a custom Doctrine data type for Uuid. When I search for an object using `find($uuid)`, it works correctly, i.e. the attribute is converted using `convertToDatabaseValue()` before executing the query, and converted back with `convertToPhpValue()` when value is retrieved.

The conversion is ignored if I use the QueryBuilder. Example:

```
$qb = $this->createQueryBuilder('s');
$qb = $qb->where( //some conditions...
      $qb->expr()->eq( 's.uuid', ':uuid' ))->setParameter( 'uuid', $uuid );
```

How can I force the conversion of the parameter before executing the query? Is there a way to access the `convertToDatabaseValue()` function of the custom data type from the repository?

Thanks

**Comment by ninjabachelor** [comment]
Thanks @deeky666 , that is perfect! :)
