### ISSUE TITLE
DropDatabaseDoctrineCommand option if-exists

### ISSUE THREAD

**Issue by Prims47** [doctrine/DoctrineBundle#361]
Hello,

I have a question about "DropDatabaseDoctrineCommand" command. Why did you add "if-exists" option ? Actually, I have to write this option everytime I want to drop my database. Running this command means that my database already exists, otherwise you could catch the error.

**Comment by kimhemsoe** [comment]
@Prims47 Does this fix everything for you ?

**Comment by Prims47** [comment]
I am sorry but https://github.com/doctrine/DoctrineBundle/commit/48a3f32bbd798dd175f6fca74d595a85fded281e#diff-b46232fa79d53e95a9b5efea5b606a8dR89 is not correct for me.

 $ifExists is null by default and if $name is not in array on $connection->getSchemaManager()->listDatabases() you drop a database who dont exist...

**Comment by deeky666** [comment]
@Prims47 this is expected behaviour. If you want to avoid errors for non-existing databases, you HAVE to pass the `--if-exists` option. Otherwise it is expected that the command fails if the database to drop does not exist. Think of it like `DROP DATABASE IF EXISTS` query.

**Comment by kimhemsoe** [comment]
Closing.

@Prims47 Thanks for reporting the issue. If you still have issues you are welcome to open a new ticket.
