### ISSUE TITLE
Connection/Driver options does not support arrays

### ISSUE THREAD

**Issue by smurfy** [doctrine/DoctrineBundle#365]
I tried adding "userDefinedFunctions" for a sqlite db via configuration.

While the DoctrineBundle maps the `options` field of the configuration to the correct parameter in the `PDOSqlite\Driver`'s `connect` method, it does not allow arrays therefore it's not useable for my use-case.

I handled this by overwriting `driver_class` and extending the connect method to append the userDefinedFunctions but i still think it should be supported via configuration.

Please don't confuse this with extending dql function which is already supported by the configuration.

**Comment by jbenoit2011** [comment]
I encounter the same problem today.
I think the problem comes from this [line](https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/Configuration.php#L148)
 where each node of `options` parameter is considered as a scalar.

**Comment by smurfy** [comment]
@jbenoit2011 If you need help with implementing the workaround i mentioned, i can post it as a gist.

**Comment by jbenoit2011** [comment]
That's what I did and thank you very much because it worked. But that's not very convenient :/

**Comment by bmxpira** [comment]
Same issue :/.
@smurfy I used same approach :)

**Comment by mikeSimonson** [comment]
@smurfy @bmxpira Can you post the gist ?

**Comment by smurfy** [comment]
Sure: https://gist.github.com/smurfy/2fdf411fddb2dcac122a83dcd5f7d963

**Comment by alcaeus** [comment]
Fixed in #1085, will be released in 1.12.3.
