### ISSUE TITLE
[DX][Proposal] Separate doctrine:generate:entities command in another repository

### ISSUE THREAD

**Issue by Nek-** [doctrine/DoctrineBundle#370]
Hello,

In most cases I saw people use this command, people didn't knew what effect it have. They just tell "yes, i need to run it". The result is a bad usage of this one, and an horrible generated entity.

In addition, this make people lost the sense of the entity and the control of their code. And obviously they make sometime wrong choices of implementation because they don't want to touch the entities.

I don't speak about the fact that the command generate "old saved files" that newbies loooove to commit. (files that most of the time they didn't notice ... because they don't understand why they are generated and so on...)

All theses reasons led me to write this post to suggest the removal of this command. I'm pretty sure this will be awesome for everybody. (after all, every code editor can generate getter/setter)

What do you think about ?

**Comment by Ocramius** [comment]
> Remove the doctrine:generate:entities command

The idea that we had in mind for a lot of time is to just split out the `EntityGenerator` and related logic into a different repository.

Until that happens, the command will sadly have to stay here.

**Comment by deeky666** [comment]
I would not remove it entirely but extract it into another repo. As the main idea is to make people think about what they are actually doing this should be enough as they'll first have to pass a "barrier" that discourages them to use it (sort of).

**Comment by Nek-** [comment]
Adding a barrier is a pretty good idea. What's the need before it happens ? Maybe I can handle it ?

**Comment by pkruithof** [comment]
> The result is a bad usage of this one, and an horrible generated entity

Interesting...I use it every time I add/change a property. It always felt to me like best practice, like: this is the way Doctrine intended your model to look like. For example, with collections there is no generated setter, but an adder/remover instead. Without the generate command I would probably have created a setter.

Can you give an example of a 'horrible generated entity'?

**Comment by Ocramius** [comment]
> horrible generated entity

The fact that the generated entities are just a giant set of getters/setters already clashes with practices like object calisthenics and DDD, for example.

**Comment by Nek-** [comment]
An example of horrible entities ?

```php

class User
{
    private $id;
    private $username;
    private $Group;

    /**
     * Get Username
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;

         return $this;
    }

    private $password;

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }
}
```

Here are things not relevant:

* `Get username`: you don't say !
* Property in the middle of the class (because yes, it was added after everything in the mapping)
* Uppercase on first letter for `Group` attribute... Because the guy that use the command didn't realize the name he precise in the mapping have an impact in the entity (after all, you still get it with `getGroup()`)

> I precise that's not from my imagination but things I seen at work.

**Comment by pkruithof** [comment]
Most of those points are sloppy code writing though, and have more to do with not following proper code style than the command generating code, in my opinion.

I get the DDD argument, but I don't think removing this command will result in better models. Isn't there a case to be made that _if_ you're using getters/setters (leaving aside the discussion of whether you should be) that those should be created in the best way possible?

By the way, I'm not saying I'm against removing it. I just found it odd that the way the Doctrine project has been documenting models up till now is a reason to suggest this removal.

**Comment by Ocramius** [comment]
@pkruithof we are not going to remove it until a separate repository deals with the same issue in a similar way.

**Comment by Majkl578** [comment]
Closing this as wont fix here since entity generator is deprecated and will be removed in ORM 3.0.
