### ISSUE TITLE
appDevDebugProjectContainer::getDoctrine_Orm_DefaultEntityManagerService() doesn't work

### ISSUE THREAD

**Issue by phansys** [doctrine/DoctrineBundle#382]
Since #381, ```appDevDebugProjectContainer::getDoctrine_Orm_DefaultEntityManagerService()``` calls ```\Doctrine\ORM\EntityManager::__construct()``` (tries to create a new instance of a class with a protected constructor) instead of calling ```\Doctrine\ORM\EntityManager::create()```:

```
PHP Fatal error:  Call to protected Doctrine\ORM\EntityManager::__construct() from context 'appDevDebugProjectContainer' in /path/to/app/cache/dev/appDevDebugProjectContainer.php on line ...
```
There are my installed versions of ```doctrine/orm``` and ```symfony/symfony```:

```
$ composer show -i doctrine/orm
name     : doctrine/orm
descrip. : Object-Relational-Mapper for PHP
keywords : database, orm
versions : * dev-master, 2.5.x-dev
type     : library
license  : MIT
source   : [git] https://github.com/doctrine/doctrine2.git ffaffa0b8a577d5778e973ce5af65596fd3d2306
dist     : [zip] https://api.github.com/repos/doctrine/doctrine2/zipball/ffaffa0b8a577d5778e973ce5af65596fd3d2306 ffaffa0b8a577d5778e973ce5af65596fd3d2306
names    : doctrine/orm
...
```
```
$ composer show -i symfony/symfony
name     : symfony/symfony
descrip. : The Symfony PHP framework
keywords : framework
versions : * dev-master, 2.6.x-dev
type     : library
license  : MIT
source   : [git] https://github.com/symfony/symfony.git ad74db991610fb6a43e4058cf80a715aace35144
dist     : [zip] https://api.github.com/repos/symfony/symfony/zipball/ad74db991610fb6a43e4058cf80a715aace35144 ad74db991610fb6a43e4058cf80a715aace35144
names    : symfony/symfony, symfony/browser-kit, symfony/class-loader, symfony/config, symfony/console, symfony/css-selector, symfony/debug, symfony/debug-bundle, symfony/dependency-injection, symfony/doctrine-bridge, symfony/dom-crawler, symfony/event-dispatcher, symfony/expression-language, symfony/filesystem, symfony/finder, symfony/form, symfony/framework-bundle, symfony/http-foundation, symfony/http-kernel, symfony/intl, symfony/locale, symfony/monolog-bridge, symfony/options-resolver, symfony/process, symfony/propel1-bridge, symfony/property-access, symfony/proxy-manager-bridge, symfony/routing, symfony/security, symfony/security-acl, symfony/security-bundle, symfony/security-core, symfony/security-csrf, symfony/security-http, symfony/serializer, symfony/stopwatch, symfony/templating, symfony/translation, symfony/twig-bridge, symfony/twig-bundle, symfony/validator, symfony/var-dumper, symfony/web-profiler-bundle, symfony/yaml
...
```

The last commit that works in my environment is @c12410c. Now I just changed my requirements from  ```"doctrine/doctrine-bundle": "~1.2"``` to ```"doctrine/doctrine-bundle": "dev-master#c12410c as 1.2"```.

**Comment by stof** [comment]
Can you show your installed version of doctrineBundle too ?

**Comment by phansys** [comment]
Of course @stof:

```

**Comment by stof** [comment]
Are you overwriting the definition of the entity manager service in any way ? We have tests in the testsuite ensuring that the creation of the EntityManager service is working.

**Comment by phansys** [comment]
@stof, no. Also I will check my 3rd party bundles in order to confirm if I find something related to this issue.
Thank you.

**Comment by phansys** [comment]
After disabling 36 of 46 bundles that compounds my app (included dev ones) the issue persists. Currently I only have enabled the same bundles that came with the [standard edition](https://github.com/symfony/symfony-standard/blob/7a8a4fb179d7c98f2129ffd37eeb8e20a1bca3d7/app/AppKernel.php#L8..L30) (and even less):

```php
public function registerBundles()
{
    $bundles = array(
        new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
        new Symfony\Bundle\SecurityBundle\SecurityBundle(),
        new Symfony\Bundle\TwigBundle\TwigBundle(),
        new Symfony\Bundle\MonologBundle\MonologBundle(),
        new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
        new Symfony\Bundle\AsseticBundle\AsseticBundle(),
        new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
        new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
    );

    if (in_array($this->getEnvironment(), array('dev', 'test'))) {
        $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
        $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
    }

    return $bundles;
}
```

Note that I did try a fresh standard edition install and the issue is not present there, so I only can conclude that this problem can be originated by my locked down requirements. Then, I just replaced the ```composer.lock``` file in the SE with the file commited in my app and after run ```composer install``` the issue was thrown again. This ```composer.lock``` was updated today with the last Composer DEV version, so it's seems really weird to me.

Now my project is working again after running ```rm composer.lock && composer clear-cache && composer install --prefer-dist```.

Thank you.

**Comment by kminh** [comment]
I also encounter this exact same error when upgrading to DoctrineBundle 1.4.0, using Symfony 2.6.1. Downgrading to DoctrineBundle 1.3.0 solves it for me.

Any idea?

**Comment by stof** [comment]
Please provide a reproducing testcase (a small project based on the SE and reproducing the bug) to help debugging it

**Comment by mvrhov** [comment]
Deleting a cache doesn't help?

**Comment by kminh** [comment]
Unfortunately no. Will try to provide a testcase to reproduce.

**Comment by hafuta** [comment]
Had the same issue, solved by upgrading doctrine/odm to 2.5 (from 2.2)

**Comment by nicolas-san** [comment]
@hafuta @kminh 
I experience the same today, to solve it, I take the composer.json https://github.com/symfony/symfony-standard/blob/2.6/composer.json here, take the Require part, add the 3rd party bundle I need, and it's ok.
```
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0"
```

**Comment by Genjito** [comment]
I also experience this.
When doing a fresh build with the project I always get this error:

 [exec] PHP Fatal error:  Call to protected Doctrine\ORM\EntityManager::__construct() from context 'appDevDebugProjectContainer' in /var/www/servicebus/app/cache/dev/appDevDebugProjectContainer.php on line 3747

The only thing that solved it for me was in composer.json setting:
"doctrine/doctrine-bundle": "1.3.0",
which was before:
"doctrine/doctrine-bundle": "~1.2",

Or setting: "symfony/symfony": "2.5.5",
instead of "symfony/symfony": "2.6.*",

**Comment by henrypenny** [comment]
I had this issue and it turned out to be something really weird.
I had somehow gotten a copy of my vendors folder in one of my web/bundle folders. It seemed I had two versions of every vendor file in play.
This might just be a freak accident ... but perhaps its worth trying to delete and re-link your assets.
