### ISSUE TITLE
Cross Db Relationships

### ISSUE THREAD

**Issue by crash21** [doctrine/DoctrineBundle#387]
Hello,

I have 2 entity managers with two different connections. There are 2 different dataabases.
In short I have one database that keeps all my user credentials with FosUser and then each application gets this database to authenticate user. So one db for authentication centralized for all apps.

The problem is that I need iduser as FK in an entity of my application 
Imagine have an entity photo:

then somewhere need to do this:

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\OneToOne(targetEntity="Foo\UserBundle\Entity\User")
     * @Orm\JoinColumn(name="iduser", referencedColumnName=".id")
     */
     private $user;

When I do doctrine:schema:update I get this error:

  [Doctrine\Common\Persistence\Mapping\MappingException]                       
  The class 'Foo\UserBundle\Entity\User' was not found in the chain confi  
  gured namespaces Foo\FrontEndBundle\Entity     

So whats the best practice to define cross db relationships with doctrine and Symfony2?

Thanks a lot.

**Comment by stof** [comment]
Please ask support on the Doctrine support channels: http://www.doctrine-project.org/community.html

This issue tracker is only about reporting bugs and feature requests for the integration of Doctrine into Symfony. Pure doctrine questions should be asked to the ORM team.
