### ISSUE TITLE
ServiceCircularReferenceException on EventSubscriber

### ISSUE THREAD

**Issue by havvg** [doctrine/DoctrineBundle#389]
Hi there,

I created a class which depends on a repository. Now I want to re-use this class within an EventSubscriber (`doctrine.event_subscriber`). However by doing this, I get the `ServiceCircularReferenceException` due to the way the container is creating the services, the respective `ObjectManager` and its `EventManager`.

What do you think about moving from the `RegisterEventListenersAndSubscribersPass` to a service configurator, which injects the subscriber and listener at the runtime level instead? This way the listener may consume services having e.g. an `ObjectManager` (or `Repository`, ..) in their dependency graph.

**Comment by stof** [comment]
This would not change the fact that you are a circular reference in the object graph. It would just make the container unable to detect them (but it might still cause issues when laoding the object graph)

**Comment by havvg** [comment]
Well, I didn't try it, maybe the code won't be generated the way I thought it would. What I got in mind would be something like:

```php
<?php

function create() {
    $eventManager = new EventManager();
    $entityManager = EntityManager::create($con, $config, $eventManager);

    return $entityManager;
}

function wire(EntityManager $entityManager) {
    // done outside/after of the service creation of $entityManager retrieving the respective entity manager
    $subscriber = new EventSubscriber($entityManager);
    $entityManager->getEventManager()->addEventSubscriber($subscriber);
}
```

Which is not a circular reference as for creating the instances, but only for a one-pass setup, which is currently in place. The issue I see here, there are actually two steps (that's why two functions): the first one to actually create a working instance of the class and the second would be the wiring. Those two steps are currently done as one.

**Comment by stof** [comment]
@havvg the event object received as argument by the listener already gives you the entity manager. This could be a better way to access it

**Comment by alcaeus** [comment]
As per @stof, injecting any EM-aware class in an event subscriber is a no-go: the event subscriber is manager agnostic and receives the entity manager that triggered the event in the respective `*EventArgs` argument. If you need to access a repository in the subscriber, you should always fetch it from the `EntityManager` instance you fetched from event args. This may work by default when only running a single entity manager, but running multiple entity managers will break your subscribers hard. Closing here as this is not something we will or even should fix.
