### ISSUE TITLE
Type bigint maps to int, expected string

### ISSUE THREAD

**Issue by jarekj** [doctrine/DoctrineBundle#392]
http://doctrine-orm.readthedocs.org/en/latest/reference/basic-mapping.html#doctrine-mapping-types

"bigint: Type that maps a database BIGINT to a PHP string."

When I add column with type bigint in my yml config, and then use command doctrine:generate:entities, it creates field as integer, not string.

here is part of my yml config:

        externalId:
            type: bigint
            column: external_id

Here is what I get:

	/**
	 * @var integer
	 */
	private $externalId;

**Comment by stof** [comment]
This is not a DoctrineBundle issue. The EntityGenerator is part of the ORM itself. Please report it there.

**Comment by jarekj** [comment]
@stof I can't create an issue here: https://github.com/doctrine/doctrine2

**Comment by mvrhov** [comment]
bigint is integer!. Please note tha if you are using bigints you should also use 64bit PHP

**Comment by jarekj** [comment]
I know, but result and docs are inconsistent

**Comment by deeky666** [comment]
@mvrhov bigint column type values are treated as strings in DBAL for x86 compat. See [here](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/BigIntType.php#L48-L62).
Therefore a string param annotation would indeed be correct.

**Comment by deeky666** [comment]
@jarekj we are managing issues via our JIRA issue tracker. Please report the issue here: http://www.doctrine-project.org/jira/browse/DDC
