### ISSUE TITLE
Entities with keyworld name

### ISSUE THREAD

**Issue by cirovargas** [doctrine/DoctrineBundle#408]
I have a mysql table with name "List" and a entity mapped too.

when i try to generate:entities or schema:update return the error:

[Symfony\Component\Debug\Exception\FatalErrorException]
  Parse Error: syntax error, unexpected 'List' (T_LIST), expecting identifier (T_STRING)

PHP Parse error:  syntax error, unexpected 'List' (T_LIST), expecting identifier (T_STRING) in /usr/share/nginx/www/revista/src/Project/AdminBundle/Entity/List.php on line 13

On line 13: 

class List{

Solution:

On mapping:import throws exception on the db tables have PHP keyworlds

**Comment by kimhemsoe** [comment]
You can manually fix class names after a import, If we throw an exception that would no longer possible.

Closing as wont fix
