### ISSUE TITLE
DoctrineBundle 1.4 Schema Update Issue with DBAL 2.5 Binary Type

### ISSUE THREAD

**Issue by alexgurrola** [doctrine/DoctrineBundle#415]
Every time I run a `doctrine:schema:update` command, it tries to execute this sql query every single time:

```sql
ALTER TABLE user_sessions CHANGE sess_id sess_id VARBINARY(128) NOT NULL;
```

The PHP Annotations I am using for this column is as follows:

```php
/**
 * @var string
 *
 * @ORM\Column(name="sess_id", type="binary", length=128, nullable=false)
 * @ORM\Id
 * @ORM\GeneratedValue(strategy="IDENTITY")
 */
private $sessId;
```

It seems the binary type is somehow registering a change even though no change has actually been made.  I'm not sure if this is truly roots to a  DBAL Issue, but I updated both DBAL to 2.5 and the Doctrine Bundle to 1.4 before getting the binary type to be accepted by the `doctrine:schema:update` command.

Thanks in advance for any assistance in squashing this odd bug.

--Alex Gurrola

**Comment by stof** [comment]
This is not a DoctrineBundle issue. DoctrineBundle does not implement any logic related to the schema comparison.
Please report it in the issue tracker of the DBAL project itself.

**Comment by alexgurrola** [comment]
Thanks!
