### ISSUE TITLE
How to build query in symfony 2 that can update a field of datetime type?

### ISSUE THREAD

**Issue by ginkgo6** [doctrine/DoctrineBundle#417]
How to build query in symfony 2 that can update a field of datetime type?
The expireTime field in the entity is \DateTime type, I need to update this field and my code is as below:
$query = $dq->update()
    ->set('u.token', $dq->expr()->literal($token))
    ->set('u.isDeleted', false)
    ->set('u.expireTime', $dq->expr()->literal($expireTime->format('Y-m-d H:i:s')))
    ->where('u.email= :email')
    ->setParameter('email', $email)
    ->getQuery();
but I got the following error:
Execute query error:[Syntax Error] : Error: Expected Literal, got ','

Thanks for your help!

**Comment by stof** [comment]
Use query parameters to set values in queries rather than literals.

Anyway, this has nothing to do with DoctrineBundle or Symfony2. Asking support about the usage of Doctrine itslef should be done either on IRC or the mailing-list: http://www.doctrine-project.org/community.html
