### ISSUE TITLE
To display also total query time in debug mode

### ISSUE THREAD

**Issue by pmithrandir** [doctrine/DoctrineBundle#418]
Hello,

In the debug toolbar, we have this wonderful system to analyze our queries.
I realized coming from qualif to prod that my performances decreased a lot. The main difference was that on prod I have separate mysql and PHP on different machine, and therefore the network connection was more relevant.

I would love to have a way to assert that.

In the current debug toolbar, we have only the query execution time from DB perspective. I think it would be very nice to have also the view on how long the query took in term of network.. could be latency, amount of data to retreive... many useful improvments can be deduced by this second value.

We would then have : 
Query 55ms (166ms in total)

What do you think ? Isd it big to do ? I tried to look into the code but I didn't find for the moment where this query time is find. Not sure it will be calculated at the same place whatever.

Best regards,
Pierre

**Comment by stof** [comment]
The timing already includes networking actually, given that it is collected on the PHP side.

**Comment by pmithrandir** [comment]
hi, it's strange... it's not get from the request result from DB ?

**Comment by stof** [comment]
which request result ?

**Comment by pmithrandir** [comment]
OK, we can close it.
I thought some function existed to retrieve this info from the result. i must have mis remember from another thing.
Sorry for this request.
Pierre
