### ISSUE TITLE
Debug log should include connection name

### ISSUE THREAD

**Issue by igorw** [doctrine/DoctrineBundle#43]
When working with multiple connections, it would be really useful if the log entry would include the connection name.

**Comment by ostrolucky** [comment]
This is oldest issue we have here without any feedback, for which I'm sorry. Unfortunately this doesn't seem concrete enough proposal and more discussion would be required about changing our logging messages in general, as currently format is simple `{query} [{queryParameters}]`. I don't see there good position where to put connection name. Ideally it would be in parameters, but currently it's reserved for query parameters. And putting it before or after query might be problematic for future extensions, as people will start requesting adding more and more information to display there. If there is demand for this, message format should be revamped in more general manner, so people can customize it more. Let us know in new issue if there is some interest for this, ideally with more concrete proposal. Thank you.
