### ISSUE TITLE
Symfony test suite failing

### ISSUE THREAD

**Issue by dosten** [doctrine/DoctrineBundle#435]
The test suite of Symfony (master/3.0) is failing because `Resources/config/dbal.xml` use the old way to define a factory service. Since the new way is available only in Symfony >= 2.6 i don't know what do we have to do. Maybe 2.0?

**Comment by stof** [comment]
this is wrong. the latest releases of the bundle (1.4.0 and 1.5.0) are not using deprecated APIs anymore.
