### ISSUE TITLE
'zend_mm_heap corrupted' when upgrading from 1.4 to 1.5

### ISSUE THREAD

**Issue by stephanvierkant** [doctrine/DoctrineBundle#437]
If I upgrade the DoctrineBundle from 1.4.0 to 1.5.0 I get a 'zend_mm_heap corrupted' error:

Here's my log:
```
composer install --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
- Removing doctrine/doctrine-bundle (v1.4.0)
- Installing doctrine/doctrine-bundle (v1.5.0)
Loading from cache
Generating optimized autoload files
Updating the "app/config/parameters.yml" file
Clearing the cache for the dev environment with debug true
zend_mm_heap corrupted
```

**Comment by stof** [comment]
Well, you are getting this error when running Composer, not when running DoctrineBundle.

and anyway, ``zend_mm_heap corrupted`` denotes a bug in PHP itself, as it is an issue in the memory management of PHP

**Comment by stof** [comment]
Closing this as there is nothing we can fix in the bundle

**Comment by naroga** [comment]
@stephanvierkant This is indeed a bug with PHP itself. You can try running `export USE_ZEND_ALLOC=0` before running this command and you'll see the error goes away.
