### ISSUE TITLE
Can't generate CRUD with Doctrine2 and PSR-4

### ISSUE THREAD

**Issue by quentincurtet** [doctrine/DoctrineBundle#440]
Hi,

I just want to generate CRUD for my bundle but i can't, i have this error : 
Can't find base path for "My/Entity/In/MyBundle" (path: "My/Entity/In/MyBundle", destination: "My/Entity/In/MyBundle").

Can someone help me ?

**Comment by Ocramius** [comment]
Doctrine generates files in a PSR-0 compliant structure. You can move the files after generating them.

**Comment by quentincurtet** [comment]
But i can't generate them due to this error
