### ISSUE TITLE
How to turn off Elastic Search

### ISSUE THREAD

**Issue by henrypenny** [doctrine/DoctrineBundle#446]
Is there a quick way to disable elastic search?
I've currently getting this error:

Couldn't connect to host, Elasticsearch down?

**Comment by trsteel88** [comment]
@henrypenny, elasticsearch doesn't have anything to do with this bundle. You must be including elasticsearch in your project.

**Comment by henrypenny** [comment]
I'm using a new install from composer. There seems to be an elastic search provider set up by default.

The following service definitions are present:

    kunstmaan_node_search.node_index_update.listener                   Kunstmaan\NodeSearchBundle\EventListener\NodeIndexUpdateEventListener                      
    kunstmaan_node_search.search.node                                  Kunstmaan\NodeSearchBundle\Search\NodeSearcher                                             
    kunstmaan_node_search.search.service                               Kunstmaan\NodeSearchBundle\Services\SearchService                                          
    kunstmaan_node_search.search_configuration.node                    Kunstmaan\NodeSearchBundle\Configuration\NodePagesConfiguration                            
    kunstmaan_node_search.service.indexable_pageparts                  Kunstmaan\NodeSearchBundle\Helper\IndexablePagePartsService                                
    kunstmaan_node_search.twig.extension                               Kunstmaan\NodeSearchBundle\Twig\KunstmaanNodeSearchTwigExtension                           
    kunstmaan_search.command.delete                                    Kunstmaan\SearchBundle\Command\DeleteIndexCommand                                          
    kunstmaan_search.command.populate                                  Kunstmaan\SearchBundle\Command\PopulateIndexCommand                                        
    kunstmaan_search.command.setup                                     Kunstmaan\SearchBundle\Command\SetupIndexCommand                                           
    kunstmaan_search.search                                            Kunstmaan\SearchBundle\Search\Search                                                       
    kunstmaan_search.search.factory.analysis                           Kunstmaan\SearchBundle\Search\AnalysisFactory                                              
    kunstmaan_search.search_configuration_chain                        Kunstmaan\SearchBundle\Configuration\SearchConfigurationChain                              
    kunstmaan_search.search_provider.elastica                          Kunstmaan\SearchBundle\Provider\ElasticaProvider                                           
    kunstmaan_search.search_provider_chain                             Kunstmaan\SearchBundle\Provider\SearchProviderChain              

There are references to Elastica in there.

**Comment by henrypenny** [comment]
Basically I have no need for search on my current project and I want to turn searching off.

**Comment by henrypenny** [comment]
Bugger - I've posted in the wrong place. My apologies.

**Comment by trsteel88** [comment]
This has nothing to do with DoctrineBundle. You are using KunstmaanSearchBundle which requires ElasticSearch: https://github.com/Kunstmaan/KunstmaanSearchBundle/blob/master/composer.json#L19

**Comment by henrypenny** [comment]
@trsteel88 you're absolutely right. Sorry about that.

**Comment by trsteel88** [comment]
:+1:
