### ISSUE TITLE
DataCollector templates cannot be used out side Symfony Standard.

### ISSUE THREAD

**Issue by henrikbjorn** [doctrine/DoctrineBundle#454]
Since i saw the redesign of the toolbar i decided to play around with adding additional collectors to the Silex WebProfiler.

Sadly the templates for the datacollector in this bundle uses the old `WebProfiler:Profiler:template.html.twig` syntax. Also it uses a hardcoded controller notation for explaining queries instead of a service id.

**Comment by stof** [comment]
Fixed by #468 and #452 for templates.

For the controller, I don't yet know how to fix this.

**Comment by henrikbjorn** [comment]
I think the controller notation can be fixed by using service ids?

**Comment by stof** [comment]
yeah, it might work.

**Comment by kimhemsoe** [comment]
Already fixed.
