### ISSUE TITLE
Solution for `1452 Cannot add or update a child row: a foreign key constraint fails`

### ISSUE THREAD

**Issue by igormukhingmailcom** [doctrine/DoctrineBundle#463]
Hi, guys.

Sometimes we work with databases where data in database is not in sync state with entities.
When we have unsync constraints and trying to update this - we need previously prepare data before.

For example, `businesses_menumetatags` have records that point to inexistent records of `businesses`.
In this case we must previously delete all `businesses_menumetatags` records (because this is what system expects due to `ON DELETE CASCADE`):

```
$this->addSql('DELETE FROM businesses_menumetatags WHERE businesses_id NOT IN (SELECT id FROM businesses)');
$this->addSql('ALTER TABLE businesses_menumetatags ADD CONSTRAINT FK_42CD5A017AC46E66 FOREIGN KEY (businesses_id) REFERENCES businesses (id) ON DELETE CASCADE');
```

Second example, where we don't need to delete any records. We update `business_image_comments` records that point to inexistent records of `business_images` and set `business_image_id` to NULL:
```
$this->addSql('UPDATE business_image_comments SET business_image_id=NULL WHERE business_image_id NOT IN (SELECT id FROM business_images)');
$this->addSql('ALTER TABLE business_image_comments ADD CONSTRAINT FK_5A59FAA435952BFB FOREIGN KEY (business_image_id) REFERENCES business_images (id)');
```

Otherwise we will have next error during `doctrine:schema:update` or `doctrine:migrations:migrate`:

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`database_name`.`#sql-51b_2ab8`, CONSTRAINT `FK_42CD5A017AC46E66` FOREIGN KEY (`businesses_id`) REFERENCES `businesses` (`id`) ON DELETE CASCADE)          
```

Maybe we can add this right into update query generator? So it will generate not 1 query for update constraint, but 2 - first for prepare data, second - for update constraint.

Thanks.

**Comment by igormukhingmailcom** [comment]
BTW, I know that doctrine/doctrine2 is better place for this issue, but I haven't access to add issue there.

**Comment by kimhemsoe** [comment]
You should **never** use doctrine:schema:update in production. 

You can generate the needed sql for bringing the schema in sync and then use some database patch system like doctrine migrations for deploying the changes.
Migrations and others allow you to write whatever sql you need to do the job.

What i am trying to say is that this does not sound like a doctrine problem. It is very much a application problem and should be solved there.

I would search a bit on howto solve your problems in pure sql. Mysql have alot of scary settings you can use when altering tables.

With postgresql one would delete the constraint which is in ones way and add them back when done.

**Comment by kimhemsoe** [comment]
Closing for now, if have more to add you are welcome reopen the issue.

**Comment by stof** [comment]
> BTW, I know that doctrine/doctrine2 is better place for this issue, but I haven't access to add issue there.

You have access, if you use the Doctrine2 issue tracker. But the ORM does not use github as issue tracker. It uses Jira (as linked in the readme)
