### ISSUE TITLE
backticking tablename does not work for JoinTable

### ISSUE THREAD

**Issue by CptLausebaer** [doctrine/DoctrineBundle#475]
I have a Database with uppercase table names, so that I need to write the names in backticks (\`\`). That works fine with the @Table annotation but at the @JoinTable() annotation where is an exception on the backtick. The generated SQL shows that the backtick is not substituted to the expected double quotes.

### example of an entity

    /**
    * @ORM\Table(name="schemaname.`Schemadaten`")
    */
    class Metadaten
    {

    /*...*/
   
    /**
    * @ORM\ManyToMany(targetEntity="SchemaDatenStichwort")
    * @ORM\JoinTable(name="schemaname.`Schema_hatSchluesselwort`",
    *      joinColumns={@ORM\JoinColumn(name="`MD_id`", referencedColumnName="`MD_id`")},
    *      inverseJoinColumns={@ORM\JoinColumn(name="keyword_id", referencedColumnName="id")}
    * )
    */
    private $SchemaDatenStichworte;
    }

### generated SQL

    ... INNER JOIN schemaname.`Schema_hatSchluesselwort` ON ...

    SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"
    ...

**Comment by stof** [comment]
This is not an issue in DoctrineBundle, which only provides an integration in Symfony. Please open the issue in the ORM issue tracker instead (maintainers are not the same)
