### ISSUE TITLE
[Deprecated method] FormTypeInterface::setDefaultOptions()

### ISSUE THREAD

**Issue by zatikbalazs** [doctrine/DoctrineBundle#476]
I ran ``generate:doctrine:crud`` in a Symfony 2.7.5 application and the profiler gave me the following warning when I accessed one of the generated files:

> DEPRECATED - AppBundle\Form\UserType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead.

Is DoctrineBundle still using ``FormTypeInterface::setDefaultOptions()`` because of backwards compatibility?

**Comment by stof** [comment]
Generation commands are part of SensioGeneratorBundle, not of DoctrineBundle.
