### ISSUE TITLE
 Caching when doctrine:generate entities? 

### ISSUE THREAD

**Issue by ivaaaan** [doctrine/DoctrineBundle#479]
I'm have a simple entity:

``` php
<?php
/**
 * @Table(name="tickets")
 * @Entity(repositoryClass="AppBundle\Entity\TicketRepository")
 */
class Ticket 
{
   /**
     * @var \DateTime
     * @Column(type="datetime", name="created_at")
     * @Timestampable(on="create")
     */
    protected $createdAt;

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt = null)
    {
        $this->createdAt = $createdAt;
    }
}
```

Next I'm executing `app/console doctrine:generate:entities`. And add item:

``` php
$ticket = new Ticket(); 
//..
$em->flush();
```

If i'm not execute app/console doctrine:generate:entities - all ok, but when I do it - i got error Integrity constraint violation: 1048 Column 'created_at' cannot be null. And only when I cleared all doctrine cache - all was well

It's strange. 

For fix it i'm just clear all doctrine cache: 

`app/console doctrine:cache:clear-result`
`app/console doctrine:cache:clear-query`

**Comment by Ocramius** [comment]
Generating entities means also changing them (and their mappings), so this seems normal to me.

What would the expected behavior be?

**Comment by ivaaaan** [comment]
i'm don't see changes in file.

**Comment by nicodmf** [comment]
@Ocramius : to close ?
