### ISSUE TITLE
doctrine/doctrine-cache-bundle ~1.0 requires symfony/security-acl ~2.7|~3.0

### ISSUE THREAD

**Issue by choonge** [doctrine/DoctrineBundle#481]
People running on Symfony 2.6 who have not yet upgraded to 2.7 can now no longer install doctrine/doctrine-bundle, because it requires doctrine-cache-bundle ~1.0 and that one requires security-acl 2.7. Would it be possible to get a tag in between, locked to a version of doctrine-cache-bundle which doesn't have said requirement?

**Comment by nicolas-grekas** [comment]
Should be fixed by https://github.com/doctrine/DoctrineCacheBundle/pull/74

**Comment by choonge** [comment]
Thanks a lot!
