### ISSUE TITLE
composer.json doctrine/doctrine-cache-bundle dependency

### ISSUE THREAD

**Issue by Raffaello** [doctrine/DoctrineBundle#485]
running composer update it will upgrade the doctrine-cache-bundle from 1.0.1 to 1.2.1

the 1.2.1 it breaks the code. It is a different structure.

should it be constrained in the doctrine bundle to do not upgrade doctrine-cache-bundle?

thanks.

**Comment by xabbuh** [comment]
@Raffaello What exactly is breaking for you? Which issues do you experience?

**Comment by Raffaello** [comment]
It miss some component in the doctrine cache bundle from the previous version.

The whole application is not able to run due to missing classes.

Don;t remember right now the name of the class missing. But it was a bootstrap.cache error.

It is something that version 1.2 is in a different structure.

My step to reproduce thay:

 just a common symfony 2.7 app. ran composer update and it updated doctrine-cache-bundle from 1.0.1 to 1.2.* and some class where missing.

the fatal error was the boostrap.cache not able to load a required class.

looked into the bundle and a lot of file were missing.

restored the ver 1.0.1 (constrained in my composer.json app) and everything work smoothly again.

**Comment by xabbuh** [comment]
It will be easier to help you if you can provide the error messages you got.

**Comment by Raffaello** [comment]
I know.... :\

I am not able to replicate it right now.

I will try to do it on Monday.
Thank you

**Comment by Raffaello** [comment]
this happen when updatting from 1.0.1 to 1.2.1. 
The reported file is not present in the doctrine cache bundle v 1.2.1
```
/var/www/[....]/vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/SymfonyBridgeAdapter.php): failed to open stream: No such file or directory in /var/www/[...]/app/bootstrap.php.cache on line 281
```

probaby it might be even an incompatibility issue with the `stof/doctrine-extensions-bundle` or something related. not sure.

thank you

**Comment by stof** [comment]
@Raffaello are you using an ApcClassLoader in your project to cache the mapping between classes and files in APC to speed up the autoloader ? If yes, you need to clear your APC cache after updating the dependencies, to make it forget the previous location, as it has indeed changed (the DoctrineCacheBundle no longer uses the legacy ``target-dir`` setting of composer)

**Comment by Raffaello** [comment]
@stof.
You are right! The APC caused the issue.
Thank you very much.
