### ISSUE TITLE
1553 error everytime I want to update my database from the console

### ISSUE THREAD

**Issue by zacharyzh** [doctrine/DoctrineBundle#487]
I am not good at english.

    My\Bundle\Entity\MyTable:
        ...
        fields:
            type:
                type: string
                length: 12
                nullable: false

I need the ```nullable``` to be true so I changed it. But I got exceptions when I update schema from console:

> [Doctrine\DBAL\Exception\DriverException]
> An exception occurred while executing 'DROP INDEX idx_d317d5a826e7dda8 ON my_table': 
> SQLSTATE[HY000]: General error: 1553 Cannot drop index 'IDX_D317D5A826E7DDA8': needed in a foreign key constraint

So I dump all sql from console:

    ALTER TABLE my_table CHANGE type `type` VARCHAR(12) DEFAULT NULL;
    DROP INDEX idx_d317d5a826e7dda8 ON my_table;
    CREATE INDEX IDX_D317D5A87F9B5959 ON my_table (`resize_key`);

I never change anything except ```type``` column.

Symfony 2.7.6
DoctrineBundle 1.4
Doctrine/ORM 2.4.6
MySQL 5.5.46-log
PHP 5.6

    # my.cnf
    collation-server = utf8mb4_general_ci
    character-set-server = utf8mb4

**Comment by stof** [comment]
This is not an issue in the bundle. It should be reported to the Doctrine DBAL project itself, which is a different project than the bundle
