### ISSUE TITLE
Humanized text of entity fields

### ISSUE THREAD

**Issue by JHGitty** [doctrine/DoctrineBundle#490]
Is there any common way to get the humanized text of entity fields?

Example:
```php
/* @var EntityManager $em */
$fieldNames = $em->getClassMetadata('AppBundle:User')->getFieldNames();
```

**Output should be ``First Name`` or ``First name`` for entity field ``firstName``.**

If no: What's about a Twig extension in DoctrineBundle for it?

Example idea:
```twig
{{ fieldName|humanizeEntityField }}
```

**Comment by stof** [comment]
Humanizing the field names for output is totally out of the scope of DoctrineBundle. It has nothing to do with Doctrine (it is just about formatting a string in a different way).
Just build your own Twig filter providing such transformation (or rely on the [filter available in Symfony for the form integration](https://github.com/symfony/symfony/blob/074a4bf89eb3ae190990ddae821d82245abcf24b/src/Symfony/Bridge/Twig/Extension/FormExtension.php#L83), which may do what you need here).

In any translated application, you would not be able to format the field name directly anyway. You would have to use a translation string to translate it.
