### ISSUE TITLE
Test DB creation error in symfony

### ISSUE THREAD

**Issue by ghostika** [doctrine/DoctrineBundle#492]
Hello,

I just run a composer update and it's installed the 1.6 doctrine bundle version, (a5b3ba908ba68f3e14e42762a7b940fde65ed7da) and since then if I run this command, I get an error:
```
php app/console do:da:cr --env=test
Could not create database "XXX/app/cache/test/test.db" for connection named default
An exception occured in driver: SQLSTATE[HY000] [14] unable to open database file
```
If I change back the version for v.1.5.2 there is no problem at all.

**Comment by xabbuh** [comment]
see #482 (this has already been fixed in #483 and will be included in the next release)

**Comment by kimhemsoe** [comment]
@ghostika Can you confirm this is fixed in newest release?

**Comment by kimhemsoe** [comment]
Closing as fixed. You are welcome to write if the your problem still persist in the newest version.
