### ISSUE TITLE
Same entity instance for 2 differents cases with join condition

### ISSUE THREAD

**Issue by BrownSim** [doctrine/DoctrineBundle#493]
Hello, well I don't really know if it is a bug, but here is my case.

I have 4 entities: exam, score, field and data.
The relations are : 
exam manyToMany score 
score oneToMany field
field oneToMany data
exam oneToMany data

I need to return the exam with their scores, with their fields and with their data.
To do this I add a join condition : 
$this->_em->getRepository('FwFollowBundle:Exam')
->createQueryBuilder('exam')
->leftJoin('exam.score', 'score')
->leftJoin('score.fields', 'field')
->leftJoin('field.data', 'data', 'WITH', 'data.exam = exam')
->select ('exam', 'score', 'field', 'data')

The SQL is work, when I run the query, I get the proper results.
But when I dump the result in doctrine, I don't get the proper results.
Because I can get 2 different exams with the same scores, so the same fields but without the same data, doctrine use the same fields instance.

I do not know if I make myself clear.

If someone has already encountered the same case. Maybe it is a doctrine bug?

Thx

**Comment by stof** [comment]
This should be asked in the Doctrine ORM support channels. It has nothing to do with DoctrineBundle itself. So I'm closing this.

Note that I'm maintainer of this bundle, but I'm not a maintainer of the ORM. So asking in the right place will also mean you will ask the right people (most if not all maintainers of the ORM are not reading this issue tracker unless explicitly requested)
