### ISSUE TITLE
php7, proxies don't replicate signature if setter strictly typed

### ISSUE THREAD

**Issue by allan-simon** [doctrine/DoctrineBundle#494]
I got a entity AppGame with a getter`getId() : int` and  it seems to confuse doctrine

"Compile Error: Declaration of Proxies\\__CG__\\AppBundle\\Entity\\AppGame::getId() must be compatible with AppBundle\\Entity\\AppGame::getId(): int

I'm aware php7 is still not released yet, but I think it might be useful to know this problem.

**Comment by stof** [comment]
This mist be reported to Doctrine Common, not to DoctrineBundle. DoctrineBundle is not responsible for generating proxies

**Comment by Ocramius** [comment]
A PR supporting this is already in the works: will be merged/released soon.

**Comment by allan-simon** [comment]
@Ocramius  thanks, good to know :)
