### ISSUE TITLE
Adding doctrine:database:purge/truncate functionality

### ISSUE THREAD

**Issue by xDaizu** [doctrine/DoctrineBundle#495]
I find strange that there is not such an option. Yes, you can use

```
$ php bin/console doctrine:database:drop --force
$ php bin/console doctrine:database:create
$ php bin/console doctrine:schema:update
```

But in some environments you just don't have the option (or permission) to create databases, even if you can do as you wish with your currently created database. 

Actually, this _purge method_ seems to be implemented as part of **doctrine:fixture:load** and I've found myself creating empty fixtures as a quick easy _kinda dirty_ workaround to purge databases before re-initializing them (granted, doesn't reset the index auto-increment counters, but for some use cases that's not a big deal).

**Comment by c33s** [comment]
still this would be a good feature. 
as @xDaizu wrote, in environments where the user is not allowed to delete a database, it could be necessary to recreate the table structure (after adding a new field). having not the option to empty the database leads to a `table already exist` error.

**Comment by kimhemsoe** [comment]
Closing for now.
