### ISSUE TITLE
OneToMany from ManyToOne problem

### ISSUE THREAD

**Issue by Brahim1992** [doctrine/DoctrineBundle#496]
Hi everyone,

My code is :
return $this->repository->createQueryBuilder("z")
            ->select("absence","eleve","note")
            ->from("AppBundle:Absence", "absence")
            ->join("absence.eleve","eleve")
            ->join("eleve.notes","note")
            ->getQuery()
            ->getArrayResult();

absence.eleve is a ManyToOne relationship and eleve.notes is a OneToMany RelationShip, so after many experiences i noticed that when i move from the ManyToOne to the OneToMany eleve.notes is an array that contains always a single object, can you please help me to figure it out.

This is an example of the result :

{"absences":
    [
        {"id":1,"column1":"***","eleve":
            {"id":38,"notes":
                [
                    {"id":131,"note":10}
                ]
            }
        },
        {"id":2,"column1":"***","eleve":
            {"id":39,"notes":
                [
                    {"id":130,"note":5}
                ]
            }
        }
    ]
}

the array named "notes" should contain many objects not only one.

when in do this : return $this->repository->createQueryBuilder("z")
            ->select("eleve","note")
            ->from("AppBundle:Eleve", "eleve")
            ->join("eleve.notes","note")
            ->getQuery()
            ->getArrayResult();

it works fine and for each eleve notes is an array of multiple objects.

Thanks to help me

**Comment by xabbuh** [comment]
This has nothing to do with DoctrineBundle and you probably get better help when asking this on a support channel like IRC or StackOverflow.

**Comment by kimhemsoe** [comment]
Not related to bundle.
You want to take a look at how to get support for the ORM(https://github.com/doctrine/doctrine2) and @xabbuh suggestions.
