### ISSUE TITLE
How to use version 1.6

### ISSUE THREAD

**Issue by arodiss** [doctrine/DoctrineBundle#506]
Sorry for stupid question, but I don't understand how can I install version 1.6 of this bundle

On tag 1.6.1 bundle [claims](https://github.com/doctrine/DoctrineBundle/blob/1.6.1/composer.json) to require `doctrine/orm` 2.3 or higher. This is not actually true - it [uses](https://github.com/doctrine/DoctrineBundle/blob/1.6.1/Resources/config/orm.xml#L54) class `Doctrine\ORM\Tools\AttachEntityListenersListener` which is only [available](https://github.com/doctrine/doctrine2/blob/2.5/lib/Doctrine/ORM/Tools/AttachEntityListenersListener.php) in `doctrine/orm` since version 2.5
That's not the story yet. Package `doctrine/orm` 2.5 [requires] (https://github.com/doctrine/doctrine2/blob/2.5/composer.json) `doctrine/dbal` or higher, while symfony itself [requires](https://github.com/symfony/symfony/issues/12278) `doctrine/dbal` to be strictly lower than 2.5 due to [known issue](https://github.com/symfony/symfony/issues/16150) with 2.5

So how do you ever use this?
(Again, sorry for potentially stupid question)

**Comment by stof** [comment]
it uses it only if you enable the feature. If you use doctrine/orm 2.3, just don't configure the 2.5+ features

**Comment by stof** [comment]
and btw, Symfony can totally run with doctrine/orm 2.5 (Symfony 2.8 even ships with it by default). 

The "known issue" you have has a known workaround: specify the server version explicitly instead of letting DBAL guess it (which indeed cannot be done if it cannot connect to the DB)

**Comment by arodiss** [comment]
@stof 
I don't see how can I "avoid using this feature" - as far as I see listener is [called](https://github.com/doctrine/DoctrineBundle/blob/1.6.1/DependencyInjection/DoctrineExtension.php#L448) on `loadClassMetadata` which is not something avoidable :smile: So I think you should bump version contraint
However, workaround you suggested helped, thank you

**Comment by stof** [comment]
Have you checked the code 2 lines above ? This is enclosed in a ``if (version_compare(Version::VERSION, "2.5.0-DEV") >= 0) {`` check. so this is **not** called if you use older versions

**Comment by arodiss** [comment]
@stof 
Right you are
