### ISSUE TITLE
Symfony Doctrine JoinTable

### ISSUE THREAD

**Issue by shubaivan** [doctrine/DoctrineBundle#510]
How to JoinTable in DB if I have relation OneToOne->ManyToOne? 
	
I have Data Base MySQL and in table users I need see row client_id. But now I have row user_id in table clients, thats all. But need clien_id in table users. I Post this is question in issue in github in doctrinebundle because this is annotation @ORM\JoinColumn

In entity when ManyToOne I have filed in DB entity_id, but I need entity_id in OneToMany too, I try 

         * @ORM\JoinColumn(name="developer_id", nullable = true, referencedColumnName="id")

but in DB not see this column

this my entity Clients in DB I have user_id

    /**
     * Clients.
     *
     * @ORM\Table(name="clients")
     * @Gedmo\SoftDeleteable(fieldName="deletedAt")
     * @ORM\Entity(repositoryClass="Artel\ProfileBundle\Entity\Repository\ClientsRepository")
     * @ExclusionPolicy("all")
     */
    class Clients
    {
    use Timestampable;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Artel\ProfileBundle\Entity\Users", inversedBy="client", cascade={"persist", "remove"}, fetch="EAGER")
     */
    protected $user;

And this my entity Users (not column client_id):

    /**
     * Users.
     *
     * @ORM\Table(name="users")
     * @Gedmo\SoftDeleteable(fieldName="deletedAt")
     * @ORM\Entity(repositoryClass="Artel\ProfileBundle\Entity\Repository\UsersRepository")
     * @ExclusionPolicy("all")
     */
     class Users
    {
    use Timestampable;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="Clients", mappedBy="user", orphanRemoval=true, cascade={"persist"})
     * @ORM\JoinColumn(name="client_id", nullable = true, referencedColumnName="id")
     */
    public $client;

**Comment by xabbuh** [comment]
This has nothing to do with DoctrineBundle which just integrates Doctrine into Symfony. Also there already is an existing thread on StackOverflow: http://stackoverflow.com/questions/34787633/symfony-doctrine-jointable

**Comment by shubaivan** [comment]
I think this is doctrine annotation @ORM\JoinColumn

**Comment by xabbuh** [comment]
Even the annotation is not defined in this bundle.

**Comment by stof** [comment]
Closing as this is indeed the wrong place to ask. This repo is not the ORM. It is only the integration of the ORM into the Symfony configuration system (and the web debug toolbar)
