### ISSUE TITLE
Cannot seem to access EntityManager service within the Compiler Pass

### ISSUE THREAD

**Issue by yellow1912** [doctrine/DoctrineBundle#512]
Not sure if this is an issue on my end, but when I try to access the entity within a compiler pass using the following code on SF 2.8 and doctrine latest version:

```php
$container->get('doctrine.orm.entity_manager')
```

I get the error like this

```
[ReflectionException] 
Class does not exist 


Exception trace:
() at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:921
ReflectionClass->__construct() at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:921
```

The service that the container builder was trying to build (and got stuck) is doctrine.dbal.default_connection.configuration, not sure why the class is empty/null at this point?

**Comment by trsteel88** [comment]
@yellow1912, you shouldn't be using any services within a compiler pass. I believe it's job is just to change the configuration before everything is compiled.

Instead, you should access the reference to the service id. Then you can inject it into a service that modifies how the application works. To inject a reference you can do something like this:

```php
<?php

namespace Acme\DemoBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

class RequiresChannelCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $definition = $container->getDefinition('acme.service.override');

        $definition->setClass('Acme\Some\New\Class')
            ->setArguments(array(new Reference('doctrine.orm.entity_manager'))
        ;
    }
}

```

**Comment by stof** [comment]
@trsteel88 is right. In a compiler pass, the container is not yet ready to be used.
