### ISSUE TITLE
Patch release missing

### ISSUE THREAD

**Issue by werdlv** [doctrine/DoctrineBundle#514]
#500 was fixed code wise but patch release was never released

@stof https://github.com/symfony/symfony/blob/v3.0.1/composer.json#L79 - release 1.4.1 should do the trick

**Comment by werdlv** [comment]
@stof friendly reminder :)

**Comment by werdlv** [comment]
@kimhemsoe maybe You can take care of this?

**Comment by xabbuh** [comment]
@werdlv This was fixed in #505 which is part of the 1.6.2 release, isn't it?

**Comment by kimhemsoe** [comment]
@werdlv Can you confirm this is fixed in newest release?

**Comment by werdlv** [comment]
@kimhemsoe confirmed. Thanks!
