### ISSUE TITLE
Second Level Cache using Symfony2 yml configuration

### ISSUE THREAD

**Issue by jonbev** [doctrine/DoctrineBundle#516]
I have a bunch of entities and would like to test the Second Level Cache but I can't get it to work. I just get zero hits, misses & puts in the profiler.

All entities have annotations as below.

```
use Doctrine\ORM\Mapping AS ORM;

/**
 * @ORM\Entity
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region="my_region")
 */
class Property extends Base\PropertyBase
{
```

My config file has -

```
doctrine:
    orm:
        metadata_cache_driver:
                    type:           memcache
        result_cache_driver:
                    type:           memcache
        query_cache_driver:
                    type:           memcache
        second_level_cache:
              region_cache_driver:
                    type:           memcache
              enabled:              true
              log_enabled:          true
              regions:
                    my_region:
                        cache_driver:  memcache
                        lifetime:   3600

```
The profiler shows the cache is enabled but I am not getting any activity.

Any suggestions as to how I might debug this?

**Comment by jonbev** [comment]
After spending a long time following it through the code I realised that the metadata was cached in memcache and so was not picking up the new annotations.

**Comment by clytemnestra** [comment]
@jonbev a question, the metadata is cached in memcache, so that means that in the profiler there will always be 0-0-0, or is there a way to display it there?

I'm asking because if I disable memcache, I still get 0-0-0.

**Comment by jonbev** [comment]
In terms on the metadata just make sure you have restarted memcache and done an app/console cache:clear and you should be all good. You need to do this after any annotation changes.

Any entities that you want to cache must have the annotations as far as I am aware.

**Comment by tanasecosminromeo** [comment]
@jonbev 

> After spending a long time following it through the code I realised that the metadata was cached in memcache and so was not picking up the new annotations.

After spending a long time, I've seen your comment 👍
