### ISSUE TITLE
Query Cache driver Chain

### ISSUE THREAD

**Issue by gimler** [doctrine/DoctrineBundle#522]
I try to get the query cache driver type chain to work.

this doesn't work

```
    <doctrine:config>
        <doctrine:orm>
            <doctrine:query-cache-driver
                    type="chain"
            >
                <provider>array</provider>
                <provider>apc</provider>
            </doctrine:query-cache-driver>
```

```
Warning: Invalid argument supplied for foreach() in ...vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/ChainDefinition.php on line 47
```

it seems to work with

```
    <services>
        <service id="doctrine.cache.query.array" class="Doctrine\Common\Cache\ArrayCache" />
        <service id="doctrine.cache.query.apc" class="Doctrine\Common\Cache\ApcCache" />

        <service id="doctrine.cache.query.chain" class="Doctrine\Common\Cache\ChainCache">
            <argument type="collection">
                <argument type="service" id="doctrine.cache.query.array" />
                <argument type="service" id="doctrine.cache.query.apc" />
            </argument>
        </service>
    </services>

    <doctrine:config>
        <doctrine:orm>
            <doctrine:query-cache-driver id="doctrine_cache.providers.chain" />
```

i think the configuration (vendor/doctrine/doctrine-bundle/DependencyInjection/Configuration.php:612) has no providers value.

**Comment by stof** [comment]
The chain cache provider is not supported by the configuration of DoctrineBundle. I don't even understand how this config could validate against the Configuration class before reaching the DoctrineCacheBundle code we are using here. ``provider`` is not a valid child of ``query_cache_driver

If you want a chain, I would suggest configuring it through the DoctrineCacheBundle configuration (which supports more complex configurations of doctrine/cache) and then referencing these cache providers in the Doctrine ORM config.

**Comment by kimhemsoe** [comment]
Closing. Solution suggested by Stof.
