### ISSUE TITLE
create-database creates strange filename with SQLite and URL-configuration

### ISSUE THREAD

**Issue by KingCrunch** [doctrine/DoctrineBundle#524]
This `sqlite:///somedb.sqlite`
leads to this: 

``` bash
$ ls *db*
"somedb.sqlite"
```

(Note the double quotes around the filename)

when I use `doctrine:database:create`

When I remove [`CreateDatabaseCommand:83](https://github.com/doctrine/DoctrineBundle/blob/e47b0b6680c40288c418ad13ef6f035f25fff51f/Command/CreateDatabaseDoctrineCommand.php#L83)

``` php
if (!$hasPath) {
    $name = $tmpConnection->getDatabasePlatform()->quoteSingleIdentifier($name);
}
```

It creates the file as expected `somedb.sqlite`. Thus I assume it is related to how `$hasPath` relates to sqlite, or how `$hasPath` was created before.

**Comment by kimhemsoe** [comment]
Is this still valid?

There is quite a few issues there predates this but with similar problems.

**Comment by KingCrunch** [comment]
Havent looked at it any further, but I assume it is still valid.

**Comment by gelbehexe** [comment]
In case you want to put your database in a subfolder it fails with 
```
Could not create database "data/data.db" for connection named default
An exception occured in driver: SQLSTATE[HY000] [14] unable to open database file
```
And YES, subfolder "data" exists. It seems trying to create a file name '"data/data.db"'.

**Comment by gelbehexe** [comment]
Ahhh, after a look in the code I see there is an config option "path", if i set it to "data/data.db" it works correctly without any quotes!

**Comment by mikeSimonson** [comment]
@gelbehexe can you make a failing test case ?

**Comment by kimhemsoe** [comment]
I believe this has been fixed. If the issue still persist i will reopen.
