### ISSUE TITLE
support --skip-mapping and --skip-sync in d:schema:validate

### ISSUE THREAD

**Issue by SimonHeimberg** [doctrine/DoctrineBundle#529]
Support the options--skip-mapping and --skip-sync in doctrine:schema:validate. This are supported by the underlying [doctrine ValidateSchemaCommand](https://github.com/doctrine/doctrine2/blob/e6be52af3ae867f4c1f8c4a754239bd13dde9fcc/lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php#L50).

I thought this arguments should already work because they are set when calling [`parent::configure` in configure](https://github.com/doctrine/DoctrineBundle/blob/56d6cf2b55b94052c6c462dd38a9133fee716746/Command/Proxy/ValidateSchemaCommand.php#L36). But --help does not list them and using them raises an error.

**Comment by stof** [comment]
Well, for me, they are listed. I'm quite sure that you are using an older version of the ORM, which does not have these options yet (could it be that you are running the 2.4 version of the ORM ? These options are new features in 2.5)

**Comment by SimonHeimberg** [comment]
You are absolutely right. I use doctrine/orm v2.4.8
Thank you very much for answering this quickly. :+1: 

(In the history of my shell I see that I only checked if `parent::configure` is called. I was convinced to have checked more.)
