### ISSUE TITLE
Nothing to update if change from text to tinytext

### ISSUE THREAD

**Issue by skornev** [doctrine/DoctrineBundle#530]
Changing from 
```
 /**
     * @var  string
     * @ORM\Column(name="text", type="text", length=65535)
     *
     */
```
to
```
  /**
     * @var  string
     * @ORM\Column(name="text", type="text", length=65)
     *


```
has no effect  

./bin/console doctrine:schema:update --force
Nothing to update - your database is already in sync with the current entity metadata.
Removing column only helps to update table structure.

**Comment by stof** [comment]
closing this as DoctrineBundle is not responsible for computing schema changes. This depends of the ORM and DBAL.

Btw, I think you are confusing ``type="text"`` and ``type="string"`` in the mapping.
