### ISSUE TITLE
Unknown "doctrine_pretty_query" filter in "DoctrineBundle:Collector:db.html.twig"

### ISSUE THREAD

**Issue by fredericmalo** [doctrine/DoctrineBundle#539]
Hello, 

Each time i clean symfony cache with command line

`sudo -u www-data php app/console cache:clear --env=prod --no-debug`

I get this error : 

`assetic.ERROR: The template "DoctrineBundle:Collector:db.html.twig" contains an error: Unknown "doctrine_pretty_query" filter in "DoctrineBundle:Collector:db.html.twig" at line 169. [] []`

I'm using Symfony 2.7.11 with  "doctrine/doctrine-bundle": "~1.4" composer instructions. 

Can you help me please ? Thanks

**Comment by kimhemsoe** [comment]
Would it be possible for you to try the newest version?

**Comment by fredericmalo** [comment]
Hello kimhemsoe,

Thanks for your help ! 

I've composed that :

```
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "1.6.*",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "2.6.*",

        "doctrine/mongodb": "1.2.*",
        "doctrine/mongodb-odm-bundle": "3.0.*",
```

Strangely, Symfony upgraded to 2.7.12 but I've seen no upgrade notice or errors for doctrine-bundle. 

I've got the same error about doctrine_pretty_query 

Si I've made a 

```
sudo rm -R vendor/doctrine/ 
sudo composer update
```
with this result : 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing doctrine/lexer (v1.0.1)
    Loading from cache

  - Installing doctrine/annotations (v1.2.7)
    Loading from cache

  - Installing doctrine/collections (v1.3.0)
    Loading from cache

  - Installing doctrine/cache (v1.6.0)
    Loading from cache

  - Installing doctrine/inflector (v1.1.0)
    Loading from cache

  - Installing doctrine/common (v2.6.1)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Installing doctrine/dbal (v2.5.4)
    Loading from cache

    Skipped installation of bin bin/doctrine-dbal for package doctrine/dbal: name conflicts with an existing file
  - Installing doctrine/orm (v2.5.4)
    Loading from cache

    Skipped installation of bin bin/doctrine for package doctrine/orm: name conflicts with an existing file
    Skipped installation of bin bin/doctrine.php for package doctrine/orm: name conflicts with an existing file
  - Installing doctrine/doctrine-cache-bundle (1.3.0)
    Loading from cache

  - Installing doctrine/doctrine-bundle (1.6.2)
    Loading from cache

  - Installing doctrine/mongodb (1.2.2)
    Loading from cache

  - Installing doctrine/mongodb-odm (1.0.5)
    Loading from cache

  - Installing doctrine/mongodb-odm-bundle (3.0.2)
    Loading from cache

doctrine/mongodb suggests installing jmikola/geojson (Support GeoJSON geometry objects in 2dsphere queries)
doctrine/mongodb-odm-bundle suggests installing doctrine/data-fixtures (Load data fixtures)
```

... and I always have the same error 

`[2016-05-03 14:32:55] assetic.ERROR: The template "DoctrineBundle:Collector:db.html.twig" contains an error: Unknown "doctrine_pretty_query" filter in "DoctrineBundle:Collector:db.html.twig" at line 169. [] []`

Quiet strange. Thanks for your help !

**Comment by stof** [comment]
Could it be possible that you have another Twig extension named ``doctrine_extension`` which would overwrite the extension registered by DoctrineBundle ?

**Comment by fredericmalo** [comment]
Hello stof, 

I just checked /src folder and can't find any trace of doctrine_extension. 

Perhaps it is in another /vendor bundle ? I will check that

**Comment by meetmatt** [comment]
Same thing, happens on container build.
Symfony 3.0.8
DoctrineBundle 1.6.3
AsseticBundle 2.8.0

**Comment by meetmatt** [comment]
@fredericmalo I was able to reproduce you issue and figure out the cause.
https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/DoctrineExtension.php#L75
Twig extension gets loaded only if you have `dbal` section in config.

**Comment by fredericmalo** [comment]
Many thanks @meetmatt

**Comment by stof** [comment]
I suggest you to tell AsseticBundle about the list of bundles it should scan to locate assetic tags, instead of making it scan all bundles. This will avoid such issues (as it won't scan DoctrineBundle anymore).
Registering the Twig extension only when we are enabling the profiler panel makes sense IMO
