### ISSUE TITLE
"bin/console doctrine:mapping:import AppBundle annotation" overwrites existing entities

### ISSUE THREAD

**Issue by aschmidt1976** [doctrine/DoctrineBundle#540]
When I execute
`sudo -u www-data bin/console doctrine:mapping:import AppBundle annotation`

WITHOUT the "--force" option, it overwrites existing entities in the folder
"src/AppBundle/Entity/" anyway.

Shouldn't they be kept? I want to create only mapping files for newly added tables in the database...

**Comment by kimhemsoe** [comment]
I recommend specifying where the entities should be put so it wont overwrite existing entities.
