### ISSUE TITLE
Query parameters not always resolved in the profiler

### ISSUE THREAD

**Issue by 1ed** [doctrine/DoctrineBundle#545]
When using a POPO (Ramsey\Uuid\Uuid) object as query parameter I get this:

![image](https://cloud.githubusercontent.com/assets/162986/15740354/dd818880-28b4-11e6-828f-f6337e73a6a9.png)

As you can see the parameter not resolved and the runnable query not runnable at all.

When I use a User entity and write a query like this the parameter resolved correctly

``` php
$user = $this->getUser();
$this->getDoctrine()->getRepository('AppBundle:Patient')->findOneBy(['user' => $user]);
```

![image](https://cloud.githubusercontent.com/assets/162986/15741122/80ff2190-28b8-11e6-9fb8-ada07a8394d2.png)

but for a query like this it's not

``` php
$user = $this->getUser();
$this->getDoctrine()->getRepository('AppBundle:Patient')->createQueryBuilder('p')
    ->andWhere('p.user = :user')
    ->setParameter('user', $user)
    ->setMaxResults(1)
    ->getQuery()
    ->getOneOrNullResult();
```

![image](https://cloud.githubusercontent.com/assets/162986/15741324/6837d8fe-28b9-11e6-9317-fed0dc97b0d8.png)

**Comment by kimhemsoe** [comment]
This the is issue tracker for the symfony bundle. You should reopen the issues for the doctrine.

**Comment by stof** [comment]
@kimhemsoe the profiler integration is part of the bundle, so this is the right issue tracker

**Comment by stof** [comment]
The thing is, the data collector needs to ensure that all data it contains is serializable. This means that in some cases, it cannot retain the original data, and so generating the runnable query does not work fine (we should have enough info to hide the button in this case though IIRC)
The difference is that ``findOneBy`` is probably passing the parameter as a string, not as an object.

**Comment by kimhemsoe** [comment]
@stof Sorry, i missread "runable" part as not run-able when query was constructed.

**Comment by kimhemsoe** [comment]
Is this still an issue?

**Comment by PReimers** [comment]
@1ed is this still an issue?

**Comment by 1ed** [comment]
I'm not sure, but I think we can close this now.
