### ISSUE TITLE
doctrine:schema:drop does not drop schema in Postgres

### ISSUE THREAD

**Issue by AlanEdwardScott** [doctrine/DoctrineBundle#548]
I've prepared the following simple wrapper script while developing my database with Doctrine annotations:
```
#!/usr/bin/env bash

php bin/console doctrine:schema:drop --force
php bin/console cache:clear
php bin/console doctrine:cache:clear-metadata --flush
php bin/console doctrine:schema:create
php bin/console doctrine:fixtures:load --purge-with-truncate
```

However, I notice that when `doctrine:schema:drop` is run, there are no SQL commands generated to drop the schema in my Postgres database. The results of my `doctrine:schema:drop --dump-sql` include:

```
...
DROP SEQUENCE account.user_id_seq CASCADE;
DROP SEQUENCE account.user_role_id_seq CASCADE;
DROP SEQUENCE account.user_scope_permission_id_seq CASCADE;
DROP TABLE system.schema_log;
DROP TABLE kernel.module;
DROP TABLE account.user_scope_permission;
DROP TABLE kernel.configuration;
DROP TABLE kernel.scope;
DROP TABLE kernel.code;
DROP TABLE kernel.code_module;
DROP TABLE kernel.configuration_scope;
DROP TABLE account.permission;
DROP TABLE account.role;
DROP TABLE account.user_role;
DROP TABLE account.assignment;
DROP TABLE account.role_permission
```

As you can see, there are no SQL statements for dropping the schema. And yet, `doctrine:schema:create --dump-sql` begins with the following:

```
CREATE SCHEMA system;
CREATE SCHEMA kernel;
CREATE SCHEMA account;
CREATE TABLE system.schema_log (id SERIAL NOT NULL, status_id INT DEFAULT NULL, created_id INT DEFAULT NULL, file_name VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX UNIQ_38CD4290D7DF1668 ON system.schema_log (file_name);
CREATE INDEX IDX_38CD42906BF700BD ON system.schema_log (status_id);
...
```

Is it possible to update the `doctrine:schema:drop` command to include generation of statements to drop created schema when using Postgres?

**Comment by mikeSimonson** [comment]
@AlanEdwardScott Can you paste a copy of your configuration ?

Thanks

**Comment by AlanEdwardScott** [comment]
@mikeSimonson 
```
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping:    true
```

**Comment by mikeSimonson** [comment]
I am a little bit a loss.
You have only one database connection to one specific database but then it seems that your schema is also connected to 2 other databases.

**Comment by AlanEdwardScott** [comment]
This is PostgreSQL. A single database can have multiple schema. All three
schema exist within a single database. Hence the single connection.

**Comment by kimhemsoe** [comment]
Can you write a unittest to reproduce this error? Also i think that dbal may be a better place to have this talk.

**Comment by AlanEdwardScott** [comment]
@kimhemsoe 
I'll work on preparing a test and will submit the issue on `dbal`.

**Comment by cordoval** [comment]
i am having the same problem @AlanEdwardScott how did you solve it?

**Comment by cordoval** [comment]
I also did --dump-sql and it is not dropping the schema, it does drop everything inside but not the schema

so doing this manually:
```sql
DROP SCHEMA canary;
```
