### ISSUE TITLE
Second Cache Level - allow "default_multi" in region type

### ISSUE THREAD

**Issue by orfin** [doctrine/DoctrineBundle#549]
Currently it is only possible to configure "default" region type but https://github.com/doctrine/doctrine2/pull/954 introduced optimized Doctrine\ORM\Cache\Region\DefaultMultiGetRegion region that uses fetchMultiple method.

**Proposal:** 
- allow to use "default_multi" under second_level_cache.regions.type configuration.

BTW. currently DefaultMultiGetRegion is not even documented in Doctrine docs: http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/second-level-cache.html#cache-regions so I'm not sure if it is production-ready?

**Comment by kimhemsoe** [comment]
Pull requests are welcome :)

**Comment by ostrolucky** [comment]
Doctrine team is contemplating switching to PSR caches in our projects. In such case this configuration would no longer be needed, as all PSR caches support multi get

**Comment by dmaicher** [comment]
From what I can tell this is obsolete now. `DefaultMultiGetRegion` is deprecated and the second level cache is now using PSR caches.
