### ISSUE TITLE
FatalThrowableError after #559

### ISSUE THREAD

**Issue by nullziu** [doctrine/DoctrineBundle#562]
After #559 I get this exception:

```
 [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                             
  Fatal error: Call to protected DoctrineORMEntityManager_000000001664df44000000007f2773e7d25220c7e940adfdba71a0bbbd0d7051::__construct() from context 'ap_DevDebugProjectContainer' 
```

I'm running Symfony 2.7.9 and doctrine-bundle 1.6.4 in PHP 7.0.8

**Comment by kimhemsoe** [comment]
@nicolas-grekas @Ocramius Any idea?

**Comment by Ocramius** [comment]
Any stack trace to show us? Might have reached a limitation of ProxyManager that I may not have found yet (despite the huge load of tests).

Could you also copy the generated container file into a gist?

**Comment by nullziu** [comment]
stack trace:
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to protected DoctrineORMEntityManager_000000005352a240000000001b1bac3234c74b49ef521c849392ccdbccc7223b::__construct() from context 'appDevDebugProjectContainer' in /srv/erp.sziget.hu/var/cache/dev/appDevDebugProjectContainer.php:7038
Stack trace:
#0 /srv/erp.sziget.hu/var/bootstrap.php.cache(2155): appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManager_DelegateService()
#1 /srv/erp.sziget.hu/var/cache/dev/appDevDebugProjectContainer.php(982): Symfony\Component\DependencyInjection\Container->get('doctrine.orm.de...')
#2 /srv/erp.sziget.hu/var/bootstrap.php.cache(2155): appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()
#3 /srv/erp.sziget.hu/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php(35): Symfony\Component\DependencyInjection\Container->get('doctrine.orm.de...')
#4 /srv/erp.sziget.hu/vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php(231 in /srv/erp.sziget.hu/var/cache/dev/appDevDebugProjectContainer.php on line 7038
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                                                                                                                                                                                             
  [RuntimeException]                                                                                                                                                                                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                                                                                  
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to protected DoctrineORMEntityManager_000000005352a240000000001b1bac3234c74b49ef521c849392ccdbccc7223b::__construct() from context 'a  
  ppDevDebugProjectContainer' in /srv/erp.sziget.hu/var/cache/dev/appDevDebugProjectContainer.php:7038                                                                                                                                       
  Stack trace:                                                                                                                                                                                                                               
  #0 /srv/erp.sziget.hu/var/bootstrap.php.cache(2155): appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManager_DelegateService()                                                                                                   
  #1 /srv/erp.sziget.hu/var/cache/dev/appDevDebugProjectContainer.php(982): Symfony\Component\DependencyInjection\Container->get('doctrine.orm.de...')                                                                                       
  #2 /srv/erp.sziget.hu/var/bootstrap.php.cache(2155): appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()                                                                                                            
  #3 /srv/erp.sziget.hu/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php(35): Symfony\Component\DependencyInjection\Container->get('doctrine.orm.de...')                                                               
  #4 /srv/erp.sziget.hu/vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php(231 in /srv/erp.sziget.hu/var/cache/dev/appDevDebugProjectContainer.php on line 7038                                              
  .
```

appDevDebugProjectContainer.php: https://gist.github.com/nullziu/eb6ad74543341b2d1f96c4a9218b4c4f

**Comment by antanas-arvasevicius** [comment]
Hi,
Maybe this problem also relates to that: (lazy services stopped working after 1.6.4)
https://github.com/doctrine/DoctrineBundle/pull/559#issuecomment-241442703

**Comment by gxolin** [comment]
Hi, 
@antanas-arvasevicius same issue for me with  #559
````
[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]                                    
Circular reference detected for service "doctrine.dbal.default_connection", path: "doctrine.dbal.default_connection". 
````
after installing doctrine bundle 1.6.4. 

On my project, replacing : 
```<service id="doctrine.orm.entity_manager.abstract" class="%doctrine.orm.entity_manager.class%" abstract="true" lazy="true" />```
with : 
```<service id="doctrine.orm.entity_manager.abstract" class="%doctrine.orm.entity_manager.class%" abstract="true"/>```
will fix the circular reference.

**Comment by kimhemsoe** [comment]
@Ocramius I am lost here, you have an idea what is going on here?

**Comment by antanas-arvasevicius** [comment]
Hi,  looks like container doesn't support  lazy -> lazy -> lazy  service
chains or something like that.

**Comment by nicolas-grekas** [comment]
Related to https://github.com/symfony/symfony/issues/19901

**Comment by gxolin** [comment]
Since this issue won't be fixed until Symfony next release, will #559 be reverted ? 

We have many lazy->lazy->manager relations, and I was wondering if we should change either those relations or use fixed 1.6.3 version for doctrine until revert or Symfony update.

**Comment by antanas-arvasevicius** [comment]
Hi,
actually it's not due lazy->lazy, but due strange behavior of lazy:true on EntityManager service. What does doctrine bundle is that it clones a service and suffix it with ".delegate", and then creates "proxy service" which uses that ".delegate", but the problem occurs that cloning process of lazy services will expand "inlined services" definitions into service arguments and by that "expansion"  PhpDumper.php now sees that there is direct circular dependency while creating "doctrine.dbal.default_connection".
```
hasReference: (doctrine.dbal.default_connection) , visited: doctrine.orm.default_listeners.attach_entity_listeners -> listener.event_logger (my lazy service) -> doctrine.orm.default_entity_manager -> doctrine.orm.default_entity_manager.delegate -> doctrine.dbal.default_connection 
```
And without that "expansion" EntityManager service configuration object is left as "Inlined definition" thats why without "lazy:true" EntityManager with other lazy services works.
If EntityManager is lazy:true, then inlined Configuration service becomes explicitly defined (expanded) and then relationships/references is tracked by "hasReference".
It looks like this "lazy:true" was working accidentally due that case that "inlined definitions" of services was hidding relationships/references and "hasReference" method won't crawl inside these "inlined defs".
It's strange why "hasReference" is looking up references in lazy services as references is only indirectly and not important in runtime initialization of services.

PS. this is still not officially confirmed and it is just my view of this problem.

**Comment by kimhemsoe** [comment]
Is this still an issue?

**Comment by nullziu** [comment]
Not relevant to me anymore.
