### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by dunglas** [doctrine/DoctrineBundle#563]
Hi,

Is it possible/planned to release a new version of this bundle? The last version is almost 1 year old. I especially need the support of the PropertyInfo component (#502) that is shipped with Symfony 2.8+.

**Comment by kimhemsoe** [comment]
Hi

Newest version is 9 day old and no new changes have been merged since :)

**Comment by dunglas** [comment]
Sorry I got confused by the order of tags on GitHub (it's because old tags was following the `v0.0.0` format and new tags doesn't include the `v`  anymore (e.g. `1.6.0`).

**Comment by stof** [comment]
yeah, it depends of who made the release

**Comment by kimhemsoe** [comment]
I am all up for a convention. I just followed guilhermeblanco :D
