### ISSUE TITLE
Merging of the `mappings` option of Entity Managers

### ISSUE THREAD

**Issue by thedamnedrhino** [doctrine/DoctrineBundle#570]
As it stands, the values for the `mappings` Option are merged if redefined. This makes it impossible to remove any mappings used in other environments, here is my Use Case:
I have separated the **Entity Manager** and **Connection** for my **User** Entity from other Entities in the **test** Environment, because I clean the database in each test before loading my fixtures, and that would cause the User Data to also be removed. So I need to remove the `mapping` for my User Entity from the default Entity Manager's `mappings`. But it's not possible to do that right now.

**Comment by kimhemsoe** [comment]
Dump content of the table and load it in after the clean or create the user data with fixtures.

Also this repo is for the bundle and only the bundle :)

**Comment by stof** [comment]
Using a separate entity manager for the user entity in tests means that your tests are testing a totally different codebase than what you actually run in prod. so this seems a very strange setup to me.
