### ISSUE TITLE
Cannot cascade remove entities but they are configured through annotations, throws foriegn key error on deletion

### ISSUE THREAD

**Issue by idchlife** [doctrine/DoctrineBundle#571]
I have this error

![image](https://cloud.githubusercontent.com/assets/4563032/18643361/79de1100-7ead-11e6-8952-918554e2d29e.png)

And this in annotations:

![image](https://cloud.githubusercontent.com/assets/4563032/18643381/859bb2b8-7ead-11e6-9a02-0fa81d2972d8.png)

Trouble happened today, and I should say it was not the case for about 2 days ago. Everything seemed regular, but now there is error :(

Anyone experiencing same issue?

**Comment by mikeSimonson** [comment]
Can you show the mapping on the other side of the relation ?

**Comment by stof** [comment]
This should be asked to the ORM, not to the bundle (which is only responsible for the Symfony integration)

**Comment by idchlife** [comment]
@mikeSimonson 

![image](https://cloud.githubusercontent.com/assets/4563032/18664663/4a050e82-7f2c-11e6-8aba-59df52b03241.png)

@stof you are right, will make issue in the doctrine repository
