### ISSUE TITLE
Doctrine commands do not ignore entities with ReadOnly flag

### ISSUE THREAD

**Issue by podorozhny** [doctrine/DoctrineBundle#573]
For example, I want to use database view for read-only purposes, but commands like `doctrine:schema:drop` will affect it.

So, can I submit PR for this? Or its a desired behaviour?

**Comment by kimhemsoe** [comment]
That is not how read-only works in the orm.

You can read https://github.com/doctrine/DoctrineBundle/issues/564#issuecomment-241415479 for a bit more info about the subject.

**Comment by podorozhny** [comment]
@kimhemsoe okay. Then I would suggest to create a new entity metadata property for this, maybe `isView` or smth.

**Comment by stof** [comment]
Closing this issue as it is not a DoctrineBundle issue anyway. the bundle respects how the ORM works
