### ISSUE TITLE
Impossible to connect to SQL Server

### ISSUE THREAD

**Issue by Saint-Cyr** [doctrine/DoctrineBundle#577]
After installation of the MS SQL Server driver, and set-up of the php.ini file I can connect to SQL Server with the pure php code as follow: 

'<?php
$serverName = "AMISSAH-PC\SQLEXPRESS"; //serverName\instanceName

// Since UID and PWD are not specified in the $connectionInfo array,
// The connection will be attempted using Windows Authentication.
$connectionInfo = array( "Database"=>"epayzone");
$conn = sqlsrv_connect( $serverName, $connectionInfo);

if( $conn ) {
 echo "Connection established.<br />";
}else{
 echo "Connection could not be established.<br />";
 die( print_r( sqlsrv_errors(), true));
}
?>'
But when a setup the parameters.yml of symfony to connect with my Smyfony3 app, it does not work:
# This file is auto-generated during the composer install
parameters:
    database_driver: sqlsrv
    database_host: AMISSAH-PC\SQLEXPRESS
    database_port: 3306
    database_name: epayzone
    database_user: AMISSAH-PC\user
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
 

and the doctrine config:
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
I get the following error: SQLSrvException in SQLSrvException.php line 42: SQLSTATE [IMSSP, -1]: Invalid option  was passed to sqlsrv_connect.

**Comment by mikeSimonson** [comment]
Encoding issue in your symfony app ?
Can you look at the content that is passed to sqlsrv_connect ?

**Comment by Saint-Cyr** [comment]
I've solve the issue just by change the all production environment to : MS Server 2008 OS, MS SQL Server Express, php 5.6
