### ISSUE TITLE
Mysql  max number columns

### ISSUE THREAD

**Issue by fabgg** [doctrine/DoctrineBundle#578]
For one project with Symfony 2.8.*  I have one table with 257 columns. 
The command doctrine:schema:update  does an alter table each time even table is ok.
ALTER TABLE myTable ADD field256  INT DEFAULT NULL, ADD field257  INT DEFAULT NULL, DROP field256, DROP field257;
Problem I loose part of data;
It seems the limit to 255 columns per row. 
Question : Is it normal ?

**Comment by mikeSimonson** [comment]
Queries to altered the schema are not generated by this library but by the schema comparator of Doctrine DBAL. This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue.
