### ISSUE TITLE
mkdir is not safly called in concurrency situations in EntityGenerator

### ISSUE THREAD

**Issue by lbayerl** [doctrine/DoctrineBundle#580]
in class EntityGenerator, function writeEntityClass there is this code:

`if ( ! is_dir($dir)) {
            mkdir($dir, 0775, true);
 }`

which is not concurrency safe: "This issue is difficult to reproduce, as any of concurrency-related issues. It appears when several processes are attempting to create a directory which is not yet existing, but between is_dir() and mkdir() calls another process already managed to create a directory."

Following construct shall be used: 'if (!@mkdir(...) && !is_dir(...)) { throw ...; }'

Relates to an issue described on StackOverflow (was trying to find a solution for OP and was stubbling into the finding above): http://stackoverflow.com/questions/40464836/symfony-error-when-creating-entity-warning-mkdir-file-exists

**Comment by Ocramius** [comment]
The `EntityGenerator` is NOT supposed to be used at runtime. It's a development-only tool.

**Comment by lbayerl** [comment]
Fully agreed, but it's used in the GenerateEntitiesDoctrineCommand, so it'll be used, and to my understanding it's a simple check to at least throw some meaningful error. Not a big deal, of course.

**Comment by Ocramius** [comment]
@lbayerl indeed, it's good to have it reported, but I felt like closing before it lays eggs :-)

People wildly abuse the entity generator, especially in symfony-standard based projects.
