### ISSUE TITLE
DoctrineMigrationsBundle and doctrine:schema:drop --force

### ISSUE THREAD

**Issue by spdionis** [doctrine/DoctrineBundle#584]
`doctrine:schema:drop --force` does not drop the migrations table. This means that you can't do
```
doctrine:schema:drop --force
doctrine:migrations:migrate
```
without manually dropping the table. It would be nice if this bundle would automatically drop the migrations table too.

**Comment by mikeSimonson** [comment]
You can drop the database instead of the schema ?

**Comment by spdionis** [comment]
But then you have to run `doctrine:database: create` before running migrations, so it's an additional command.

This issue is a nice to have by the way. Also it feels kinda inconsistent.

**Comment by xabbuh** [comment]
The problem is that the DoctrineBundle doesn't know anything about your migrations table. It's just an additional table not managed by Doctrine. Thus, it will leave the table untouched as it does with any other table not managed by the ORM.

**Comment by stof** [comment]
There is a ``--full-database`` option in the ``schema:drop`` command, allowing to drop tables which are not known by the ORM.

Anyway, the ``schema:drop`` command itself is part of the ORM, not of the bundle

**Comment by spdionis** [comment]
My original idea was to create a special case for the DoctrineMigrationsBundle, but the --full-database option works for me. Thanks @stof.

**Comment by allan-simon** [comment]
I just came across this issue while googling , so just for reference 

> You can drop the database instead of the schema ?

in my use case in "testenv" environment, the symfony user has not the right to drop nor create database  (least privilege principle) , so i needed a way to drop all the table used by symfony  , so fortunately there's --full-database :)
