### ISSUE TITLE
PHP7.1 nullable types not supported in doctrine:schema:update

### ISSUE THREAD

**Issue by fmonts** [doctrine/DoctrineBundle#586]
I'm running PHP 7.1.0RC6 and I want to take advantage of the nullable types. 
(PHP 7.1 GA will be released on December 1)

This is a sample field in an entity:

```
/**
 * @ORM\Column(type="string", nullable=true)
 */
private $optionalField;


public function getOptionalField() : ?string
{
	return $this->optionalField;
}

public function setOptionalField(?string $optionalField)
{
	$this->optionalField = $optionalField;
}
```

Running doctrine:schema:update fails because of the following error:

> $ php bin/console doctrine:schema:update --dump-sql
> 
> 
>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Parse error: syntax error, unexpected '?'

**Comment by stof** [comment]
This has nothing to do with the bundle, which only handles configuring things in Symfony.

This should be reported to either doctrine/doctrine2 or doctrine/common depending on where the exception happens (run the command in verbose to make the Symfony console display the stack trace of the exception)

**Comment by fmonts** [comment]
ok sorry, I'll open an issue in doctrine/common
