### ISSUE TITLE
DoctrineDataCollector throws if QueryBuilder was sent instead of actual string query

### ISSUE THREAD

**Issue by tomasfejfar** [doctrine/DoctrineBundle#592]
When using query builder like this
```
$sql = $this->db->createQueryBuilder();
        $sql->select('*')
            ->from(self::TABLE);
$this->db->fetchAssoc($sql);
```
DoctrineDataCollector fails with exception 
```
PDOException in DataCollector.php line 49:
You cannot serialize or unserialize PDO instances
```
The above usage is perfectly legal (there is `$sql->__toString()` method). But when `DoctrineDataCollector` logs queries it saves them in full (as passed to `fetchAssoc()` or any other call used). Therefore `\Doctrine\DBAL\Connection` leaks and therefore `PDO` leaks as well, causing the serialization to fail later. 

Potential workarounds would IMO be:
* somehow sanitize the query before serializing
* converting to string when pulling the query from profiler
* (potentially) somehow notifying the user that such use is unexpected/discouraged/unsupported with DoctrineDataCollector. Lack of meaningful error message, causing more then an hour of debugging was actually the main problem.

**Comment by Ocramius** [comment]
> (there is `$sql->__toString()` method)

This doesn't make it a string. Under strict mode (PHP 7) it would fail, and that will happen as well when we drop PHP 5.6 support ([end of year, I suppose](http://php.net/supported-versions.php))

**Comment by tomasfejfar** [comment]
Anyhow, wouldn't it make sense to have some "best effort" code in place, that would try string conversion and throw exception if what it receives is not serializable / is not string? Not everyone is using strict mode anyway.

**Comment by stof** [comment]
This looks like a bug in DBAL itself. Its SqlLogger is documented as receiving a string always as the query

**Comment by Ocramius** [comment]
I think @stof's analysis is correct here. Closing here therefore: please re-open on DBAL after verifying the behavior in an isolated test case.
