### ISSUE TITLE
A way to enable auto_mapping with multipe Entity Manager

### ISSUE THREAD

**Issue by goetas** [doctrine/DoctrineBundle#60]
Currently i have 50 active bundles in my project.

10 bundles do not require database interaction.
39 bundles uses the default entity manager, that uses the default dbal connection.
1 bundle use the 'custom' entity manager, that uses the 'custom' dbal connection.

to do this, i need to disable auto_mapping and specify all mappings.

<pre>
doctrine:
    dbal:
        default_connection: default
        connections:
                default:
                    driver:   %database_driver%
                   ....
                custom:
                    driver:   pdo_pgsql
                    ...
    orm:
        entity_managers:
            default:
                mappings:
                    Bundle1: ~
                    Bundle2: ~
                    Bundle3: ~
                    Bundle4: ~
                    Bundle4: ~
                    ........
            superdpi:
                mappings: 
                    SuperDpiCoreBundle: ~
                connection: custom     
</pre>

this is very annoying... 
currently i've resolved the problem in this way:
1)

<pre>
doctrine:
    orm:
        entity_managers:
            default:
                auto_mapping : true
            superdpi:
                mappings: 
                    SuperDpiCoreBundle: ~
                connection: custom     
</pre>

2)
removed auto_mapping check inside `DoctrineExtension::loadOrmEntityManager()`
3)
removed auto mapping expansion inside `AbstractDoctrineExtension::loadMappingInformation()`
4) added `DoctrineExtension::collectAutoMappings()` 

<pre>
protected function collectAutoMappings (array $entityManagerConfigs, ContainerBuilder $container){
    $defindedBundles = array_keys($container->getParameter('kernel.bundles'));
    foreach ($entityManagerConfigs as $name => $entityManager) {
        if(isset($entityManager['auto_mapping']) && $entityManager['auto_mapping']){
            foreach ($defindedBundles as $bundle){
                foreach ($entityManagerConfigs as $name2 => $entityManager2) {
                    if($entityManager2['mappings'][$bundle]){
                        continue 2;
                    }
                }
                $entityManagerConfigs[$name]['mappings'][$bundle]['mapping']=true;
            }
        }
    }
    return $entityManagerConfigs;
}
</pre>

5) added 

<pre>
$config['entity_managers'] = $this->collectAutoMappings($config['entity_managers'], $container);
</pre>

inside `DoctrineExtension::ormLoad()` just before

<pre>
foreach ($config['entity_managers'] as $name => $entityManager) {
       $entityManager['name'] = $name;
       $this->loadOrmEntityManager($entityManager, $container);
}
</pre>

suggestions?

**Comment by CharlyPoppins** [comment]
Hi,

I tried to enable auto_mapping on multiple EM but I've got this error :
´´´
You cannot enable "auto_mapping" on more than one manager at the same time (found in "default" and client1").
´´´
Did I miss something in the config.yml ?
´´´
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                ...
            client1:
                ...
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
            client1:
                connection: client1
                auto_mapping: true
´´´

**Comment by stof** [comment]
@CharlyPoppins which version of DoctrineBundle are you using ? Use ``composer show -i doctrine/doctrine-bundle`` to get it if you use composer

**Comment by stof** [comment]
And which version of Symfony ? This feature requires Symfony 2.6+

**Comment by CharlyPoppins** [comment]
Hi, I'm on Symfony 2.8.0 and I'm using Doctrine :
```
name     : doctrine/doctrine-bundle
descrip. : Symfony DoctrineBundle
keywords : database, dbal, orm, persistence
versions : * dev-master, 1.6.x-dev
type     : symfony-bundle
```

**Comment by xabbuh** [comment]
@CharlyPoppins What is the output of `composer show -i symfony/symfony` and `composer show -i symfony/doctrine-bridge`?

**Comment by CharlyPoppins** [comment]
**php composer.phar show -i symfony/symfony **
```
name     : symfony/symfony
descrip. : The Symfony PHP framework
keywords : framework
versions : * v2.8.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/symfony/symfony.git 5615b92cd452cd54f1433a3f53de87c096a1107f
dist     : [zip] https://api.github.com/repos/symfony/symfony/zipball/5615b92cd452cd54f1433a3f53de87c096a1107f 5615b92cd452cd54f1433a3f53de87c096a1107f
names    : symfony/symfony, symfony/asset, symfony/browser-kit, symfony/class-loader, symfony/config, symfony/console, symfony/css-selector, symfony/debug, symfony/debug-bundle, symfony/dependency-injection, symfony/doctrine-bridge, symfony/dom-crawler, symfony/event-dispatcher, symfony/expression-language, symfony/filesystem, symfony/finder, symfony/form, symfony/framework-bundle, symfony/http-foundation, symfony/http-kernel, symfony/intl, symfony/ldap, symfony/locale, symfony/monolog-bridge, symfony/options-resolver, symfony/process, symfony/property-access, symfony/property-info, symfony/proxy-manager-bridge, symfony/routing, symfony/security, symfony/security-bundle, symfony/security-core, symfony/security-csrf, symfony/security-guard, symfony/security-http, symfony/serializer, symfony/stopwatch, symfony/swiftmailer-bridge, symfony/templating, symfony/translation, symfony/twig-bridge, symfony/twig-bundle, symfony/validator, symfony/var-dumper, symfony/web-profiler-bundle, symfony/yaml

autoload
psr-4
Symfony\Bridge\Doctrine\ => src/Symfony/Bridge/Doctrine/
Symfony\Bridge\Monolog\ => src/Symfony/Bridge/Monolog/
Symfony\Bridge\ProxyManager\ => src/Symfony/Bridge/ProxyManager/
Symfony\Bridge\Swiftmailer\ => src/Symfony/Bridge/Swiftmailer/
Symfony\Bridge\Twig\ => src/Symfony/Bridge/Twig/
Symfony\Bundle\ => src/Symfony/Bundle/
Symfony\Component\ => src/Symfony/Component/
classmap
src/Symfony/Component/Intl/Resources/stubs
exclude-from-classmap

requires
doctrine/common ~2.4
php >=5.3.9
psr/log ~1.0
symfony/polyfill-intl-icu ~1.0
symfony/polyfill-mbstring ~1.0
symfony/polyfill-php54 ~1.0
symfony/polyfill-php55 ~1.0
symfony/polyfill-php56 ~1.0
symfony/polyfill-php70 ~1.0
symfony/polyfill-util ~1.0
symfony/security-acl ~2.7
twig/twig ~1.23|~2.0

requires (dev)
doctrine/data-fixtures 1.0.*
doctrine/dbal ~2.4
doctrine/doctrine-bundle ~1.2
doctrine/orm ~2.4,>=2.4.5
egulias/email-validator ~1.2
monolog/monolog ~1.11
ocramius/proxy-manager ~0.4|~1.0
phpdocumentor/reflection ^1.0.7

conflicts
phpdocumentor/reflection <1.0.7

replaces
symfony/asset self.version
symfony/browser-kit self.version
symfony/class-loader self.version
symfony/config self.version
symfony/console self.version
symfony/css-selector self.version
symfony/debug self.version
symfony/debug-bundle self.version
symfony/dependency-injection self.version
symfony/doctrine-bridge self.version
symfony/dom-crawler self.version
symfony/event-dispatcher self.version
symfony/expression-language self.version
symfony/filesystem self.version
symfony/finder self.version
symfony/form self.version
symfony/framework-bundle self.version
symfony/http-foundation self.version
symfony/http-kernel self.version
symfony/intl self.version
symfony/ldap self.version
symfony/locale self.version
symfony/monolog-bridge self.version
symfony/options-resolver self.version
symfony/process self.version
symfony/property-access self.version
symfony/property-info self.version
symfony/proxy-manager-bridge self.version
symfony/routing self.version
symfony/security self.version
symfony/security-bundle self.version
symfony/security-core self.version
symfony/security-csrf self.version
symfony/security-guard self.version
symfony/security-http self.version
symfony/serializer self.version
symfony/stopwatch self.version
symfony/swiftmailer-bridge self.version
symfony/templating self.version
symfony/translation self.version
symfony/twig-bridge self.version
symfony/twig-bundle self.version
symfony/validator self.version
symfony/var-dumper self.version
symfony/web-profiler-bundle self.version
symfony/yaml self.version
```

With command **php composer.phar show -i symfony/doctrine-bridge**
```
[InvalidArgumentException]                 
  Package symfony/doctrine-bridge not found
```

**Comment by xabbuh** [comment]
This looks weird to me. Can you debug locally why [this code](https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/DoctrineExtension.php#L358-L363) gets executed?

**Comment by CharlyPoppins** [comment]
I replace my DoctrineExtension.php by the one you linked but I've still the same exception.

**Comment by xabbuh** [comment]
Well, I meant that you try to figure out why that code is executed on your system thus triggering the error message (which should not happen with the version of the packages you have installed).

**Comment by Padam87** [comment]
The exception is not thrown from https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/DoctrineExtension.php#L358-L363.

`fixManagersAutoMappings` calls `validateAutoMapping`, which throws the exception at https://github.com/symfony/doctrine-bridge/blob/master/DependencyInjection/AbstractDoctrineExtension.php#L485
