### ISSUE TITLE
Repositories and inheritance

### ISSUE THREAD

**Issue by yonisolo** [doctrine/DoctrineBundle#609]
Hi there,
I've got a problem which seems to be a lack or a misunderstanding of the process.
I got a base entity (A) with minimal properties (id), i need to inherit this one (entity B) to fill more properties with single table inheritance.
If i call getRepository on B, even if i precise the B repository with annotations and not in A, I got the A default repository.
The A entity is in another bundle and may not contain the B business, it's purpose is to be overiden.

Question is: **How to specify a custom repository for entity B without specifying it on A**

I'm working with the latest version available on composer with PHP 7+ and Symfony 3.2

Thanks everyone

**Comment by kimhemsoe** [comment]
Hi

Take a look at http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annref-entity to see if that does not solve your problem.

If your problem persist and you believe it is a bug, you are welcome to post bug report at the [ORM](https://github.com/doctrine/doctrine2) repository explaining how to reproduce the bug.
