### ISSUE TITLE
doctrine:database:import does not print or report errors

### ISSUE THREAD

**Issue by dlancea** [doctrine/DoctrineBundle#621]
When using doctrine:database:import it does not report any errors that occurred when running a SQL file. It  instead returns OK! and the command terminates successfully. 

This is very misleading when the import fails silently.

Here's the example output of an import that actually generated errors:

```
[Exec] Running php app/console doctrine:database:import fixtures/schema.sql --env=test
Processing file '/var/lib/jenkins/workspace/blog/fixtures/schema.sql'... OK!
```

**Comment by stof** [comment]
this should be reported directly to the DBAL project. This bundle does not implement the command logic.

**Comment by mikeSimonson** [comment]
@dlancea Can you report it at ttps://github.com/doctrine/dbal/issues/new with maybe a failing test case ?
