### ISSUE TITLE
Runnable queries are wrong for boolean fields on Postgresql

### ISSUE THREAD

**Issue by stof** [doctrine/DoctrineBundle#627]
When replacing query parameters to produce a runnable query in the profiler, the ``doctrine_replace_query_parameters`` filter uses ``1`` and ``0`` for booleans. This is fine for MySQL (which does not support booleans and uses an integer to represent them), but it breaks on Postgresql (and any other DB uses actual booleans).

**Comment by jordscream** [comment]
hi @stof , hi you sure about this ? 
https://www.postgresql.org/docs/9.1/static/datatype-boolean.html 

For any version, you can write boolean true => 1 and false to 0

I tried and it breask anything to me in any version of postgresql

**Comment by ostrolucky** [comment]
@stof is correct http://sqlfiddle.com/#!17/21596/3 

I've created issue at https://github.com/doctrine/dbal/issues/3763, as this looks to be a DBAL problem.

**Comment by ostrolucky** [comment]
Actually I would like to keep this bug being tracked here as well, until DBAL issue is resolved (and confirmed its resolution helps us)

**Comment by stof** [comment]
this is **not** a DBAL problem. https://github.com/doctrine/DoctrineBundle/blob/85460b85edd8f61a16ad311e7ffc5d255d3c937c/Twig/DoctrineExtension.php#L261-L263 does not ask DBAL how to represent boolean values in SQL when replacing parameters.

**Comment by ostrolucky** [comment]
It is, as DBAL does not provide correct API for getting this information.

**Comment by stof** [comment]
`AbstractPlatform::convertBooleans` seems to be the API we need, actually.

**Comment by ostrolucky** [comment]
Yes, but it doesn't work. See referenced DBAL issue for more info.

**Comment by stof** [comment]
In the referenced DBAL issue, you try to use `BooleanType::convertToDatabaseValue` which uses `abstractPlatform::convertBooleansToDatabaseValue`, which is the API suited to perform the necessary conversion for parameter binding. This is **not** the API I suggest to use here when writing SQL rather than binding a parameter (PDO still expect numbers for boolean parameters even on Postgresql)

**Comment by ostrolucky** [comment]
Could you respond in a referenced issue? We are going offtopic here.

**Comment by ostrolucky** [comment]
If you think issue I created in DBAL is invalid, please respond there instead.

**Comment by ostrolucky** [comment]
So indeed on second look, this doesn't look like DBAL problem, but doctrine bridge problem. We never get booleans here actually, [doctrine bridge changes that to database value](https://github.com/symfony/symfony/blob/75323bd68d2c5800f66d44cd20db1daf879d4811/src/Symfony/Bridge/Doctrine/DataCollector/DoctrineDataCollector.php#L187) (`1`/`0`). Fix needs to go in doctrine bridge.
