### ISSUE TITLE
Remove the .class parameters

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#630]
I was inspecting the dependency injection container generated in production and, after MonologBundle removed the `.class` params in https://github.com/symfony/monolog-bundle/pull/170 and Symfony removed its last `.class` params in https://github.com/symfony/symfony/pull/21739, DoctrineBundle is the last one that creates these params.

Would a PR to remove these params be accepted? Thanks!

**Comment by mikeSimonson** [comment]
@stof Should this be targeted at at a V2 version ?

**Comment by javiereguiluz** [comment]
I'm closing this 2-year-old bundle because there doesn't seem to be much interest about this, which is fine because it's not a big deal anyway. Thanks!

**Comment by alcaeus** [comment]
Reopening - we will create a new 2.0 release in time for ORM 3 and hopefully Symfony 3, so this is still relevant.

**Comment by alcaeus** [comment]
While taking a look, this requires some work in `symfony/doctrine-bridge`, as it relies on the class parameters to configure the correct classes for the various bundles. I'll see if I can come up with a BC way to add this to Symfony 4.4.

**Comment by alcaeus** [comment]
Currently blocked by https://github.com/symfony/symfony/pull/33319.

**Comment by javiereguiluz** [comment]
Let's close as fixed since #949 and other PRs. Thanks.
