### ISSUE TITLE
Don't add the @Doctrine Twig namespace in production

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#631]
I was inspecting the production container of some app and I saw the following call in the Twig service:

```php
$instance->addPath(($this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Resources/views'), 
'Doctrine');
```

This is automatically created by Symfony, but as you can see in https://github.com/doctrine/DoctrineBundle/tree/master/Resources/views/Collector DoctrineBundle only has 2 templates and they are related to the profiler: `db.html.twig` and `explain.html.twig`.

So, should we remove that Twig namespace when the Doctrine profiler is not enabled? Thanks!

**Comment by mikeSimonson** [comment]
How are we supposed to do that ?

**Comment by javiereguiluz** [comment]
I don't know if it's possible to remove the Doctrine namespace in the DoctrineExtension.

**Comment by javiereguiluz** [comment]
In the Symfony repo, @stof [added a comment](https://github.com/symfony/symfony/issues/21758#issuecomment-282674845) explaining why this is not worth it. So let's close this issue as "won't fix".
