### ISSUE TITLE
Changed table collation does not trigger schema update when using doctrine:schema:update

### ISSUE THREAD

**Issue by podorozhny** [doctrine/DoctrineBundle#632]
Hello.

When I change table collation (using `@ORM\Table` annotation) - `doctrine:schema:update` do not update it. But if I do `doctrine:schema:drop` before update - it will update it.

**Comment by mikeSimonson** [comment]
This should be reported to the [Doctrine DBAL issue tracker](https://github.com/doctrine/dbal/issues).

Btw, when reporting it to DBAL, you should mention the platform you use. Generated queries for the schema changes are highly dependant on the platform.

Thanks for taking the time to report those issue.
