### ISSUE TITLE
Fix possible memory leak break unit tests improvement

### ISSUE THREAD

**Issue by LordWeedlle** [doctrine/DoctrineBundle#638]
A fix was made in https://github.com/doctrine/DoctrineBundle/commit/79bc1e440f8401cc87d33fad45d811ea4ccb8c5d to avoid possible memory leak as descibed in https://github.com/Behat/Symfony2Extension/issues/52.

In my company we used to recycle connections between tests using savepoints to improve unit tests time and avoid reloading database for each test. We first load all data in database and then only use savepoints so we can rollback on initial state before running next test.

Is there a way to specify if we want to close connections?
We could use parameters to check if connections and also entity managers need to be cleared:
```php
// Clear all entity managers to clear references to entities for GC
if ($this->container->hasParameter('doctrine.entity_managers') && !($this->container->hasParameter('doctrine.keep_entity_managers') && $this->container->getParameter('doctrine.keep_entity_managers') === true)) {
    foreach ($this->container->getParameter('doctrine.entity_managers') as $id) {
        if (!$this->container instanceof IntrospectableContainerInterface || $this->container->initialized($id)) {
            $this->container->get($id)->clear();
        }
    }
}

// Close all connections to avoid reaching too many connections in the process when booting again later (tests)
if ($this->container->hasParameter('doctrine.connections') && !($this->container->hasParameter('doctrine.keep_connections') && $this->container->getParameter('doctrine.keep_connections') === true)) {
    foreach ($this->container->getParameter('doctrine.connections') as $id) {
        if (!$this->container instanceof IntrospectableContainerInterface || $this->container->initialized($id)) {
            $this->container->get($id)->close();
        }
    }
}
```

**Comment by sandvige** [comment]
:+1:

**Comment by dmaicher** [comment]
@LordWeedlle I know this issue is quite old but maybe this bundle can help you: https://github.com/dmaicher/doctrine-test-bundle

**Comment by alcaeus** [comment]
I believe the bundle @dmaicher suggested is better suited to help with this. I believe cleaning up on shutdown is desired and should not be worked around in certain environments (e.g. tests). Closing here.

**Comment by LordWeedlle** [comment]
It seems this bundle can help me, I'll try it out!
