### ISSUE TITLE
How to config the app/config.yml to enable doctrine orm result cache using redis?

### ISSUE THREAD

**Issue by zjsxwc** [doctrine/DoctrineBundle#643]
hello,

the [page](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/caching.html#redis)  says that i could use redis to cache some result.

and this [page](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/second-level-cache.html) says how to config the instance.

now i want to find how to config the app/config.yml to enable doctrine cache using redis, but i am not real understand how to config after reading http://symfony.com/doc/current/bundles/DoctrineBundle/configuration.html.

is there some documents i could read to get the enough infomation about how to do?

**Comment by kimhemsoe** [comment]
You can use the doctrine cache bundle for creating the cache and then use the configured service id in the doctrine bundle config.

```yaml
doctrine:
    orm:
        result_cache_driver:
            id: 'doctrine_cache.providers.[name]'
```

http://symfony.com/doc/current/bundles/DoctrineCacheBundle/index.html
