### ISSUE TITLE
update changelog regularly

### ISSUE THREAD

**Issue by craigh** [doctrine/DoctrineBundle#644]
please update the changelog. It hasn't been modified since 1.5.2. This is the first place I look when investigating problems. It is easier than scanning commits...

**Comment by kimhemsoe** [comment]
We have been writing release in github for a while now. One could argue that we maybe should start writing them in the changelog again.

**Comment by Ocramius** [comment]
I'm currently writing an automation tool to do that, since I'm also really annoyed by the process (which is why merges/releases are also this slow - I simply can't find the time to do them). Hopefully that will also add entries to the changelog file.

Meanwhile, closing here.
