### ISSUE TITLE
Which tag is correct doctrine.entity_listener or doctrine.orm.entity_listener

### ISSUE THREAD

**Issue by mmucklo** [doctrine/DoctrineBundle#650]
When tagging service to be a listener your online docs on symfony.com say to tag it "doctrine.entity_listener".

However the code seems to search for doctrine.orm.entity_listener.

Which is correct?

DependencyInjection/Compiler/EntityListenerPass.php:
```php
        $resolvers = $container->findTaggedServiceIds('doctrine.orm.entity_listener');
```

**Comment by mmucklo** [comment]
So there seems to be two pieces of documentation on symfony.com:

http://symfony.com/doc/current/doctrine/event_listeners_subscribers.html
http://symfony.com/doc/current/bundles/DoctrineBundle/entity-listeners.html

Which one is the correct one to follow?

**Comment by stof** [comment]
There are 2 different tags:

- `doctrine.event_listener` (and its sibling `doctrine.event_subscriber`) to register an event listener in the EventManager
- `doctrine.orm.entity_listener` to register an EntityListener (which will be called only when the event concerns the entity for which it is attached).

Both tags are valid. They refer to different features (the EntityListener feature internally registers an event listener btw).

AFAIK, there is no documentation talking about `doctrine.entity_listener`. If there is one, it is a typo.

**Comment by kimhemsoe** [comment]
Closing this one in favor of https://github.com/doctrine/DoctrineBundle/issues/457
