### ISSUE TITLE
file_put_contents() failed to open stream: Invalid argument

### ISSUE THREAD

**Issue by luislaborda** [doctrine/DoctrineBundle#655]
I'm trying to generate entities from an existing schema in an Oracle database. When running the command: 

`php bin/console doctrine:mapping:import --force AppBundle xml`

I the the following error:

```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: file_put_contents(C:\www\SWWebApp\src\AppBundle/Entity/"user".php): failed to open stream: Invalid argument
```

Could it be that there is an issue with the path? I notice that up to AppBundle the path is using backslah \ then after AppBundle is using forward slash / 

I'm using windows. Am I missing something?

**Comment by Ocramius** [comment]
Do you actually have a table called `"user"` (with double quotes in the
name)?

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by luislaborda** [comment]
The thing is for oracle, user is a reserved word, so oracle uses CREATE TABLE "user"  with double quotes.

**Comment by Ocramius** [comment]
Yeah, you will have to manually create the entity there, since double
quotes aren't valid path characters on Windows (nor valid PHP class name
characters)
