### ISSUE TITLE
Symfony 3.3 - deprecation messages

### ISSUE THREAD

**Issue by mkalisz77** [doctrine/DoctrineBundle#665]
With Symfony 3.3 I have such depreciation message
Symfony\Component\HttpKernel\DependencyInjection\Extension::addClassesToCompile() is deprecated since version 3.3, to be removed in 4.0. 

from 3.3 changelog
 * The `Extension::addClassesToCompile()` and `Extension::getClassesToCompile()` methods have been deprecated and will be removed in 4.0.

**Comment by xabbuh** [comment]
You need to use DoctrineBundle 1.6.7 or higher.

**Comment by thomas2411** [comment]
I have 1.6.8 version and have the same issue.

**Comment by xabbuh** [comment]
Are you sure the deprecation message is triggered by DoctrineBundle and not, for example, AsseticBundle?

**Comment by qvolant** [comment]
I have the same error.

Disabled assetic, warning is gone. Re-enabled assetic, warning is back. It's safe to say that assetic is the culprit here.

**Comment by nmeirik** [comment]
For anyone else still experiencing this issue after upgrading both DoctrineBundle and AsseticBundle, JMSSecurityExtraBundle also appears to be prone to this issue, ref https://github.com/schmittjoh/JMSSecurityExtraBundle/issues/218 (no fix as of yet).

**Comment by MatrixOfDeath** [comment]
Same issue here on this this day, waiting for a fix.

**Comment by alcaeus** [comment]
@MatrixOfDeath you are aware that DoctrineBundle 1.6.7 and newer don't have this issue, right? You'll have to figure out which bundle is to blame and report the issue to them.
