### ISSUE TITLE
PHP 7.1 Nullable Types '?' not supported

### ISSUE THREAD

**Issue by Khalphion** [doctrine/DoctrineBundle#675]
The console command `doctrine:schema:update` leads to `PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE)` for entity methods containing optional parameters, e.g.

```
public function __construct(
        User $user,
        ?string $message = null,
        ?string $routeOnSuccess = null,
        ?string $routeOnFailure = null,
        ?\DateTime $mustSignUntil = null
    )
```

I'm using PHP 7.1, Symfony 3.2.9 and Doctrine Bundle ^1.6 (ORM ^2.5)

**Comment by Ocramius** [comment]
@Khalphion are you running the same version of PHP both in your dev and your deployment environment?

**Comment by Khalphion** [comment]
@Ocramius Thank you for bringing me onto the right path. Symfony was running on PHP 7.1 but not the console window. Sorry for any inconveniences!
