### ISSUE TITLE
Could not load type

### ISSUE THREAD

**Issue by allfreelancers** [doctrine/DoctrineBundle#682]
After register type as
```
types:
    UserRoleType: AF\Bundle\UserBundle\DBAL\Types\UserRoleType
```
I get exception:
Could not load type "UserRoleType"

**Comment by Ocramius** [comment]
@allfreelancers can you provide a full exception trace?

**Comment by allfreelancers** [comment]
@Ocramius 
```
Symfony\Component\Form\Exception\InvalidArgumentException:
Could not load type "ProjectStatusType"

  at vendor\symfony\symfony\src\Symfony\Component\Form\FormRegistry.php:87
  at Symfony\Component\Form\FormRegistry->getType('ProjectStatusType')
     (vendor\symfony\symfony\src\Symfony\Component\Form\FormFactory.php:74)
  at Symfony\Component\Form\FormFactory->createNamedBuilder('status', 'ProjectStatusType', null, array('required' => true))
     (vendor\javiereguiluz\easyadmin-bundle\Form\Type\EasyAdminFormType.php:91)
```
and ... But there is nothing interesting beyond that

**Comment by Ocramius** [comment]
That has nothing to do with this bundle: the form component obviously doesn't know what to do with a custom `UserRoleType`. It probably knows how to act on date/datetime/integer/string/etc out of the box, but nothing about custom types :-)

Closing as `invalid`.

**Comment by allfreelancers** [comment]
@Ocramius what did you mind?
