### ISSUE TITLE
CreateDatabaseDoctrineTest leaves the repo in a dirty state

### ISSUE THREAD

**Issue by stof** [doctrine/DoctrineBundle#686]
Running CreateDatabaseDoctrineTest creates files named `"shard_1"` and `"test"` at the root of the repo, leaving it in a dirty state. Running states should not create weird file in a non-ignored location.

**Comment by beberlei** [comment]
Fixed in https://github.com/doctrine/DoctrineBundle/commit/1aa2acd933720be3cf62e8c5b61497d22a8a2201
