### ISSUE TITLE
Auto-registration of commands deprecated since Symfony 3.4

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineBundle#693]
For example: `Auto-registration of the command "Doctrine\Bundle\DoctrineBundle\Command\Proxy\QueryRegionCacheDoctrineCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead`.
Same for other commands

**Comment by kimhemsoe** [comment]
We already have a ready a PR ready to be merged.

https://github.com/doctrine/DoctrineBundle/pull/684

**Comment by nicolas-grekas** [comment]
can be closed
