### ISSUE TITLE
The reverse engineering command requires existing entities

### ISSUE THREAD

**Issue by Kwadz** [doctrine/DoctrineBundle#694]
The [documentation][1] states that the first step is to create the metadata files:

> <img width="718" alt="screen shot 2017-09-16 at 12 55 10" src="https://user-images.githubusercontent.com/1472599/30511719-71bee4e6-9adf-11e7-98fc-2ec68db385bd.png">

This suggests we can start from scratch, without any existing entities in `AppBundle/Entity`. However with a fresh install of a symfony_demo project, created with `symfony demo`, when we execute the following command:

`php bin/console doctrine:mapping:import --force  AppBundle xml`

we get:

```
Fatal error: Symfony\Component\Debug\DebugClassLoader::loadClass(): Failed opening required 'xxx/symfony_demo/vendor/composer/../../src/AppBundle/Entity/Post.php' (include_path='.:') in xxx/symfony_demo/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php on line 144
```

[1]: https://symfony.com/doc/current/doctrine/reverse_engineering.html

**Comment by kimhemsoe** [comment]
I have no idea what is going here. I never use the the import (My experience is that it becomes very messy very fast, as import is trying to do an impossible task). Do you have some input to this? Is still an issue and etc?

**Comment by Kwadz** [comment]
I just tested with a fresh install of Symfony v3.3.9 with Symfony Installer version 1.5.9, I couldn't reproduce the issue...

**Comment by mickadoo** [comment]
@Kwadz I had the same error as you, but judging by the difficulty I had in finding anyone else I'd say it's pretty rare.

My issue was that I was _regenerating_ entities, and composer had a cache of the old entity files, which was what was causing the problem. I scoured the codebase for any reference to the file that couldn't be loaded, the following fixed it for me:

```
composer dump-autoloader
bin/console cache:clear
rm var/cache/dev/annotations.map
```

I'm pretty sure that after a few years it's not so relevant for you anymore, but maybe someone else will end up here with the same problem.
