### ISSUE TITLE
The doctrine:mapping:import command does not support bundle-less projects

### ISSUE THREAD

**Issue by mtnorthrop** [doctrine/DoctrineBundle#699]
It appears that Symfony 4 will be recommending bundle-less projects as a best practice, and will generate a bundle-less default project, but the `doctrine:mapping:import` command requires that a bundle name be passed as an argument.

Would it work to make this command _not_ require a bundle name?

**Comment by Ocramius** [comment]
@mtnorthrop it would be a BC break, and `mapping:import` is probably too generic

**Comment by mtnorthrop** [comment]
Ah, I see. 

If it would help, I can edit this issue to make it a feature request for a command that generates mapping data based on an existing database, but does not require a bundle (so that it's compatible with a bundle-less project). If not, I'll just delete this issue.

**Comment by Ocramius** [comment]
@mtnorthrop if you can propose something and it makes sense to @stof and @kimhemsoe, then it's alright

**Comment by mtnorthrop** [comment]
@Ocramius thanks for your time and your comments.

I'm very much just a Doctrine user, and don't feel confident enough about my knowledge of all of its inner workings to be able to propose a change that would actually be constructive, so I'll close this issue for now.

I posted it because I'm migrating an existing project to a bundle-less Symfony 3.3 environment and wanted to generate Doctrine entities from the database, as explained on http://symfony.com/doc/current/doctrine/reverse_engineering.html, but found it wasn't possible as I don't have an AppBundle. I imagine this might become a common problem once Symfony 4 is released since they're encouraging a bundle-less structure as a best practice.

I'm sorry I can't offer anything more constructive here, but thanks again to all of you for maintaining this bundle!

**Comment by danielnv18** [comment]
Even if you (@mtnorthrop)  don't feel confident enough that doesn't mean that this is not an issue

I would suggest 2 things
1. Just assume that that Symfony 3.4 and 4.0 will be bundle-less and now the default namespace is App inside src
2. Add an extra option like --path=PATH and in case you want to have a custom folder

**Comment by barell** [comment]
My suggestion in the pull request: #779 

Suggested something like:
`php bin/console doctrine:mapping:import --bundle-less src annotation`
