### ISSUE TITLE
This bundle should follow Symfony min requirements

### ISSUE THREAD

**Issue by fabpot** [doctrine/DoctrineBundle#704]
I can see that version 1.7 of this bundle already requires PHP 7.1, which is a bad idea IMHO as we are still supporting PHP 7.0 for Symfony Flex. Not having a DoctrineBundle compatible with PHP 7.0 and Symfony Flex means that many people won't be able to use Flex/Doctrine for a long time.

Moreover, reading #684, it is suggested to drop support for Symfony 2.7. Again, this is a bad idea IMHO as this is a Symfony LTS version.

I think that min requirements of this bundle should follow the one from Symfony as this is a Symfony bundle.

Can we reconsider these changes?

**Comment by Ocramius** [comment]
As mentioned in the other thread, only if maintenance is passed over: we
don't follow Symfony's versioning, we just have it as a dependency.

**Comment by fabpot** [comment]
see #705
