### ISSUE TITLE
Should slaves define the server_version option too?

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#711]
Related to https://github.com/symfony/symfony-docs/pull/8392 I wonder if we should allow slaves to configure the `server_version` option instead of throwing *Unrecognized option "server_version" under "doctrine.dbal.connections..."*.

Note: I've never used master/slave connections ... so this proposal may be absurd!

**Comment by mikeSimonson** [comment]
It has been removed. Thanks
