### ISSUE TITLE
[Question] Can I flush only one class of entities?

### ISSUE THREAD

**Issue by Jan0707** [doctrine/DoctrineBundle#716]
Hello everyone,

in my application I do write to a read model table (think CQRS) at certain times. While doing so, I also have to remove older read models. So at any given point I need to:

 1. Remove entities a,b,c
 2. Persist entities x,y,z

In order to maintain a valid read model throughout the lifecycle, I would like to encapsulate this process in a single transaction. [Doctrine does provide the necessary means][1].

However, I also must guarantee that no other entities are being flushed in the process. Sadly, calling doctrine's `$em->getConnection()->commit();` seems to to flush the whole unit of work. But according to the docs I have to call that to finalise my transaction.

I cannot introduce a second entity manager to only take of my read model entities as they are in the same namespace as the other entities and apparently that is not the way the doctrine-orm-bundle is supposed to be used.

The only other approach I see is to work on a lower level and circumvent the EntityManager and UnitOfWork completely, but I would like to guarantee transactional integrity and do not see a way to do so without em/ouw.

Any help would be kindly appreciated !

  [1]: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/transactions-and-concurrency.html

**Comment by dmaicher** [comment]
This issue seems not related to the DoctrineBundle but simply to Doctrine itself?

**Comment by alcaeus** [comment]
Yes, it is related to Doctrine ORM, not the bundle. However, only flushing selected entities through `flush` is not something you should do without understanding the consequences: for example, all new entities are written to the database, but only the entity/entities you have provided will be updated. This unpredictable behavior is the reason why flushing selected entities will be removed in ORM 3.0.

If you want to control what entities are flushed to the database, read about change tracking policies in the documentation: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/change-tracking-policies.html
