### ISSUE TITLE
bin/console doctrine:schema:update --force -e prod does not work in 1.6.13 tag

### ISSUE THREAD

**Issue by N-M** [doctrine/DoctrineBundle#718]
`bin/console doctrine:schema:update --force -e prod` does not work in 1.6.13
In 1.6.12 is fine

![screen shot 2017-10-17 at 1 13 40 pm](https://user-images.githubusercontent.com/781417/31661990-0543cedc-b33d-11e7-9761-35d401d64753.png)

**Comment by stof** [comment]
which version of Symfony are you using ?

**Comment by N-M** [comment]
Symfony 3.3.6

**Comment by kimhemsoe** [comment]
is this still an issue?

**Comment by Tobion** [comment]
Seems like we can close this.
