### ISSUE TITLE
Show trace for database queries

### ISSUE THREAD

**Issue by aik099** [doctrine/DoctrineBundle#722]
When viewing query in debug toolbar it would be useful to see what code actually caused the query to be executed.

Here is how I see this implemented:

1. when query is recorded by Web Profiler do a `debug_backtrace` and remove all entries coming from Doctrine itself to find only entries that user code (or it's dependency library) made
2. in the query list show 1st entry (the line that made Doctrine call) with a link to opening it in the ide
3. add link that via AJAX call would show full stack trace (as done with explain now)

I saw similar functionality in Laravel DebugBar and thought that it can be helpful in here as well.

**Comment by ostrolucky** [comment]
https://github.com/doctrine/dbal/pull/535
https://github.com/doctrine/dbal/pull/719

**Comment by kimhemsoe** [comment]
Closing as "wont fix" Take a look the linked PRs and take it from there. Maybe someday if dbal get support for it.

**Comment by ostrolucky** [comment]
Implemented in https://github.com/doctrine/DoctrineBundle/pull/954
