### ISSUE TITLE
Failure to extend doctrine command UpdateSchemaDoctrineCommand

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#728]
Moved from https://github.com/symfony/symfony/issues/24787 created by @tuxgasy

-----

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Hi,

To ignore some entities when running doctrine:schema:update, I extends UpdateSchemaDoctrineCommand like that :

```php
<?php

namespace AppBundle\Command;

use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Doctrine\ORM\Tools\SchemaTool;

class DoctrineUpdateCommand extends \Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand
{
	protected $ignoredEntities = array(
		'AppBundle\Entity\Test',
	);

	protected function executeSchemaCommand(InputInterface $input, OutputInterface $output, SchemaTool $schemaTool, array $metadatas)
	{
    $newMetadatas = array();
    foreach($metadatas as $metadata){
      if(!in_array($metadata->getName(), $this->ignoredEntities)){
        array_push($newMetadatas, $metadata);
      }
    }

    parent::executeSchemaCommand($input, $output, $schemaTool, $newMetadatas);
  }
}
```

When I update dependencies with composer, it does not work anymore. I tried with a new installation, it work but not after update.

Sorry for my very bad english! Thank you all!

**Comment by PashaKoval** [comment]
@javiereguiluz, I had the same issue, I think this is some bug in new doctrine version. To fix it you can downgrade to 1.6.7 version of doctrine bundle (for sure hardcode "doctrine/doctrine-bundle": "1.6.7" in your composer.json and run composer update).

**Comment by tuxgasy** [comment]
@PashaKoval Thank for this temporary fix.

**Comment by alcaeus** [comment]
@tuxgasy @PashaKoval "failure to extend" is a rather broad error - could you elaborate as to what's breaking? Also, what version is this? 1.6.8 or 1.7.0?

**Comment by tuxgasy** [comment]
@alcaeus As you can see on the example, when you run the command `php bin/console doctrine:schema:update --dump-sql`, the method executeSchemaCommand is ignored.
No bug in 1.6.8. I can't test 1.7.0 because it's need php 7.1. I will test it later if necessary.

**Comment by alcaeus** [comment]
How did you configure your command? Did you confirm that your command is getting executed or is it the original command from the bundle that is run?

**Comment by stof** [comment]
@javiereguiluz in the latest version, commands are registered as services (to be compatible with Symfony 4). Maybe the priority of commands is different when using services and the service one wins over your own convention-based registration (this is just a wild guess, I haven't tried to confirm it).
If this is the case, the solution would be simple: using a command as service too instead of using a convention-based registration.

**Comment by tuxgasy** [comment]
What should I configure? Should I register my command as service? How to do?

**Comment by tuxgasy** [comment]
Nobody can help me or give me a link to a documentation about that?
Thank!

**Comment by mikeSimonson** [comment]
https://symfony.com/doc/current/console/commands_as_services.html

**Comment by geniuspegasus** [comment]
this is the solution:  

`<?php
namespace present\UserBundle\Command;


class DoctrineUpdateCommand extends \Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand {

  protected $ignoredEntities = array(
      'present\UserBundle\Entity\Bl','present\UserBundle\Entity\Cheque','present\UserBundle\Entity\Client','present\UserBundle\Entity\Colis','present\UserBundle\Entity\Colis','present\UserBundle\Entity\Escale',
      'present\UserBundle\Entity\Factures','present\UserBundle\Entity\March','present\UserBundle\Entity\Navire','present\UserBundle\Entity\Payement','present\UserBundle\Entity\Port','present\UserBundle\Entity\Trafic',
      'present\UserBundle\Entity\prestation',
      'present\UserBundle\Entity\CarteAcces'
  );

  protected function executeSchemaCommand(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output, \Doctrine\ORM\Tools\SchemaTool $schemaTool, array $metadatas, \Symfony\Component\Console\Style\SymfonyStyle $ui)
	{
    $newMetadatas = array();
    foreach($metadatas as $metadata){
      if(!in_array($metadata->getName(), $this->ignoredEntities)){
        array_push($newMetadatas, $metadata);
      }
    }


    parent::executeSchemaCommand($input, $output, $schemaTool, $newMetadatas,$ui);
  }

}`

**Comment by najd-mrabet** [comment]
update code : 

```
<?php
namespace App\Command;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand;
use Symfony\Component\Console\Style\SymfonyStyle;
use Doctrine\ORM\Tools\SchemaTool;
use App\Entity\VueTechnomap;


class DoctrineUpdateCommand extends UpdateSchemaDoctrineCommand {

  protected $ignoredEntities = [
      VueTechnomap::class
  ];

  protected function executeSchemaCommand(InputInterface $input, OutputInterface $output, SchemaTool $schemaTool, array $metadatas, SymfonyStyle $ui)
	{
        $newMetadatas = [];
        foreach($metadatas as $metadata){
          if(!in_array($metadata->getName(), $this->ignoredEntities)){
              array_push($newMetadatas, $metadata);
          }
        }

        return parent::executeSchemaCommand($input, $output, $schemaTool, $newMetadatas,$ui);
  }

}
```
