### ISSUE TITLE
WebProfilerExtension dumpData() array given Type error.

### ISSUE THREAD

**Issue by gogus** [doctrine/DoctrineBundle#730]
Hey,

I have problem with Doctrine profiling on MySQL database.
`Type error: Argument 2 passed to Symfony\Bundle\WebProfilerBundle\Twig\WebProfilerExtension::dumpData() must be an instance of Symfony\Component\VarDumper\Cloner\Data, array given`

This is coming from:
`vendor/doctrine/doctrine-bundle/Resources/views/Collector/db.html.twig:241`

I changed the profiler_dump to dump and it contains array with my query params:
Example:
`array(1) { [0]=> string(36) "bc54bece-c234-11e7-85e6-0242ac140003" }`

I am using: symfony/orm-pack ^1.0 with symfony 4.0 beta-2.

**Comment by ostrolucky** [comment]
same here

**Comment by ostrolucky** [comment]
same here
