### ISSUE TITLE
Symfony 2.7 : v1.6 or v1.8?

### ISSUE THREAD

**Issue by sdespont** [doctrine/DoctrineBundle#734]
Hey, quick question : 

With a Symfony 2.7 in production using PHP 7.0, should I use this bundle in version 1.6.X or the new one 1.8.X released 3 days ago?

Changelog.md is not very up to date, so it is not easy to select a version to use .

Thanks

**Comment by timwsuqld** [comment]
:+1: for updating the changelog

**Comment by alcaeus** [comment]
I'll try to document the changes. @fabpot can you please update the changelog when you release new features? Thanks!

**Comment by alcaeus** [comment]
To answer the original question:

> With a Symfony 2.7 in production using PHP 7.0, should I use this bundle in version 1.6.X or the new one 1.8.X released 3 days ago?

You should always use the latest stable release. We're not backporting bugfixes to 1.7 or 1.6 anymore.

**Comment by sdespont** [comment]
@alcaeus thanks for your comment. I understand that, but the "latest release" tagged in the release view is the v1.7.0 which requires PHP 7.1 and not one of eight following releases. 

You should remove the "latest release" tag of the 1.7.0 version,, it is a bit confusing.

**Comment by alcaeus** [comment]
> You should remove the "latest release" tag of the 1.7.0 version

Can't - this is GitHub. The last releases were only pushed as tags without creating a GitHub releas object. This is a combination of GitHub putting up misleading badges and us not having a well-defined release process (and by far not enough maintainers). I'll get to it later this week or next week.
