### ISSUE TITLE
Symfony 4 doctrine:mapping:import missing bundle

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#736]
Reported originally by @pedroresende in https://github.com/symfony/symfony/issues/25013

-----

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0-beta4

If I ty to run the command

```
php bin/console doctrine:mapping:import
```

I receive the following message 

```
Not enough arguments (missing: "bundle").
```

However in Symfony 4 there is no bundle.

**Comment by weaverryan** [comment]
This is complex, because the Doctrine guys want to actually remove these commands. Still, if it’s an easy fix to point to a directory instead of a bundle, I think we should do that.

**Comment by weaverryan** [comment]
Note: when this is fixed, the Symfony docs need to be updated. I'm currently adding a warning about this in https://symfony.com/doc/master/doctrine/reverse_engineering.html

**Comment by pedroresende** [comment]
@weaverryan Thanks, any idea when will this be fixed ? I'm asking this, since Symfony 4 will be released next week

**Comment by weaverryan** [comment]
@pedroresende Not sure - we're running around updating many little things in bundles from the community. I'm also not sure how complex this will be to fix. It's very possible the workaround will be required when 4.0 comes out.

**Comment by weaverryan** [comment]
It's kind of on my list? But there are so many more important things. So, if someone else can try a patch, it will happen faster :)

**Comment by Gemorroj** [comment]
sse https://github.com/doctrine/DoctrineBundle/issues/729#issuecomment-348858634

**Comment by barell** [comment]
My suggestion in the pull request: #779 

Suggested something like:
`php bin/console doctrine:mapping:import --bundle-less src annotation`

**Comment by weaverryan** [comment]
I've continued @barell's nice work at #791
