### ISSUE TITLE
Symfony 4  doctrine:generate:entities psr-4

### ISSUE THREAD

**Issue by psfpro** [doctrine/DoctrineBundle#739]
*doctrine:generate:entities* doesn't work with psr-4
I want to create entities from yml annotation.

**Comment by alcaeus** [comment]
#729. Please search before opening issues. Thanks.

**Comment by nicodmf** [comment]
as i see, no good answer on this thread

**Comment by Majkl578** [comment]
@nicodmf Answer is in the thread referenced above: Entity generator is deprecated and will be removed in ORM 3.0, thus not receiving further features.

**Comment by nicodmf** [comment]
@Majkl578 unfortunnally it is that i saw

**Comment by AndranikHovhannisyan** [comment]
I find that now we can generate getter, setter and repository with "php bin/console make:entity --regenerate" command
https://symfony.com/doc/current/doctrine.html#doctrine-generating-getters-and-setters
