### ISSUE TITLE
Aggregation framework: get related object

### ISSUE THREAD

**Issue by NikitaKharkov** [doctrine/DoctrineBundle#741]
At first my code and examples of data:

```
event: {
    "_id" : 3,
    "name": "someTestName",
    ...,
    "seoBlock" : {
        "$ref" : "event_seo_block",
        "$id" : 1004
    }
}
```

```
event_seo_block: {
    "_id": '1004',
    "text": "someText",
    "image": "http://lorempixel.com/640/480/?34447"
}
```

Fetch code:
```
$builder =  $this->getDocumentManager()->getDocumentCollection('AppBundle:Event')->createAggregationBuilder();
$builder
            ->match()
                ->field('status')->equals(Event::STATUS_ONLINE)
                ->field('leadingTradeFair')->equals(true)
                ->field('eventTo')->gte($this->getStartOfToday())
                ->field('seoBlock.$id')->in($validSeoBlocksIds)
            ->lookup('event_seo_block')
                ->localField('seoBlock.$id')
                ->foreignField('_id')
                ->alias('seoBlock')
            ->group()
                ->field('_id')->expression('$fairId')
                ->field('events')->push('$$ROOT')
            ->project()
                ->excludeIdField()
                ->field('seo')->expression('$events.seoBlock')
                ->field('events')->expression('$events')
                ->field('order')->add(null, null)
            ->sort('events.fairId', 1)
```

Explanation of problem:

I have `event` table with relation `event_seo_block` table as 1:1 . So when I made all the operations I have to get all info from related object, but I can't do it, because I can't point in expression `seoBlock.$id` (`->localField('seoBlock.$id')` string in code), I have an error:  

`FieldPath field names may not start with '$'.`

I read about this problem, here I found about problem: [jira.mongodb.org](https://jira.mongodb.org/browse/SERVER-14466). But ODM don't support objectToArray and I can't solve problem in this way. Other links says the same.

What you do advise to do? Thanks

**Comment by alcaeus** [comment]
Wrong Doctrine bundle: this is the ORM, not MongoDB ODM. As for what to do, you're out of luck: MongoDB does not support their own DBRef objects in references. As for support for `$objectToArray`, this will be added after we're done moving to `ext-mongodb` in MongoDB ODM 2.0.

If you have any further questions, please open an issue at https://github.com/doctrine/mongodb-odm/issues.

**Comment by NikitaKharkov** [comment]
Thanks very much and I'm sorry for wrong section of question!
