### ISSUE TITLE
PHP 7.2 not supported

### ISSUE THREAD

**Issue by fmonts** [doctrine/DoctrineBundle#744]
PHP 7.2 doesn't seem to work, I get

> (4/4) DBALException
> An exception occured while establishing a connection to figure out your platform version.
> You can circumvent this by setting a 'server_version' configuration value

I just upgraded to the latest versions:
  - Updating doctrine/dbal (v2.6.2 => v2.6.3): Downloading (100%)
  - Updating doctrine/orm (v2.5.12 => v2.5.13):  Checking out 93103f44a3
  - Updating doctrine/doctrine-bundle (1.7.2 => 1.8.1): Downloading (100%)

**Comment by mikeSimonson** [comment]
In the new version of the doctrine bundle you have to secify the server_version in your symfony config.
