### ISSUE TITLE
cannot create database if connection url without password

### ISSUE THREAD

**Issue by TangMonk** [doctrine/DoctrineBundle#746]
I am using Symfony 4, and the `.env` file is bellow:

```
DATABASE_URL=mysql://tangmonk:@127.0.0.1:3306/testd
```
after execute `doctrine:database:create` command, it throw errors:
```
$ bin/console doctrine:database:create
Could not create database `testd` for connection named default
An exception occurred while executing 'CREATE DATABASE `testd`':

SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user ''@'localhost' to database 'testd'
```

**Comment by mikeSimonson** [comment]
This is not a doctrine error but a mysql one. It tells you that the user tangmonk can't access the testd database with a tcp connection from localhost.
It's either the password that is wrong or that user that can't connect from localhost at all.

try using ```mysql -u tangmonk -p testd -h localhost```

**Comment by TangMonk** [comment]
My local mysql instance did not have password for convenient , so I am use `mysql` command without specify user name and password to connect:

```
$ tangmonk@macbook (master)  > mysql

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 36
Server version: 5.6.25 Homebrew

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

So I am trying to do not specify password in database connection url, like above, but failed, I can connect the mysql without password using Rails framework, but Symfony4 cannot.

**Comment by baris1892** [comment]
I did this in my `.env` file:

```
DB_USER=root
DB_PASSWORD=
DB_HOST=localhost
DB_PORT=3307
DB_NAME=symfony4-api-fosrest
DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
```

Just change `DB_USER` to `tangmonk` or what you need. It works for me using Symfony 4.

**Comment by TangMonk** [comment]
thanks

**Comment by erethilclaw** [comment]
Hi, I'm using Symfony 4, i have configured .env file for my machine, but when i try to create the database nothing happens, no error message, it just stares there.

**Comment by Lisa90210** [comment]
Thanks baris1892! It's work
