### ISSUE TITLE
doctrine:generate:entity command doesn't work with naming_strategy configuration

### ISSUE THREAD

**Issue by bilel-noomene** [doctrine/DoctrineBundle#752]
I have this configuration for naming_strategy in config.yml file:
```
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
```
But when generating the entity, columns names are generated with lowerCamelCase strategy. 
```
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="publishedAt", type="date")
     */
    private $publishedAt;
```
I'm working with version 1.8.1.

**Comment by Ocramius** [comment]
This won't be enhanced nor worked on, as the entity generator is deprecated and removed in 3.x, while closed for improvement in 2.x.
