### ISSUE TITLE
Please make private $em property in SQLFilter class protected/pubic

### ISSUE THREAD

**Issue by yubinchen18** [doctrine/DoctrineBundle#753]
For my current client I need to make a global doctrine filter extending the SQLFilter class. Inside the addFilterConstraint() method I need to build custom logic to determine whether or not a certain clause should be added to the query. This check involves checking a setting stored in the database and for that I need the EntityManagerInterface $em, which is injected in the SQLFilter class' constructor.

But why does it HAVE to be private? And why is the constructor 'final'? This way I can't access it in the child filter class and can't override the constructor. Can this be changed?

Kind regards,
Big fan

**Comment by mikeSimonson** [comment]
This is private because when you use the SQLFilter class, you don't need to know how it works internally.
If you need the entity manager for you filter in your functionality, you can get it from the container.

Cheers

**Comment by yubinchen18** [comment]
Thanks for reply!

I sure will try, but maybe due to my limited knowledge and experience, I don't know how can I inject the container if i can't make my own __construct in this child class? Thanks in advance!

**Comment by yubinchen18** [comment]
Thanks for reply!
I'm still quite unexperienced with Symfony and Doctrine bundle. So how can I inject/autowire the container into my custom filter class if I can't make my own __construct() there? I even tried to inject to a setterMethod but it doesn't seem to work as the addFilterConstraint() is called before it.

**Comment by naitsirch** [comment]
Same question here @mikeSimonson
