### ISSUE TITLE
doctrine:schema:update --dump-sql as default ?

### ISSUE THREAD

**Issue by gregoirepaqueron** [doctrine/DoctrineBundle#754]
Hello,

I have a question : Why the option `--dump-sql` of command `doctrine:schema:update` is not the default behaviour when we precise no option ?

I don't find problems if it would be the case, currently, using the command without option is useless. 
The sentence "The Schema-Tool would execute "19" queries to update the database." could be printed after all the SQL queries.

**Comment by mikeSimonson** [comment]
A command that by default drowns your screen under queries is arguably not very useful either.

And if we do that then we need to add a --no-sql-dump option.

I don't see the added value in usability or user friendliness.

Maybe we should add a message after the number of queries that would execute that warn the user about the --dump-sql option.

**Comment by Ocramius** [comment]
Closing here - not to be fixed.
