### ISSUE TITLE
[Profiler] Explain is broken

### ISSUE THREAD

**Issue by ssaki** [doctrine/DoctrineBundle#757]
Hitting the "Explain query" link in the Doctrine's profiler screen reports "An error occurred while loading the query explanation." with request to profiler controller reporting 500 status.

It's caused by `vendor/doctrine/doctrine-bundle/Controller/ProfilerController.php:102`
```php
    private function explainOtherPlatform(Connection $connection, $query)
    {
        return $connection->executeQuery('EXPLAIN '.$query['sql'], $query['params'], $query['types'])
            ->fetchAll(\PDO::FETCH_ASSOC);
    }
```

The second parameter of `executeQuery()` must be an array while `$query['params']` is an instance of `Symfony\Component\VarDumper\Cloner\Data`.

**Comment by PaddyLock** [comment]
I'm also experiencing this issue. I have Symfony 4.1.4 with Flex.
