### ISSUE TITLE
Data encryption

### ISSUE THREAD

**Issue by kironet** [doctrine/DoctrineBundle#762]
Hey,

Is there a way to encrypt table or database in doctrine? 
GDPR is almost here and I think I should encrypt customers sensitive data.

Thanks

**Comment by Ocramius** [comment]
Encrypting can be done at FS level. You are required to delete non-vital user-sensitive data: not cheating and retaining it ;-)

**Comment by Ocramius** [comment]
To answer the original question: https://github.com/carnage/doctrine-encrypted-column

**Comment by kironet** [comment]
@Ocramius it says the data should be encrypted and I'm not planning to cheat and retain it :) But thanks for link

**Comment by Ocramius** [comment]
Data is encrypted if your FS is luks-protected.
