### ISSUE TITLE
No options for cascading delete/remove between 2 entities with discriminators work

### ISSUE THREAD

**Issue by silverbackdan** [doctrine/DoctrineBundle#773]
I've got 2 entities with discriminator mapping. Between the two I have Many-to-One and One-to-Many relations (parent and children).

There seems to be an issue with the One-to-Many relation from the parent to the children. I get all the children when getting the parent until I add a getter function to the abstract class that has the discriminator mapping. I thought it may be related to type hinting, but I removed all type hints and I get the same issue still.

I'm also using API Platform which I know does a little tinkering with doctrine but from what I can see, I don't think it's doing anything at this level.

It's also a problem if I delete the parent, the children are not deleted (although it seems that in the preFlush event listener, if I check the children the collection is empty again).

Is this expected and do I have to add mapping to every individual entity? If so, are there any docs to see if this is possible to be done during dependency injection (it's in a re-usable bundle)

Thank you.

**Comment by mikeSimonson** [comment]
Can you report this on the https://github.com/doctrine/doctrine2 repo ?

This issue is not related to the doctrineBundle.

Thanks

**Comment by silverbackdan** [comment]
Sure, thank you.
