### ISSUE TITLE
Doctrine Entity / Repository class generation for Bundle-FUL projects

### ISSUE THREAD

**Issue by wucdbm** [doctrine/DoctrineBundle#786]
Are there any plans for re-introducing this feature and unlike the ongoing trend, making it compatible with projects that STILL use bundles in src/

Furthermore, with the improvements to the Symfony container, the repository generation could generate something like

```
<?php

namespace App\Core\Repository;

use App\Core\Entity\SomeEntity;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

class SomeEntityRepository extends ServiceEntityRepository {

    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, SomeEntity::class);
    }

}
```

Which is basically the class created and ready for use where you can add your own methods. This would save some time typing all of that which is tedious and simply redundant

As for the getters / setters, I believe it could also be improved to generate proper doc blocks and possibly return types (I guess we need to be cautious here)

EDIT: Symfony Maker or a 3rd-party bundle is also fine, since generation is not really something the Doctrine project is keen on supporting.

Please share your thoughts

**Comment by Ocramius** [comment]
Hello,

The doctrine entity generator is deprecated and will no longer be improved, so I'm closing this as `won't fix`.

See also https://github.com/doctrine/DoctrineBundle/issues/739 and https://github.com/doctrine/DoctrineBundle/issues/729
