### ISSUE TITLE
Symfony 3.4 deprecations warnings

### ISSUE THREAD

**Issue by gnutix** [doctrine/DoctrineBundle#799]
I'm upgrading a Symfony project from 2.3 to 3.4 (that uses Sonata Admin) and receive the following deprecation warning from the PHPUnit bridge when running the application's tests : `The "form.type.entity" service is private, getting it from the container is deprecated`.

I've searched for `form.type.entity` in the project and the only two occurrences are the service definition in `orm.xml` and this : https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/DoctrineExtension.php#L327

Is it the culprit ? Should the service be made public or this line done differently ?

I also have warnings about : 

* `The "form.type_guesser.doctrine" service is private, getting it from the container is deprecated`
* `The "form.type_guesser.doctrine" service is private, checking for its existence is deprecated`

But I can't find any usage for it (only the `form.type_guesser.doctrine.class` parameter and the `form.type_guesser.doctrine` service definition in `orm.xml`)... So I guess the deprecation is caused by code in Symfony itself (related to the `form.type_guesser` tag). Again, should the service be public ?

**Comment by kimhemsoe** [comment]
Do you have a trace where these deprecation notices is coming from?

Could it be Sonata Admin that is trying to use these services?

**Comment by weaverryan** [comment]
Yea, the usages in this bundle look ok to me also.

**Comment by gnutix** [comment]
I found the issue and fixed it with : 

```
sonata_core:
    form:
        mapping:
            enabled: false
```

So indeed, it was related to Sonata Admin in the end. Sorry! :bowing_man:
