### ISSUE TITLE
Stack trace of query

### ISSUE THREAD

**Issue by peter-gribanov** [doctrine/DoctrineBundle#800]
Is it possible to add a stack trace to the profiler to at least roughly understand the context of the query?

Sometimes, in the profiler there are querys that are not quite clear where they [came from](https://github.com/doctrine/doctrine2/issues/7175).
Sometimes, in the profiler there are querys that are obviously cached in repository, but they don't cached anyway.

In such cases, i want to understand where this query came from.

**Comment by kimhemsoe** [comment]
dup of https://github.com/doctrine/DoctrineBundle/issues/722

I understand where you come from. Overall the profiling could be improved like caching. I think the way to go is to improve one feature at the time and map out what require better hooks into dbal and what does not.

**Comment by kimhemsoe** [comment]
I suggest you start by looking at the previous issues and pull requests and continue to dbal. I believe that is where the implementation should begin. When dbal have support we can add it here.

**Comment by Ocramius** [comment]
DBAL already has a DebugStack logger doing this

**Comment by kimhemsoe** [comment]
well then it just need to be integrated :D go go @peter-gribanov

**Comment by peter-gribanov** [comment]
@kimhemsoe :laughing:
