### ISSUE TITLE
[Question] Where is ManagerRegistry in 1.9.0 version?

### ISSUE THREAD

**Issue by lloonnyyaa** [doctrine/DoctrineBundle#803]
In my project, I use a service (https://github.com/lloonnyyaa/reviews/blob/master/src/Form/Type/EntityHiddenType.php) that depends on ManagerRegistry (Doctrine\Common\Persistence\ManagerRegistry)

After the upgrade doctrine/doctrine-bundle to version 1.9.0 there was an errors:
![screen shot 2018-04-19 at 12 02 51 pm](https://user-images.githubusercontent.com/25372355/38982749-5b19d774-43cb-11e8-8192-9a986184c16c.png)
![screen shot 2018-04-19 at 12 03 10 pm](https://user-images.githubusercontent.com/25372355/38982757-63f6bb0a-43cb-11e8-87b2-b38c58fdcc06.png)

In the config doctrine/doctrine-bundle/Resources/config/dbal.xml I saw that this service is not declared, whereas in version 1.8.1 it was declared: `<service id="Doctrine\Common\Persistence\ManagerRegistry" alias="doctrine" public="false" /> `

Tell me please, will this interface no longer be used?

**Comment by jvasseur** [comment]
https://github.com/doctrine/DoctrineBundle/releases/tag/1.9.0
> Removal of ManagerRegistry and ObjectManager as autowirable aliases. Use RegistryInterface or EntityManagerInterface instead

**Comment by lloonnyyaa** [comment]
Thanks, sorry, I missed the release documentation

**Comment by iltar** [comment]
For the sake of BC, this should have been 2.0.0 according to Semver, it now broke my build + update.

**Comment by Ocramius** [comment]
This likely needs a revert and to be pushed to the next major

**Comment by iltar** [comment]
Can the alias remain though?

**Comment by alcaeus** [comment]
I've explained the reason for the change in the original pull request: #740. Long story short, #640 (which became part of 1.6.8 and should've been 1.7.0) introduced some aliases that are incorrectly taken by this bundle: we have multiple implementations for the interfaces defined in `Doctrine\Common`, and none of the Doctrine integrations should assume ownership of those interfaces, as there will inevitably be conflicts when multiple implementations of those interfaces exist (as happens when people combine ORM and MongoDB ODM for example). Thus, the decision was made to remove those interfaces, as they were added in error.

People should not typehint stuff from `Doctrine\Common` when they expect ORM implementations. If they want to do so, they should create the necessary aliases themselves to avoid the conflict mentioned above. As bad as the BC break may sound, the original change should never have been introduced.

**Comment by weaverryan** [comment]
Yea, for sure, these aliases shouldn't have been added.

But, this was a BC break, though, a BC break that (at least) hits you at container "compile time", so it's unavoidable and obvious.

However, I would be fine with a revert and a push to the next major. Unfortunately, it's not possible yet to deprecate aliases, but hopefully we will have that in Symfony 4.2 (and then would could add deprecations to this bundle if the user has this version).

So, revert or leave?

**Comment by alcaeus** [comment]
IMO it would be ok to revert it, but how do we prepare people for the break? We can't mark aliases as deprecated, so people will still hit the error when upgrading to the next major. One further question is the release date of the new major version - there's no point doing this if we're not releasing a new major in the near future IMO.

**Comment by kimhemsoe** [comment]
When we revert i will push for a 2.0 very fast with this change and removal of ".class" parameters. Anything else people want removed?

**Comment by alcaeus** [comment]
We've had the PHP version requirement discussion - maybe a new major version release would be a good opportunity to drop old versions, maybe with a longer support window for 1.9?

**Comment by weaverryan** [comment]
See #805 for the revert.

@kimhemsoe removing the class params for 2.0 is a good idea. We may be able to find a few other things, and hopefully deprecate them when possible :).

**Comment by alcaeus** [comment]
Thanks Ryan!

**Comment by mikeSimonson** [comment]
fixed in #805 and pushed in 1.9.1

**Comment by natewiebe13** [comment]
This appears to still be an issue while upgrading to Symfony 4.4. Was the fix for this reverted in a later version?

**Comment by greg0ire** [comment]
@natewiebe13 what version of the doctrine bundle are you using?

**Comment by natewiebe13** [comment]
@greg0ire 2.0.0

**Comment by natewiebe13** [comment]
@greg0ire Looking with fresh eyes, my issue wasn't with using `Doctrine\Common\Persistence\ObjectManager` in the `load()` function, since that's what's specified in the interface, but with autowiring the ObjectManager in the constructor of the fixture class. This can be ignored.

**Comment by maxhelias** [comment]
@natewiebe13, The `ObjectManager` is no longer autowiring to doctrine service since 2.0. Please read the upgrade 2.0 and adjust your code
