### ISSUE TITLE
[BUG] Symfony 4 (flex) not found service

### ISSUE THREAD

**Issue by piotrantosik** [doctrine/DoctrineBundle#804]
> The DoctrineBundle is not registered in your application. Try running "composer require symfony/orm-pack".

After update bundle to 1.9
But in cli command:
```php
bin/console debug:container doctrine

Information for Service "doctrine"
==================================

 ---------------- ----------------------------------------- 
  Option           Value                                    
 ---------------- ----------------------------------------- 
  Service ID       doctrine                                 
  Class            Doctrine\Bundle\DoctrineBundle\Registry  
  Tags             -                                        
  Public           yes                                      
  Synthetic        no                                       
  Lazy             no                                       
  Shared           yes                                      
  Abstract         no                                       
  Autowired        no                                       
  Autoconfigured   no                                       

```

**Comment by weaverryan** [comment]
Hey @piotrantosik!

Hmm, interesting. Unless there is somewhere else with an identical error, this comes from: https://github.com/symfony/symfony/blob/8c4fd1299b33d73b0ebfd9d89940239e17958ffd/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php#L331

But yea, it doesn't make any sense - as you showed, the `doctrine` service is available AND public.

Can you post some additional code?

**Comment by stof** [comment]
Can you try again with 1.9.1 of the bundle ? AbstractController is using the Doctrine Common interface for autowiring: https://github.com/symfony/symfony/blob/8c4fd1299b33d73b0ebfd9d89940239e17958ffd/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L83
So the autowiring alias removed in 1.9.0 (and added back in 1.9.1 to fix the BC break) might be the cause of the issue.

**Comment by piotrantosik** [comment]
Now is ok
