### ISSUE TITLE
New version 1.9.0 breaks fixtures

### ISSUE THREAD

**Issue by InputOutput** [doctrine/DoctrineBundle#808]
The new 1.9.0 deprecated autowiring of ObjectManager in favour of the EntityManagerInterface. However, the [FixtureInterface](https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/FixtureInterface.php) from the Doctrine project uses the ObjectManager as typehint. This disallows implementation of the `load()` method in combination with autowiring.

I am unsure were this should be fixed. I have openend an issue for this at the doctrine/data-fixtures repo: https://github.com/doctrine/data-fixtures/issues/293. However, I guess it's also possible this should be fixed at https://github.com/doctrine/DoctrineFixturesBundle.

**Comment by mikeSimonson** [comment]
@InputOutput Fixed in 1.9.1
