### ISSUE TITLE
Entity manager parameter on getRepository does not exist

### ISSUE THREAD

**Issue by geoff-maddock** [doctrine/DoctrineBundle#809]
According to this documentation: https://symfony.com/doc/current/doctrine/multiple_entity_managers.html

There is a 2nd parameter on getRepository to specify the entity manager the repository uses:

```
$customers = $this->getDoctrine()
            ->getRepository(Customer::class, 'customer')
            ->findAll()
```

However, looking at the current version included when in composer require doctrine, there is no such parameter. Documentation issue or a codebase issue?

**Comment by Majkl578** [comment]
It is declared in [`Doctrine\Common\Persistence::ManagerRegistry::getRepository()`](https://github.com/doctrine/common/blob/v2.8.1/lib/Doctrine/Common/Persistence/ManagerRegistry.php#L75).
