### ISSUE TITLE
"region_lifetime" and "region_lock_lifetime" are ignored

### ISSUE THREAD

**Issue by DangerLifter** [doctrine/DoctrineBundle#814]
It seems that "region_lifetime" and "region_lock_lifetime" defined as direct child of "second_level_cache" in configuration are ignored. There is no any activity with them in DoctrineExtension.

If config defines them there are no error. But these options do no affect constructed cache classes and default lifetime is used.

**Comment by romainbrancourt** [comment]
Any update on this ? 
The issue still persist.
Global "region_lifetime" does not seem to work.
Cache lifetime is always 3600 (at least in Redis)
A workaround is to set lifetime particularly for a region
```yaml
regions: 
        my_region: 
              lifetime: 0
```
But i want all my regions lifetime to be at 0.

**Comment by ostrolucky** [comment]
There is not much point for support of these anymore, since we only support symfony cache pools instead, but these options should be deprecated since they are inactive

**Comment by Khartir** [comment]
@ostrolucky I'm not sure if I understood you correctly, but I think these settings are still required. The lifetime set on a symfony cache pool is not used. Instead the region lifetime is used, so having a way to set this for all regions (and/or the default region) would be appreciated.
Or do you plan to completely phase out the region lifetime and always use the lifetime of the underlying symfony cache pool?

**Comment by I70l0teN4ik** [comment]
I have created a duplicated issue in Symfony core repo, because I've didn't found this one. But generally speaking here is a [link](https://github.com/symfony/symfony/issues/36881) maybe my description of the issue will be helpful.

**Comment by I70l0teN4ik** [comment]
And just to be clear with cache pools - I also didn't succeed when tried to set the default ttl for the pool.
Nomatter how I tried to set it up `$defaultLifetime = 3600` was always used. 
Maybe some description of that confing is missing in the docs?

**Comment by ostrolucky** [comment]
Indeed, looks like we will have to add support for this, otherwise limit to 3600 cannot be increased.
