### ISSUE TITLE
Support postgresql 10 

### ISSUE THREAD

**Issue by VereschakSun** [doctrine/DoctrineBundle#819]
Hi. In  new version of doctrine dbal 10 postgresql is supporting. Why does not upgrade bundle for new stable version of dbal packege?

**Comment by jwage** [comment]
It should work. What problem are you running in to?

**Comment by Ocramius** [comment]
DBAL v2.7.1 already supports PostgreSQL 10: https://github.com/doctrine/dbal/blob/v2.7.1/lib/Doctrine/DBAL/Platforms/PostgreSQL100Platform.php

Closing here, as a `composer update` with a correct environment would solve the issue.
