### ISSUE TITLE
Fatal error: Call to protected DoctrineORMEntityManager_00000000269a7ffd000000007f98586228a0c7188fe871033e49ce7a85e414ea::__construct() from context 'appDevDebugProjectContainer'

### ISSUE THREAD

**Issue by sterichards** [doctrine/DoctrineBundle#828]
I've recently updated Symfony from 2.7 to 2.8, in the process of upgrading to 3.0 next

I have stripped down composer.json and re-built from scratch. This is the output of `composer show -i` for the doctrine and symfony packages:

```doctrine/annotations                 v1.5.0                                              Docblock Annotations Parser
doctrine/cache                       v1.7.0                                              Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.5.0                                              Collections Abstraction library
doctrine/common                      v2.8.0                                              Common Library for Doctrine projects
doctrine/data-fixtures               v1.3.1                                              Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        v2.6.0                                              Database Abstraction Layer
doctrine/doctrine-bundle             1.9.1                                               Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.3                                               Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle    v2.4.1                                              Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle  v1.3.1                                              Symfony DoctrineMigrationsBundle
doctrine/inflector                   v1.2.0                                              Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.1.0                                               A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1                                              Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  v1.5.0                                              Database Schema migrations using Doctrine DBAL
doctrine/orm                         v2.6.1                                              Object-Relational-Mapper for PHP
friendsofsymfony/oauth-server-bundle 1.6.1                                               Symfony2 OAuth Server Bundle
friendsofsymfony/oauth2-php          1.2.2                                               OAuth2 library
friendsofsymfony/rest-bundle         2.3.1                                               This Bundle provides various tools to rapidly develop RESTful API's with Symfony
friendsofsymfony/user-bundle         v2.1.2                                              Symfony FOSUserBundle
ensio/distribution-bundle           v5.0.22                                             Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.29                                             This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.1.7                                              This bundle generates code for you
sensiolabs/security-checker          v4.1.8                                              A security checker for your composer.lock
symfony/assetic-bundle               v2.8.2                                              Integrates Assetic into Symfony2
symfony/console                      v3.0.0                                              Symfony Console Component
symfony/monolog-bundle               v3.3.0                                              Symfony MonologBundle
symfony/polyfill-intl-icu            v1.8.0                                              Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.8.0                                              Symfony polyfill for the Mbstring extension
symfony/polyfill-php54               v1.8.0                                              Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55               v1.8.0                                              Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56               v1.8.0                                              Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.8.0                                              Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.8.0                                              Symfony utilities for portability of PHP codes
symfony/security-acl                 v2.8.0                                              Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle           v3.2.2                                              Symfony SwiftmailerBundle
symfony/symfony                      v2.8.0                                              The Symfony PHP framework```

**Comment by weaverryan** [comment]
Hmm, I’m familiar with this. Just to make sure, if you totally clear the cache dir (with an rm -rf) does it still happen?

Since you’ve deconstructed it so far, could you use your composer.json and composer.lock files to push a test repo to GitHub (like, the Symfony standard edition, but with your composer files and a few pieces of code to trigger the error)?

Cheers!

**Comment by sterichards** [comment]
@weaverryan Yes, i've tried clearing the cache manually using `rm -rf ./app/cache/dev/*` and also `rm -rf ./app/cache/prod/*`. I've also tried rebooting the VM this is hosted on a few times. I've tried a couple of different versions of Symfony

The problem comes into play when I add the following to ./app/config/config.yml:

`services:
    fos_user.doctrine_registry:
        alias: doctrine`

The reason for adding that is that i'm using Symfony 2.8 and research has suggested adding that line to avoid the following error:

`[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "fos_user.doctrine_registry".`

Trying to work out if you're asking me to upload my configs so you can try and replicate them locally or not? I can certainly send you my composer.json/lock if need be

I should also add that this was a working project using Symfony 2.7. I am in the process of updating all of the packages so a lot of libraries have been updated via Composer. This would suggest initially to me that this is a version problem somewhere but i'm happy to accept any information or suggestions that you offer

Many thanks, Ste

**Comment by sterichards** [comment]
composer.json (slightly modified to remove some libraries that are noise in this debugging):

`{
    "require": {
        "symfony/symfony": "2.8",
        "symfony/swiftmailer-bundle": "^3.2",
        "doctrine/doctrine-bundle": "1.9.1",
        "doctrine/doctrine-migrations-bundle": "^1.3",
        "doctrine/doctrine-fixtures-bundle": "2.4.1",
        "doctrine/doctrine-cache-bundle": "^1.3",
        "doctrine/inflector": "1.2.0",
        "doctrine/instantiator": "1.1.0",
        "doctrine/lexer": "^1.0",
        "doctrine/data-fixtures": "^1.3",
        "doctrine/common": "2.8.0",
        "doctrine/collections": "1.5.0",
        "doctrine/cache": "1.7.0",
        "doctrine/annotations": "1.5.0",
        "doctrine/orm": "2.6.1",
        "doctrine/migrations": "1.5.0",
        "doctrine/dbal": "2.7.1",
        "symfony/console": "3.0",
        "friendsofsymfony/oauth-server-bundle": "^1.6",
        "friendsofsymfony/oauth2-php": "^1.2",
        "friendsofsymfony/rest-bundle": "^2.3",
        "friendsofsymfony/user-bundle": "^2.1",
        "symfony/monolog-bundle": "^3.3",
        "symfony/assetic-bundle": "^2.8",
        "php-http/curl-client": "^1.7",
        "php-http/discovery": "^1.4",
        "php-http/httplug": "^1.1",
        "php-http/message": "^1.6",
        "php-http/message-factory": "^1.0",
        "php-http/promise": "^1.0",
        "psr/http-message": "^1.0",
        "psr/log": "^1.0",
        "twig/twig": "^2.4",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "3.0.29",
        "sensio/generator-bundle": "^3.1",
        "sensiolabs/security-checker": "^4.1",
        "gedmo/doctrine-extensions": "^2.4",
        "guzzlehttp/guzzle": "^6.3",
        "guzzlehttp/psr7": "^1.4",
        "guzzlehttp/ringphp": "^1.1",
        "guzzlehttp/streams": "^3.0",
        "happyr/linkedin-api-client": "^1.0",
        "incenteev/composer-parameter-handler": "^2.1",
        "knplabs/gaufrette": "^0.6.0",
        "knplabs/knp-components": "^1.3",
        "knplabs/knp-gaufrette-bundle": "^0.5.3",
        "knplabs/knp-paginator-bundle": "^2.8",
        "kphoen/doctrine-state-machine": "^1.1",
        "kphoen/doctrine-state-machine-bundle": "^1.1",
        "league/csv": "^9.1",
        "mandrill/mandrill": "^1.0",
        "monolog/monolog": "^1.23",
        "behat/transliterator": "^1.2",
        "phpcollection/phpcollection": "^0.5.0",
        "phpoption/phpoption": "^1.5",
        "react/promise": "^2.7",
        "endroid/twitter-bundle": "^2.0",
        "stof/doctrine-extensions-bundle": "^1.3"
    }
    "autoload": {
        "psr-4": {
            "": "src/"
        }
    },
    "config": {
        "platform": {
            "php": "7.2.6"
        }
    },
}
`

**Comment by stof** [comment]
Can you give the stack trace of the exception you get ? and if this goes into your `appDevDebugProjectContainer.php` file in the cache, please paste the context around the file where the error happens (let's say, from 10 lines before to 10 lines after)

**Comment by sterichards** [comment]
@stof This is the full stack trace:

```PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to protected DoctrineORMEntityManager_000000006444ce1a000000001b9f1c3a28a0c7188fe871033e49ce7a85e414ea::__construct() from context 'appDevDebugProjectContainer' in /vagrant/app/cache/dev/appDevDebugProjectContainer.php:1114
Stack trace:
#0 /vagrant/app/bootstrap.php.cache(2155): appDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()
#1 /vagrant/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php(35): Symfony\Component\DependencyInjection\Container->get('doctrine.orm.de...')
#2 /vagrant/vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php(183): Symfony\Bridge\Doctrine\ManagerRegistry->getService('doctrine.orm.de...')
#3 /vagrant/app/cache/dev/appDevDebugProjectContainer.php(2859): Doctrine\Common\Persistence\AbstractManagerRegistry->getManager('default')
#4 /vagrant/app/bootstrap.php.cache(2155): appDevDebugProjectContainer->getFosUser_UserManagerService()
#5 /v in /vagrant/app/cache/dev/appDevDebugProjectContainer.php on line 1114```

These are the lines that are causing the fatal in appDevDebugProjectContainer.php"

```/**
     * Gets the 'doctrine.orm.default_entity_manager' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @param bool    $lazyLoad whether to try lazy-loading the service with a proxy
     *
     * @return \Doctrine\ORM\EntityManager A Doctrine\ORM\EntityManager instance.
     */
    public function getDoctrine_Orm_DefaultEntityManagerService($lazyLoad = true)
    {
        if ($lazyLoad) {
            $container = $this;

            return $this->services['doctrine.orm.default_entity_manager'] = new DoctrineORMEntityManager_000000006444ce1a000000001b9f1c3a28a0c7188fe871033e49ce7a85e414ea(
                function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = $container->getDoctrine_Orm_DefaultEntityManagerService(false);

                    $proxy->setProxyInitializer(null);

                    return true;
                }
            );
        }

        $a = $this->get('annotation_reader');```

Specifically the `return new DoctrineORMEntityManager_000000006444ce1a000000001b9f1c3a28a0c7188fe871033e49ce7a85e414ea()` call

If I follow through to the `DoctrineORMEntityManager_000000006444ce1a000000001b9f1c3a28a0c7188fe871033e49ce7a85e414ea` class definition, within appDevDebugProjectContainer.php, I see this:

```protected function __construct(\Doctrine\DBAL\Connection $conn, \Doctrine\ORM\Configuration $config, \Doctrine\Common\EventManager $eventManager)
    {```

**Comment by stof** [comment]
What is the version of `ocramius/proxy-manager` installed in your project ? It is not shown in your `composer show` output.

**Comment by sterichards** [comment]
`ocramius/proxy-manager               2.2.0`

**Comment by sterichards** [comment]
It may help if you could provide me with a composer.json file example that you use, that is PHP7.2 compatible and uses Symfony 2.8 with whichever set of Doctrine packages that you use

I can then use those versions, Composer update and see if that eliminates the error that i'm seeing

If it helps you out, I can maybe push my codebase to a test EC2 and give you SSH access?

**Comment by sterichards** [comment]
I'm wondering if setting $lazyLoad to false is going to help me out at all but i'm not sure any configuration parameter for me to set that could force $lazyLoad to false?

**Comment by cobyl** [comment]
@sterichards I have the same problem. How did you manage to solve this?

**Comment by sterichards** [comment]
> @sterichards I have the same problem. How did you manage to solve this?

I think I solved the problem by changing the package version of multiple packages. It was too long ago for me to remember exactly what I changed. Maybe if I post the composer.json that I have now, you could try that and see if it works for you:

`"require": {
    "php": ">=7.1",
    "codegyre/robo": "^0.7.2",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/doctrine-migrations-bundle": ">=1.3",
    "doctrine/orm": "^2.5",
    "friendsofsymfony/oauth-server-bundle": "dev-master",
    "friendsofsymfony/rest-bundle": "dev-master",
    "friendsofsymfony/user-bundle": "dev-master",
    "gedmo/doctrine-extensions": "^2.4",
    "incenteev/composer-parameter-handler": "^2.0",
    "jms/serializer-bundle": "^2.4",
    "knplabs/knp-paginator-bundle": "^2.8",
    "nelmio/api-doc-bundle": "^3.2",
    "nelmio/cors-bundle": "^1.5",
    "sensio/distribution-bundle": "^5.0.19",
    "sensio/framework-extra-bundle": "^5.0.0",
    "symfony/monolog-bundle": "^3.1.0",
    "symfony/polyfill-apcu": "^1.0",
    "symfony/swiftmailer-bundle": "^2.6.4",
    "symfony/symfony": "3.4.*",
    "symfony/templating": "^4.1",
    "symfony/validator": "4.0",
    "twig/twig": "^1.0||^2.0"
  },`

**Comment by PReimers** [comment]
I'm closing this issue since it seams fixed.

**Comment by greentopsecret** [comment]
Just got same failure 
```
bin/console doctrine:database:update --force -vvv
Error {#328
  #message: "Call to protected Doctrine\ORM\EntityManager::__construct() from context 'ContainerKlDRrUP\srcWHC_KernelDevDebugContainer'"
  #code: 0
  #file: "./var/cache/dev/ContainerKlDRrUP/srcWHC_KernelDevDebugContainer.php"
  #line: 2510
  trace: {
    ./var/cache/dev/ContainerKlDRrUP/srcWHC_KernelDevDebugContainer.php:2510 {
      ContainerKlDRrUP\srcWHC_KernelDevDebugContainer->getQueueRepositoryService()^
      ›
      ›     return $this->privates['WHC\\Infrastructure\\Persistence\\Repository\\QueueRepository'] = new \WHC\Infrastructure\Persistence\Repository\QueueRepository(($this->privates['Doctrine\\ORM\\EntityManager'] ?? ($this->privates['Doctrine\\ORM\\EntityManager'] = new \Doctrine\ORM\EntityManager())));
      › }
    }
    ./var/cache/dev/ContainerKlDRrUP/srcWHC_KernelDevDebugContainer.php:2452 { …}
    ./vendor/symfony/dependency-injection/Container.php:444 { …}
    ./vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40 { …}
    ./vendor/symfony/console/CommandLoader/ContainerCommandLoader.php:45 { …}
    ./vendor/symfony/console/Application.php:542 { …}
    ./vendor/symfony/console/Application.php:743 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:143 { …}
    ./vendor/symfony/console/Application.php:555 { …}
    ./vendor/symfony/console/Application.php:581 { …}
    ./vendor/symfony/console/Application.php:651 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:117 { …}
    ./vendor/symfony/console/Application.php:236 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:83 { …}
    ./vendor/symfony/console/Application.php:148 { …}
    ./bin/console:42 { …}
  }
}
[18-Mar-2020 12:24:45 America/New_York] 2020-03-18T12:24:45-04:00 [critical] Uncaught Error: Call to protected Doctrine\ORM\EntityManager::__construct() from context 'ContainerKlDRrUP\srcWHC_KernelDevDebugContainer'
```

composer.json

```
  "require": {
    "php": "^7.2",
    "ext-ctype": "*",
    "ext-iconv": "*",
    "ext-json": "^1.6",
    "doctrine/doctrine-bundle": "^2.0",
    "liip/monitor-bundle": "^2.10",
    "overblog/graphiql-bundle": "^0.2.0",
    "overblog/graphql-bundle": "^0.13.1",
    "stof/doctrine-extensions-bundle": "^1.3",
    "symfony/asset": "4.4.*",
    "symfony/console": "4.4.*",
    "symfony/dotenv": "4.4.*",
    "symfony/flex": "^1.3.1",
    "symfony/framework-bundle": "4.4.*",
    "symfony/monolog-bundle": "^3.5",
    "symfony/property-access": "4.4.*",
    "symfony/serializer": "4.4.*",
    "symfony/stopwatch": "4.4.*",
    "symfony/yaml": "4.4.*"
  },
  "require-dev": {
    "doctrine/doctrine-fixtures-bundle": "^3.3",
    "friendsofphp/php-cs-fixer": "^2.16",
    "jangregor/phpstan-prophecy": "^0.6.0",
    "phpstan/extension-installer": "^1.0",
    "phpstan/phpstan": "^0.12.5",
    "phpstan/phpstan-doctrine": "^0.12.9",
    "phpstan/phpstan-symfony": "^0.12.3",
    "phpunit/phpunit": "8.3",
    "roave/security-advisories": "dev-master",
    "symfony/browser-kit": "4.4.*",
    "symfony/maker-bundle": "^1.14",
    "symfony/phpunit-bridge": "v4.4.2"
  },
```

**Comment by PReimers** [comment]
Hello @greentopsecret 

Could you check your bundle version with this command: `composer show doctrine/doctrine-bundle`

It should print something like
```
...
versions : * 2.0.7
...
```

**Comment by greentopsecret** [comment]
@PReimers , thank you for quick reply
it seems I have outdated version

```
versions : * 2.0.2
```

will update it firstly

**Comment by PReimers** [comment]
@greentopsecret 

try `composer why doctrine/doctrine-bundle` to see which other bundle rely on this bundle. 😉
