### ISSUE TITLE
DBAL cache "no result driver is configured" error

### ISSUE THREAD

**Issue by aprat84** [doctrine/DoctrineBundle#833]
Hi.

I'm trying to cache the result of a simple query, and I'm getting exception with message "Trying to cache a query but no result driver is configured".

```php
$query = $connection->createQueryBuilder()
    ->select('*')
    ->from('common.Language')
    ->getSQL();

$stmt = $connection->executeCacheQuery($query, [], [], new QueryCacheProfile(0, "languages"));
$rows = $stmt->fetchAll();
$stmt->closeCursor();
```

I've read I could enable cache by implementing a small bundle just for it, [like this guide](http://www.symfony-grenoble.fr/en/376/how-to-use-doctrine-dbal-cache-with-symfony2/).
Is there no way to enable result caching via configuration files?

I'm not using ORM, just plain DBAL. In fact, I had to delete the ORM part from `config/packages/doctrine.yaml` file.
Bundle version is 1.9.1, installed via flex.

**Comment by alcaeus** [comment]
> I'm not using ORM, just plain DBAL. In fact, I had to delete the ORM part from `config/packages/doctrine.yaml` file.
> Bundle version is 1.9.1, installed via flex.

This is an issue with the flex recipe for DoctrineBundle, which we can't fix at the moment. @stof might be able to tell you more about this.

> I'm trying to cache the result of a simple query, and I'm getting exception with message "Trying to cache a query but no result driver is configured".

You are absolutely correct: configuring the DBAL result cache currently isn't possible. We'll be adding this feature in 1.11.

**Comment by alcaeus** [comment]
Closing here: this duplicates #114.
