### ISSUE TITLE
Better error message when index keys surpass the 767 limit

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#834]
If the following conditions met:

* You are using `utf8mb4`
* You set `unique=true` in a column
* That column is a string with more than 190 character length (which happens when you don't define the length and 255 is used by default)

You'll see this cryptic error message:

```
[PDOException] SQLSTATE[42000]: Syntax error or access violation:
1071 Specified key was too long; max key length is 767 bytes
```

This is [a well-known MySQL restriction](https://dev.mysql.com/doc/refman/5.6/en/innodb-restrictions.html) but maybe we could display a better error message to help users? Example:

```
When using utf8mb4, the length of the unique columns must be 190 or
less but the %s property of the %s entity has a length of %d.
```

**Comment by Majkl578** [comment]
Shouldn't this be reported to [DBAL](https://github.com/doctrine/dbal) instead?

**Comment by javiereguiluz** [comment]
@Majkl578 thanks! I'm closing this issue then and I've created https://github.com/doctrine/dbal/issues/3230 instead.
