### ISSUE TITLE
Bug: SQLite-path misses leading /

### ISSUE THREAD

**Issue by Hecke29** [doctrine/DoctrineBundle#845]
I'm on macOS highSierra 10.13.5 using PHP 7.1.19 and doctrine/doctrine-bundle 1.9.1.

I have the following config in my dev-environment:
```yml
doctrine:
    dbal:
      driver: pdo_sqlite
      url: "%kernel.cache_dir%/dev.db"
```

Wanted to load fixtures with `bin/console doctrine:fixtures:load -n` which lead to a `[14] unable to open database file`.

Started backwards the stacktrace in `vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php` around line 56 where the `PDOConnection` is made. Dumped the `$params`-array there and found something interesting:

```
array(11) {
'driver' => "pdo_sqlite"
...
'url' => "/Users/myuser/dev/project/var/cache/dev/dev.db"
...
'path' => "Users/myuser/dev/project/var/cache/dev/dev.db"
```
Please note the `path` does not having a leading `/`.

Adding that leading `/` hard-coded to the `path` variable directly in that Driver fixed the problem but is obviously not the proper bugfix.

---

Using `url: "/%kernel.cache_dir%/dev.db"` (leading / in url) leads to `url => "//Users/myuser/dev/project/var/cache/dev/dev.db"` and `path => "myuser/dev/project/var/cache/dev/dev.db"` [sic] in the driver

**Comment by jwage** [comment]
Can you look in the code for the Symfony container and see if it is Symfony passing through the path without the leading forward slash or if it gets stripped after being passed to Doctrine?

**Comment by Hecke29** [comment]
After not finding a place where I can debug that I added a `var_dump($config['dbal']['connections']['default']);` to `Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension` in the `load`-method directly after the config was processed with the result that no `path`-variable exists in there:

```array(15) {
  'driver' =>
  string(10) "pdo_sqlite"
  'server_version' =>
  string(3) "5.7"
  'charset' =>
  string(7) "utf8mb4"
  'default_table_options' =>
  array(2) {
    'charset' =>
    string(7) "utf8mb4"
    'collate' =>
    string(18) "utf8mb4_unicode_ci"
  }
  'url' =>
  string(46) "/Users/myuser/dev/project/var/cache/de_/dev.db"
  'host' =>
  string(9) "localhost"
  'port' =>
  NULL
  'user' =>
  string(4) "root"
  'password' =>
  NULL
  'logging' =>
  bool(true)
  'profiling' =>
  bool(true)
  'options' =>
  array(0) {
  }
  'mapping_types' =>
  array(0) {
  }
  'slaves' =>
  array(0) {
  }
  'shards' =>
  array(0) {
  }
}
```

Url really says `.../cache/de_/` (with a _ in the path) but I think that's some magic that will be resolved to `.../cache/dev/` later?

**Comment by Hecke29** [comment]
Ok, I'm sorry. I think I misunderstood your question.
Now I dumped $params in the `Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection` which is may more that what you asked for (?)

But the result is also no `path` exists:
```
array(10) {
  'driver' => string(10) "pdo_sqlite"
  'charset' => string(7) "utf8mb4"
  'url' => string(46) "/Users/myuser/dev/project/var/cache/dev/dev.db"
  'host' => string(9) "localhost"
  'port' => NULL
  'user' => string(4) "root"
  'password' => NULL
  'driverOptions' => array(0) { }
  'serverVersion' => string(3) "5.7"
  'defaultTableOptions' =>
  array(2) {
    'charset' => string(7) "utf8mb4"
    'collate' => string(18) "utf8mb4_unicode_ci"
  }
}
```

**Comment by Hecke29** [comment]
Ok. I'm kinda clueless now.
The removal of the leading `/` is intended.

It is made in `Doctrine\DBAL\DriverManager::normalizeDatabaseUrlPath` called from `Doctrine\DBAL\DriverManager::parseDatabaseUrlPath` and I have no idea why.

I should head over to doctrine main-repo, shouldn't I?

**Comment by jwage** [comment]
Yes, I think this belongs in https://github.com/doctrine/dbal

Thanks for reporting!

**Comment by Hecke29** [comment]
Solutions was quite simple... Use `url: "sqlite:///%kernel.cache_dir%/test.db"` in bundle-config
