### ISSUE TITLE
Error after composer update

### ISSUE THREAD

**Issue by sonic4002** [doctrine/DoctrineBundle#847]
Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /private/var/www/php_lib/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php on line 16

![image](https://user-images.githubusercontent.com/19172723/45263696-20b90f00-b437-11e8-9dc9-777758bc3df5.png)

i dont understand the problem in order to solve it

i tried using php 7.0.22, 7.0.27, 7.1.21 , 7.2.9 with intellij
none of them worked

**Comment by Ocramius** [comment]
Your web SAPI is most likely running PHP 7.0: please make sure you are running at least 7.1.

Use a `phpinfo()` in a web page to check that: CLI and web-related SAPIs may be running oj different engine versions.

**Comment by jagusport** [comment]
amigos! si me funcionó solucionar este errror. 

Yo lo tenía al instalar chamilo en un servidor web. 

Le habilite php 7.1 al servidor y me logró relacionar la base de datos con la instalación. 


muchas gracias
