### ISSUE TITLE
Doctrine command make absolutely nothing

### ISSUE THREAD

**Issue by GothShoot** [doctrine/DoctrineBundle#850]
Symfony version(s) affected : 4.1.2

Description : Hey everyone, I have a very strange problem with my project, i want to create my database with doctrine:create:database. But nothing run (cmd.exe use only 16Mb of RAM, no CPU and no disk) MySQL not have request and after a lot's of hours, yes hours .. only nothing .. I have verified my database config, clear cache with remove var/cache directory, checked php config, but nothing work ..

Any idea ?

Thank's

How to reproduce : Code is open in: https://github.com/NitroxLab/valvoja

**Comment by jwage** [comment]
Hi, you will need to debug the code unfortunately to see what it is doing. Hard for us to say what it might be.

**Comment by GothShoot** [comment]
Hi, i comment the code for you this week-end 👍

**Comment by GothShoot** [comment]
Hi, is commented and cleaned a little, and i have fixed small thing's 😄

**Comment by jwage** [comment]
Hi, did you debug the code and look for why the database is not being created? You will need to go in to the source code and trace through what is being executed to see why it doesn't end up creating the database.

**Comment by GothShoot** [comment]
Hi, every database access are affected, in CLI and CGI, php and/or symfony not print log or error.
I have checked database config in my .env and trying to changing this, it's absolutely inexplicable :thinking:

**Comment by GothShoot** [comment]
If use external database, it work, it's probably my local mysql 😞
