### ISSUE TITLE
Remove Entity/Document/CouchDocument auto-detection

### ISSUE THREAD

**Issue by beberlei** [doctrine/DoctrineBundle#86]
The auto detection and differentiation between Entity/Document/CouchDocument folders is really a pain.

The FOS Bundles went to an ugly MappedSuperClass + Extend pattern to work around this.

In general Doctrine is a DataMapper, because its supposed to be persistence ignorant. All the classes can be in any folder.

Idea:
- AutoMapping points to Bundle directory, not to subdirectories anymore. That means Entities can be in any folder of the bundle.
- DoctrineBundle (Bridge) provides a way to avoid the same classes to be mapped by multiple persistence mappers, so that FOSBundle style distribution of mappings for all bundles is still possible.

**Comment by ostrolucky** [comment]
As far as I see logic of this is in symfony doctrine bridge, so if this is important, this issue should be raised there. And as far as we see, this didn't gaing much traction and issue itself is confusing - title talks about different things than description and description proposes two different things. If comments address right thing, we agree with @stof and @dbu opinion that making automapping scan whole bundle dir by default might be too much. Feel free to reopen issue with more concrete proposal.
