### ISSUE TITLE
Sylius customizing model dose not working

### ISSUE THREAD

**Issue by Zhasan040** [doctrine/DoctrineBundle#878]
**It's my class file Country.php** 

`<?php

namespace App\Entity;

use Sylius\Component\Addressing\Model\Country as BaseCountry;

class Country extends BaseCountry {

/**
 * @var bool
 */
private $flag;

/**
 * @return bool|null
 */
public function getFlag(): ?bool {
    return $this->flag;
}

/**
 * @param bool $flag
 */
public function setFlag(bool $flag): void {
    $this->flag = $flag;
   }

}`

**It's my orm file. AppBundle/Resources/config/doctrine/Country.orm.yml**

`App\Entity\Country:`
   `type:entity`
   `table: sylius_country`
   `fields:`
       `flag:`
           `type: boolean`
           `nullable: true`

**It's my config file. config/_sylius.yml**
`sylius_addressing:`
   `resources:`
       `country:`
           `classes:`
               `model: App\Entity\Country`

**Comment by kimhemsoe** [comment]
This does not look like a doctrine bundle issue. I would suggest you ask Sylius about extending their framework.
