### ISSUE TITLE
Compatibility with Symfony 4.2

### ISSUE THREAD

**Issue by QuentinCurtet** [doctrine/DoctrineBundle#880]
Upgrading to symfony 4.2 with this bundle leads to this deprecation :
> The "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated since Symfony 4.2, use "Symfony\Component\Console\Command\Command" with dependency injection instead.

It is precisely in this file :
https://github.com/doctrine/DoctrineBundle/blob/master/Command/DoctrineCommand.php (on line 15)

**Comment by alcaeus** [comment]
See #877.
