### ISSUE TITLE
Drop support for php  <7.1

### ISSUE THREAD

**Issue by kimhemsoe** [doctrine/DoctrineBundle#885]
@jwage Would it be an issue to drop support for 5.5 here and now? 

My reasoning is that 5.5 have not been supported for quite a while and we should push towards getting the bundle to 7.1 so we align better with the other bundles

**Comment by alcaeus** [comment]
I've talked to Ryan about this and we agreed that it would be ok to drop PHP < 7.1 from the bundles. I would suggest doing so in a minor release though, not in a patch release like the milestone suggests.

**Comment by kimhemsoe** [comment]
@alcaeus OK drop 5.x in 1.11 then and 7.0 in next 1.12 or 2.0?

**Comment by alcaeus** [comment]
Drop 5.x and 7.0 in 1.11 😉

**Comment by alcaeus** [comment]
Closing now that #892 has been merged.
