### ISSUE TITLE
Missing doctrine/common dependency

### ISSUE THREAD

**Issue by umulmrum** [doctrine/DoctrineBundle#887]
Hi,

in `\Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration::getAutoGenerateModes()` the class `Doctrine\Common\Proxy\AbstractProxyFactory` is used, but doctrine/common is not required.
As symfony/doctrine-bridge 4.2 does no longer require common either, it was removed from my project after upgrading and crashed (that project uses DBAL and the debug toolbar collector, but not ORM).

I'm not sure what the best solution is, but maybe one of these:
- Add the dependency in DoctrineBundle.
- Check if the class exists and deactivate parts of the bundle if not (not sure if this makes sense, I'm not too familiar with the bundle).

**Comment by kimhemsoe** [comment]
Sounds like a dup of https://github.com/doctrine/DoctrineBundle/pull/881
