### ISSUE TITLE
Docs page is broken

### ISSUE THREAD

**Issue by vladyslavstartsev** [doctrine/DoctrineBundle#889]
This page is broken
https://www.doctrine-project.org/projects/doctrine-bundle/en/latest/entity-listeners.html#entity-listeners
the broken part is xml thing

also the link at the end (the http://doctrine-orm.readthedocs.org/en/latest/reference/events.html#entity-listeners ) is outdated

**Comment by alcaeus** [comment]
Link was fixed in #891, XML block in #897. Closing here.
