### ISSUE TITLE
[Entity Listeners] always lazy load via ServiceLocator

### ISSUE THREAD

**Issue by dmaicher** [doctrine/DoctrineBundle#899]
Since soon support for Symfony < 3.4 will be dropped we could use a `ServiceLocator` here 

https://github.com/doctrine/DoctrineBundle/blob/master/Mapping/ContainerAwareEntityListenerResolver.php#L20

to and get rid of the `lazy` attribute completely?

https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/Compiler/EntityListenerPass.php#L44

So we don't have to mark the listeners `public` anymore and we can always lazily fetch them.

Or is there any reason **to not always lazy load** them?

**Comment by alcaeus** [comment]
Just a heads up, I've decided to leave this out from #892 but will be changing this in time for a 1.11 release so we can deprecate the original behaviour. I just need some more time to wrap my head around the logic.

**Comment by dmaicher** [comment]
Looking into this now at EUFOSSA hackathon :+1:

**Comment by alcaeus** [comment]
Closing as #951 was merged 🎉
