### ISSUE TITLE
resolve_target_entities for many entities implementing the same interface  

### ISSUE THREAD

**Issue by cronk1986** [doctrine/DoctrineBundle#914]
Hello,

It's possible to resolve more than one entity for the same interface with resolve_target_entities option? 

I want to make independent bundle for my storage files, inside it has an entity with the following structure:
/**
 * MyFiles
 *
 * @ORM\Table()
 * @ORM\Entity()
 */
class MyFiles
{
   ...
    /**
     * @var MyInterface
     * @ORM\ManyToOne(targetEntity="MyInterface", cascade={"persist"})
     private $reference;
   ...
}

I want to do something like below code:

doctrine:
    dbal
      ...
    orm:
        resolve_target_entities:
            MyInterface: 
                - ProductEntity
                - CategoryEntity
                ...
But it's not possible. I try in a compiler pass like below code:

$definition = $container->findDefinition('doctrine.orm.listeners.resolve_target_entity');
$definition->addMethodCall('addResolveTargetEntity', [  'MyInterface', 'ProductEntity', []]); 
$definition->addMethodCall('addResolveTargetEntity', [  'MyInterface', 'CategoryEntity', []]); 

the previous code throw an exception because is expecting CategoryEntity if is passed ProductEntity instance. Eg:
$file = new MyFiles();
$file->setReference(new ProductEntity());

this throw an exception, it  seems the previous  registered classes to CategoryEntity are forgotten, and only the last one takes effect.

How can I solve it?

@fabpot @javiereguiluz 

best regards

**Comment by greg0ire** [comment]
Please refraing from pinging people like this, especially when they are as busy as Javier or Fabien. Now let's think. How do you expect this to work? How can there be a resolution towards _one_ entity when there are _several_ of them to choose from? Also, please learn [how to format code properly on Github](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by alcaeus** [comment]
> How can I solve it?

You can create your own resolve listener by taking inspiration from the original. Then you can also tell the listener how to decide whether to use `ProductEntity` or `CategoryEntity` whenever `MyInterface` is being used. The built-in listener can't decide this for you and never will be able to.
