### ISSUE TITLE
Dynamic EntityManager find () method returns “table not found” when a ServiceEntityRepository is in use

### ISSUE THREAD

**Issue by Zathey92** [doctrine/DoctrineBundle#926]
**Exact code and problem:** [https://stackoverflow.com/questions/53801836/dynamic-entitymanager-find-method-returns-table-not-found-when-a-custom-rep](https://stackoverflow.com/questions/53801836/dynamic-entitymanager-find-method-returns-table-not-found-when-a-custom-rep)

I had this problem solved some time ago and someone said that if the solution solves it I should open a bug report.

Basically I build the dinamic entity managers by making use of this:
> $em = EntityManager::create($conn, $this->em->getConfiguration ())
$entity = $em->getRepository(Configuration::class)->find($confId);
_*Conection data is taken from database._

If the entity Configuration has a repository of type **ServiceEntityRepository**, the default method like find() doesn't work and the repository has to reconnect to de dynamic database. If it extends from EntityRepository there is no problem.

> @ORM\Entity() <-- Works like a charm
@ORM\Entity(repositoryClass="App\Repository\ConfigurationRepository")<-- Table not found because default manager is in use.

```
class ConfigurationRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry, EntityManager $em)
    {
        parent::__construct($registry, Configuration::class);
        $this->em= $em;
    }
...
}
```

The guy that sent me here said that ServiceEntityRepository sould work but in my experience doesn't take the same EntityManager that calls getRepository().

**Comment by alcaeus** [comment]
As mentioned in the linked StackOverflow post, the `ServiceEntityRepository` is a simplified class to help create services for repositories used for auto wiring. This class uses the manager registry to fetch the appropriate entity manager for the class in question. If you have multiple entity managers managing a single class or in even more "special" cases like your entity manager with dynamic connections, this logic will no longer hold true.

In such cases, create your own repository class that implements `ServiceEntityRepositoryInterface` and inject the correct entity manager into the constructor.
