### ISSUE TITLE
[Question] Support `.yaml` file extension

### ISSUE THREAD

**Issue by emulienfou** [doctrine/DoctrineBundle#931]
Hi there,
With the recent changes regarding the YAML extension in Symfony4 (https://medium.com/@fabpot/symfony-4-best-practices-b4bbd6a9c994), every files in the configurations folder changed from `.yml` to `.yaml`.

However, when trying to add Doctrine mapping when calling the method `DoctrineOrmMappingsPass::createYamlMappingDriver()`, the Factory class is still waiting for files with the `.yml` extension.
In my opinion, I think it should be great to support also files with `.yaml` extensions has well.

**Comment by Majkl578** [comment]
Given that Doctrine ORM is dropping support for YAML mapping driver ([it's already been deprecated](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html#yaml-mapping)), this is unlikely to happen.

**Comment by emulienfou** [comment]
Oh, didn't see the notice
