### ISSUE TITLE
Wire the validator metadata factory

### ISSUE THREAD

**Issue by dunglas** [doctrine/DoctrineBundle#938]
This is the missing part for https://github.com/symfony/symfony/pull/27735.
This bundle must register the new metadata loaders.

**Comment by alcaeus** [comment]
@dunglas I'm sorry, I have no idea what needs to be done here. Can you prepare a pull request or what needs to be done? I'd like to release 1.11 along Symfony 4.3 to provide support for the new features in the Validator and Messenger components, but haven't had time to familiarise myself with them yet.

**Comment by dunglas** [comment]
Hi @alcaeus, I started #939 but it's not 100 ready yet (not sure if I'll be able to finish it soon as I'll be away for computer for a few weeks starting tomorrow).

**Comment by dunglas** [comment]
Actually, it is ready and tested (even if adding a functional test would be better).

**Comment by alcaeus** [comment]
@dunglas thank you so much, I'll take care of the PR and fix up any remaining issues!

**Comment by dunglas** [comment]
Thank you very much!

**Comment by alcaeus** [comment]
#939 was merged, closing here.
