### ISSUE TITLE
Deprecate class parameters

### ISSUE THREAD

**Issue by alcaeus** [doctrine/DoctrineBundle#949]
With DoctrineBundle 2.0, we'll be dropping the `.class` parameters from the service configuration (see #630). In order for people to be aware of that, we should document the upcoming removal in 1.11.

**Comment by SenseException** [comment]
Do you have a place on the documentation page in mind where this should be mentioned in?

**Comment by ostrolucky** [comment]
Perhaps this is just a question of adding it to upgrade guide?

**Comment by alcaeus** [comment]
Upgrade guide would be a good place. Note that a whole bunch are still in and most likely require cleanup in DoctrineBridge first.
