### ISSUE TITLE
issue with merge up from 1.10 into master?

### ISSUE THREAD

**Issue by dmaicher** [doctrine/DoctrineBundle#952]
@alcaeus as mentioned I think something went wrong while merging some changes into master.

See 
https://github.com/symfony/symfony/issues/30948
https://github.com/doctrine/DoctrineBundle/pull/950#issuecomment-480580987

**Comment by alcaeus** [comment]
After digging into the code and analysing this we found out that this wasn't an issue with merging up to master but rather the code was inadvertently removed in #892. Closing here as there are no other merge issues.
