### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by jakzal** [doctrine/DoctrineBundle#957]
[Example](https://travis-ci.org/doctrine/DoctrineBundle/jobs/525705708#L380):
```
Testing DoctrineBundle for the Symfony Framework
.....PHP Fatal error:  Interface 'Symfony\Component\Translation\TranslatorInterface' not found in /home/travis/build/doctrine/DoctrineBundle/vendor/symfony/validator/Util/LegacyTranslatorProxy.php on line 21
Fatal error: Interface 'Symfony\Component\Translation\TranslatorInterface' not found in /home/travis/build/doctrine/DoctrineBundle/vendor/symfony/validator/Util/LegacyTranslatorProxy.php on line 21
```

Steps to reproduce:
1. Clone the repository
2. `composer install`
3. `./vendor/bin/phpunit`

**Comment by xabbuh** [comment]
I guess that's caused by symfony/symfony#31152

**Comment by jakzal** [comment]
Yeah, just traced it back to https://github.com/symfony/symfony/commit/064e369e06afac79ff4200bf1fb52231d1f5112c#diff-d96162ef2f1eeb1800551ea8121b4e00

**Comment by jakzal** [comment]
re https://github.com/symfony/symfony/pull/31156

**Comment by alcaeus** [comment]
Yep, waiting for 4.2.8 to be released. Can’t really work around that for now, but shouldn’t be more than a few days.

**Comment by jakzal** [comment]
Tests are passing again since a new version of Symfony was released.
