### ISSUE TITLE
AbstractClassMetadataFactory::loadMetadata not working in prod

### ISSUE THREAD

**Issue by lukepass** [doctrine/DoctrineBundle#959]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | v2.6.3

#### Summary

Hello, I am using Symfony 4 and I have the following error when loading a page in my website:

```
No metadata found for property `App\Application\Sonata\UserBundle\Entity\User::$groups`. Please make sure your Doctrine mapping is properly configured.
```

This error **only happens in prod** and not dev.

If I manually change the `APP_ENV` variable from prod to dev the page loads **just fine**.

After digging a lot in the source code I discovered that `AbstractClassMetadataFactory::loadMetadata` returns a different value for the fields `associationMappings`.

You can spot the difference here:

---> APP_ENV=prod (array is empty!)
```
AbstractClassMetadataFactory.php on line 208:
ClassMetadata {#380 ▼
  +name: "App\Application\Sonata\UserBundle\Entity\User"
  +namespace: "App\Application\Sonata\UserBundle\Entity"
  +rootEntityName: "App\Application\Sonata\UserBundle\Entity\User"
  +customGeneratorDefinition: null
  +customRepositoryClassName: null
  +isMappedSuperclass: false
  +isEmbeddedClass: false
  +parentClasses: []
  +subClasses: []
  +embeddedClasses: []
  +namedQueries: []
  +namedNativeQueries: []
  +sqlResultSetMappings: []
  +identifier: array:1 [▶]
  +inheritanceType: 1
  +generatorType: 4
  +fieldMappings: array:34 [▶]
  +fieldNames: array:34 [▶]
  +columnNames: array:34 [▶]
  +discriminatorValue: null
  +discriminatorMap: []
  +discriminatorColumn: null
  +table: array:1 [▶]
  +lifecycleCallbacks: array:2 [▶]
  +entityListeners: []
  +associationMappings: []
  +isIdentifierComposite: false
  +containsForeignIdentifier: false
  +idGenerator: IdentityGenerator {#381 ▶}
  +sequenceGeneratorDefinition: null
  +tableGeneratorDefinition: null
  +changeTrackingPolicy: 1
  +isVersioned: null
  +versionField: null
  +cache: null
  +reflClass: ReflectionClass {#378 ▶}
  +isReadOnly: false
  #namingStrategy: null
  +reflFields: array:34 [▶]
  -instantiator: Instantiator {#376}
}
```

---> APP_ENV=dev (array contains the groups property)
```
AbstractClassMetadataFactory.php on line 208:
ClassMetadata {#8116 ▼
  +name: "App\Application\Sonata\UserBundle\Entity\User"
  +namespace: "App\Application\Sonata\UserBundle\Entity"
  +rootEntityName: "App\Application\Sonata\UserBundle\Entity\User"
  +customGeneratorDefinition: null
  +customRepositoryClassName: null
  +isMappedSuperclass: false
  +isEmbeddedClass: false
  +parentClasses: []
  +subClasses: []
  +embeddedClasses: []
  +namedQueries: []
  +namedNativeQueries: []
  +sqlResultSetMappings: []
  +identifier: array:1 [▶]
  +inheritanceType: 1
  +generatorType: 4
  +fieldMappings: array:34 [▶]
  +fieldNames: array:34 [▶]
  +columnNames: array:34 [▶]
  +discriminatorValue: null
  +discriminatorMap: []
  +discriminatorColumn: null
  +table: array:1 [▶]
  +lifecycleCallbacks: array:2 [▶]
  +entityListeners: []
  +associationMappings: array:1 [▼
    "groups" => array:20 [▼
      "fieldName" => "groups"
      "targetEntity" => "App\Application\Sonata\UserBundle\Entity\Group"
      "cascade" => []
      "joinTable" => array:3 [▶]
      "type" => 8
      "mappedBy" => null
      "inversedBy" => null
      "isOwningSide" => true
      "sourceEntity" => "App\Application\Sonata\UserBundle\Entity\User"
      "fetch" => 2
      "isCascadeRemove" => false
      "isCascadePersist" => false
      "isCascadeRefresh" => false
      "isCascadeMerge" => false
      "isCascadeDetach" => false
      "joinTableColumns" => array:2 [▶]
      "isOnDeleteCascade" => true
      "relationToSourceKeyColumns" => array:1 [▶]
      "relationToTargetKeyColumns" => array:1 [▶]
      "orphanRemoval" => false
    ]
  ]
  +isIdentifierComposite: false
  +containsForeignIdentifier: false
  +idGenerator: IdentityGenerator {#2797 ▶}
  +sequenceGeneratorDefinition: null
  +tableGeneratorDefinition: null
  +changeTrackingPolicy: 1
  +isVersioned: null
  +versionField: null
  +cache: null
  +reflClass: ReflectionClass {#3233 ▶}
  +isReadOnly: false
  #namingStrategy: UnderscoreNamingStrategy {#2111 ▶}
  +reflFields: array:35 [▶]
  -instantiator: Instantiator {#6026}
}
```

What is causing this very strange behaviour? It took me more than 3 hours to debug the whole thing :)

**Comment by alcaeus** [comment]
> If I comment the marked line (the dispatch) the dev environment isn't working just as the prod environment.

That's strange. While the code you posted is in `ClassMetadataFactory::doLoadMetadata`, the whole thing is called from the abstract factory from `doctrine/persistence`. If the class metadata was found in the cache, no `loadClassMetadata` event is thrown. However, if the class wasn't found in the cache, the event is called before metadata is cached, so the result should always be the same. Since you say the dev environment breaks if you remove the loadClassMetadata event, it looks related to that.

You could try changing the prod environment to use an array cache: this is a non-persistent cache which should ensure metadata load on every request without using a persistent cache. **Beware that this can have serious performance implications, so you shouldn't just roll that out on a production system.**

In addition to the above, is the `groups` mapping added by a loadClassMetadata event? If so, I'm wondering why its presence isn't ensured in the cache, but I'm also wondering what cache you are using for your metadata - maybe the problem isn't with the event after all.

**Comment by dmaicher** [comment]
@lukepass did you solve it in the end? 

If not we would need a reproducer to be able to further debug it.

**Comment by lukepass** [comment]
Hello @dmaicher, unfortunately for this particular project we had to revert back to Symfony 3.4 (for this and other bundle-compatibility issues). In the next months we will have another project (probably in Symfony 4) and so I should be able to report this issue if it's happening again.

Thanks.

**Comment by dmaicher** [comment]
Ok thanks @lukepass . I will close here in the meantime. Please open a new issue if you still experience this problem with the latest DoctrineBundle release.
