### ISSUE TITLE
New option: profiling_collect_backtrace: Key "file" for array with keys "function, class, type" does not exist.

### ISSUE THREAD

**Issue by bambucha4** [doctrine/DoctrineBundle#967]
I run a new option by added a value true, next I get a error on db collector in in \vendor/doctrine/doctrine-bundle/Resources/views/Collector/db.html.twig (line 293) - the key "file" does not exist.

Suggest problem ? Maybe firstly check if "file" key is defined or use |default filter ?

![Przechwytywanie](https://user-images.githubusercontent.com/16488888/57615802-db784e80-757c-11e9-8e8c-2f39f3e3f3de.PNG)

**Comment by ostrolucky** [comment]
Fixed in https://github.com/doctrine/DoctrineBundle/pull/968
