### ISSUE TITLE
DbalSchemaFilterPass is never called

### ISSUE THREAD

**Issue by alterphp** [doctrine/DoctrineBundle#969]
Hi,

Please forgive me if I open an invalid issue. But I'm unable to make `doctrine.dbal.schema_filter` configuration to be working (in order to ignore custom tables with **doctrine/migrations-bundle**).

I'm using doctrine/doctrine-bundle on `2.9.x` branch, the one that transforms this config into tagged services (tag is `doctrine.dbal.schema_filter`).

It seems that DbalSchemaFilterPass is never called (if I add it into `DoctrineBundle::build()` it's ok).

Am I doing wrong ?

**Comment by deguif** [comment]
This should be fixed very soon by a new release. See https://github.com/doctrine/DoctrineBundle/pull/966

**Comment by alterphp** [comment]
Ok, thanks @deguif ! I was going to be mad :-D

**Comment by alcaeus** [comment]
1.11.1 has been released so this is fixed now.
