### ISSUE TITLE
Add priority support for tagged entity listeners

### ISSUE THREAD

**Issue by deguif** [doctrine/DoctrineBundle#991]
I was wondering if priority support could be added to entity listeners tags in the compiler pass as it's supported for doctrine `event_subscriber` and `event_listener` tags in doctrine symfony bridge.

https://github.com/doctrine/DoctrineBundle/blob/ead3f067e82b4f5ff91642cd86112401c6e5c6a8/DependencyInjection/Compiler/EntityListenerPass.php#L24

**Comment by alcaeus** [comment]
Yes, that should be possible, at least I don't see why it shouldn't be. Are you up for working on it?

**Comment by ostrolucky** [comment]
I am missing something here, because I think tag priority concept is core symfony DI feature, so I assume it already works?

**Comment by dmaicher** [comment]
@ostrolucky well yeah tag priorities are a Symfony core feature. But they are not used by default :blush: 

So here the tags are not sorted:

https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/Compiler/EntityListenerPass.php#L25

We would need to use this: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php#L41

**Comment by ostrolucky** [comment]
Oh so this just about `findTaggedServiceIds` -> `findAndSortTaggedServices`? Allright that looks like easy pick.
