### ISSUE TITLE
Transaction commit failed because the transaction has been marked for rollback only

### ISSUE THREAD

**Issue by followyounger** [doctrine/DoctrineBundle#993]
what happened

**Comment by xabbuh** [comment]
I am sorry, but without more information, we won't be able to help you with this.

**Comment by followyounger** [comment]
hi, actually i do not know where this error was happened.
when i made a new entity, and inserted the data, and the data has been insert into the MySql  successfully, but also throw a exception.

**Comment by SenseException** [comment]
Can you please provide us an example code where this error can be reproduced?

**Comment by followyounger** [comment]
> Can you please provide us an example code where this error can be reproduced?

now the error is disappeared.
i thought it maybe caused by supervisor. i let supervisor monitor the consumer.
supervisor is start-up by root. and there is a file in /var/cache/ which authority is root. the authority of the program is start-up by www.  So it can not be deleted.

but thanks.

**Comment by SenseException** [comment]
That sounds like your issue is solved.

**Comment by followyounger** [comment]
no. maybe i found the real reason.

it is caused by exception.
when i send a get, the server send me the 500, 502 or 504 code. i did not deal with it, and maybe it influence the insert or update action.

**Comment by followyounger** [comment]
i use the inject dependency action.
it maybe influence a lot of action.
