### ISSUE TITLE
Doctrine Transport for Messenger is only available with ORM

### ISSUE THREAD

**Issue by micheh** [doctrine/DoctrineBundle#997]
Currently, it is not possible to use the Doctrine transport for the Messenger component when only the DBAL is installed without the ORM.

The problem is that the `DoctrineTransportFactory` is not registered, which leads to the following exception:
> No transport supports the given Messenger DSN "doctrine://default".

This is because the Messenger services are only registered when the ORM is available:
https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/DoctrineExtension.php#L403

I think the transport should always be loaded, as it doesn't seem to use the ORM features (only the middlewares use the entity manager).

**Comment by stof** [comment]
Fixed by #1028
